### ISSUE TITLE
How to check if a method's returnTypeName is Void?

### ISSUE THREAD

**Issue by mbarclay** [krzysztofzablocki/Sourcery#100]
I may just be using it wrong...I am only interested in methods that return `Void` my `if` condition is never entered even though I have numerous methods that return `Void` in the source. I am I doing something wrong with `{% if method.returnTypeName == "Void" %}`?

```{% for class in types.classes %}
Class: {{ class.name }}, Methods: {{ class.methods.count }}
  {% for method in class.methods %}
  {{ method.shortName }}, returnTypeName: {{ method.returnTypeName }}
    {% if method.returnTypeName == "Void" %}
      {{ method.shortName }}
      {{ method }}
    {% endif %}
  {% endfor %}
{% endfor %}

**Comment by ilyapuchka** [comment]
@mbarclay does `{% if method.returnTypeName.isVoid %}` also not working for you?

**Comment by mbarclay** [comment]
@ilyapuchka ah now that does work...I couldn't see `.isVoid` as an option in the documentation. Many thanks!
