### ISSUE TITLE
Bad CPU type in executable with 1.6.0

### ISSUE THREAD

**Issue by RalfK92** [krzysztofzablocki/Sourcery#1000]
After updating to 1.6.0 i am getting the following error. 

`/Pods/Sourcery/bin/sourcery: Bad CPU type in executable`

I am integrating Sourcery via CocoaPods. When i force the version to 1.5.0 my build completes.

My MacBook is from 2018 an has the 6-Core i9

**Comment by krzysztofzablocki** [comment]
there was an update to binary you need to call 
`pod cache clean 'Sourcery' --all`
