### ISSUE TITLE
How to reference the type “SourceryRuntime.Protocol” using Swift templates?

### ISSUE THREAD

**Issue by notcome** [krzysztofzablocki/Sourcery#1012]
If I just write `Protocol`, the compiler will complain of ambiguity between `SourceryRuntime.Protocol` and `ObjectiveC.Protocol`:

```
/private/var/folders/qr/m95k0bgx4cldcf37ftvqst900000gn/T/SwiftTemplate/1.6.0/Sources/SourceryRuntime/Protocol.swift:15:33: note: found this candidate
@objcMembers public final class Protocol: Type {
                                ^
ObjectiveC.Protocol:1:14: note: found this candidate
public class Protocol {
             ^
```

If I use `SourceryRuntime.Protocol` directly, Swift will treat the `SourceryRuntime` in `SourceryRuntime.Protocol` as a type (but it is a module) and `.Protocol` as referencing the protocol metatype of SourceryRuntime.

One solution would be doing

```
import class SourceryRuntime.Protocol
```

But I wonder if this is another way to do this? If not, should we consider adding a handy type alias for this type?

**Comment by krzysztofzablocki** [comment]
it's just regular swift, so normal swift limitation but there is a typealias already that we use `SourceryProtocol`
