### ISSUE TITLE
autoMockableImports does not work with single value from command line

### ISSUE THREAD

**Issue by ipodishima** [krzysztofzablocki/Sourcery#1013]
I attached a project to demonstrate.

## Using a Config.yml file
This config contains

```
args:
  autoMockableImports: ["CoreData"]
```

To run: `sh withConfig.sh`
Output: WithConfigGenerated/AutoMockable.generated.swift

It **contains** 

`import CoreData` as expected

## Using only the command line
Why did I got into the issue? Because my templates are shared with an SPM and I need the path from `${BUILD_DIR%Build/*}`
So I had no option but use the arguments and no config file

Using `--args autoMockableImports="CoreData"`

To run: `sh withoutConfig.sh`
Output: WithoutConfigGenerated/AutoMockable.generated.swift

It **does not contain** `import CoreData`

## Using only the command line but with an array (naive way)
Using `--args autoMockableImports=["CoreData"]`

To run: `sh withoutConfig2.sh`
Output: WithoutConfig2Generated/AutoMockable.generated.swift

It **does not contain** `import CoreData`

## How to get the non config working

`--args autoMockableImports="CoreData", autoMockableImports="AnotherImport"`

## Conclusion
Either I'm not doing it correctly or there is something wrong.
I have the feeling that it's because `--args autoMockableImports="CoreData"` is not considered as an array
When I "print" `argument.autoMockableImports`, it returns `CoreData`

When we have `--args autoMockableImports="CoreData,autoMockableImports="AnotherImport"`, it prints `[CoreData, AnotherImport]` (`{{ argument.autoMockableImports }}`)

Here is the project attached

[TestImport.zip](https://github.com/krzysztofzablocki/Sourcery/files/7605811/TestImport.zip)

**Comment by artem-alexandrov** [comment]
I have the same issue with autoMockableTestableImports. It also produces odd output when I use environment variables:

```
--args autoMockableTestableImports="App_${PLATFORM_FAMILY_NAME}" 
```

produces:

```
@testable import _capacityAndFlags
@testable import _countAndFlags
```

**Comment by ipodishima** [comment]
I understood something today, when you run {{ argument.autoMockableImports.count }} you get the count of the characters of the single autoMockableImports argument. Can't find a workaround though :/

**Comment by Nikoloutsos** [comment]
> I have the feeling that it's because --args autoMockableImports="CoreData" is not considered as an array

Exactly, you have to write `--args autoMockableImports=["CoreData"]` instead

**Comment by artem-alexandrov** [comment]
I'm still having 

```
@testable import _capacityAndFlags
@testable import _countAndFlags
```

Instead of what I need even if I use 

```
--args autoMockableTestableImports=["App_${PLATFORM_FAMILY_NAME}"]
```

**Comment by DominikBucher12** [comment]
Hello @ipodishima , @artem-alexandrov .

the problem lies within the escaping of quotes inside the array when you try to pass the array. What you need to do is this :

`--args autoMockableTestableImports='["FirstModule","SecondModule"]'`

zsh is super confused about the quotes even if you escape it with backlash. 

Have a great day :)

**Comment by DominikBucher12** [comment]
Also @krzysztofzablocki would it be worth to update the documentation how to pass those types (other than Strings/Paths) to stencil parameters? I literally spend 20 minutes to realise what is wrong 😀 I believe lot of people struggle with this as well.

**Comment by krzysztofzablocki** [comment]
@DominikBucher12 wanna join the contributor list? I'd gladly accept PR with that info

**Comment by DominikBucher12** [comment]
@krzysztofzablocki No problem, I will create PR later this evening, thank you!
