### ISSUE TITLE
lib_InternalSwiftSyntaxParser.dylib missing x86_64 architecture

### ISSUE THREAD

**Issue by tapsandswipes** [krzysztofzablocki/Sourcery#1016]
The library bundled in release (1.6.1) from cocoapods,  comes with arm64 support only so It can't run on Intel Macs.

**Comment by krzysztofzablocki** [comment]
interesting, I see it but surprised how it built thin version of lib rather than use the fat one, I've updated the zip to contain the right one.

You need to run `pod cache clean 'Sourcery' --all`
