### ISSUE TITLE
How to know if a Method is async?

### ISSUE THREAD

**Issue by alexito4** [krzysztofzablocki/Sourcery#1018]
I've looked at the docs and printed a method using `{{ method }}` but I don't see how to know if a method is async. 
I can see a boolean for the throwing effect (`throws = true`) but not for the async one. 

Is there a way to know if a method is async or is just not supported yet?

**Comment by krzysztofzablocki** [comment]
Not supported yet, we'd need to add it

**Comment by grsouza** [comment]
I'm also interested in that, I have a template for generating initializers but thats not working with async closures.

```
{% for type in types.structs %}
{% if type|annotated:"AutoInit" %}
{% set spacing %}{% if type.parentName %}    {% endif %}{% endset %}
{% map type.storedVariables into parameters using var %}{{ var.name }}: {% if var.typeName|hasPrefix:"(" %}@escaping {% endif %}{{ var.typeName }}{% endmap %}
// sourcery:inline:auto:{{ type.name }}.AutoInit
{{spacing}}{{ type.accessLevel }} init({{ parameters|join:", " }}) {
{{spacing}}    {% for variable in type.storedVariables %}
{{spacing}}    self.{{ variable.name }} = {{ variable.name }}
{{spacing}}    {% endfor %}
{{spacing}}}
// sourcery:end
{% endif %}
{% endfor %}
```

Is someone already adding support for this? If not I can try to add it, just point me to the right direction @krzysztofzablocki

**Comment by ailtonvivaz** [comment]
When I run the command `sourcery` in root path of project, i get this error.

```
Using configuration file at '.sourcery.yml'
Scanning sources...
Found 57 types in 41 files, 7 changed from last run.
Loading templates...
error: Error Domain=NSCocoaErrorDomain Code=260 "The file “ejs.js” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/opt/homebrew/bin/ejs.js, NSUnderlyingError=0x13d686420 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
Error Domain=NSCocoaErrorDomain Code=260 "The file “ejs.js” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/opt/homebrew/bin/ejs.js, NSUnderlyingError=0x13d686420 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}%     
```

**Comment by ailtonvivaz** [comment]
I submitted the PR, but the tests are failing in CircleCI.
I didn't know why.

**Comment by ailtonvivaz** [comment]
@krzysztofzablocki I think this issue could be closed, doesn't it?
The implementation was merged and available for using in master branch.

**Comment by alexito4** [comment]
FYI I used the master branch to update our templates and this works as expected 👌🏻 
Thanks!
