### ISSUE TITLE
`@MainActor` results in class not being found

### ISSUE THREAD

**Issue by sroebert** [krzysztofzablocki/Sourcery#1022]
When using `@MainActor` for a class it does not get picked up and it will not be part of `type.classes` in the templates for generating code.

As soon as I remove `@MainActor` the class gets picked up as normal. I guess there is some update needed to support this new syntax since Swift 5.5?

**Comment by sroebert** [comment]
Actually it does work if I put the comments underneath `@MainActor`, so:

This works:
```swift
@MainActor
// sourcery: someAnnotation
class SomeClass {
}
```

This does not:
```swift
// sourcery: someAnnotation
@MainActor
class SomeClass {
}
```

**Comment by art-divin** [comment]
This should have been fixed since a couple of releases. Here's a test with the latest version of Sourcery (2.1.4):

```swift
Stencil.template:
{% for class in types.classes %}
    {{ class.name }} - {{ class.annotations }}
    {% for variable in class.variables %}
        {{ variable.name }} - {{ variable.annotations }}
    {% endfor %}
{% endfor %}
```

```swift
Input.swift
// sourcery: someAnnotation
@MainActor
class SomeClass {
    var hello: String?
}
```

```swift
Output.swift
// Generated using Sourcery 2.1.4 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

    SomeClass - {
    someAnnotation = 1;
}
        hello - {
}
```
