### ISSUE TITLE
[Suggestion] Add support for the new SPM build plugins

### ISSUE THREAD

**Issue by BrentMifsud** [krzysztofzablocki/Sourcery#1023]
Apple just announced that the new SPM build commands is going to be available in the next version of xcode. Its currently in beta, but adding support for this feature would be an awesome addition to Sourcery

```
Swift Package Manager
New Features
Swift Packages now support build tool plugins, as defined in [SE-0303](https://github.com/apple/swift-evolution/blob/main/proposals/0303-swiftpm-extensible-build-tools.md) and [SE-0325](https://github.com/apple/swift-evolution/blob/main/proposals/0325-swiftpm-additional-plugin-apis.md). This allows packages to define plugins that can specify tools that should run during a build operation, for example to generate source code. This is supported in both swift package and in Xcode’s support for packages. (79876749)

The swift package command now supports command plugins, as defined in [SE-0332](https://github.com/apple/swift-evolution/blob/main/proposals/0332-swiftpm-command-plugins.md). This allows Packages to define commands that can be invoked using the swift package command line to perform custom actions on the package. (82895553)
```

**Comment by krzysztofzablocki** [comment]
@BrentMifsud until they support R-Path rewrites you can't build Sourcery properly with SPM only

**Comment by pchmelar** [comment]
Is this possible now (after changes in https://github.com/krzysztofzablocki/Sourcery/pull/1037) ? 🤔

**Comment by krzysztofzablocki** [comment]
yeah it should be possible now, anyone wants to contribute that integration? 😉 
I'm pretty low on having personal time between work and conferences

**Comment by cal-os** [comment]
+1 would love to see this as a feature with apple's new plugin build tool system

**Comment by doozMen** [comment]
I would love to work on this and might be very interesting in my project at work. It would be my first time contributing. Any tips before I start?

**Comment by krzysztofzablocki** [comment]
@doozMen 🙇 shouldn't require anything special given Sourcery now builds purely with SPM. The 2 WWDC sessions about plugins cover everything I think, but if you run into issues you can report here and I can get Apple folks to look at it if we can't figure it out ourselves

**Comment by pkurzok** [comment]
I was trying out building a Command Plugin using Sourcery as a dependency. But I get the following error when the Packages are resolved:

`error: multiple targets named 'lib_InternalSwiftSyntaxParser' in: 'sourcery', 'swiftlint'`

My Package File looks like this:

```
let package = Package(
    ...
    dependencies: [
        .package(url: "https://github.com/krzysztofzablocki/Sourcery", branch: "master")
    ],
    targets: [
      ...
        .plugin(name: "MockGeneratorPlugin",
                ...
                dependencies: [
                    .product(name: "sourcery", package: "Sourcery")
                ])
    ])
```

Any ideas what could be the issue and how to fix it?

**Comment by krzysztofzablocki** [comment]
I see SwiftLint also uses static swift syntax release workaround, but not sure how the 2 are related, we don't need SwiftLint in this project, I wonder if it's any related dependency, are you brining in SwiftLint in that project @pkurzok ?

**Comment by pkurzok** [comment]
In the Plugin I'm building Sourcery is literaly the only dependency I'm using. In the project where I'm using the plugin, there is also no direct SwiftLint dependency also dont see it in the package list. I'm wondering where it comes from.

Although I have it installed on my machine. But that shouldn't make any difference, does it?

**Comment by pkurzok** [comment]
Found it: stencilswiftkit depends on komondor and they depend on swiftlint.

Nice tool for that: https://swift-dependency-graph.opticalaberration.com

**Comment by doozMen** [comment]
I will follow up on this later cool you guys picked this up already. Will have more time end of July.

**Comment by doozMen** [comment]
I have found a workable solution for using swiftgen which uses sourcery too I guess. It relies on providing a build artifact. This is very nice explained in https://github.com/SwiftGen/SwiftGen/pull/926. Making sourcery available in a simular way would be a good way to do it. 

The problem happens when you do not expose it as a build artefact that if you apply it to a target for iOS, which a lot will do, then it will try to build sourcery for a simulator target 🥴 which you do not want.

I do not have the time now to make sourcery build into a build artifact nor do I know if somebody did already attempt this kind of thing?

**Comment by markst** [comment]
Not sure if this is helpful: https://github.com/KarimAlweheshy/spm-build-tools
