### ISSUE TITLE
Project Setup For Contributing

### ISSUE THREAD

**Issue by alexvbush** [krzysztofzablocki/Sourcery#1026]
Hi, I'm trying to setup the project to walk through its codebase in order to better understand how it works and to potentially contribute with changes. Specifically I'm trying to figure out why passing import arguments in my config file doesn't work https://github.com/krzysztofzablocki/Sourcery/issues/1024

I am experiencing issues setting up Sourcery project for development. 

I looked at `.circleci/config.yml` https://github.com/krzysztofzablocki/Sourcery/blob/master/.circleci/config.yml file to get a high level overview of what is need to setup the project locally.  It has the following commands:

```
      - checkout
      - run: sudo defaults write com.apple.dt.Xcode IDEPackageSupportUseBuiltinSCM YES
      - run: rm ~/.ssh/id_rsa || true
      - run: for ip in $(dig @8.8.8.8 bitbucket.org +short); do ssh-keyscan bitbucket.org,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true 
      - run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts || true
      - run: brew update 1> /dev/null 2> /dev/null
      - run: brew install sourcekitten
      - run: brew install coreutils
      - run: echo "ruby-3.0.0" > ~/.ruby-version
      - run: bundle install
      - run: bundle exec rake validate_docs
      - run: bundle exec danger || true
      - run: set -o pipefail
      - run: bundle exec rake build
      - run: bundle exec rake tests
```

So, `brew install sourcekitten`, `brew install coreutils`, `echo "ruby-3.0.0" > ~/.ruby-version`, `bundle install` all worked fine for me.

But `bundle exec rake tests` fails with different errors:
<img width="930" alt="Screen Shot 2022-02-13 at 1 17 57 PM" src="https://user-images.githubusercontent.com/311077/153771000-60626ad7-0ca6-4ff9-8fc9-18baefe0836d.png">

I also tried to generate the xcode project with `swift package generate-xcodeproj`. It worked fine but I get compile errors:
<img width="1392" alt="Screen Shot 2022-02-13 at 1 19 23 PM" src="https://user-images.githubusercontent.com/311077/153771054-0f0df65f-221b-4a5d-bb92-6518a2d0ecc5.png">

What am I missing? Probably something simple. 
Thank you for your help in advance!

**Comment by krzysztofzablocki** [comment]
don't use `swift package generate-xcodeproj` like I said above, just open Package.swift, Apple have not updated project generation for a while and it's broken

**Comment by alexvbush** [comment]
ah, I missed it, sorry about that! it works now, thank you! now I can play around with it.

**Comment by krzysztofzablocki** [comment]
no problem, and thanks for wanting to contribute 🙇
