### ISSUE TITLE
[QUESTION] Is there a way to get the source file a type is defined in?

### ISSUE THREAD

**Issue by hborawski** [krzysztofzablocki/Sourcery#1027]
Been looking through the docs and issues here and either can't find anything about it or my search skills are lacking.

Looking into using `completeDeclarationRange` to copy the actual code for annotated types, the byte range doesnt really have any use if i dont know what file its from. But haven't been able to figure out a way to get the file a given type is declared in.

Also open to other ways of doing this, my usecase is to be able to annotate "examples" for my SwiftUI component library, and show the code alongside a generated screenshot of the component (which i generated a snapshot test with sourcery annotations currently)

**Comment by krzysztofzablocki** [comment]
you can get `path` just use `type.path`, it's [not documented] (https://github.com/krzysztofzablocki/Sourcery/blob/master/SourceryRuntime/Sources/AST/Type.swift#L338) because I didn't think anyone will need it but it's reliable since it's needed for Sourcery processing

**Comment by Nikoloutsos** [comment]
Keep in mind `type.path` will give you the full path. So you would have to do a text processing to get what you want :/

**Comment by krzysztofzablocki** [comment]
or just send up pr with computed property 😉

**Comment by hborawski** [comment]
`type.path` will work for me, I already have a bunch of different post-processing for this project, so i don't mind additional processing

Thank you!

I'll look into putting up a PR to make it easier when i get some extra time. Just to keep it in this thread, the computed property would be to provide the path relative to the execution directory? Or relative to the config file?

**Comment by krzysztofzablocki** [comment]
yeah I just meant to get specifics parts of the path we already have e.g. just file name.
