### ISSUE TITLE
[Stencil] How to get count of filtered array.

### ISSUE THREAD

**Issue by Nikoloutsos** [krzysztofzablocki/Sourcery#1028]
Looking for getting the filtered count. Any ideas? I've been searching for an hour and couldn't find how this syntax is.
I know this is not a strictly sourcery issue but a little help would be appreciated!

**Usecase:**
I want to know the number of method's parameters that are not closures

BTW:
Filtering for for loops works great
```stencil
{% for param in method.parameters where not param.typeName.isClosure %} {% endfor%}
```

**Example:**
```swift
// sourcery: Example
protocol Foo {
    func talk(a: Int, b: (Int) -> Void)
    func walk(a: Int, b: Int)
    func eat(a: () -> ())
}
```

Given the above protocol function:
`talk` --> 1
`walk` --> 2
`eat` --> 0

Thank you in advance! ❤️

**Comment by Nikoloutsos** [comment]
@krzysztofzablocki 
Hmm, thanks for the sourceryPro looks good 🚀 .
My goal is to write a stencil if statement that will evaluate to true only if there is at least 1 non-closure parameter.

I hope i could write something like this (but still haven't found how to do it):
```stencil
{% if method.parameters|!isClosure|count > 0 %}....{% endif %}
```
I guess I have to create my own filter? Since I have tried many combinations from your jazzy docs. Is there any documentation for that?

Thank you for prompt response. 😸

**Comment by krzysztofzablocki** [comment]
Can't you just do `{% if method.parameters|!isClosure|count %}` since that will execute if it's not zero ? given how bool are evaluated

**Comment by Nikoloutsos** [comment]
```stencil
{% if method.parameters|!isClosure|count %}
```
Will produce error when running Sourcery. It must be a syntactic error.
So what are you suggesting? Still haven't found an answer to my question 😞

**Comment by krzysztofzablocki** [comment]
```
    {% if type.allMethods|private|count %} 
    {{ type.name }} has private methods 
    {% else %} 
    {{ type.name }} doesn't have private methods 
    {% endif %}
```

works just fine, are you trying to use filter that doesn't exist ? I don't see `isClosure` filter in the codebase

**Comment by Nikoloutsos** [comment]
@krzysztofzablocki 
Yes I'm trying to find a filter that maybe doesn't exist. I want to know if a method has at least 1 argument that is not a non-escaping closure. Is there a way to make my own filter?

When doing a for loop I use isClosure and works fine but for what I want I don't find something...

**Comment by krzysztofzablocki** [comment]
@Nikoloutsos you can submit PR, I'm ok with accepting additional filters, you can see how they are [done here](https://github.com/krzysztofzablocki/Sourcery/blob/c8a9d15efb2353e48daa9862e44585dfa16ec589/SourceryStencil/Sources/StencilTemplate.swift) and it should just follow this setup
