### ISSUE TITLE
Whether and how to submit general-purpose templates?

### ISSUE THREAD

**Issue by fvolchyok** [krzysztofzablocki/Sourcery#1032]
I have a simple and cool template that I think might be useful to other developers. Should I submit it somewhere and if so then how? Is there some public repo with general-purpose templates? Submitting PR that treats my template as README.md worthy and modifies it feels kind of rude and invasive. What should I do?

**Comment by krzysztofzablocki** [comment]
@fvolchyok there isn't a generic repo  but if you share it here I can decide whether to add it to bundled one, what does the template do?
