### ISSUE TITLE
What's the name of syntax used by sourcery?

### ISSUE THREAD

**Issue by Nikoloutsos** [krzysztofzablocki/Sourcery#1033]
I've been creating some templates for my team for a while and I always looking Sourcery objects like this because I can see what options I have.
![image](https://user-images.githubusercontent.com/14034942/155130627-d806a6ba-b415-4340-ab0f-13362a56ff1d.png)

I want to beatify this (just like we do with json beautifiers) but don't know what's the name of this syntax.
Does anyone know?

Thank you 💙

**Comment by krzysztofzablocki** [comment]
This is just rendering objc description I think, so you could try generating custom description for our Runtime types (you can use Sourcery for it, same way we do encoding etc)
