### ISSUE TITLE
Sourcery 1.8.0 isn't buildable on non-supported Xcode 13.3 Macs

### ISSUE THREAD

**Issue by AF-cgi** [krzysztofzablocki/Sourcery#1045]
Thanks a lot for the new release and the fast fix for integrating the new SwiftSyntax release. But now it's required to use Xcode 13.3 to build Sourcery. Xcode 13.3 isn't available for the same Macs like Xcode 13.2.1 did this. Do you see a chance to add this support again?

**Comment by krzysztofzablocki** [comment]
we won't be adding backward compatibility, we are always moving forward since we are also integrating newer SwiftSyntax versions and people can stay on older version until they are ready to switch

**Comment by AF-cgi** [comment]
I see your point. But Xcode 13.3 requires a Mac running macOS Monterey 12 or later. That means that new Sourcery features are only available for Macs with macOS Monterey 12 or later. I know, that SwiftLint solve this point.

**Comment by liamnichols** [comment]
The prebuilt binary of 1.8.0 (downloaded from the releases page, or via CocoaPods/Homebrew) should work on any supported macOS version (10.12+ iirc), this is only about compiling the tool (i.e using it with Mint).

Given that pre 1.8.0 always discouraged using Mint, I don't think this would be a widespread issue. 

As a temporary workaround, can you use a precompiled version instead of Mint on your CI infrastructure that doesn't have Xcode 13.3 installed?

**Comment by AF-cgi** [comment]
Our CI infrastructure doesn't support macOS 12 right now. From that point the local and CI builds are diverge. There is also some Apple hardware which doesn't supports macOS 12.
We use also Mint as CLI dependency manager, because we use many other CLIs. From that perspective it would be great to find a solution to solve it.
As a temporary workaround it's possible to use a precompiled version. But that's not the preferred way.
My Question on that point how other CLIs solve this, f.e. SwiftLint? SwiftLint is buildable over Mint with Xcode 13.3 and Xcode 13.2.1. I thing it's a also possible to install SwiftLint via Home-brew on multiple macOS versions.

**Comment by liamnichols** [comment]
So I thought a bit harder about this, maybe #1049 is what we want. It's still Sourcery using SwiftSyntax 5.6 with the statically linked lib_internalSwiftSyntaxParser, but it allows for building using Xcode 13.x.

This approach would probably be good up until we want to use Swift 5.6 specific language features in the codebase, which is probably far enough away to give teams time to move to Xcode 13.3 (i.e later this year).

**Comment by AF-cgi** [comment]
Looks fine for me and works perfect. Thanks @liamnichols

**Comment by krzysztofzablocki** [comment]
fixed on main
