### ISSUE TITLE
Sourcery 1.8.0 - No config file provided or it does not exist issue

### ISSUE THREAD

**Issue by bolo992** [krzysztofzablocki/Sourcery#1047]
After installing Sourcery using mint, i am getting this error now:

"No config file provided or it does not exist. Using command line arguments.
error: No sources provided.
No sources provided.%"

Does anyone knows how to solve this issue?

**Comment by bolo992** [comment]
If i run this command:
**sourcery --sources . --templates tools/sourcery/templates/ --output tools/sourcery/**

It's generating the code but i am getting again:
"No config file provided or it does not exist. Using command line arguments."

**Comment by krzysztofzablocki** [comment]
the default (and recommended) mode is having the `.sourcery.yml` file

**Comment by bolo992** [comment]
Ok, i didn't notice this warning before so that's why i asked. I'll close this issue.
