### ISSUE TITLE
Question - ViewBuilder Injectable for SwiftUI

### ISSUE THREAD

**Issue by pjcau** [krzysztofzablocki/Sourcery#1052]
Hi Guys, 

so I think to reduce the code to implement the Inject on View...so I image to create a ViewBuilder

```
public struct Injectable<Content: View>: View {
    
    @ObservedObject private var iO = Inject.observer
    
    let content: () -> Content
    
    public init(@ViewBuilder content: @escaping () -> Content) {
        self.content = content
    }
    
    public var body: some View {
         content()
        .enableInjection()
    }
}

```

and obvious to call it 

```
struct CustomView: View {
 
  var body: some View {
    Injectable{
       ...
    }
  }
}
```

but unfortunately doesn't work. I see that's pass correctly in `InjectionObserver`. 
So anybody can help me or did someone did like that this

Thank you

Jonny Cau

**Comment by krzysztofzablocki** [comment]
Wrong repo but this won't work for Inject in that form
