### ISSUE TITLE
Version 1.8.1 is not available for download

### ISSUE THREAD

**Issue by aomathwift** [krzysztofzablocki/Sourcery#1055]
Release URL for v1.8.1 is not found and version 1.8.1 is not available for download.
https://github.com/krzysztofzablocki/Sourcery/releases/download/1.8.1/sourcery-1.8.1.zip

Version 1.8.1 exists on Cocoapods, but the tag does not exist on Github Release.
https://github.com/krzysztofzablocki/Sourcery/releases
https://github.com/CocoaPods/Specs/blob/master/Specs/9/2/2/Sourcery/1.8.1/Sourcery.podspec.json

If there is a difference between these version, we will not be able to use the new version.
Would you please solve this problem? @krzysztofzablocki

**Comment by krzysztofzablocki** [comment]
I reverted the release, 1.8.1 will come out later
