### ISSUE TITLE
Multiline doc comments not working properly

### ISSUE THREAD

**Issue by dan-stytch** [krzysztofzablocki/Sourcery#1056]
As I was building documentation w/ DocC and generating code (with docs) using Sourcery, I noticed that not all documentation comments are parsed correctly (and this may also affect parsed annotations). It seems the multiline doc comment style is not properly parsed. I've tried to outline some examples below. Thanks for having a look!
``` swift
// sourcery: notWorkingAnnotation
/** 
 These are doc comments
*/
func something() {}
...
// sourcery: workingAnnotation
/// These are doc comments
func somethingElse() {}
...
// sourcery: workingAnnotation
/// These are doc comments
/* Incorrectly appearing doc comments */
func somethingElse() {}
```
## Relates to
https://github.com/krzysztofzablocki/Sourcery/issues/766
https://github.com/krzysztofzablocki/Sourcery/pull/1002

**Comment by art-divin** [comment]
👋🏻 Hello,

thank you for reporting the issue @dan-stytch ,

it was quite tough to resolve, but easy to investigate.
#1293 resolves this.
