### ISSUE TITLE
Bad CPU type in executable with 1.8.1

### ISSUE THREAD

**Issue by djbe** [krzysztofzablocki/Sourcery#1058]
Refs #1000.

Installed through CocoaPods, tried pods cache clean as mentioned in previous issue. I'm on `i386`, output of `lipo` on the Sourcery binary:
```bash
$ lipo -info sourcery
Non-fat file: sourcery is architecture: arm64
```

Edit: reverting to 1.8.0 fixes the issue.

**Comment by krzysztofzablocki** [comment]
Something is wrong with rake using non-fat build for gh release, I'll look into it, in the meantime I've updated the distro, so just running the cache clean should fix it:

`pod cache clean 'Sourcery' --all`
