### ISSUE TITLE
Consider taking over the maintainership of the syntax highlighting plugin

### ISSUE THREAD

**Issue by Cyberbeni** [krzysztofzablocki/Sourcery#1059]
It seems to be completely neglected: https://github.com/stencilproject/vscode-stencil/pull/2 https://github.com/stencilproject/Stencil/issues/304

[My current version](https://github.com/Cyberbeni/vscode-stencil) has the fix from that PR, the fix from [this issue comment](https://github.com/stencilproject/vscode-stencil/issues/4#issuecomment-777800425) and also added a script to package.json to be able to export the extension.

IIRC it still has some issues but it's still better than not having any syntax highlighting.

**Comment by krzysztofzablocki** [comment]
I can't possibly maintain anything else, also SourceryPro has way more powerful Stencil editor with types and inline errors / documentation
