### ISSUE TITLE
Brew doesn't install latest 1.8.1

### ISSUE THREAD

**Issue by Nikoloutsos** [krzysztofzablocki/Sourcery#1061]
I can't get brew install sourcery 1.8.1 on this machine.
It only installs 1.7.0

![CleanShot 2022-05-05 at 11 00 48](https://user-images.githubusercontent.com/14034942/166883456-648d68a4-a895-4890-9441-82ffc3754492.png)

Xcode version 13.3
MACOS:  12.2
brew: 3.4.10

Can this be related to MacOS version? Does anyone know any fix on that?

**Comment by krzysztofzablocki** [comment]
that's more of a question to brew not Sourcery since the formula is released https://formulae.brew.sh/formula/sourcery#default

need brew up or brew doctor maybe?

**Comment by Nikoloutsos** [comment]
anyway I finally manually downloaded the binary!
