### ISSUE TITLE
String annotation not parsed correctly by sourcery

### ISSUE THREAD

**Issue by Nikoloutsos** [krzysztofzablocki/Sourcery#1064]
According to documentation
```
All annotations of declaration stored by their name. Value can be `bool`, `String`, float `NSNumber`
     or array of those types if you use several annotations with the same name.
    
     **Example:**
     
     ```
     //sourcery: booleanAnnotation
     //sourcery: stringAnnotation = "value"
     //sourcery: numericAnnotation = 0.5
```

But when i do
```swift
// sourcery: example = "["1","2"]"
struct Foo {
    let name: String
}
```
The " characters are removed! 
![CleanShot 2022-05-11 at 11 01 11](https://user-images.githubusercontent.com/14034942/167799384-ee18f03f-ab32-48b0-af59-4f3c66d2749e.png)

So I can't have a string with [] (array) as it parses differently? I want it as it is. without any change. It is a string after all.

Sourcery will give me `[1,2]` instead of `["1","2"]`

**Comment by krzysztofzablocki** [comment]
what does this return?

```swift
// sourcery: example = "1"
// sourcery: example = "2"
struct Foo {
    let name: String
}
```

**Comment by art-divin** [comment]
Related to #1316 , might actually be resolved by that one.
