### ISSUE TITLE
/Applications/Xcode.app hardcoded?

### ISSUE THREAD

**Issue by lexon** [krzysztofzablocki/Sourcery#1066]
Is the path to Xcode, to be concrete: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/lib_InternalSwiftSyntaxParser.dylib

hardcoded? I am on a m1 mac and I am not using Xcode.app, since its a CI agent, which compiles different Apps with different requirements to Xcode version, e.g. we have Xcode_13.1.app etc.
We are setting current Xcode using DEVELOPER_DIR environment var.

**Comment by krzysztofzablocki** [comment]
We moved over to static lib in last releases so it shouldn't care what Xcode you have

**Comment by art-divin** [comment]
Closing this issue due to long inactivity, please reopen if needed 🙏🏻
