### ISSUE TITLE
Infinite recursion crash when a protocol and class conform to each other.

### ISSUE THREAD

**Issue by cheeseonhead** [krzysztofzablocki/Sourcery#1067]
I think this is a language feature to allow protocols to limit the conformers to a particular class, but it's also valid to have that class conform to that protocol:
```swift
protocol Hi: Test {}

class Test: Hi {
    func test() {}
}
```

This snippet of code is totally valid in Swift, but I can see why it might cause an infinite recursion during Sourcery parsing.

It doesn't happen if there are no members involved on either types:
```swift
protocol Hi: Test {}

class Test: Hi {}
```

**Comment by art-divin** [comment]
🙌🏻  Hello @cheeseonhead ,

thank you for your report! Indeed, such cases should be supported.

However, I was not available to reproduce. Could you please provide an example of `stencil` file that you've used to reproduce this recursion issue?

Thank you 🙏🏻

**Comment by art-divin** [comment]
Closing, might have been fixed by another bug fix. Please re-open in case this is not the case. Thanks!
