### ISSUE TITLE
Generate output on a per directory basis

### ISSUE THREAD

**Issue by markst** [krzysztofzablocki/Sourcery#1073]
Rather than generate one giant file, I wish to generate files based on my original directory structure.

This is my stencil currently:

```swift
{% for type in types.based.PreviewProvider %}
// sourcery:file:Generated/{{ type.path|replace:".swift","" }}/{{ type.name }}+TemplateName
import SwiftUI
import UIPreviewCatalog

@testable import {{ argument.mainTarget }}

let previewItems: [PreviewItem] = [
    .init(name: "{{type.name}}", previews: {{type.name}}._allPreviews),
]
// sourcery:end
{% endfor %}
```

However I'd like to ignore the last component of the path entirely, rather than just replacing the `swift` extension. 

Is this possible?

Otherwise is it possible to loop through directories & perform generate rather than loop through all discovered types?

**Comment by markst** [comment]
Ah perhaps I've been able to achieve it with the following:
```swift
// sourcery:file:Generated/{{ type.path|replace:type.fileName,"" }}/{{ type.name|replace:"_Previews","" }}
```

**Comment by markst** [comment]
Although ideally like to generate based on files in each directory, rather than one generated file per discovery.

**Comment by krzysztofzablocki** [comment]
hmm, how can you have the same type name in a single file? do you have a sample?

**Comment by krzysztofzablocki** [comment]
but those are different type names right? not sure what the original issue was

**Comment by markst** [comment]
Resolved with combo of changes in PR & the following script to achieve what we're after:

```shell
for f in ../../Qatar22/*; do
    if [ -d "$f" ]; then
        name=$(basename "$f")
        escapedFolder=$(printf %q $name)
        sourcery --sources "$f" --templates ./PreviewItem.stencil --args mainTarget=Qatar22,baseName="$escapedFolder" --output ../Generated/"$escapedFolder"
    fi
done
```
