### ISSUE TITLE
Documentation links result in 404

### ISSUE THREAD

**Issue by Cyberbeni** [krzysztofzablocki/Sourcery#1078]
Both in `README.md` and `Writing templates.md` the links pointing to `merowing.info/Sourcery/...` result in 404

**Comment by krzysztofzablocki** [comment]
Fixed the old one in writing, dont' see any in readme?

**Comment by Cyberbeni** [comment]
The image of the badge in readme is still broken.

**Comment by krzysztofzablocki** [comment]
updated, thanks!
