### ISSUE TITLE
Twitter script for making class final not working as expected

### ISSUE THREAD

**Issue by Nikoloutsos** [krzysztofzablocki/Sourcery#1085]
Hi Ι saw in your Twitter you added this, and our team liked it and we tried to integrate it as well: https://twitter.com/merowing_/status/1522558910648967174
```
<% for type in types.classes { -%>
  <%_ if type.attributes["final"] != nil || type.attributes["open"] != nil || types.based[type.name].isEmpty == false { continue } -%>
<%_ _%>git grep -lz 'class <%= type.name %>' | xargs -0 perl -i'' -pE "s/class <%= type.name %>(?=\s|:)/final class <%= type.name %>/g"
<% } %>
```

I observed that something is wrong with `type.attributes["final"]`. As I see sourcery swiftTemplate `attributes` dictionary property is empty. I guess this is a bug on swifttemplates. So I fixed by using this workaround:

```
#!/usr/bin/env bash
<% for type in types.classes { -%>
  <%_ if type.modifiers.map{ $0.name }.contains("final") || type.modifiers.map{ $0.name }.contains("open") || types.based[type.name].isEmpty == false { continue } -%>
<%_ _%>git grep -lz 'class <%= type.name %>' | xargs -0 perl -i'' -pE "s/class <%= type.name %>(?=\s|:)/final class <%= type.name %>/g"
<% } %>
```

So if you don't mind update your gist 😄 
https://gist.github.com/krzysztofzablocki/338eddf527a351de825bd62cf2a1de28

**And some other comments:** 
I also noticed that the script will not work for nested classes. e.g
```swift

struct Foo {
    class Bar { // This will not be changed to final.
        init() {}
    }
```

And last but not least the script doesn't work well if you have name collisions between different modules. For example I had a class named `SceneDelegate` and because it was appeared in 2-3 places/module sourcery wasn't sure which one to parse. So now I am running this for 1 module only at a time.

Thank you for sharing this sexy script 🙈

**Comment by krzysztofzablocki** [comment]
thanks! I wrote this originally on older AST version and the modifiers model changed since then. Do you use project integration with Sourcery? otherwise it doesn't know anything about different modules, even with that though multi-module global scripts like this are not trivial

**Comment by Nikoloutsos** [comment]
@krzysztofzablocki  Out of curiosity at this time, I'm adding a SPM path to sourcery input and for some reason sourcery is parsing its dependencies as well. My module is `Analytics` and have a dependency on Firebase. 

Is there any way to disable this dependency parsing for SPM? I want the sourcery to parse only my spm. Firebase has many classes and it takes a lot of time 😄 

Thank you!

**Comment by Nikoloutsos** [comment]
Indeed, it was the .build/checkouts folder that contained the dependencies in case someone face the same problem 😲
