### ISSUE TITLE
Is it possible to read documentation comment

### ISSUE THREAD

**Issue by tahirmt** [krzysztofzablocki/Sourcery#1095]
Hey I'm wondering if it is possible to read the documentation comments for a property and add it to the resulting file

For example I have a file like this

```swift
struct Colors {
    /// To be used where red is needed
    let appRed: UIColor = .red
    
    /**
    To be used where blue is needed
    */
    let appBlue: UIColor = .blue
}
```

Then I use Sourcery to generate a file like this

```swift
extension UIColor {
    static var appRed: UIColor {
        constant.small
    }

    static var appBlue: UIColor {
        constant.large
    }
}
```

I would like to transfer the code documentation to this generated extension. Is that possible?

**Comment by krzysztofzablocki** [comment]
It's opt-in, If you pass in `parseDocumentation` option it will scan documentation comments and that's available as `documentation` field in AST

**Comment by Nikoloutsos** [comment]
@krzysztofzablocki 
Is this opt-in `parseDocumentation ` enabled for sourceryPRO?

**Comment by krzysztofzablocki** [comment]
@Nikoloutsos I don't think so, but I can turn it on in next update, just waiting for SwiftSyntax to merge a PR that removes dylib dependency since it's been causing signing issues since we moved to static lib in here

**Comment by tahirmt** [comment]
@krzysztofzablocki hmm it's not working

This is my swifttemplate

```
<% for type in types.structs { -%>
    <%_ if type.name == "Colors" { -%>

import UIKit

public extension UIColor {
    <% for variable in type.variables { -%>

    // <%= variable.documentation %>
    static var <%= variable.name %>: UIColor {
        currentTheme.color.<%= variable.name %>
    }
    <% } -%>

}
    <%_ } -%>
<% } -%>

```

The `documentation` field seems to be an empty array

**Comment by krzysztofzablocki** [comment]
@tahirmt so because the parseDocumentation is changing AST model, you probably have cached data, if you run with --disableCache it generates documentation at least for `///` variant, something seems off with the multiline one, but you could look at AnnotationParser since that's what's scanning for comments

```swift
import UIKit

public extension UIColor {
    private static let colors = Colors()
    
    // ["To be used where red is needed"]
    static var appRed: UIColor {
        colors.appRed
    }
    
    // []
    static var appBlue: UIColor {
        colors.appBlue
    }
    
}
```

**Comment by tahirmt** [comment]
@krzysztofzablocki Okay now I'm very confused. I'm running this on my M1 Mac and even when I use `--disableCache` it only ever shows an empty array. I'm using Sourcery 1.8.2

**Comment by tahirmt** [comment]
Oh because I was using a config file it was ignoring the `--parseDocumentation` argument. I needed to pass `parseDocumentation: true` in the config

**Comment by tahirmt** [comment]
I'll close this now since I figured out my issues. Thank you so much for the help!
