### ISSUE TITLE
Unable to install 1.9 via CocoaPods

### ISSUE THREAD

**Issue by djbe** [krzysztofzablocki/Sourcery#1098]
Just updated my pods in an iOS project, including Sourcery from 1.8.1 to 1.9. Installation now fails with this error:
> [!] The platform of the target `Kiwi` (iOS 14.0) is not compatible with `Sourcery (1.9.0)`, which does not support `iOS`.

My project is indeed an iOS only project (`platform :ios, '14.0'`), but that shouldn't be an issue, as it previously worked with 1.8.1 (and older). The problem is [this commit](https://github.com/krzysztofzablocki/Sourcery/commit/46395777f7cf85b1ec5164b2108f246884b14d57) which incorrectly added a `s.platform  = :osx, '10.15'` to the `Sourcery.podspec` file. The other podspecs have it because they need to be built on macOS, but the general podspec doesn't (it's a tool).

Note: did a quick search for other issues but couldn't find any dupes.

**Comment by fangmobile** [comment]
same here.
`s.platform = :osx, '10.15'` just breaks any iOS only project unless they stay with 1.8.x.
