### ISSUE TITLE
Support for variables in replace, filter, contains

### ISSUE THREAD

**Issue by mnowackifm** [krzysztofzablocki/Sourcery#1104]
Hi,
I'm writing my custom template for code generation. I have been trying to find a way to use variables in Stencil functions like replace, filter, contains. However, these functions support hardcoded values only. Is there any possibility to, e.g. check if a given variable contains some text passed as another variable one or replace any occurrence of some hardcoded text with text stored in that variable?

For example, I'm able to this 
```
{% macro convertMethodName inputMethod %}
{{ inputMethod.name|replace:":","_" }}
{% endmacro %}
```

but unable to

```
{% macro convertMethodName inputMethod %}
{{ inputMethod.name|replace:":", {{ inputMethod.parameters.count }} }}
{% endmacro %}
```

**Comment by mnowackifm** [comment]
cc: @krzysztofzablocki

**Comment by krzysztofzablocki** [comment]
it's more of a Stencil question than Sourcery itself, I don't think it supports that kind of evaluation

**Comment by mnowackifm** [comment]
Ok, I'll try workaround this constraint some way. Thanks for your response!
