### ISSUE TITLE
Question: Is it possible to get a list of instantiated generic types?

### ISSUE THREAD

**Issue by ivangoremykin** [krzysztofzablocki/Sourcery#1105]
Hello,

Is it possible to get a list of instantiated generic types that are being defined in a `.swift` file?

E.g.,
- there is `struct PriorityQueue<Element>` which is being used in multiple places in the codebase
  - `PriorityQueue<Patient>`, `PriorityQueue<Job>`, etc.
- is it possible to get list of types that `PriorityQueue` has been used with, i.e. `[Patient, Job]`?

Apologies if this question has been asked previously or if it has an obvious answer that I missed 🙂

Thank you.

**Comment by krzysztofzablocki** [comment]
Sourcery only scans AST, so you could potentially find all type defined variables with those types but not code execution points, e.g. if you create local variable in a function we wouldn't know

**Comment by art-divin** [comment]
Closing, if this is still unclear, here's an example:

```swift
// sourcery: AutoMockable
struct MyStruct<A, B> {
 ...
}

// Sourcery would be able to detect alternative versions of generic constraints when constructing AST from this function
// sourcery: AutoMockable
func doSomething(_ arg: MyStruct<String, Int>) -> MyStruct<Bool, Float> {
  ...
}

// Sourcery would **not** be able to detect alternative versions of generic constraints when constructing AST from this function's body
func doSomething() {
  var temp: MyStruct<String, Int>?
  var temp2: MyStruct<Bool, Float>?
}
```

**Comment by ivangoremykin** [comment]
@art-divin All clear, thank you for the example 👍
