### ISSUE TITLE
Lookup dependancy targets for type information but not generate 

### ISSUE THREAD

**Issue by rubensamsonyan** [krzysztofzablocki/Sourcery#1108]
We are currently modularising a big app into smaller modules. We are using Sourcery to generate mocks and factories for our protocols and models and use them in unit testing.

For now, we are generating all the mocks into the unit-tests target, and to make it work, we need to specify all the other modules in the `sources` to make sourcery able to lookup for the parents and composite types. 

The issue is that all the annotated types from the other modules are generated in the current module. This causes a lot of duplication and makes the generated file huge.

E.g. we have the following modules

- Core
- Networking
- DomainCommon
- DesignSystem
- etc

The feature modules depend on all of these modules and we need to specify them in sources to generate mocks from these modules to be used in the feature modules for the testing.

What I want to do is to create a separate target for each module to include all the generated mocks for that specific module and exclude these mocks from the feature tests. Then feature tests can just include these targets. 

- Core
  - Testing
- Networking
  - Testing
- DomainCommon
  - Testing
- DesignSystem
  - Testing

```swift
import Networking.Testing

class FeatureTest: XCTestCase {
    var networkServiceMock: NetworkServiceMock
    
    override func setUp() {
        super.setUp()
        networkServiceMock = NetworkServiceMock()
    }
}
```

The issue, in this case, is that some types in the feature module can still inherit from the types specified in the other module, and without the information on these parent types the generated mocks are incomplete and do not conform to the parent protocol. 

My question is if it's possible to do it currently or if this functionality is missing. If the second option, is there a plan to add it?

**Comment by utahwithak** [comment]
Probably already have this solved, but for anyone else...
I was running into this as well for a similar architecture. Project is using Xcode plugins, I switched to passing in a specific sourcery argument that specifies the module (as a root path) that is being mocked. In the sources argument though I pass in that module as well as the directories of the modules it depends on. This is pretty easy to access in the plugin architecture as it comes through as target.dependencies. 

Then in the generator it just checks that the type.path has the module to be mocked path. This makes all the other modules type information available but only outputs the expected module.

**Comment by art-divin** [comment]
👋🏻  Hello @rubensamsonyan ,

thank you for reporting the issue.

> My question is if it's possible to do it currently or if this functionality is missing. If the second option, is there a plan to add it?

To answer your question: it is possible, using separate `.sourcery.yaml` configuration files and multiple Sourcery invocations.

For example:

```
-- App
       | - Sources
                | - ProtocolA
       | -- .sourcery.yaml
       |
--- FeatureA
         | - Sources
                 | - ProtocolB : ProtocolA
         | -- .sourcery.yaml
--- FeatureB
         | -- .sourcery.yaml
```
In this example, `FeatureA.sourcery.yaml` file's `- sources` must include path `/App/Sources/` in order to expose `ProtocolA` definition to Sourcery's AST builder in runtime. Only then the mocked `ProtocolB` would include `ProtocolA`'s members & functions.

Hope this helps, if not, please re-open 🤝
