### ISSUE TITLE
Does sourcery scan code like SwiftKitten ?

### ISSUE THREAD

**Issue by pkasson** [krzysztofzablocki/Sourcery#1110]
How does sourcery scan the code - using AST ?

Can it extract all artifacts, such as method names and bodies, vars, etc ?

Thanks !

**Comment by krzysztofzablocki** [comment]
it uses SwiftSyntax so yes

**Comment by pkasson** [comment]
Does using SwiftSyntax provide the artifacts from a file, such as function bodies, variables, etc .?

**Comment by krzysztofzablocki** [comment]
it can but I don't want Sourcery to scan bodies of functions, it's meant to focus on AST
