### ISSUE TITLE
Does Sourcery CLI supports multiple sources?

### ISSUE THREAD

**Issue by joaobzao** [krzysztofzablocki/Sourcery#1111]
Probably stupid question but I'm wondering if there's a way to pass multiple `--sources` in the Sourcery CLI?

I know it's possible to define multiple source paths with `.sourcery.yml` config file. Also I could always pass a single parent path that would include both my child paths but well didn't want to go that way 😀

Great tool btw 👏

**Comment by Nikoloutsos** [comment]
Sourcery uses Commander for making this CLI.
If you look at the implementation it is defined as `VariadicOption`. That means you can try repeating the `--sources`.

e.g `sourcery --sources "foo1" --sources "foo2"`.

Hope this answers your question 😄 

Fun fact same thing applies to these parameters as well:
```swift
 VariadicOption<Path>("sources", description: "Path to a source swift files. File or Directory."),
        VariadicOption<Path>("exclude-sources", description: "Path to a source swift files to exclude. File or Directory."),
        VariadicOption<Path>("templates", description: "Path to templates. File or Directory."),
        VariadicOption<Path>("exclude-templates", description: "Path to templates to exclude. File or Directory."),
```

**Comment by joaobzao** [comment]
Indeed you are right. 

That was my expectation but I had a typo in my previous attempt which led me to open this issue.

It works, nothing to see here. 
Thanks @Nikoloutsos. Closing the issue
