### ISSUE TITLE
Sourcery generating mocks from a protocol that does not exist anymore

### ISSUE THREAD

**Issue by kacper1703** [krzysztofzablocki/Sourcery#1116]
Hello, I have done the following:

- Created a protocol `Foo` and marked it with `AutoMockable` annotation (using default template)
- Generated the mocks
- Renamed `Foo` to `Bar`
- Generated the mocks

The result is that in the generated file I have now both `FooMock: Foo` and `BarMock: Bar`, which prevents my project from building. Temporarily I have added an empty `Foo` protocol to tackle this but there must be a way to somehow fix this. 

I have already tried reinstalling Sourcery, using `--no-cache` flag too, to no avail.

**Environment:**
Sourcery 1.9.0, using .yml config file, installed via Homebrew, M1 Pro Mac, Xcode 14.1.

**Comment by krzysztofzablocki** [comment]
can you provide sample project that reproduce the issue? it has to be something with cache

**Comment by BooNoo** [comment]
> can you provide sample project that reproduce the issue? it has to be something with cache

Faced the same problem. What could be the problem?
Version 2.0.2

**Comment by krzysztofzablocki** [comment]
I'd nuke the cache folders, this could only happen if old AST Data was loading

**Comment by art-divin** [comment]
👋🏻 Hello, thank you for creating the issue 👍🏻 

Indeed, the only source of such (mis)behaviour might be the cache. Try using `--disableCache` flag and see if the mock for the removed (un-annotated) protocol is generated still. 

If not, you can either set `--cacheBasePath` path for cache, or clean up the default cache location at `~/Library/Caches/Sourcery`.

Feel free to re-open in case this is not solved.
