### ISSUE TITLE
Distributed actors

### ISSUE THREAD

**Issue by Obbut** [krzysztofzablocki/Sourcery#1123]
Since Swift 5.7, Swift provides language-level support for distributed actors. Distributed actors can be defined using the `distributed actor` keywords. On distributed actors, one can define distributed methods using `distributed func`. For example:

```swift
distributed actor HelloActor {
    init(actorSystem: ActorSystem) {
        self.actorSystem = actorSystem
    }

    distributed func hello() {
        print("Hello!")
    }
}
```

Sourcery currently does not seem to provide a way to inspect if an actor or method is declared as `distributed`, for example with an `isDistributed` property on `Actor` or `Method`.

**Comment by Obbut** [comment]
I just realised that it is possible to query this information by getting the `modifiers` of a type or method. However, I think it would still be nice if there would be a more convenient or obvious way to query this information.

**Comment by krzysztofzablocki** [comment]
@Obbut want to propose / make a pr with the more useful API? I'd be game to merge something like this
