### ISSUE TITLE
Properties with types conforming to a protocol not detected

### ISSUE THREAD

**Issue by kdubroff** [krzysztofzablocki/Sourcery#1148]
I'm creating a script to detect types conforming to a ghost protocol so I can convert those objects to `JSONConvertibleObject` and implement a json dictionary as a property.

With `{% if not var.type.implements.JSONConvertibleObject %}{{ var.name }}{% else %}{{var.name}}.json` I'm attempting to detect if a variable conforms to the JSONConvertibleObject protocol. If so, I want its `.json` property instead of the swift object.

I've tried defining this protocol during codegen and outside of codegen. Either way, structs defined during codegen aren't detected as conforming to `JSONConvertibleObject`. I've also used `.based` instead of `.implements` but I always get `{{var.name}}` instead of `{{var.name}}.json`

```swift
import Foundation

protocol JSONConvertibleObject: Codable {
    var json: [String: Any] { get }
}

{% for type in types.implementing.JSONConvertible %}
struct {{ type.name }}: JSONConvertibleObject {
    {% for var in type.variables %}
    let {{ var.name }}: {{ var.typeName }}
    {% endfor %}

    var json: [String: Any] {        
        [
        {% for var in type.variables %}
            "{{var.name}}": {% if not var.type.implements.JSONConvertibleObject %}{{ var.name }}{% else %}{{var.name}}.json{% endif %}{% if not forloop.last %},{% endif %}
        {% endfor %}
        ]
    }
}
{% endfor %}
```

Given:
```swift
struct A: JSONConvertible {
  let a: String
  let b: B
}

struct B: JSONConvertible {
  let a: Int
}
```

I would expect to see:
```swift
struct A: JSONConvertibleObject {
  let a: String
  let b: B

  var json: [
    "a": a,
    "b": b.json
  ]
}

struct B: JSONConvertibleObject {
  var a: Int
  
  var json: [
    "a": a
  ]
}
```

However, I get `"b": b` instead in struct `A`'s `json` property

**Comment by kdubroff** [comment]
The structs are defined in different modules which is why they share the same name

**Comment by brookshanes** [comment]
i would have approved with "not sure but i trust you"
