### ISSUE TITLE
Issue with filters in if tag

### ISSUE THREAD

**Issue by sibljon** [krzysztofzablocki/Sourcery#115]
> What version of Swift are you using (swift --version)?

3

> What did you do?

```
{% for type in types.all %}

	{% for variable in type.storedVariables %}

		{% if variable.name|contains: "date" %}

			{{ variable.name }}

		{% endif %}

	{% endfor %}

{% endfor %}
```

> What did you expect to see?

I expected to see all variable names containing `date` to be printed.

> What did you see instead?

```
Scanning sources...
Scanning sources... 25% (4 files)
Scanning sources... 50% (4 files)
Scanning sources... 75% (4 files)
Found 32 types.
Loading templates...
Loaded 1 templates.
Generating code...
'if' expression error: dangling token
```

Is this just a limitation of the Sourcery parser? I don't get the `dangling token` error if I use anything that doesn't contain a dot as the input to `contains`. I've also tried the following syntax:

```
// Exception: this class is not key value coding-compliant for the key name|contains:"date"
variable.name|contains:"date"

// Danging token error
variable.name | contains:"date"
variable.name | contains: "date"
variable.name |contains: "date"
```

**Comment by ilyapuchka** [comment]
That's a known issues - #102 We will need support for that in Stencil (https://github.com/kylef/Stencil/issues/90)

**Comment by krzysztofzablocki** [comment]
@ilyapuchka #106 already has if filter support, I'm waiting on sourcekitten change to merge it, but maybe I should go ahead with blocking version and we can add the disable cache later on if sourcekitten accepts that
