### ISSUE TITLE
Enum with rawValue parses comment

### ISSUE THREAD

**Issue by rocketnik** [krzysztofzablocki/Sourcery#1154]
The rawValue of enum cases is parsed wrong in sourcey 2.0.1.
As you can see in the output, the comment "some comment" is part of the rawValue.
I would expect the comment not to be part of the rawValue.
Currently wrong: `zero = 0 // some comment`
Expected correct: `zero = 0`
Workaround until fixed: put the comment on an extra line

source.swift
```
public enum SomeEnum: Int {
    case zero = 0 // some comment
    case positive = 1
    case negative = -1
}
```

template.ejs
```
<%
function asdf() {
    const typesEnums = types.all.filter(type => type.kind === "enum")
    return typesEnums
        .map((theEnum) =>
            theEnum.cases.map((enumCase) =>
                `${enumCase.name} = ${enumCase.rawValue}`
            )
            .join("\n")
        )
}
%>
<%-
asdf()
%>
```

output
```
// Generated using Sourcery 2.0.1 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

zero = 0 // some comment
positive = 1
negative = -1
```

**Comment by art-divin** [comment]
Hello @rocketnik 👋,

thank you very much for providing enough details to reproduce the bug.

I have reproduced it in minutes and I am investigating the root cause.

Will keep you posted ⏲️

**Comment by art-divin** [comment]
#1176 resolves this issue
