### ISSUE TITLE
Extracting generic type name from an extension

### ISSUE THREAD

**Issue by bdbergeron** [krzysztofzablocki/Sourcery#1160]
I have an extension on a Swift `Collection` type:

```swift
protocol StubProviding {
  static var stub: Self { get }
}

struct Person: StubProviding {
  let name: String

  static var stub: Person {
    .init(name: "John")
  }
}

extension [Person]: StubProviding {
  static var stub: [Person] {
    [
      .init(name: "John"),
      .init(name: "Jane"),
    ]
  }
}
```

I'm trying to generate some code for all objects that conform to `StubProviding`, grouping the generated code output into a file named by the core object type. So for the example code above, I'd like the generated code for both `Person` and `[Person]` to be placed in `Person.generated.swift`.  If there were another struct, e.g. `Car`, it's generated code should be in `Car.generated.swift`.

It seems Sourcery parses an extension like this as a simple `Type` that doesn't give much to play with. I'm still relatively new to writing templates so I'm wondering if there's something I may have missed.

**Comment by krzysztofzablocki** [comment]
Extensions are combined with original types in the final AST phase, so there is no distinction between whether it was an extension or not, so conformance would appear on the original type, don't remember how this plays with unknown types like Array here, normally if there is an extension into an unknown type it would register that type into AST system but only expose extension provided AST

You can specify file code should be generated with annotations:

```swift
{% for type in types.all %}
// sourcery:file:Generated/{{ type.name}}+TemplateName
// sourcery:end
{% endfor %}
```
