### ISSUE TITLE
AutoMockable: Ability to skip duplicate mocks creation while scanning external module sources

### ISSUE THREAD

**Issue by dbulaienko** [krzysztofzablocki/Sourcery#1164]
Hey folks, I've stumbled across the following problem - sourcery doesn't generate the funcs/variables for the internal protocol which conforms to some protocol that is defined in the external module, **which is expected**, given that the path to external module isn't specified in `"sources"`:
```
// Some shared module "Foo"
// sourcery: AutoMockable
public protocol FooProtocol { 
    func doFoo()
}

// My current module `Bar`
import Foo
// sourcery: AutoMockable
protocol BarProtocol: FooProtocol {
    func doBar()
}

// results in mock that fails to compile due to `doFoo()` is missing:
final class BarMock: BarProtocol {
    lazy var doBarMockFunc = ...
    func doBar() {...}
}
```

**Workaround:** This can be solved by extending the `"sources"` with the path to `Foo` module directory, as now it can properly scan the `FooProtocol`, but a side-effect here is that it generates the `FooMock` in my current module, which I would like to avoid:
```
final class BarMock: BarProtocol {
    lazy var doBarMockFunc = ...
    func doBar() {...}
    lazy var doFooMockFunc = ...
    func doFoo() {...}
}

// This mock is now duplicated in both `Bar` and `Foo` module, which is desirable to keep only in `Foo` module.
final class FooMock:  FooProtocol {
    lazy var doFooMockFunc = ...
    func doFoo() {...}
}
```

**Expected:** Basically what I would like to achieve is some extra argument to sourcery config file that will allow to scan sources for types but at the same time SKIP the actual code generation for that particular path. Some sort of 
```
sources:
     includeTypesOnly: 
         - {path to external module}
      include:
         - {existing path handling goes here}
...
```

Probably there is already a better way of dealing with use-case like that, I would really appreciate any help on that.
Thanks

**Comment by krzysztofzablocki** [comment]
You can use annotations to skip mock generation, so just change your template to skip those classes that have `skipMocking`

**Comment by dbulaienko** [comment]
Thanks @krzysztofzablocki , indeed that works!
