### ISSUE TITLE
Failed to link file

### ISSUE THREAD

**Issue by SylvainDruaux** [krzysztofzablocki/Sourcery#1166]
Hello,

I am using Xcode 14.3.1 (Swift version 5.8.1).

I removed the default file AutoMockable.generated.swift from my project and modified AutoMockable.stencil to generate one file per mock by adding this line among other changes:

// sourcery:file:{{ type.name }}Mock

I also used the “link” key in my ".sourcery.yml" file and added a script to my build phase to run Sourcery.

Everything works as expected, but I still get this warning after a build:

Failed to link file at /MyProject/MyProjectTests/Sourcery/AutoMockable.generated.swift to /MyProject/MyProject.xcodeproj. The file at path /MyProject/MyProjectTests/Sourcery/AutoMockable.generated.swift doesn't exist

Does anyone know why this is happening and how to fix it?

**Comment by art-divin** [comment]
Hello @SylvainDruaux, 

Thank you very much for reporting the issue.

I will update you on this and in a very nice way, I'll keep you posted 👍

**Comment by art-divin** [comment]
Hello @SylvainDruaux ,

as promised, [here's a link](https://github.com/qonto/XcodeGroupSync) to a swift script, which synchronizes contents of a folder with files in Xcode project's group.

Feel free to use it and send any feedback 🙏🏻
