### ISSUE TITLE
Some unit tests are executed for too long

### ISSUE THREAD

**Issue by art-divin** [krzysztofzablocki/Sourcery#1180]
## Context

The following list of unit tests are being executed for too long, like if they were to generate files with more than hundreds of thousands of lines of code.

## List

SwiftTemplate__has_same_templates_in_outputs_as_in_inputs (98.837 seconds)
SwiftTemplate__return_all_outputs_values (97.162 seconds)
SwiftTemplate__with_existing_cache__and_missing_build_dir__generates_the_code (27.950 seconds)
SwiftTemplate__has_no_stdout_json_output_if_isDryRun_equal_false___also_default_value_ (23.111 seconds)
SwiftTemplate__rethrows_template_runtime_errors (18.461 seconds)
SwiftTemplate__rethrows_template_parsing_errors (17.133 seconds)
SwiftTemplate__handles_file_includes_without_swift_extension (14.707 seconds)
SwiftTemplate__handles_includes_without_swifttemplate_extension (14.581 seconds)
SwiftTemplate__handles_file_includes (14.430 seconds)
SwiftTemplate__handles_includes (14.331 seconds)
SwiftTemplate__handles_includes (14.301 seconds)
SwiftTemplate__handles_file_includes (14.204 seconds)
SwiftTemplate__handles_includes_without_swifttemplate_extension (14.133 seconds)
SwiftTemplate__handles_file_includes_from_included_files_relatively (14.129 seconds)
SwiftTemplate__handles_file_includes_from_included_files_relatively (14.109 seconds)
SwiftTemplate__handles_includes_from_included_files_relatively (14.093 seconds)
SwiftTemplate__handles_free_functions (14.074 seconds)
SwiftTemplate__handles_free_functions (14.060 seconds)
SwiftTemplate__handles_includes_from_included_files_relatively (14.057 seconds)
SwiftTemplate__handles_file_includes_without_swift_extension (14.019 seconds)
SwiftTemplate__rethrows_errors_thrown_in_template (13.725 seconds)
SwiftTemplate__generates_correct_output (13.454 seconds)
SwiftTemplate__generates_correct_output__if_isDryRun_equal_true (13.121 seconds)

**Comment by krzysztofzablocki** [comment]
Can't really do anything about this, this is due to SwiftTemplates being actual compiled programs, when I work on Sourcery I usually just turn them off for TDD workflow and only run them at the end to make sure everything is still fine (usually is since we cover most stuff via normal tests)

**Comment by krzysztofzablocki** [comment]
I don't feel like it's worth it TBH, those are more like integration tests anyway, they are order of magnitude slower so it wouldn't be fast enough for TDD workflow anyway

**Comment by art-divin** [comment]
Thanks, well noted. 👍
