### ISSUE TITLE
Xcode fails to find Sourcery. Shows Sourcery not installed error

### ISSUE THREAD

**Issue by r3econ** [krzysztofzablocki/Sourcery#1185]
I followed the documentation and installed Sourcery using `homebrew`. Unfortunatelly, Xcode is unable to run Sourcery although it is installed. It shows the following error:

<img width="367" alt="Screenshot 2023-07-27 at 12 26 43" src="https://github.com/krzysztofzablocki/Sourcery/assets/505054/fde63902-dc55-4e09-959a-9ab4c4439ffb">

```
Sourcery not installed. Install via 'brew install sourcery'
```

However, I can see that Sourcery is installed, I can confirm it by running:

```
% which sourcery
/opt/homebrew/bin/sourcery
```

Sourcery build phase:

<img width="800" alt="Screenshot 2023-07-27 at 12 33 51" src="https://github.com/krzysztofzablocki/Sourcery/assets/505054/98e59210-c350-4c27-a5c7-8852a77ccce8">

I am able to manually generate the mocks by running Sourcery  in Terminal using `sourcery --sources . --templates . --output .` However. What could be the reason that Xcode can't find/run sourcery?

My system setup:
- macos Ventura 13.4.1 (22F82)
- Xcode Version 14.3.1 (14E300c)
- Sourcery 2.0.3

**Comment by jimmya** [comment]
That's a known issue with running brew tools from Xcode build phases. A solution can be found here: https://stackoverflow.com/a/66003612

By adding 
```
export PATH="$PATH:/opt/homebrew/bin"
```
to your buildphase.

**Comment by r3econ** [comment]
Works great now, thanks!
