### ISSUE TITLE
Mintfile issue when a new version of Sourcery is released 

### ISSUE THREAD

**Issue by stefanomondino** [krzysztofzablocki/Sourcery#1201]
Ciao @krzysztofzablocki  and all maintainers,

I am using Sourcery with Mint on different projects (and saving a lot of time with it btw - thanks!)

I have a Mintfile that gets bootstrapped (`mint bootstrap`) and has a locked version of Sourcery in it. 

Then in xcode build phases I'm using `mint run sourcery ...` with my config files to "do my things™".

The issue is that  every time you folks release a new version of Sourcery by tagging that on Github, I get the following error:

```
🌱 Finding latest version of Sourcery
🌱 Cloning Sourcery 2.1.0
🌱 Resolving package
error: 'github.com_krzysztofzablocki_sourcery': Invalid manifest (compiled with: ["/usr/bin/swiftc", "-vfsoverlay", "/var/folders/ms/821j3r5j00j7h4fyd1txrrfm0000gn/T/TemporaryDirectory.eXamI4/vfs.yaml", "-L", "/Applications/Xcode-14.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-lPackageDescription", "-Xlinker", "-rpath", "-Xlinker", "/Applications/Xcode-14.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-target", "arm64-apple-macosx12.0", "-sdk", "/Applications/Xcode-14.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk", "-F", "/Applications/Xcode-14.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks", "-I", "/Applications/Xcode-14.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib", "-L", "/Applications/Xcode-14.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib", "-swift-version", "5", "-I", "/Applications/Xcode-14.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/pm/ManifestAPI", "-sdk", "/Applications/Xcode-14.3.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk", "-package-description-version", "5.8.0", "/private/var/folders/ms/821j3r5j00j7h4fyd1txrrfm0000gn/T/mint/github.com_krzysztofzablocki_Sourcery/Package.swift", "-Xfrontend", "-disable-implicit-concurrency-module-import", "-Xfrontend", "-disable-implicit-string-processing-module-import", "-o", "/var/folders/ms/821j3r5j00j7h4fyd1txrrfm0000gn/T/TemporaryDirectory.wp5tjT/github.com_krzysztofzablocki_sourcery-manifest"])
<unknown>:0: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX'
<unknown>:0: error: unable to load standard library for target 'arm64-apple-macosx12.0'
🌱 Encountered error during "swift package resolve". Use --verbose to see full output
🌱  Failed to resolve Sourcery 2.1.0 with SPM
```

While in my Mint file I have locked it to `2.0.3` and using `mint run sourcery --config sourcery.yml` to run it.

If I upgrade the current version to `2.1.0` in the Mintfile and bootstrap again, everything is fine. But I get many different project failing on pipelines at the same time and this is not easy to immediately fix on our side.

Also, if after installing the 2.1.0 on my machine I move back my Mintfile to 2.0.3, also it seems to be working again.

Note: 2.1.0 is not even an official release in the "releases" page of github (at the moment I am writing).

Do you have any idea why this is happening? I've seen some comments about a fixed rpath in past issues, but I also see Mint as officially supported, so this should really not be an issue.

Cheers :)

**Comment by art-divin** [comment]
Hi @stefanomondino ,

thank you for your comment.

In fact, I am working on releasing 2.1.0 since yesterday, and so once I have the packed binary and release notes generated as always, that release will be available as a normal release.

I have faced a number of issues but should be resolved now (running tests).

I will keep you posted, and sorry for the noise.

I'd like to automate release process via GitHub actions for the next release to make it very smooth for everyone.

Kind regards

**Comment by stefanomondino** [comment]
Hi @art-divin ,
Thank you for the effort and for replying me back.

Don't get me wrong: for me it's not a particular problem if the new version is properly released or not... take your time to properly draft it etc, it's not critical to me.

The issue is that tagging Sourcery with a new tag is affecting the OLD version, which worked right until the moment the tag was added. That's most certainly a bug in the process, or at least it is if Mint is stated as supported (in the readme). 

Do you think it's something that can be addressed?

**Comment by art-divin** [comment]
> The issue is that tagging Sourcery with a new tag is affecting the OLD version

Now this is weird.
I might have messed something up with tags, even though I do simply run the scripting which was working before, without changes. In fact this is my first release for that matter, but I do get the experience I need to integrate GH actions for releasing. 

So please 🐻 with me.

**Comment by stefanomondino** [comment]
@art-divin it's definitely not your fault (or at least not this release fault), as this behavior was happening also in all past releases also before 2.0.

**Comment by art-divin** [comment]
I see, it sounds a bit weird. 

In the log you posted: "Finding latest version of Sourcery" is mentioned. It means that `.lockfile` for `mint` is ignored. Otherwise the version would be locked. It is the same for `Gemfile.lock` and `Podfile.lock`. 

Since you are using Xcode build phase, to quote, "`in xcode build phases I'm using mint run sourcery`", I suspect there is something weird about current directory, where `mint` might not find that lock file and thus, presumes there is no need to lock the version? 

Such behaviour would explain why this happens.

Update about the release: [2.1.0 was published](https://github.com/krzysztofzablocki/Sourcery/releases/tag/2.1.0) 😓 It took me 2 days 🥇 🤓 🥇

**Comment by stefanomondino** [comment]
@art-divin you actually pointed me in the right direction I guess...

First of all, Mint doesn't have a mintfile.lock, meaning that the Mintfile *IS* the file providing locks (you don't get the `~>` syntax with semver versions like Gemfile, Podfile etc. You put in there the proper version and that's it). And the version is locked in there.

But you are right, I have something "weird" in my folder setup: since I am using Tuist and a modular architecture, I have split my project in different folders, while Mintfile is being kept in the root one. I am providing proper paths for Sourcery config files, but it never occurred to my mind that also Mint should look for its Mintfile in the proper folder (that's an option I should provide to `mint run`, something like `mint run -- mintfile "../../Mintfile" sourcery ...`).

More details in [this issue](https://github.com/yonaskolb/Mint/issues/263)

Let me try tomorrow if this works properly - I also think that I should **really** know this is fixed only once you'll have released the next version (2.1.1 or so) :D 
OR... I can try to fork Sourcery repo, have mintfile point to that, push a new random tag and see what happens.

But seriously, thank you for taking the time for analyzing this.

**Comment by art-divin** [comment]
> Let me try tomorrow if this works properly - I also think that I should really know this is fixed only once you'll have released the next version (2.1.1 or so) :D
OR... I can try to fork Sourcery repo, have mintfile point to that, push a new random tag and see what happens.

That's a good option. Looking forward to hearing if this is resolved, if not, we can dig deeper 🤿 

> But seriously, thank you for taking the time for analyzing this.

Absolutely, my pleasure 🤝

**Comment by art-divin** [comment]
👋🏻  Hello @stefanomondino ,

I hope you are having the nicest day 🌻 

Could you please tell me, did you face this issue with 2.1.1 release?

Thanks 🙏🏻

**Comment by stefanomondino** [comment]
Ciao @art-divin ,
I can confirm that, let me leave the solution for "future people".

If you are using a Mintfile in your root folder, but your xcodeproj is in another subfolder and you are using sourcery (or any other tool) from a build phase, run it with:

`mint run --mintfile ../../Mintfile sourcery --config yourconfig.yml`

Of course you have to change the mintfile path and yourconfig.yml path accordingly and relative to your xcodeproj folder.
