### ISSUE TITLE
AssociatedType is missing annotaions property

### ISSUE THREAD

**Issue by lagubull** [krzysztofzablocki/Sourcery#1214]
Hi!

Just like other entities, e.g: Var, Type I would like to be able to annotate associatedTypes so that i can provide a specific value for them so that classes with generic which types cant be inferred can still be mocked.

Thank you!

**Comment by art-divin** [comment]
Hey @lagubull ,

I have implemented it for protocols with associated types, in a way that the generated mock is exposed as a generic requirement of the generated class.

Do you find your use case fulfilled?

See #1345 for more info
