### ISSUE TITLE
Malformed artifactBundle

### ISSUE THREAD

**Issue by johndelong** [krzysztofzablocki/Sourcery#1216]
Since release version 2.1.0, it seems that the contents of release artifact `sourcery-{version}.artifactbundle` may be malformed. As the associated `info.json` file describes, I believe the file content hierarchy should be as follows:

- info.json
- sourcery/bin/sourcery

However, the current artifact bundles have the following file hierarchy:
- info.json
- sourcery/bin/sourcery/bin/sourcery

**Comment by art-divin** [comment]
Thank you @johndelong 👋🏻 ,

I'll make sure to fix this. Unsure which part of the automation fails, but it is straightforward to fix it manually in the meantime. I won't close this issue after the next release though, to make the actual fix in the future.

Cheers 🍉

**Comment by blindspotbounty** [comment]
+1, thank you for looking into it.

**Comment by art-divin** [comment]
Issue should be resolved in 2.1.3
