### ISSUE TITLE
Sourcery thinks directory doesn't exist when run from Xcode15.01 Build Phase

### ISSUE THREAD

**Issue by infiniteNIL** [krzysztofzablocki/Sourcery#1221]
I'm on Xcode 15.01, macOS Sonoma, and I've installed Sourcery via brew. I have the latest which is version 2.1.2

Here's the command I run in a build phase.

/opt/homebrew/bin/sourcery --sources "${SRCROOT}" --templates "${SRCROOT}/Sourcery/Templates" --output "${SRCROOT}/Sourcery/GeneratedCode"

and I get the following error:

error: '/Users/rod/Documents/infiniteNIL/Development/InstallSync/installsync-ios/InstallSync' does not exist or is not readable.

When I run from the terminal everything works fine and the build phase worked fine before. I haven't run it in a while, but in worked in the previous version of macOS and Xcode.

I think it might be a sandbox issue, but I don't know how to work around it.

**Comment by infiniteNIL** [comment]
I found the problem. Xcode 15 adds a new User Script Sandboxing build setting and defaults it to yes. Setting this to no fixes the problem.

**Comment by art-divin** [comment]
Hello @infiniteNIL 👋🏻 ,

firstly, thank you very much for creating the issue. This gives visibility for the problem so others can quickly solve it in case they face it. 👍🏻 

Lastly, thanks for sharing the solution you've found 🤝
