### ISSUE TITLE
Disable Circle-CI project

### ISSUE THREAD

**Issue by art-divin** [krzysztofzablocki/Sourcery#1226]
👋🏻  Hello @krzysztofzablocki , 

Since GitHub actions are working well and there is no consistency issue with the results of integrations,
I suggest to disable CircleCI project for good.

What do you say? 🚂

**Comment by krzysztofzablocki** [comment]
go ahead :)

**Comment by art-divin** [comment]
@krzysztofzablocki I have tried, but I do not have enough permissions on CircleCI do disable the project.

**Comment by krzysztofzablocki** [comment]
ok turned it off
