### ISSUE TITLE
Broken Cache Logic, as hash of string is not unique

### ISSUE THREAD

**Issue by pavel-trafimuk** [krzysztofzablocki/Sourcery#1230]
Hello, we're using Sourcery on our project (dozens of difficult templates), so thank you for your hard job

Currently our all generations took up 80 seconds and I'm trying to find how to improve it, checking cache I found that it sometimes it doesn't work for the same 1-5 files in each module.
After research I found that Sourcery use 'hash' for strings, but hash logic for strings is not unique.
(I replaced NDA words with XXXXX)

E.g. 
        let line1 = "/Users/pavel.trafimuk/Developer/Viber_iOS/Classes/Assembly/Modules/ViberXXXXManager/Dependencies/LastXXXXXXNotificationProcessorDependency.swift"
        let line2 = "/Users/pavel.trafimuk/Developer/Viber_iOS/Classes/Assembly/Modules/ViberXXXXManager/Dependencies/NewXXXXXXeNotificationProcessorDependency.swift"

In both cases we receive 5181768815062482058

In results Sourcery doesn't find valid cache (unarchived file shows another modification date) and replace it with another classes. On the next run will be the same

**Comment by krzysztofzablocki** [comment]
hey, where do you think it use's string hash for cache invalidation? we use modified date or sha256 unless I missed some pr change that would do something else

**Comment by pavel-trafimuk** [comment]
Sorry, forgot to insert the code
`        let artifactsPath = cachesPath + "\(path.string.hash).srf"`
As I understand that you use .hash instead of .hashValue to have the same values during multiple running of the app. But seems like .hash uses a small parts of the string to calculate itself

**Comment by krzysztofzablocki** [comment]
I guess we can just replace that with sha256 as well

**Comment by pavel-trafimuk** [comment]
sha256 of filename or of content? I'm afraid about performance)

**Comment by krzysztofzablocki** [comment]
the bug you are talking about is the filename just, we don't do hashing on contents because modified date is faster and more convenient, if you can run local sourcery build on your codebase and see if it fixes your issue that would be great, you could send the pr with that line change too if that works

**Comment by pavel-trafimuk** [comment]
as quick solution I use:

`extension String {
    var uniqueHashValue: String {
        stride(from: 0, to: count, by: 40).map {
            let start = index(startIndex, offsetBy: $0)
            let end = index(start, offsetBy: 40, limitedBy: endIndex) ?? endIndex
            let substing = String(self[start..<end])
            return "\(substing.hash)"
        }.joined(separator: "-")
    }
}`

I know that it doesn't look great, just reduce collision)


BTW, quick question, I assumed that if template was not modified, source files were not modified too -> rendering is obsolete and we can skip it. What do you think?

**Comment by pavel-trafimuk** [comment]
`let artifactsPath = cachesPath + "\(path.string.sha256()?.addingPercentEncoding(withAllowedCharacters: .alphanumerics) ?? "\(path.string.hash)").srf"`
helped, problem was gone, thanks! will prepare PR
