### ISSUE TITLE
Suppor for `package` access modifier

### ISSUE THREAD

**Issue by mr-swifter** [krzysztofzablocki/Sourcery#1234]
In Swift 5.9 a new access level modifies [`package`](https://github.com/apple/swift-evolution/blob/main/proposals/0386-package-access-modifier.md) has been introduced. It should be supported in Sourcery, currently it falls back to `internal`.

**Comment by art-divin** [comment]
I wanted to include this into `2.1.3` release, but it seems that the fix would not be as trivial as it seemed to be.
I'll keep you posted 📰
