### ISSUE TITLE
Release 2.1.3 to Homebrew and cocoapods

### ISSUE THREAD

**Issue by art-divin** [krzysztofzablocki/Sourcery#1248]
👋🏻  Hello @krzysztofzablocki ,

since the upload of the release to Homebrew and Cocoapods is not automated yet, and you are the owner of these (at least from my understanding how things work), could you please handle it?

And also, if this can be automated somehow (i.e. release to cocoapods) -> I'd appreciate pointers.

Cheers 👍🏻

**Comment by arbyruns** [comment]
@art-divin do you see this also happening with 2.1.4?

**Comment by art-divin** [comment]
So, after 2 weeks of trying, I was able to successfully run:

```
brew bump-formula-pr sourcery --version 2.1.4
```

; however, 2.1.4 was released 2 days ago to homebrew without my intervention.

BUT `rake release:homebrew` would never work, no matter how many times I have tried, it would always fail on one or the other step. In my opinion, `rake release:homebrew` is outdated and should be removed.

Regarding Cocoapods:

I've made countless attempts running `rake release:cocoapods`, and it was always failing with:
```
    - ERROR | [Sourcery/CLI-Only] file patterns: The `preserve_paths` pattern did not match any file.
```

It would also fail with this error unless I would bump version of OSX to 10.15:
```
    - NOTE  | [iOS] xcodebuild:  clang: error: SDK does not contain 'libarclite' at the path '/Applications/Xcode-15.1.0-Release.Candidate.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a'; try increasing the minimum deployment target
```

Version 2.1.4 was pushed as a result of trial and error configuring different filepath of CLI-Only subspec. That is, the pushed version **does not work** with `CLI-Only` podspec - the `preserve_paths` is set to `*/bin` which does not exist, i.e. everything is deleted, that is, podspec does not exist, or is not installable via `pod install`.

I have debugged ruby scripts and for one or the other reason, `bin` folder cannot be found during validation of `CLI-Only` subspec.

@krzysztofzablocki did you see this error before? What do you suggest to do with CLI-Only? Thanks 🙏🏻

**Comment by art-divin** [comment]
I'll close this issue since 2.1.4 was released to brew and cocoapods. But the question about `CLI-Only` remains open, waiting for Krzysztof's response.
