### ISSUE TITLE
Missing bin folder with 2.1.3

### ISSUE THREAD

**Issue by arbyruns** [krzysztofzablocki/Sourcery#1255]
I recently updated from `1.6.1` and I noticed that on `2.1.3` the bin file that holds the `CLI` is missing now. Has this moved or removed?

**Comment by art-divin** [comment]
Hello @arbyruns ,

thank you for creating the issue.

Are you referring to the structure of the artifactbundle, or to Sourcery archived executable?
The structure of these as of 2.1.3 version, is as follows:

|artifactbundle.zip|sourcery.zip|
:-:|:-:
<img width="365" alt="image" src="https://github.com/krzysztofzablocki/Sourcery/assets/1614869/955c5a8a-1838-4749-824a-7f19df6cf187">|<img width="365" alt="image" src="https://github.com/krzysztofzablocki/Sourcery/assets/1614869/bdd77b68-c9e5-4dc5-b437-d2f85efd5bde">

In version 1.6.1, the structure was as follows:

sourcery.zip
:-:
<img width="364" alt="image" src="https://github.com/krzysztofzablocki/Sourcery/assets/1614869/6c357d0a-a822-4d72-a256-172b5670af1e">

**Comment by arbyruns** [comment]
This is what I have for `2.1.3`

![image](https://github.com/krzysztofzablocki/Sourcery/assets/2520545/7df08ee7-304b-4c7c-b74a-4839b550d021)

This is what I had for `1.6.1`

![image](https://github.com/krzysztofzablocki/Sourcery/assets/2520545/0cfefef2-b8ba-457a-8331-59a009c7d2fa)

Could this be because I'm pulling in via a commit vs a version? 
`pod 'Sourcery', :git => 'https://github.com/krzysztofzablocki/Sourcery.git', :commit => '23179e8'`

**Comment by art-divin** [comment]
@arbyruns looks exactly like it. In fact, version 2.1.3 was not released yet (cc @krzysztofzablocki ) as managed by #1248.
What you want to try is using 2.1.2 version, which should be available on cocoapods.

Please check. If 2.1.2 would not be available, 2.1.1 should be.

I hope Krzysztof would have a minute to release 2.1.3 to cocoapods and homebrew, because I have no idea (or permissions) how to do it exactly.

**Comment by arbyruns** [comment]
I came across #1248 today after spending a better part trying to get `2.1.3` added today 😄 .

I'll hold off and see if `2.1.4` gets released soon. Thanks! 

We can probably close this out?

**Comment by art-divin** [comment]
Thanks, closed this issue, and I hope #1247 would automate releases to cocoapods and homebrew. Currently I am automating macOS & Linux releases ⏲️
