### ISSUE TITLE
Missing bin folder with 2.1.4

### ISSUE THREAD

**Issue by arbyruns** [krzysztofzablocki/Sourcery#1258]
I recently updated from `1.6.1` and I noticed that on `2.1.4` the bin file that holds the `CLI` is missing now. Has this moved or removed? 

This is what I have for `2.1.4`

![image](https://github.com/krzysztofzablocki/Sourcery/assets/2520545/7df08ee7-304b-4c7c-b74a-4839b550d021)

This is what I had for `1.6.1`

![image](https://github.com/krzysztofzablocki/Sourcery/assets/2520545/0cfefef2-b8ba-457a-8331-59a009c7d2fa)

Could this be because I'm pulling in via a commit vs a version? 
`pod 'Sourcery', :git => 'https://github.com/krzysztofzablocki/Sourcery.git', :commit => '8df9735'`

**Comment by art-divin** [comment]
Hey @arbyruns ,

Sourcery 2.1.4 was released to cocoapods just now.

However, I could not get `CLI-Only` version to work. That means that 2.1.4 cannot be integrated as:
```
pod 'Sourcery', '= 2.1.4', :subspecs => ['CLI-Only']
```

2.1.4 is only installable as (version can be omitted):
```
pod 'Sourcery', '= 2.1.4'
```

**Comment by art-divin** [comment]
> Thank you, is CLI-Only being removed going forward?

Not sure, I just need to figure out how to make it work, that's all 👍🏻

**Comment by art-divin** [comment]
@arbyruns 2.1.5 should support `CLI-Only` pod as before 2.1.4.

**Comment by arbyruns** [comment]
Thanks!
