### ISSUE TITLE
Homebrew does not include latest version (2.1.4)

### ISSUE THREAD

**Issue by r3econ** [krzysztofzablocki/Sourcery#1259]
Problem:

- Looks like homebrew does not include the latest version of Sourcery. The 2.1.4 is missing.
- `brew up` does not help (yields `Already up-to-date`) and `brew install sourcery` installs version 2.1.3

Results of `brew info sourcery`:

```bash
❯ brew info sourcery

==> sourcery: stable 2.1.3 (bottled), HEAD
Meta-programming for Swift, stop writing boilerplate code
https://github.com/krzysztofzablocki/Sourcery
/opt/homebrew/Cellar/sourcery/2.1.3 (7 files, 50.8MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-01-16 at 15:21:35
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/s/sourcery.rb
License: MIT
==> Requirements
Required: Xcode >= 14.3 (on macOS) ✔
==> Options
--HEAD
```

Is there a way to install Sourcery `2.1.4` via homebrew?

**Comment by arbyruns** [comment]
Also having this issue and is blocking us from completing any additional work.

**Comment by arbyruns** [comment]
Thanks, I don't see that it's been added to the pod spec repo though.

https://github.com/CocoaPods/Specs/tree/master/Specs/9/2/2/Sourcery
