### ISSUE TITLE
Separate output file for each source

### ISSUE THREAD

**Issue by ugoArangino** [krzysztofzablocki/Sourcery#126]
I think it would be nice that `Sourcery` will create separate output files for each source wenn the `output` parameter is a folder.

### Example

```
sourcery source/ templates/ output/

├─ source
│   ├── Person.swift
│   └── Car.swift
├─ templates
│   ├── Coding.stencil
│   └── Description.stencil
└─ output
    ├── Person+Coding.swift
    ├── Person+Description.swift
    ├── Car+Coding.swift
    └── Car+Description.swift
```

**Comment by krzysztofzablocki** [comment]
The reason we either generate a single file, or file per template is that if we are going to support the proposed format it will require more user maintenance, when you want to add another type to conform to automatic generation you'll need to remember to manually add new generate file to project.

**Comment by ilyapuchka** [comment]
I think it's a good thing to have too. Noticed that while working on LinuxMain template. Linked tests suites have separate manifest files for each test module, also generated. We instead can only put everything in one file. It's not a big deal of course as you don't have to maintain generated code much, but still it hurts code readability especially for large code bases.

The problem with creating smth like `Person+Coding.swift` is that we don't have guaranty that each scanned file has just a single type, so what name we should use?

When I was thinking about that I was thinking about using some comments, similar to annotations in the template itself, like :

`// output: {{ file.path }}/{{ file.name }}+Coding.generated.swift` - will tell to create file next to input file in "single-file" mode
`// output: {{ output.path}}/Coding/{{ file.name }}+Coding.generated.swift` - will tell to create file in output/Coding/ path

(the same for Swift templates just with different syntax)

Also this will require something similar as #45 - to provide list of types defined in a current file.

**Comment by ugoArangino** [comment]
> @ilyapuchka : The problem with creating smth like Person+Coding.swift is that we don't have guaranty that each scanned file has just a single type, so what name we should use?

One possibility is to create separate files based on the source. 
An alternative way can be to create separate files for each type. 
I think based on the source will be make more sense, because it is the structure the developer has chosen.

**Comment by krzysztofzablocki** [comment]
if anything then we'll do it per (original definition file, because a type can be split across multiple files) file, it will already cause us to have 3 different output modes (single file, per template, per file x per template). 

@ilyapuchka I don't think we should complicate templates with options like that, at least until we reach 1.0

**Comment by muescha** [comment]
How about an PathResolver protocol where you ship a DefaultPathResolver and then it is up to the user to create a specialized class for a different pattern / output modes

**Comment by ThePredators** [comment]
Any news about the generation per source file or that option has been forgotten ?

**Comment by krzysztofzablocki** [comment]
@muescha I'd be game if you wanted to generalize this in some kind of form like that so that maintenance is not hard
