### ISSUE TITLE
Watch mode only watches sources from last configuration file when passing multiple paths to configuration files using `--config` command line options

### ISSUE THREAD

**Issue by fvazquez-travelperk** [krzysztofzablocki/Sourcery#1277]
[Documentation](https://github.com/krzysztofzablocki/Sourcery/blob/b37ea718c07ddd104e2ddba88bb1a2c9c2321776/guides/Usage.md?plain=1#L18) states that passing multiple paths and adding multiple configurations inside the same file are equivalent. But in the first case, if `sourcery` is invoked with `--watch`, only the source files defined inside the last processed file are actually watched. 
That forces us to merge all configuration keys from several files into a single file before invoking `sourcery` as a workaround.

If multiple `--config` flags are not intended to work with `--watch` I think the documentation should reflect that.

**Comment by art-divin** [comment]
Thank you for reporting, @fvazquez-travelperk 🤝 

Looking into it 🕵🏻

**Comment by art-divin** [comment]
Hey @fvazquez-travelperk ,

I have just tested, passing the following to Sourcery:

```
--config /........../Documents/Projects/x/.sourcery.yaml
--watch
--disableCache
--parseDocumentation
--serialParse
--config /.........../1/.sourcery_without_project.yml
```

and changes in Sources specified in both `--config` files are detected and sources are regenerated automatically.
I wonder which exact set of files, or maybe, how many configuration files did you try to supply to Sourcery? There should be no limit but still, maybe you were trying something extraordinary 👀 

Please share any additional info. 🙏🏻

**Comment by fvazquez-travelperk** [comment]
@art-divin 

Thanks for taking a look. We have one configuration file per module, and more than 30 modules. I didn't test with just two config flags, but we tested multiple times with the final setup and consistently found that changes to sources defined in the last configuration files were immediately applied, while others didn't. As we have many independent modules, there isn't much overlapping between the sources being watched for each configuration file.

**Comment by art-divin** [comment]
I see, probably it comes down to some sort of a system limitation in macOS or even UNIX on the number of file descriptors opened, but I am just guessing here without brushing up my knowledge in this area since a decade ago.

Maybe @krzysztofzablocki knows, if, say, 50 `config` files are passed to Sourcery, and every `config` file includes dozens of `.swift` files in `sources`, would KZFileWatcher be able to observe all of these source files, 
or would it fail silently for some and only some descriptors would stay alive?

**Comment by krzysztofzablocki** [comment]
FileWatcher is definitely inferior to file events we use here, I wouldn't even consider using that approach

**Comment by art-divin** [comment]
Thank you Krzysztof!

@fvazquez-travelperk my suggestion is to fire multiple instances of sourcery and observe each module separately.

Concurrency in Sourcery works and proven to be stable in [similar scenarios](https://medium.com/qonto-way/how-one-line-of-code-led-to-50-faster-swift-compilation-for-tens-of-thousands-of-teams-f55c3b0da933).

**Comment by fvazquez-travelperk** [comment]
@art-divin

Will do that. To be fair, this issue popped up at a time when Sourcery did not support concurrency. I have still to test with a more recent version.

Thanks for taking the time to look into this!
