### ISSUE TITLE
Possible to generate asset catalog constants?

### ISSUE THREAD

**Issue by philipsawyer** [krzysztofzablocki/Sourcery#1279]
Hello!

I am trying to migrate away from SwiftGen to Sourcery. One of the things I use SwiftGen for currently is generating constants for our asset catalogs. Is this possible using Sourcery? I looked around the docs and didn't see anything but want to double check.

Thanks!

https://github.com/SwiftGen/SwiftGen#asset-catalog

**Comment by krzysztofzablocki** [comment]
Hey, so Sourcery isn't a good replacement for SwiftGen, Sourcery takes source code as input and generates whatever, SwiftGen took data and generated code
