### ISSUE TITLE
Detecting if a variable is an Enum works if enum is declared in the file but doesn't otherwise.

### ISSUE THREAD

**Issue by OmranK** [krzysztofzablocki/Sourcery#1282]
Sources:

User.swift
```
public struct User {
    var role: Role
}
```

Role.swift 
```
enum Role: String {
    case admin
    case employee
}
```

Template:
```
{%if var.type.kind|enum and var.type.rawTypeName != nil %}
var {{ var.name }}: {{ var.actualTypeName }}.RawValue {% newline %}
{%else%}
```

Expected Result: `var role: Role.RawValue `
Actual Result: `var role: Role`

If I move the Role enum into the User.swift file, it starts working as expected. 

Is this a limitation of Sourcery or am I just missing something?

**Comment by OmranK** [comment]
Documentation says:  "Currently Sourcery only scans files from paths or targets that you tell it to scan. " 
so it turns out this is a limitation with workaround but how do we specify which sources sorcery will scan when using Sourcery Pro?

**Comment by OmranK** [comment]
![Screenshot 2024-03-02 at 5 37 26 PM](https://github.com/krzysztofzablocki/Sourcery/assets/33832722/b69d79fc-b4c0-46e7-ae47-4f68f38e2e54)
I also having this warning showing. How can I cast the type to Enum so rawTypeName property is known?

**Comment by art-divin** [comment]
👋🏻  @krzysztofzablocki this one you most likely can answer, thanks 🤝

**Comment by krzysztofzablocki** [comment]
@OmranK SourceryPro can't access anything outside the given file, that's Xcode limitation not Sourcery's, we are simply not allowed to anything outside text buffer. 

You can cast variables to type using {% typed type as Enum %} but you'd need to pass var.type to a function or store it in a variable for that, using either Macro or Set from https://github.com/SwiftGen/StencilSwiftKit?tab=readme-ov-file
