### ISSUE TITLE
Swift macros and method bodies

### ISSUE THREAD

**Issue by AF-cgi** [krzysztofzablocki/Sourcery#1286]
I have 2 questions:
1. Is there a way to get the whole content body of a method?
2. Is it possible to grab Swift macros?
Thanks a lot.

**Comment by krzysztofzablocki** [comment]
hey, we don't scan bodies since we only care about AST model which is definitions and not implementations, you should be able to get attributes https://krzysztofzablocki.github.io/Sourcery/Classes/Type.html#/c:@M@SourceryRuntime@objc(cs)Type(py)attributes
