### ISSUE TITLE
[0.5.3] Illegal instruction: 4  

### ISSUE THREAD

**Issue by muukii** [krzysztofzablocki/Sourcery#130]
The following error occurred when executed.

```
Pods/Sourcery/bin/sourcery: line 6: 14149 Illegal instruction: 4  "${parent_path}"/Sourcery.app/Contents/MacOS/Sourcery "$@"
```

**Comment by krzysztofzablocki** [comment]
How did you invoke the tool?

**Comment by muukii** [comment]
I'm sorry less information
I will search for a reproduction method.

**Comment by krzysztofzablocki** [comment]
I'll close this since no one else reported it yet, if you get more info feel free to reopen
