### ISSUE TITLE
Old swift-collections version

### ISSUE THREAD

**Issue by michalnowak061** [krzysztofzablocki/Sourcery#1330]
Please update swift-collections dependency. Because I got this error:

```
Failed to resolve dependencies Dependencies could not be resolved because ***** depends on 'swift-collections' 1.1.0 and **** depends on 'sourcery' 2.2.4.
'sourcery' 2.2.4 practically depends on 'swift-collections' 1.0.1..<1.1.0 because 'sourcery' 2.2.4 depends on 'swift-package-manager' 1.0.3..<2.0.0.
'swift-package-manager' >= 1.0.3 practically depends on 'swift-collections' 1.0.1..<1.1.0 because 'swift-package-manager' 1.0.3 depends on 'swift-collections' 1.0.1..<1.1.0 and no versions of 'swift-package-manager' match the requirement 1.0.4..<2.0.0.
```

**Comment by art-divin** [comment]
Hello @michalnowak061 ,

thank you for reporting!

I have updated my fork of `swift-package-manager` and now it mentions `swift-collections` as `from: "1.0.1"` and not as it was before, `upToNextMinor`

**Comment by michalnowak061** [comment]
> Hello @michalnowak061 ,
> 
> 
> 
> thank you for reporting!
> 
> 
> 
> I have updated my fork of `swift-package-manager` and now it mentions `swift-collections` as `from: "1.0.1"` and not as it was before, `upToNextMinor`

Awesome. Thanks 😊
