### ISSUE TITLE
Associatedtype not parsing to mock

### ISSUE THREAD

**Issue by SeRG1k17** [krzysztofzablocki/Sourcery#1333]
```swift
//sourcery:AutoMockable
protocol TestProtocol {
    associatedtype Value

    func getValue() -> Value
}
```

Generated.swift:
```swift
class TestProtocolMock: TestProtocol {
    //MARK: - getValue

    var getValueIntCallsCount = 0
    var getValueIntCalled: Bool {
        return getValueIntCallsCount > 0
    }
    var getValueIntReturnValue: Value!
    var getValueIntClosure: (() -> Value)?

    func getValue() -> Value {
        getValueIntCallsCount += 1
        if let getValueIntClosure = getValueIntClosure {
            return getValueIntClosure()
        } else {
            return getValueIntReturnValue
        }
    }
}
```

Also this doesn't work for **primary associatedType**
Environment:
* Sourcery - 2.2.4
* templete - AutoMockable.stencil (default)
* command: Pods/Sourcery/bin/sourcery --sources ./SourceryMocks/Test.swift --templates Pods/Sourcery/Templates/AutoMockable.stencil --output ./SourceryMocks

**Comment by art-divin** [comment]
Hey @SeRG1k17 ,

thank you for reporting this issue!

Do you have a vision what would be the expected generated mock?
Would you consider adding generics to the generated definition which would define the `associatedType` protocol requirement as a solution to this problem?

Thank you 🙏🏻
