### ISSUE TITLE
Property annotation parsing broken for properties starting with the text `case...` in version 2.1.8 and later

### ISSUE THREAD

**Issue by johntmcintosh** [krzysztofzablocki/Sourcery#1340]
We use a template to generate stubs for our models and noticed that starting in version `2.1.8` stub annotations are no longer being recognized for properties with names starting with the text `"case..."`. This is present in the current `2.2.4` version as well.

I've attached [a simple example zip](https://github.com/user-attachments/files/15568159/Archive.zip) that, when run, shows the output difference between versions 2.1.7 and 2.1.8.

**Input**

Here's an input struct with 4 properties:
- `basic` - a normal property name without the word case
- `caseProperty` - a breaking property, that starts with the prefix `"case..."`
- `casesProperty ` - a plural version of the breaking property, starting with the prefix `"cases..."`
- `CaseProperty ` - showing that it's ok if the case prefix is capitalized `"Case..."`

```
// sourcery: AutoStubable
struct MyStruct {

    // sourcery: stub = "A"
    let basic: String

    // sourcery: stub = "B"
    let caseProperty: String

    // sourcery: stub = "C"
    let casesProperty: String

    // sourcery: stub = "D"
    let CaseProperty: String
}
```

**Output 2.1.7**

```
extension MyStruct {

    static func stub(
            basic: String = "A", 
            caseProperty: String = "B", 
            casesProperty: String = "C", 
            CaseProperty: String = "D"
        ) -> MyStruct {

        MyStruct(
            basic: basic,
            caseProperty: caseProperty,
            casesProperty: casesProperty,
            CaseProperty: CaseProperty
        )
    }
}
```

**Output 2.1.8**

```
extension MyStruct {

    static func stub(
            basic: String = "A", 
            caseProperty: String,   // <------ this is missing the value from the annotation
            casesProperty: String,    // <------ this is missing the value from the annotation
            CaseProperty: String = "D"
        ) -> MyStruct {

        MyStruct(
            basic: basic,
            caseProperty: caseProperty,
            casesProperty: casesProperty,
            CaseProperty: CaseProperty
        )
    }
}
```

----

As a more stripped down example, here's a simplified template that just dumps out the property names and recognized annotations:

```
{% for type in types.structs|annotated:"AutoStubable" %}
{{ type.name }}
{% for variable in type.storedVariables %}
    {{ variable.name }} {{ variable.annotations }}
{% endfor %}
{% endfor %}
```

**Output 2.1.7**

```
MyStruct
    basic {
    stub = A;
}
    caseProperty {
    stub = B;
}
    casesProperty {
    stub = C;
}
    CaseProperty {
    stub = D;
}
```

**Output 2.1.8**

```
MyStruct
    basic {
    stub = A;
}
    caseProperty {   // <---------- the stub annotation is missing here
}
    casesProperty {   // <---------- the stub annotation is missing here
}
    CaseProperty {
    stub = D;
}
```

**Comment by art-divin** [comment]
Hello @johntmcintosh ,

firstly, what an amazing bug report. It is just 💯 out of 💯 👍🏻 

- readability
- minimal reproducible
- clarity & conciseness 

🙇🏻 thank you!

I took a look into the issue, and it is unbelievably simple to resolve -> just rename `case` to `cage` in the input data.
Yes, this is simply due to this check that it stops annotation parsing for anything that has "case" in the beginning of the identifier name:

```swift
let isInsideCaseDefinition = prefix.trimmingCharacters(in: .whitespacesAndNewlines).hasPrefix("case")
prefix = prefix.trimmingPrefix("case").trimmingCharacters(in: .whitespaces)
```

Clearly, this is not an expected behaviour and needs to be resolved, but until then, feel free to just change this part, if possible.
