### ISSUE TITLE
Custom filters and tags with JavaScriptCore

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#135]
I think it will be vital for the tool to provide that so that we don't constrain users with filters/tags that we implemented in the tool itself. Implementation looks very straight forward, just need to add a parameter for path to filters (1 file per filter/tag), and use Stencil `Extension` to register filter/tags with string content by the name of the file. Also we will need to adjust all the models to make them available in JS context to adopt `JSExport` protocol and move all properties declarations in a protocol.
Alternatively we can push forward Swift templates, but I think it will be still a cool feature to have for Stencil templates too.
What do you think @krzysztofzablocki

**Comment by krzysztofzablocki** [comment]
I think we should evaluate that after 1.0 is done, not saying no but I think its worth waiting and see how many people would this affect, especially since we have Swift templates.

**Comment by ilyapuchka** [comment]
@alisoftware @krzysztofzablocki since we are now using the same shared framework what do you think if we implement this feature in StencilSwiftKit? SwiftGen then can also benefit from it as its users might need some custom filters in their custom templates. The other option would be to implement it in Stencil itself, but I'm not sure if it's needed there as Stencil itself is not used as a compiled tool, but rather as a library in such tools.

**Comment by AliSoftware** [comment]
@ilyapuchka as discussed IRL last Friday, is love to see this in StencilSwiftKit, I don't see any reason not to make it common both for Sourcery and SwiftGen, so let's do it!

**Comment by krzysztofzablocki** [comment]
makes sense to me as well
