### ISSUE TITLE
[SPM] swift-syntax conflicts

### ISSUE THREAD

**Issue by michalnowak061** [krzysztofzablocki/Sourcery#1354]
Everything is visible on the screenshot. Hope for a quick fix 🤞🏻 Regards

<img width="1367" alt="Screenshot 2024-07-29 at 10 55 33" src="https://github.com/user-attachments/assets/65e20d95-f8cd-42a6-a4ab-45c9bfea78f4">

**Comment by krzysztofzablocki** [comment]
hey, if you are brining in Sourcery as framework dependency and using SwiftSyntax directly as well, it's on you to match the framework versions? 

I'm not sure what you expect us to do here, we don't even know what your setup is

**Comment by michalnowak061** [comment]
> I see the apple org changed for SwiftSyntax, it's no longer https://github.com/apple/swift-syntax We can update that, you'll still need to match up versions if you are brining in Sourcery as framework dep I think

If you update this, it will be enough for me. Thank's
