### ISSUE TITLE
Readme for AutoEquatable shows AutoHashable

### ISSUE THREAD

**Issue by hannesoid** [krzysztofzablocki/Sourcery#136]
Nothing big, but `AutoEquatable` in the examples section of readme seems to be lending a bit too much from `AutoHashable`

<img width="902" alt="AutoHashable" src="https://cloud.githubusercontent.com/assets/1856655/22341443/d1c5318e-e3be-11e6-8628-c190d6b07720.png">

**Comment by krzysztofzablocki** [comment]
Thanks for reporting this, I guess I messed it up when rebasing, will fix :)
