### ISSUE TITLE
Could not find `.sourcery.yml` for target

### ISSUE THREAD

**Issue by ssly1997** [krzysztofzablocki/Sourcery#1368]
I'm integrating Sourcery into a package managed by Swift Package Manager. I placed the .sourcery.yml in the root directory of the target, but when I run the plugin, it says it can't find the yml file. How should I fix this?
![image](https://github.com/user-attachments/assets/cc60a89b-836a-4245-bfd5-7ca773e7e39f)
![image](https://github.com/user-attachments/assets/c02bc22d-144d-4bf8-89a4-01bdbc3816e0)

**Comment by krzysztofzablocki** [comment]
.sourcery.yml not test.sourcery.yml, unless you want to manually specify path

**Comment by ssly1997** [comment]
> .sourcery.yml not test.sourcery.yml, unless you want to manually specify path

thanks!
