### ISSUE TITLE
note: 'characters' was obsoleted in Swift 5.0

### ISSUE THREAD

**Issue by bukira** [krzysztofzablocki/Sourcery#1369]
error using sourcery

❌  Error: ShellOut encountered an error
Status code: 3
Message: "Building for production...
[0/5] Write sources
[2/5] Write swift-version--58304C5D6DBC2206.txt
[4/7] Compiling SourceryRuntime AccessLevel.swift
[5/7] Emitting module SourceryRuntime
[6/9] Emitting module SwiftTemplate
[7/9] Compiling SwiftTemplate main.swift
/private/var/folders/ww/hwd5bq0s6cddnvr08x3jdspr0000gn/T/SwiftTemplate/EEB3CA17-F5BF-4C15-9B38-7F1BA781CA7D/2.2.5/Sources/SwiftTemplate/main.swift:251:96: error: 'characters' is unavailable: Please use String directly
 249 |     static func extractGenericsList(_ associatedTypes: [String]?) -> [String] {
 250 |         return associatedTypes?.flatMap {
 251 |             split($0, byFirstOccurenceOf: " where ").0.replacingOccurrences(of: " ", with: "").characters.split(separator: ":").map(String.init).first
     |                                                                                                `- error: 'characters' is unavailable: Please use String directly
 252 |         }.map { "\($0)" } ?? []
 253 |     }

Swift.String:5:16: note: 'characters' was obsoleted in Swift 5.0
3 |     public typealias CharacterView = String
4 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please use String directly")
5 |     public var characters: String { get set }
  |                `- note: 'characters' was obsoleted in Swift 5.0
6 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please mutate the String directly")
7 |     public mutating func withMutableCharacters<R>(_ body: (inout String) -> R) -> R

/private/var/folders/ww/hwd5bq0s6cddnvr08x3jdspr0000gn/T/SwiftTemplate/EEB3CA17-F5BF-4C15-9B38-7F1BA781CA7D/2.2.5/Sources/SwiftTemplate/main.swift:263:81: error: 'characters' is unavailable: Please use String directly
 261 |         let constraints = all.flatMap { t -> String? in
 262 |             let splitted = split(t, byFirstOccurenceOf: " where ")
 263 |             let constraint = splitted.0.replacingOccurrences(of: " ", with: "").characters.split(separator: ":").map(String.init)
     |                                                                                 `- error: 'characters' is unavailable: Please use String directly
 264 |             guard constraint.count == 2 else { return nil }
 265 |             let adopts = constraint[1].characters.split(separator: ",").map(String.init)

Swift.String:5:16: note: 'characters' was obsoleted in Swift 5.0
3 |     public typealias CharacterView = String
4 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please use String directly")
5 |     public var characters: String { get set }
  |                `- note: 'characters' was obsoleted in Swift 5.0
6 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please mutate the String directly")
7 |     public mutating func withMutableCharacters<R>(_ body: (inout String) -> R) -> R

/private/var/folders/ww/hwd5bq0s6cddnvr08x3jdspr0000gn/T/SwiftTemplate/EEB3CA17-F5BF-4C15-9B38-7F1BA781CA7D/2.2.5/Sources/SwiftTemplate/main.swift:265:40: error: 'characters' is unavailable: Please use String directly
 263 |             let constraint = splitted.0.replacingOccurrences(of: " ", with: "").characters.split(separator: ":").map(String.init)
 264 |             guard constraint.count == 2 else { return nil }
 265 |             let adopts = constraint[1].characters.split(separator: ",").map(String.init)
     |                                        `- error: 'characters' is unavailable: Please use String directly
 266 |             var mapped = adopts.map { "\(constraint[0]): \($0)" }
 267 |             if !splitted.1.isEmpty {

Swift.String:5:16: note: 'characters' was obsoleted in Swift 5.0
3 |     public typealias CharacterView = String
4 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please use String directly")
5 |     public var characters: String { get set }
  |                `- note: 'characters' was obsoleted in Swift 5.0
6 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please mutate the String directly")
7 |     public mutating func withMutableCharacters<R>(_ body: (inout String) -> R) -> R

/private/var/folders/ww/hwd5bq0s6cddnvr08x3jdspr0000gn/T/SwiftTemplate/EEB3CA17-F5BF-4C15-9B38-7F1BA781CA7D/2.2.5/Sources/SwiftTemplate/main.swift:1156:69: error: 'characters' is unavailable: Please use String directly
1154 |         genPart.removeLast()
1155 | 
1156 |         let parts = genPart.replacingOccurrences(of: " ", with: "").characters.split(separator: ",").map(String.init)
     |                                                                     `- error: 'characters' is unavailable: Please use String directly
1157 |         return parts.map { stripGenPart(part: $0) }
1158 |     }

Swift.String:5:16: note: 'characters' was obsoleted in Swift 5.0
3 |     public typealias CharacterView = String
4 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please use String directly")
5 |     public var characters: String { get set }
  |                `- note: 'characters' was obsoleted in Swift 5.0
6 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please mutate the String directly")
7 |     public mutating func withMutableCharacters<R>(_ body: (inout String) -> R) -> R

/private/var/folders/ww/hwd5bq0s6cddnvr08x3jdspr0000gn/T/SwiftTemplate/EEB3CA17-F5BF-4C15-9B38-7F1BA781CA7D/2.2.5/Sources/SwiftTemplate/main.swift:1171:69: error: 'characters' is unavailable: Please use String directly
1169 |         genPart.removeLast()
1170 | 
1171 |         let parts = genPart.replacingOccurrences(of: " ", with: "").characters.split(separator: ",").map(String.init)
     |                                                                     `- error: 'characters' is unavailable: Please use String directly
1172 |         return parts.filter {
1173 |             let components = $0.components(separatedBy: ":")

Swift.String:5:16: note: 'characters' was obsoleted in Swift 5.0
3 |     public typealias CharacterView = String
4 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please use String directly")
5 |     public var characters: String { get set }
  |                `- note: 'characters' was obsoleted in Swift 5.0
6 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please mutate the String directly")
7 |     public mutating func withMutableCharacters<R>(_ body: (inout String) -> R) -> R

/private/var/folders/ww/hwd5bq0s6cddnvr08x3jdspr0000gn/T/SwiftTemplate/EEB3CA17-F5BF-4C15-9B38-7F1BA781CA7D/2.2.5/Sources/SwiftTemplate/main.swift:1193:21: error: 'characters' is unavailable: Please use String directly
1191 | 
1192 |     private func stripGenPart(part: String) -> String {
1193 |         return part.characters.split(separator: ":").map(String.init).first!
     |                     `- error: 'characters' is unavailable: Please use String directly
1194 |     }
1195 | 

Swift.String:5:16: note: 'characters' was obsoleted in Swift 5.0
3 |     public typealias CharacterView = String
4 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please use String directly")
5 |     public var characters: String { get set }
  |                `- note: 'characters' was obsoleted in Swift 5.0
6 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please mutate the String directly")
7 |     public mutating func withMutableCharacters<R>(_ body: (inout String) -> R) -> R"
Output: "🌱 Finding latest version of sourcery
🌱 Running sourcery 2.2.5...
Using configuration file at '/Users/xxxxxx/Documents/Xcode/xxxxxx/.mocky6AE7B98E-AECF-4DDD-9B4F-C49B331C3B72/.config.yml.tmp'
Scanning sources...
Found 1018 types in 387 files, 0 changed from last run.
Loading templates...
Loaded 1 templates.
Generating code...
error: Building for production...
[0/5] Write sources
[2/5] Write swift-version--58304C5D6DBC2206.txt
[4/7] Compiling SourceryRuntime AccessLevel.swift
[5/7] Emitting module SourceryRuntime
[6/9] Emitting module SwiftTemplate
[7/9] Compiling SwiftTemplate main.swift
/private/var/folders/ww/hwd5bq0s6cddnvr08x3jdspr0000gn/T/SwiftTemplate/EEB3CA17-F5BF-4C15-9B38-7F1BA781CA7D/2.2.5/Sources/SwiftTemplate/main.swift:251:96: error: 'characters' is unavailable: Please use String directly
 249 |     static func extractGenericsList(_ associatedTypes: [String]?) -> [String] {
 250 |         return associatedTypes?.flatMap {
 251 |             split($0, byFirstOccurenceOf: " where ").0.replacingOccurrences(of: " ", with: "").characters.split(separator: ":").map(String.init).first
     |                                                                                                `- error: 'characters' is unavailable: Please use String directly
 252 |         }.map { "\($0)" } ?? []
 253 |     }

Swift.String:5:16: note: 'characters' was obsoleted in Swift 5.0
3 |     public typealias CharacterView = String
4 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please use String directly")
5 |     public var characters: String { get set }
  |                `- note: 'characters' was obsoleted in Swift 5.0
6 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please mutate the String directly")
7 |     public mutating func withMutableCharacters<R>(_ body: (inout String) -> R) -> R

/private/var/folders/ww/hwd5bq0s6cddnvr08x3jdspr0000gn/T/SwiftTemplate/EEB3CA17-F5BF-4C15-9B38-7F1BA781CA7D/2.2.5/Sources/SwiftTemplate/main.swift:263:81: error: 'characters' is unavailable: Please use String directly
 261 |         let constraints = all.flatMap { t -> String? in
 262 |             let splitted = split(t, byFirstOccurenceOf: " where ")
 263 |             let constraint = splitted.0.replacingOccurrences(of: " ", with: "").characters.split(separator: ":").map(String.init)
     |                                                                                 `- error: 'characters' is unavailable: Please use String directly
 264 |             guard constraint.count == 2 else { return nil }
 265 |             let adopts = constraint[1].characters.split(separator: ",").map(String.init)

Swift.String:5:16: note: 'characters' was obsoleted in Swift 5.0
3 |     public typealias CharacterView = String
4 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please use String directly")
5 |     public var characters: String { get set }
  |                `- note: 'characters' was obsoleted in Swift 5.0
6 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please mutate the String directly")
7 |     public mutating func withMutableCharacters<R>(_ body: (inout String) -> R) -> R

/private/var/folders/ww/hwd5bq0s6cddnvr08x3jdspr0000gn/T/SwiftTemplate/EEB3CA17-F5BF-4C15-9B38-7F1BA781CA7D/2.2.5/Sources/SwiftTemplate/main.swift:265:40: error: 'characters' is unavailable: Please use String directly
 263 |             let constraint = splitted.0.replacingOccurrences(of: " ", with: "").characters.split(separator: ":").map(String.init)
 264 |             guard constraint.count == 2 else { return nil }
 265 |             let adopts = constraint[1].characters.split(separator: ",").map(String.init)
     |                                        `- error: 'characters' is unavailable: Please use String directly
 266 |             var mapped = adopts.map { "\(constraint[0]): \($0)" }
 267 |             if !splitted.1.isEmpty {

Swift.String:5:16: note: 'characters' was obsoleted in Swift 5.0
3 |     public typealias CharacterView = String
4 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please use String directly")
5 |     public var characters: String { get set }
  |                `- note: 'characters' was obsoleted in Swift 5.0
6 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please mutate the String directly")
7 |     public mutating func withMutableCharacters<R>(_ body: (inout String) -> R) -> R

/private/var/folders/ww/hwd5bq0s6cddnvr08x3jdspr0000gn/T/SwiftTemplate/EEB3CA17-F5BF-4C15-9B38-7F1BA781CA7D/2.2.5/Sources/SwiftTemplate/main.swift:1156:69: error: 'characters' is unavailable: Please use String directly
1154 |         genPart.removeLast()
1155 | 
1156 |         let parts = genPart.replacingOccurrences(of: " ", with: "").characters.split(separator: ",").map(String.init)
     |                                                                     `- error: 'characters' is unavailable: Please use String directly
1157 |         return parts.map { stripGenPart(part: $0) }
1158 |     }

Swift.String:5:16: note: 'characters' was obsoleted in Swift 5.0
3 |     public typealias CharacterView = String
4 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please use String directly")
5 |     public var characters: String { get set }
  |                `- note: 'characters' was obsoleted in Swift 5.0
6 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please mutate the String directly")
7 |     public mutating func withMutableCharacters<R>(_ body: (inout String) -> R) -> R

/private/var/folders/ww/hwd5bq0s6cddnvr08x3jdspr0000gn/T/SwiftTemplate/EEB3CA17-F5BF-4C15-9B38-7F1BA781CA7D/2.2.5/Sources/SwiftTemplate/main.swift:1171:69: error: 'characters' is unavailable: Please use String directly
1169 |         genPart.removeLast()
1170 | 
1171 |         let parts = genPart.replacingOccurrences(of: " ", with: "").characters.split(separator: ",").map(String.init)
     |                                                                     `- error: 'characters' is unavailable: Please use String directly
1172 |         return parts.filter {
1173 |             let components = $0.components(separatedBy: ":")

Swift.String:5:16: note: 'characters' was obsoleted in Swift 5.0
3 |     public typealias CharacterView = String
4 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please use String directly")
5 |     public var characters: String { get set }
  |                `- note: 'characters' was obsoleted in Swift 5.0
6 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please mutate the String directly")
7 |     public mutating func withMutableCharacters<R>(_ body: (inout String) -> R) -> R

/private/var/folders/ww/hwd5bq0s6cddnvr08x3jdspr0000gn/T/SwiftTemplate/EEB3CA17-F5BF-4C15-9B38-7F1BA781CA7D/2.2.5/Sources/SwiftTemplate/main.swift:1193:21: error: 'characters' is unavailable: Please use String directly
1191 | 
1192 |     private func stripGenPart(part: String) -> String {
1193 |         return part.characters.split(separator: ":").map(String.init).first!
     |                     `- error: 'characters' is unavailable: Please use String directly
1194 |     }
1195 | 

Swift.String:5:16: note: 'characters' was obsoleted in Swift 5.0
3 |     public typealias CharacterView = String
4 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please use String directly")
5 |     public var characters: String { get set }
  |                `- note: 'characters' was obsoleted in Swift 5.0
6 |     @available(swift, deprecated: 3.2, obsoleted: 5.0, message: "Please mutate the String directly")
7 |     public mutating func withMutableCharacters<R>(_ body: (inout String) -> R) -> R
"

**Comment by art-divin** [comment]
Hello,

from the title of the issue, it seems like you are using an outdated version of '.swifttemplate' in your setup.

Please check with the vendor of your swifttemplate file if there is a newer version available.

**Comment by bukira** [comment]
I thought the template came with sourcery , seems like it’s downloading from sourcery branch as it keeps it in a folder in sourcery.I’m using swiftmockyCriss MyersOn 5 Oct 2024, at 11:13, Ruslan A. ***@***.***> wrote:﻿
Hello,
from the title of the issue, it seems like you are using an outdated version of '.swifttemplate' in your setup.
Please check with the vendor of your swifttemplate file if there is a newer version available.

**Comment by krzysztofzablocki** [comment]
SwiftyMocky has it's own templates, they use Sourcery as a tool but we are not related
