### ISSUE TITLE
Error generating Mocks using `AutoMockable.stencil` - Unknown filter `sortedValuesByKeys`. Found similar filters:`sortedDescending`

### ISSUE THREAD

**Issue by Smponias** [krzysztofzablocki/Sourcery#1370]
I am using [AutoMockable.stencil](https://github.com/krzysztofzablocki/Sourcery/blob/master/Templates/Templates/AutoMockable.stencil) with Xcode 16 (Swift 6) to generate mocks and I am using the template:

I am getting the following Error: `AutoMockable.stencil: Unknown filter 'sortedValuesByKeys'. Found similar filters: 'sortedDescending`
```
sources:
  - ..../SwiftPackageTarget
templates:
  - ....../AutoMockable.stencil
output: ..... SwiftPackageTarget/Mocks
args:
  autoMockableTestableImports: 
      - SwiftPackageTarget
```

And I am running it with:
`sourcery --config.../Config.yml`

Maybe anyone can help me? I tried to fix it but it is not working for me.

**Comment by krzysztofzablocki** [comment]
you are using old version of Sourcery, it's only available in newest
