### ISSUE TITLE
Integrating Sourcery from source locally?

### ISSUE THREAD

**Issue by bejar37** [krzysztofzablocki/Sourcery#138]
Hi,
I need the changes from #137 so I'm trying to integrate Sourcery directly in my project directly for now. I've tried two things:
* Use swift build and run the resulting binary
* Archive and export as macOS app via xcode

I'm getting two different errors, but I wouldn't be surprised if I'm doing this wrong :).

When running the `swift build` artifact:
```
Scanning sources...
2017-01-27 08:37:47.025 sourcery[66873:3025037] *** Terminating app due to uncaught exception 'NSInvalidUnarchiveOperationException', reason: '*** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (Sourcery.FileParserResult) for key (root); the class may be defined in source code or a library that is not linked'
```

When running via macOS app:
```
2017-01-27 08:36:34.384 Sourcery[66730:3022801] *** Terminating app due to uncaught exception 'NSParseErrorException', reason: 'Key 'name' not found.'
```

I'm a little lost as to whether these are bugs in master or my mistake, pointers are appreciated!

**Comment by krzysztofzablocki** [comment]
You'll need the changes I did in my inline branch, it improves how cache is dealt with, but I'll make a new release shortly, we just need to add SPM support to SwiftStencilKit and someone has to review that PR

**Comment by bejar37** [comment]
@krzysztofzablocki Are you talking about reviewing the parts of #133 that @ilyapuchka hasn't gotten to yet? I don't see a PR for [StencilSwiftKit](https://github.com/SwiftGen/StencilSwiftKit) relating to SPM support.

**Comment by krzysztofzablocki** [comment]
yes I'm talking about #133

**Comment by bejar37** [comment]
I'm not sure that I know the codebase enough to really do the review but I'll take a look!

Thanks for the help, FWIW there is a bug in master that's fixed in #133, that was the cause of my original issue.

**Comment by bejar37** [comment]
> You'll need the changes I did in my inline branch, it improves how cache is dealt with, but I'll make a new release shortly

@krzysztofzablocki any word on the next release? :)

**Comment by krzysztofzablocki** [comment]
I'll do it this week, I'd prefer if Brew was integrated already but I can do it before
