### ISSUE TITLE
User should be able to specify additional template parameters on the command line.

### ISSUE THREAD

**Issue by Szaq** [krzysztofzablocki/Sourcery#14]
There is a great sample of similar templating engine (http://atomist.com) in this talk (although for Elm):
https://www.youtube.com/watch?v=jJ4e6cIBgYM

Also default values for unspecified arguments could be configured using yaml config file. This way we could for example write:

`sourcery MyViewController.swift add_table_view_cell MyCellType --fixed_height=100`

**Comment by krzysztofzablocki** [comment]
thanks for the reference, I've added the talk to my reading list. 

As for templating engine, I do want to keep using Stencil, I evaluated some alternatives like Moustache but I like Stencil guiding principles and how close it's kept to Swift itself. Stencil is still expanding as @kylef is adding new features. But we will also be creating a shared framework to extend it purely for Swift code generation that both `Sourcery` and @alisoftware `SwiftGen` will use (so you'll have the same dialect in both).

As for parameters, it's an excellent idea and shouldn't be too hard to implement, do you have time & would like to try implementing support for it ? if not I'll be happy to do it

**Comment by Szaq** [comment]
Thanks for prompt response.

I didn't mean to replace templating engine, just wanted to point to a benchmark :)

I would love to implement that, but currently I am overburdened with work. I'll however try to find time this week.

**Comment by krzysztofzablocki** [comment]
@ilyapuchka implemented this, will be in next version 🎆

**Comment by AliSoftware** [comment]
Need this for SwiftGen too!
