### ISSUE TITLE
Does Sourcery scan's Objective-c code?

### ISSUE THREAD

**Issue by 4brunu** [krzysztofzablocki/Sourcery#141]
I was trying to generate some Swift classes based on some Objective-c protocols that I have in my project, but apparently Soucery only find protocols defined in Swift. 
Is this correct? I tried to find some information related to the support of Objective-c or not, but couldn't find anything.

This is what I was trying to do.

```
// Found {{ types.protocols.count }} Types
// {% for type in types.protocols %} {{ type.name }}  {% endfor %}
```

Thanks

**Comment by krzysztofzablocki** [comment]
We don't support Objective-C, and it is not really in the plans since it would complicate things a lot

**Comment by 4brunu** [comment]
Ok, thank you, just to make sure. 👍
