### ISSUE TITLE
Support for Xcode Build Phase input files parameters

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#143]
Currently we only support a single path parameter, but it might be the case that scanned files are located in different paths and not all the files in their common root should be scanned. That's actually the case for Sourcery itself - `GenerationContext` class is not located in the same path as all other scanned types (models). With input files parameters support we can simply add them to all scanned files in the path.

See also #126 that might also solve issue in it's own way, but adding parameters support feels a simpler solution. Generally I think more options we provide - the better, so one does not dismiss the other.

**Comment by krzysztofzablocki** [comment]
What if we introduced solution similar to SwiftLint yaml definition file? we'd be listing inputs and exclude paths there, this would simplify the configuration of the tool

**Comment by ilyapuchka** [comment]
Though I'm not a great fan of yaml files this could be the best option, especially when we start to grow the number of configurations
