### ISSUE TITLE
Dramatic build time increase for AutoLenses

### ISSUE THREAD

**Issue by mergesort** [krzysztofzablocki/Sourcery#147]
I added a very small type to test out lenses in an app, and it increased my [non-clean] build time from 12 to 34 seconds using Sourcery 0.5.4. This is a repeatable process, not just a first time bump.

The type looks like this and generates proper output, just takes a very long time.

```
protocol AutoLens {}

struct Test: AutoLens {

    var x: Int
    var y: Double
    var z: String
}
```

Let me know if there's any more information I can provide for you.

**Comment by krzysztofzablocki** [comment]
Thanks for reporting, fixed in 0.5.5
