### ISSUE TITLE
AutoEquatable generates definitions for Sourcery classes

### ISSUE THREAD

**Issue by mindz-eye** [krzysztofzablocki/Sourcery#151]
When using Sourcery 0.5.5 with the following input:
https://gist.github.com/mindz-eye/a0160791349760b1245a4419c4aa6cc9

I get the following result:
https://gist.github.com/mindz-eye/04850b90572b45a95b34248dd8625021

Obviously, it generates definitions for some Sourcery runtime classes.

Not sure what version introduced this behavior, but in 0.4.9 it definitely worked correctly.
Sourcery is installed via CocoaPods

**Comment by krzysztofzablocki** [comment]
How does your build script look like?
Can you remove the cache folder from ~/Library/Caches/Sourcery

**Comment by mindz-eye** [comment]
```sh
echo "Generating code from Sourcery templates..."
sourcery_path=${PROJECT_DIR}/${PROJECT}/Sourcery
templates_path=${PROJECT_DIR}/${PROJECT}/Templates
output_path=${PROJECT_DIR}/${PROJECT}/Gen
${sourcery_path}/bin/sourcery ${PROJECT_DIR} ${templates_path} ${output_path} --verbose
```
I switched from using CocoaPods to manually downloaded binary.

Deleting ~/Library/Caches/Sourcery doesn't help.

**Comment by ilyapuchka** [comment]
Your copy of Sourcery is inside PROJECT_DIR, which you ask it to scan, so it's scans it's own sources. So you either need to remove Sourcery sources (you only need binary any way), or you need to put it somewhere else, or pass it a directory which only contains your own project files.

**Comment by mindz-eye** [comment]
Oh, my fault. Thanks a lot!
