### ISSUE TITLE
Accessing Type properties of a type wrapped inside optional

### ISSUE THREAD

**Issue by mindz-eye** [krzysztofzablocki/Sourcery#153]
E.g, in my template I would like to check if a type wrapped inside optional implements a protocol.
Is it currently possible?

**Comment by ilyapuchka** [comment]
Hi, @mindz-eye . It should be possible with something like this:

```
{% if types[variable.unwrappedTypeName].implements.SomeProtocol %}
```

**Comment by mindz-eye** [comment]
Returns nothing. 
I test it with [URL]?

**Comment by ilyapuchka** [comment]
URL is not the type defined in your source code, it's Foundation type, so this will only work if you have extensions on URL in which you add conformance to protocol that you want to check, like this (see #87)

**Comment by mindz-eye** [comment]
Ah, I see. Thanks!
