### ISSUE TITLE
Protocol methods with default implementation in extension are duplicated in '.methods' and '.allMethods'

### ISSUE THREAD

**Issue by antonselyanin** [krzysztofzablocki/Sourcery#158]
1. What version of Swift are you using (swift --version)?
```
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9
```

2. What did you do?

For the following protocol 
```
protocol Foo { 
    func fooVoid() 
}

extension Foo { 
    func fooVoid() {} 
}
```
`type.methods` and `type.allMethods` return two identical `fooVoid` methods (most of the time :)).

3. What did you expect to see?
There should be just one method.

4. What did you see instead?
Most of the time, there are two methods.

This test fails for me most of the time (sometimes the number of methods is "correct").
```
// added to "FileParser + MethodsSpec.swift"
                it("extracts protocol extension methods properly") {
                    expect(parse("protocol Foo { func fooVoid() }; extension Foo { func fooVoid() {} }"))
                        .to(equal([
                            Protocol(name: "Foo", methods: [
                                Method(name: "fooVoid()", returnTypeName: TypeName("Void"))
                                ])
                            ]))
                }
```

Test output:

```
FileParser__parseMethod__extracts_protocol_extension_methods_properly] : idx 0: methods Different count, expected: 1, received: 2
 Actual: [Protocol: typealiases = [:], isExtension = false, kind = protocol, accessLevel = internal, name = Foo, isGeneric = false, localName = Foo, variables = [], methods = [Method: name = fooVoid(), parameters = [], shortName = fooVoid, returnTypeName = Void, throws = false, accessLevel = internal, isStatic = false, isClass = false, isInitializer = false, isFailableInitializer = false, annotations = [:], attributes = [:], Method: name = fooVoid(), parameters = [], shortName = fooVoid, returnTypeName = Void, throws = false, accessLevel = internal, isStatic = false, isClass = false, isInitializer = false, isFailableInitializer = false, annotations = [:], attributes = [:]], initializers = [], annotations = [:], staticVariables = [], instanceVariables = [], computedVariables = [], storedVariables = [], inheritedTypes = [], containedTypes = [], parentName = nil, attributes = [:]kind = protocol]
```

Also, what about adding two new attributes that would let distinguish methods with default implementations vs methods that are defined in protocol extensions?

If a method has a default implementation - `Method.hasDefaultImplementation`
If a method is defined in an extension - `Method.isDefinedInExtension`

IIRC, methods defined in extensions are linked statically. This meta information could be useful for Sourcery users.

**Comment by ilyapuchka** [comment]
what can be a use case for `hasDefaultImplementation` or `isDefinedInExtension`?

**Comment by antonselyanin** [comment]
* `isDefinedInExtension` 
TBH, I don't like this name. `isStaticallyLinked`, `isCompileTimeLinked`? Hm...

For example, I want to generate a mock/stub for a protocol.  If a method is _defined_ in an extension (not declared in the protocol body), it makes no sense to generate a testing stub for the method (it just won't be invoked). Methods defined in extensions are linked at compile time.

Here is a quick demo (I wasn't sure if I'm right :))
http://swift.sandbox.bluemix.net/#/repl/58a9d0c523010a78295ef129

* `hasDefaultImplementation`
Auto-generating default implementations? Doesn't seem that useful :)

**Comment by ilyapuchka** [comment]
Got it. What if you use annotations to skip methods in extensions? You can use them either to opt in for stub generation, or the other way around to opt out, if you want to generate stub for method by default.

**Comment by ilyapuchka** [comment]
Btw you can try to run from #161 brunch, it should fix duplicated methods issue

**Comment by krzysztofzablocki** [comment]
I think `hasDefaultImplementation` can be useful for protocol methods

**Comment by Antondomashnev** [comment]
@antonselyanin in the upcoming release `method` and `variable` will have the `definedInExtension ` property to be used in templates.
