### ISSUE TITLE
if filtering on variables collection

### ISSUE THREAD

**Issue by ggrell** [krzysztofzablocki/Sourcery#162]
I'm guessing this isn't possible currently:
```
    {% if type.variables.annotations|contains:"jsonKey"  %}
    /// Some template that only appears if there's one or more jsonKey annotations
    public static var someMapping: [String:String]? = [{% for var in type.variables|instance|annotated:"jsonKey" %}
        ... something{% endfor %}
    ]()
    {% endif %}
```
This creates an empty collection if there are no "jsonKey" annotations, but empty dictionaries require `[:]`. Since it's optional, I'd rather not even generate the code.

1. If there are no workarounds, is this something that I could look into creating if others find it useful?
2. If it's worth doing, would this be something that is implemented in Sourcery (vs Stencil)? Where would I start?

**Comment by krzysztofzablocki** [comment]
try writing the if statement like this
`{% if type.variables|annotated:"jsonKey"|count %}`

**Comment by ggrell** [comment]
The `|count` didn't work, but it turns out that `{% if type.variables|annotated:"jsonKey" %}` is true if there's at least one instance. Thanks for the hint. I don't recall seeing this information in the readme, so if it's not there I'll add it.

**Comment by ggrell** [comment]
Added #164 to document this
