### ISSUE TITLE
Converting variable names to lower_case_underscore style

### ISSUE THREAD

**Issue by ggrell** [krzysztofzablocki/Sourcery#163]
In our JSON structures, we generally name fields similarly to the JSON data field name counterparts. When generating JSON mapping code, it would be nice to be able to directly map from `someFieldName` to `some_field_name`. I see that Stencil has `capitalize`, `uppercase` & `lowercase`, and Sourcery additionally provides `upperFirst` (via what looks like a Stencil custom filter).

I'm interested in contributing a `lowercaseUnderscore` filter if that's something that people would find valuable.

**Comment by krzysztofzablocki** [comment]
We also use https://github.com/SwiftGen/StencilSwiftKit which has few other filters like `snakeToCamelCase / snakeToCamelCaseNoPrefix`, I think that might actually cover this already?

**Comment by ggrell** [comment]
Woah, I didn't know StencilSwiftKit had additional filters added to it! Looks like `snakecase` hasn't been exposed as a filter, happy to take care of it if needed.

**Comment by krzysztofzablocki** [comment]
sounds great, but we should do it on the StencilSwiftKit repo 👍
