### ISSUE TITLE
Generating mock code for protocols containing generic methods

### ISSUE THREAD

**Issue by DenHeadless** [krzysztofzablocki/Sourcery#166]
Hey!

I am just starting to use Sourcery, with experience in only couple of custom templates from SwiftGen, and from Sourcery, so my experience is not very high.

In my use case, I want to generate mock code for following protocol(simplified):

```swift
public protocol APIServiceType {
     func login(with email: String, password: String) -> Driver<APIResult<AccessTokenEnvelope>>
}
```

It's similar to [`AutoMockable`](https://github.com/krzysztofzablocki/Sourcery/blob/master/Templates/AutoMockable.stencil) template, however there does not seem to be a way to properly identify generic return types.

So, trying following template, I get 0 methods:

```swift
{% for type in types.protocols %}
{% for method in type.allMethods %}{% if method.returnType.isGeneric %}
{% endif %}
{% endfor %}
{% endfor %}
```

I worked around this by having annotation like so:

```swift
/// sourcery: mockable
func login(with email:String, password: String) -> Driver<APIResult<AccessTokenEnvelope>>
```

And was able to find method. However I immediately failed after trying to get modelType from generic returnType of the method. It seems that for protocol method with generic returnType, returnType is simply not parsed by Sourcery.

Maybe I'm missing something or this is not implemented?

**Comment by ilyapuchka** [comment]
Will check that, but can you just try to put a method return type like this `{{ method.returnType }}` in the loop, just to see what is printed out?

**Comment by DenHeadless** [comment]
{{ method.returnType }} prints nothing, however 
{{ method.returnTypeName }} returns correct full name - Driver<APIResult<AccessTokenEnvelope>>

**Comment by ilyapuchka** [comment]
Thanks. Do you have Driver type defined in the sources that are scanned by Sourcery or it comes from another place?

**Comment by DenHeadless** [comment]
Hmmm... I'm using CocoaPods, and Driver is coming from `RxSwift`\`RxCocoa` CocoaPod framework. I don't think Pods directory is getting scanned by Sourcery because I specifically pointed it to Sources folder, but I'm not sure =)

**Comment by ilyapuchka** [comment]
Then that's the reason why the type name is parsed but type is not. There are more details about that in Readme in "What are known and unknown types" section.

**Comment by DenHeadless** [comment]
Understood. One more quick question, I tried to point Sourcery to scan all files, including CocoaPods, however now Sourcery crashes with following error:

```bash
Error Domain=NSCocoaErrorDomain Code=257 "The file “FontAwesome.swift” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/Users/denystelezkin/Developer/Lanespotter-iOS/Pods/FontAwesome.swift, NSUnderlyingError=0x7fb9f58ce8e0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}
```

Is this a known issue as well when using CocoaPods or something related to my specific setup/access rights, what do you think?

**Comment by ilyapuchka** [comment]
I think it's related to CocoaPods, this way it protects you from making changes in dependencies.

**Comment by DenHeadless** [comment]
War between developer tools, one more time)) Thanks a lot for your quick responses!

Closing this one out, since the root of the problem is not Sourcery-related.
