### ISSUE TITLE
Bug report: Unwrapped type name truncating type name

### ISSUE THREAD

**Issue by dgattey** [krzysztofzablocki/Sourcery#171]
A use case for Sourcery requires using `MethodParameter`'s `typeName` without any attributes (specifically, I'd like to remove the `@escaping` attribute). There's no way to do that currently without using `unwrappedTypeName`. Here's an example of what I've tried:

`{% for method in type.NetworkProtocol.methods %}
    let {{ method.shortName }}CallTracker = MockMethodCallTracker<({% for parameter in method.parameters %}{{ parameter.typeName }}{% if parameter.name != method.parameters.last.name %}, {% endif %}{% endfor %}), {{ method.returnTypeName }}>()
{% endfor %}`

This should output:
`let getLatestOpportunityCallTracker = MockMethodCallTracker<(ConversationListApiResponse), Request?>()`

Instead, we get `let getLatestOpportunityCallTracker = MockMethodCallTracker<(@escaping ConversationListApiResponse), Request?>()`

If I try changing `{{ parameter.typeName }}` to `{{ parameter.unwrappedTypeName }}`, I get an unexpected name out: it outputs `let getLatestOpportunityCallTracker = MockMethodCallTracker<(ConversationListApiRespo), Request?>()`. Looks like it's truncating from the beginning and end of the word instead of just the beginning?

**Comment by dgattey** [comment]
@krzysztofzablocki is this something that can be looked at?

**Comment by dgattey** [comment]
(Though I can get around it with `{{ parameter.typeName.name|replace:"@escaping ","" }}`, that's not a good solution)

**Comment by ilyapuchka** [comment]
Hi, @dgattey I'll try to take a look at that as soon as possible. `unwrappedTypeName` should be used for that indeed, but looks like there is some bug. In meantime can you provide the source code that you scan and that results in invalid output in the template?

**Comment by dgattey** [comment]
I knew you'd ask @ilyapuchka. Unfortunately I can't share the source code. I'll try to replicate it with a pared down version and figure out the minimum viable code to make it happen

**Comment by krzysztofzablocki** [comment]
@dgattey I think we just need that fragment API that you showed us the failed result, we need to see how the definition looks like so we can write a test to reproduce it

**Comment by dgattey** [comment]
Sorry, what do you need? The stencil file?

**Comment by ilyapuchka** [comment]
we need method signature that produces invalid result for you

**Comment by dgattey** [comment]
Anything like `public func getConversation(_ conversationRemoteId: String, response: @escaping ConversationApiResponse) -> Request?` causes it. I think it's the `@escaping` attribute on the parameter?
