### ISSUE TITLE
Other types in annotations

### ISSUE THREAD

**Issue by fpg1503** [krzysztofzablocki/Sourcery#174]
Currently the README states
> simple entry, e.g. sourcery: skipPersistence
> key = number, e.g. sourcery: another = 123
> key = string, e.g. sourcery: jsonKey = "json_key"

However it would be really nice if I could use it with other types (like dictionaries), I don't think much has to change because it already works for dictionaries with just one key-value pair:

`/// sourcery: SampleDict = ["myKey": "myValue"]` leads to `SampleDict = "[\"myKey\": \"myValue\"]";`

but

`/// sourcery: SampleDict = ["myKey": "myValue, "otherKey": 42]` leads to `SampleDict = "[\"myKey\": \"myValue]";` leads to `"\"otherKey\": 42]" = 1;
    SampleDict = "[\"myKey\": \"myValue";`

If I use `;` as a separator instead of `,` everything works fine but the generated code is not valid Swift code, so the issue seems to be [here](https://github.com/krzysztofzablocki/Sourcery/blob/9acfa15144f638e75359956e6232abad7fe30143/Sourcery/Parsing/Utils/AnnotationsParser.swift#L147).

**Comment by fpg1503** [comment]
If I make a PR fixing this could it be merged?

**Comment by krzysztofzablocki** [comment]
You won't have a good way to access values if we were to add this kind of support so I'm not sure if we should add it, whats your use case for this?

**Comment by fpg1503** [comment]
I use it to supply informations about function parameters with a helper function, I could also solve this using annotations in parameters (but I wouldn't know how to lay them out nicely).

A sample code is:
```swift
/// sourcery: GET = "group/{id}/users"
/// sourcery: Path = ["id": "groupId"]
func groupList(for groupId: Int, completion: (Result<[User], Error>) -> Void) -> Cancelable
```

which generates

```swift
func groupList(for groupId: Int, completion: (Result<[User], Error>) -> Void) -> Cancelable {
	let httpMethod: HTTPMethod = .get
	let rawPath = "group/{id}/users"
	let rawQuery: [String: Any] = [:]

	let path = rawPath.expanded(using: ["id": "groupId"])
	let pathAndQuery = path.adding(rawQuery)

	return request(httpMethod, path: path, completion: completion)
}
```

But when I use multiple values it doesn't work.

**Comment by ilyapuchka** [comment]
How do you want to use multiple values in annotations and how would you expect to use them?

**Comment by fpg1503** [comment]
The current use case I have is mapping parameters to a string representing their key to use in the path of a request. Since there is no support to parameter annotations I pass a dictionary mapping the field to their keys and use them with a helper function (in the example above `rawPath.extended(using: {{function.annotations.Path}})`).
