### ISSUE TITLE
Detect last iteration of a loop

### ISSUE THREAD

**Issue by alexito4** [krzysztofzablocki/Sourcery#179]
> What version of Swift are you using (swift --version)?

Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9

> What did you do?

```
    init(_ persisted: {{ type.name }}) {
        self.init(
{% for var in type.variables %}
            {{ var.name }}: persisted.{{ var.name }} {% if not last %},{% endif %}
{% endfor %}
        )
    }
```

> What did you expect to see?

I expect to generate a call to the default initialiser of the struct with each parameter separated by a comma but without adding the comma to the last parameter, because Swift doesn't like to have that comma.

```
self.init(
            title: persisted.title,
            associatedUrl: persisted.associatedUrl
        )
```

> What did you see instead?

```
self.init(
            title: persisted.title,
            associatedUrl: persisted.associatedUrl,
        )
```

The variable `last`, `first`, `counter` (from [Stencil](https://stencil.fuller.li/en/latest/builtins.html#built-in-tags)) doesn't seem to be present inside the `for` loops. 
Maybe I'm doing something wrong with the template or maybe there is a different way of accomplishing the same?

Any help would be appreciated, thanks!

**Comment by krzysztofzablocki** [comment]
try `if forloop.last`

**Comment by alexito4** [comment]
Nice! 
I was looking for some namespace but didn't find it, sorry. 
Thank you Krzysztof! 🙏
