### ISSUE TITLE
Parsing generic Array's element doesn't work

### ISSUE THREAD

**Issue by Antondomashnev** [krzysztofzablocki/Sourcery#185]
The bug appears because of the mistake in the `parseArrayElementType` method in `Composer`.
It says: `if name.hasSuffix("Array<")` but it should be `if name.hasPefix("Array<")`.

**Comment by krzysztofzablocki** [comment]
👍 good catch, mind adding that to the pr ?

**Comment by Antondomashnev** [comment]
@krzysztofzablocki I will open another one because I want to add a failing tests as well 😄
