### ISSUE TITLE
Add convenience accessor on Variable for `let` vs `var`

### ISSUE THREAD

**Issue by robertjpayne** [krzysztofzablocki/Sourcery#197]
Is there any way to determine a `let` vs a `var` with sourcery? I want to generate some code specific only to properties that can mutate.

**Comment by robertjpayne** [comment]
Looking at SourceKitten output I don't think this is possible, will have to use annotations instead!

**Comment by ilyapuchka** [comment]
Hey @robertjpayne 
`let` properties will have "" in their `writeAccess`, so you can check this property. We could ad a convenience property for that.

**Comment by robertjpayne** [comment]
@ilyapuchka OH so awesome, I updated the issue ticket 👍 will use this for now though
