### ISSUE TITLE
Introduce code attributes that can be used with Sourcery

### ISSUE THREAD

**Issue by krzysztofzablocki** [krzysztofzablocki/Sourcery#20]
A very useful feature will be adding attributed comments into source code, this will allow us to generate more complex/flexible templates.

@conradev mentioned rust lib that has something like that https://github.com/serde-rs/serde

Other use-case examples might be adding json keys, skipping variable for equality generation etc.

API might look like this (Feel free to suggest better one):

```swift
// sourcery: skipEquality, jsonKey = "complex_name"
var variable: String
```

In templates you might access it like:
```swift
{% ifnot variable.attributes.skipEquality %} ///... 
{% endif %}
```

**Comment by ilyapuchka** [comment]
In dipgen I use notation like this `@dip.register SomeType` to make it look like annotations in Java. 
I would though suggest to use something shorter than the full name of the tool also tacking into account that that's not exactly grammatically correct English 😉 Maybe something like combination of functional keys (`//#!`) or just brackets like in the tool you referred to?

**Comment by krzysztofzablocki** [comment]
I kind of like using the name of the tool, mostly because it makes it clear why this is there but let's discuss alternatives. @khanlou @conradev what do you guys think?

**Comment by khanlou** [comment]
My personal feeling is that this is well-trod ground, and we should basically copy Swiftlint's format:

```
// swiftlint:disable colon
let noWarning :String = "" // No warning about colons immediately after variable names!
// swiftlint:enable colon
let hasWarning :String = "" // Warning generated about colons immediately after variable names
```

Specifically, @krzysztofzablocki's original proposal seems good to me.

**Comment by conradev** [comment]
This proposal looks great! I agree with the naming as well – they're also called attributes in Rust (and actually part of the [AST](http://manishearth.github.io/rust-internals-docs/syntax/ast/struct.Attribute_.html)).

**Comment by AliSoftware** [comment]
You should rename the Stencil context variable `annotations` (instead of `attributes`) otherwise it would make it confusing with what Swift's AST actually calls "attributes" (namely `@noescape`, `@discardableResult`, etc)

**Comment by AliSoftware** [comment]
Also wondering if the comment format shouldn't be more like SwiftLint, namely not:
```
// sourcery: skipEquality, jsonKey = "complex_name"
```
But rather:
```
// sourcery:skipEquality
// sourcery:jsonKey "complex_name"
```

**Comment by krzysztofzablocki** [comment]
I implemented support for multiple lines of attributes like that, and also comma separated

**Comment by fbartho** [comment]
Can't we have the code attributes be in code themselves?
```
var myFoo: Sourcery(String, SkipEquality, JSONKey("json_key"))
// This gets transformed into:
var myFoo: String
/* elsewhere */
func toJSON(context:JSONContext) -> JSON {
return ["json_key", self.myFoo]
}
/* elsewhere */
func ==(one: A, two: B) -> Bool {
/* myFoo is marked as SkipEquality */
…
}
```

The examples above looks like you're parsing the model "in-place" and then writing code into the same directory. My thought was to have a Specs directory that defines your model, and then code generates much of how it works.

**Comment by fbartho** [comment]
Additionally, the benefit of having the code attributes be code themselves is that you would get autocomplete support, and type checking. You could compile the specs directory as an app itself, even.

**Comment by krzysztofzablocki** [comment]
@fbartho that would have to replace your code right? Someone suggested doing Elixir like macros, but I'm not sure if the modifying source is something we should pursue (if we didn't modify, how would this be valid code?) 
Could you create a new discussion issue for something like that? we can talk more there, I'm closing this as I've just released Sourcery version that implements this annotations. 

@ilyapuchka @khanlou @conradev Annotations have been implemented https://github.com/krzysztofzablocki/Sourcery/#source-annotations
