### ISSUE TITLE
Model generation from a spec which is not Swift code?

### ISSUE THREAD

**Issue by brennanMKE** [krzysztofzablocki/Sourcery#202]
I would like to know if it is a supported feature of Sourcery to generate code from a reference file, such as JSON to provide a template which can generate models. With StravaKit I hand-coded the models in Swift for the REST API which has responses which have a lot of properties. Some are optional and some are not. The models handle extracting values in failable initializers. It would be great to generate these models. It is not clear if Sourcery is aligned at all for this purpose. I'd appreciate some guidance.

https://github.com/StravaKit/StravaKit/issues/30

**Comment by krzysztofzablocki** [comment]
JSON -> Code creation seems like more SwiftGen than Sourcery

**Comment by brennanMKE** [comment]
Great, I will look into that one instead. Thanks!
