### ISSUE TITLE
Unknown filter 'upperFirst'

### ISSUE THREAD

**Issue by damianesteban** [krzysztofzablocki/Sourcery#205]
1. What version of Swift are you using (swift --version)?

Apple Swift version 3.0-dev (LLVM 17c4c6cf7a, Clang 4ca9e01a7c, Swift 31bbb2c208)

2. What did you do?

Using the `AutoMockable` protocol from https://github.com/marinbenc/Mock-Generation-Swift:

` $ sourcery Input.swift mockable.stencil Output.swift`

3. What did you expect to see?

An auto-generated class that conformed to the `AutoMockable` protocol.

4. What did you see instead?

```
Scanning sources...
Loading templates...
Loaded 1 templates
Generating code...
Unknown filter 'upperFirst'
```

**Comment by ilyapuchka** [comment]
Are you using the latest version of Sourcery?

Ilya Puchka

Отправлено с iPhone

**Comment by damianesteban** [comment]
What's the best way to get the latest version?  I installed sourcery via Homebrew.

**Comment by damianesteban** [comment]
I'm resurrecting this issue because it is almost identical, just a different filter error.

1. What version of Swift are you using (swift --version)?

Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)

2. What did you do?

Using the `AutoEquatable` protocol from the templates folder in this repository:

` $ sourcery Input.swift equatable.stencil Output.swift`

3. What did you expect to see?

An auto-generated struct that conformed to the `AutoEquatable` protocol.

4. What did you see instead?

```
Scanning sources...
Loading templates...
Loaded 1 templates
Generating code...
Unknown filter 'enum'
```

I am most definitely using the latest release.

**Comment by gabrieloliva** [comment]
I'm still getting this error with 0.11 version.
The outputs were
```
Found 575 types.
Loading templates...
Loaded 1 templates.
Generating code...
error: Unknown filter 'upperFirst'
```

**Comment by ilyapuchka** [comment]
it's `upperFirstLetter` for a long time already

**Comment by gabrieloliva** [comment]
Thank you @ilyapuchka 👍
