### ISSUE TITLE
replace doesn't work with typeName

### ISSUE THREAD

**Issue by alexito4** [krzysztofzablocki/Sourcery#206]
Hi!
I had the need to change the name of a type while generating some code. I'm trying `replace` in the same way I used it to modify the names of the variables themselves but it's just ignored. 

Replace on the variable name works:

    var.name|replace:"a","s"

But with the typeName doesn't

    var.typeName|replace:"a","s"

It also works fine when I'm working with the type itself

    type.name|replace:"a","s"

Example of usage:

```
public struct {{ type.name|replace:"RM","" }} { // this works because is type.name
    {% for var in type.variables %}
    public let {{ var.name }}: {{ var.typeName|replace:"RM","" }} // this doesn't
    {% endfor %}
}
```

Thanks.

*Edit: I could use `var.type.name|replace:"RM",""` but that the type seems to be only available when is a custom type, so for String this would be empty. I'm using `{% if var.type %}{{ var.type.name|replace:"RM","" }}{% else %}{{ var.typeName }}{% endif %}` for now.*

**Comment by ilyapuchka** [comment]
`typeName` is not a string, it is of `TypeName` type. So you have to use `typeName.name`

**Comment by alexito4** [comment]
you are right! changing it to `typeName.name` works.

`typeName` gets printed as the name on the generation (at least in the cases I'm using it) so I didn't thought it was not a string. 

Thanks!
