### ISSUE TITLE
Get the Default Value of a Method Parameter

### ISSUE THREAD

**Issue by brassel** [krzysztofzablocki/Sourcery#209]
As far as I can see from the code this is not possible at the moment.
The default value ist contained in the full method name but it might be convenient to make this value available more easily.

Thanks for the great work on Sourcery!

**Comment by ilyapuchka** [comment]
We already received similar request in #70 but could not come up with any use case. Do you have anything in mind how that can be used in templates?

**Comment by brassel** [comment]
Did I put my comments to the wrong issue now? I added them to #70...
Sorry if I created a confusion!

**Comment by ilyapuchka** [comment]
Can you move these comments here, please? Your use case make sense, will be useful for other tasks like generated decorators and mocks. I will try to look into that,
