### ISSUE TITLE
Get the Direct Dependencies of a Method

### ISSUE THREAD

**Issue by brassel** [krzysztofzablocki/Sourcery#210]
One feature I would really love to see in Sourcery would be way to retrieve the list of methods which a given Method could call directly. As far as I see this is not possible with the current code or does Sourcery give you access to the method bodies somehow?

All hail to the swift metaprogrammers!

**Comment by krzysztofzablocki** [comment]
not right now, we'd need to analyze bodies for syntax, I'm not sure if thats worth extra time spent in parsing, seems like this would be useful for building other kind of tools rather than code generation?

**Comment by brassel** [comment]
Well, I would have need for it in my code generator. :)
Anyway, is there really any time saving in omitting this? Do you not have to parse everything according to the language definition to deliver correct results for parts of it?

**Comment by krzysztofzablocki** [comment]
whats your use case?

**Comment by brassel** [comment]
There is a tool I use which generates code from designs. (Called PaintCode, if you don't know it, really cool!) I take the generated code from this tool and use your great library to add my own definitions to the paintings. E.g., create a button for every drawing that is called "XXX Button" etc. And I would like to create a controller for everything called "YYY Screen". But right now I have now way to find out which buttons this screen would contain. But if I would know which methods "drawXXXButton" are called from "drawYYYScreen" this information would be in my hand. 

Sounds like a good use case for Sourcery?

**Comment by ilyapuchka** [comment]
For me it feels like a good use case for code generation plugin for PaintCode itself, not for Sourcery.

**Comment by ilyapuchka** [comment]
To support that in general technically should not be hard, as sourcekit already provides structured information about method body, but there are so many edge cases that it might be challenging to cover

**Comment by brassel** [comment]
Well, there is no plugin system for PaintCode yet, unfortunately. Otherwise, I would think that you are totally right about how to tackle that use case. So, how to go about this discussion? Should I maybe come up with different use cases for knowing a method's dependencies? Here are a few:

* helps with module dependency and knowing what to import in your generated code
* helps to identify dead code (not called anywhere)
* and say you wish to extend method definitions by an extra argument and add boilerplate operations on that argument. Knowing the depedendencies let's you which additional methods you have to extend as well.

As to the edge cases in finding the dependencies. I gues you would have to traverse the AST such that you are sure to visit every possible appearance of a method call, right?

**Comment by krzysztofzablocki** [comment]
Personally I feel this is going beyond regular code generation based on project types, I feel like Sourcery should focus on that, the imports use case can be made simpler than AST syntax parsing by just grabbing all the import statements from file etc

I'd rather keep Sourcery focused than diverge into this territory(thats covered by other tools), what do you think @ilyapuchka ?

**Comment by brassel** [comment]
Is there a tool by which I could easily get a parsed swift file as easily and convenient like using Sourcery? Maybe I am in the wrong territory as well. :o)

**Comment by krzysztofzablocki** [comment]
@brassel so, let me restate my issue here:
Sourcery is meant to analyse the structure of your code, the types that you have and allow you to generate boilerplate that will allow you to metaprogramming which is missing from Swift itself.

What I'm concerned about is that if we start analyzing what each method does then the amount of complexity will shoot through the roof

**Comment by brassel** [comment]
Yes, krzysztofzablocki, you have a point. Code analyzation sounds much like a different beast than code generation to avoid hand maintained boilerplate methods. And supporting code generation is good enough in itself without enabling static code analysis as well.
So, let me have one last go to describe what kind of code I want to generate (as I do not whish to do code analysis in my use case at all).
As described I have this code generated by PaintCode:

    func drawFormView(someParameters) {
      ...
      drawFormLabel(...) 
      ...
      drawCancelButton(...) 
      ... 
      drawSubmitButton(...) 
      ...
    }

and from this I want to generate classes like this

    class FormLabel: UIView {...}
    class CancelButton: UIButton {...}
    class SubmitButton: UIButton {...}
    class FormView: UIView {
      formLabel: FormLabel?
      cancelButton: CancelButton?
      submitButton: SubmitButton? 
    }

I hope this shows that, indeed, I want to omit a lot of boilerplate code by generating my classes with Sourcery. Of course, I could understand if you think that it is too far from your intended use.
However, one last remark: As I noted in issue #70 this might be done by simply exposing the AST of the methods body, which you must surely have after parsing the Swift document, or don't you?

**Comment by ilyapuchka** [comment]
I agree with @krzysztofzablocki that it's better to have a focus on one thing, at least for now, before we reach 1.0. 
What I think we can do now to support your idea it to make Sourcery a framework (only parser logic, which is the core functionality)  and expose substructure data that we get from SourceKitten and already store for each type and methods in a private property.  We can also include a method body as a string property, maybe it will be useful for some other tasks too. 
But doing any parsing of method body in order to analyse it's dependencies is just too complex and I think SourceKitten data will be not enough, so we will need to do a lot of manual parsing (which in my personal opinion we should do as less as possible, relying more on SourceKit). If we move into that direction it will fell like we are building a Swift compiler in Swift or something =)
Otherwise it seems like it's easier for you to use SourceKitten directly and do exactly what you need, not making it a generic solution what Sourcery aims to be for some subset of problems.
