### ISSUE TITLE
Cannot process large files

### ISSUE THREAD

**Issue by threat70** [krzysztofzablocki/Sourcery#222]
Hi!
Today I received error from Sourcery script: "Illegal instruction: 4"
After some research I find, that error occurs when sourcery trying parse Localized.swift (in this file I keep all NSLocalizedString, for now it have 1200 lines)
Error disappears when I remove some func.
e.g. 
I remove one function and error disappears
I remove other function and error remains, but if I remove more other functions (not from the example above), then error disappears

Maybe sourcery have limit on file parse?

As a workaround I select only necessary for scan folders
Would be nice to have ability to exclude some files

swift version:
```
Apple Swift version 3.1 (swiftlang-802.0.48 clang-802.0.38)
Target: x86_64-apple-macosx10.9
```

**Comment by ilyapuchka** [comment]
Hi @threat70 
Sourcery does not have any explicit limit on file length, so the problem is probably caused by some failure in parser. If you can share example that does not work it will help.
Do you use watch mode? Does the same error happen if you run Sourcery with `--disableCache`?

**Comment by krzysztofzablocki** [comment]
I think there is probably some unicode character thats causing issue with the byte range

**Comment by threat70** [comment]
@ilyapuchka for tests I always run with --disableCache and without watch mode

@krzysztofzablocki yes, I have the same stack trace.

I sent part of file that cause a crash to @krzysztofzablocki email

**Comment by krzysztofzablocki** [comment]
@threat70 would you mind if I added the content of that localized file as one of our tests to avoid regressions?

**Comment by threat70** [comment]
@krzysztofzablocki Of course, I already tried to remove the secret content as much as possible before sending

**Comment by krzysztofzablocki** [comment]
@threat70 sorry, english is not my native language, not sure if I understood that message correctly, is it ok to add that file to our tests?

**Comment by threat70** [comment]
@krzysztofzablocki yes :)
