### ISSUE TITLE
Improve caching for swift templates

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#229]
Currently swift templates are always compiled from scratch, which takes a lot of time comparing with using other types of templates. To run on Sourcery own code with just a single swift template takes 17 seconds on my 1,8 GHz Intel Core i5 Air.

- [x] copy template source code and binary to Sourcery cache and do not recompile it if it does not change
- [x] precompile all runtime files in a separate module and link it when compiling template

**Comment by krzysztofzablocki** [comment]
cc @kzaher

**Comment by kzaher** [comment]
Hi @krzysztofzablocki ,

yeah, I think that makes sense.

I was suggesting similar changes a while ago over Slack. 
I think you've responded that Sourcery should be fast enough now since you've added caching and that it should be ok as it is, or something similar, can't remember.

¯\\\_(ツ)\_/¯

**Comment by krzysztofzablocki** [comment]
Hehe the parsing was bottleneck then ;) Swift templates are much slower than anticipated

**Comment by ilyapuchka** [comment]
@krzysztofzablocki @kzaher for second point we will need to extract at least all "runtime" files into a framework and share it between the tool and swift templates, so that it's compiled only once. I would probably go for extracting the whole parsing layer into a framework so that we get double profit from that. But we can also do that in two steps, first extract only runtime files to improve swift templates, next - add parsing stuff. What would you say?

**Comment by kzaher** [comment]
@ilyapuchka there are two options imho, either make it part of two layer cache logic or part of the main project.

I agree that extracting runtime files into it's framework would be simpler and probably better. 👍

**Comment by ilyapuchka** [comment]
Resolved with #240 🎉
