### ISSUE TITLE
Do not fail whole process cause of error in single template file

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#233]
Currently we are failing the whole generation process when we encounter error in parsing some template file (theoretically we should not fail in parsing source files if they can be compiled). Instead we could just warn that there is an error and we can not process this file correctly, so generated code might be not complete. What do you think @krzysztofzablocki ?

**Comment by krzysztofzablocki** [comment]
I think we should keep failing on any error, one of the main goals is avoiding human errors, there might be cases when breaking one template would allow project to compile but work not as expected

**Comment by krzysztofzablocki** [comment]
does that argumentation make sense @ilyapuchka ?

**Comment by ilyapuchka** [comment]
I have mixed fillings to be honest =) From one point it makes perfect sense, from another I think that templates should be isolated and failure in one should not affect failure of the whole process, what can also save time on regeneration. And if one template fails but some code relies on it to work project will not compile any way, I guess. But maybe my feeling is caused by development process and it should be different while using the tool, what we just start to do in our project.

**Comment by krzysztofzablocki** [comment]
the tool has to be reliable otherwise people won't have confidence to use it, anything thats not build error is going to get ignored as not everyone uses treat warnings as errors etc, the watcher mode already recovers from errors so I really don't want us to start allowing partial state to be allowed in regular use

**Comment by ilyapuchka** [comment]
Ok, agree. Let's keep things like they are now. 👍

**Comment by Joannis** [comment]
I'm not sure how possible it is, but some more detailed errors on where and possibly why the template is failing would be golden. Currently a non descriptive error pops up and it forces me to remove blocks of code until I find the culprit.

**Comment by krzysztofzablocki** [comment]
its on the todo list #90
