### ISSUE TITLE
Make typealiases accessible for types and in global scope

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#235]
With typealiases becoming more stable we can make them accessible in templates. This will allow some nice tricks like using typealias value instead of annotations to generate typed things.
`Type` should provide typealiases mapped to their names via`typealias` property and array of typealiases for iteration via `typealiases` property. The same for global typealiases.

**Comment by Antondomashnev** [comment]
@ilyapuchka could you elaborate on your idea to have `typealiases mapped to their names via typealias property`?

```
class Foo {}
typealias Foo1 = Foo
typealias Foo2 = Foo

type.typealias -> "Foo1Foo2"?
```
