### ISSUE TITLE
Multiple enum case annotations are turned into arrays.

### ISSUE THREAD

**Issue by agentk** [krzysztofzablocki/Sourcery#236]
I've noticed since #226, that if an enum has cases with annotations, the annotations are incrementally added together.

Ie,
```
enum SomeEnum {
    // sourcery: value = "TYPE 1"
    case type1
    // annotations[value] = "TYPE  1"

    // sourcery: value = "TYPE 2"
    case type2
    // annotations[value] = ["TYPE  1", "TYPE 2"]
}
```

Is this the expected behaviour?
Is there still a way of not inheriting previous annotations in enum cases like the previous behaviour?

**Comment by ilyapuchka** [comment]
Hi, @agentk 
That's a bug, thanks for reporting. Can you try to put `;` after each case and see if it still happens?

**Comment by agentk** [comment]
Your amazing @ilyapuchka 😁. I didn't get a chance to get back and try it yesterday and you have already found and fixed it 🎉.
