### ISSUE TITLE
Is compareOptionals necessary in AutoEquatable template?

### ISSUE THREAD

**Issue by garnett** [krzysztofzablocki/Sourcery#246]
According to http://swiftdoc.org/v3.0/operator/eqeq/ stdlib has overloads for optionals:

```
func == <T>(_: _OptionalNilComparisonType, rhs: T?)
func == <T>(_: T?, rhs: _OptionalNilComparisonType)
func == <T : Equatable>(_: T?, rhs: T?)
```

**Comment by krzysztofzablocki** [comment]
`compareOptionals` is used for nonequatable types that have `==` implemented, like protocols or arrays

**Comment by garnett** [comment]
I see now, thanks for the explanation.
