### ISSUE TITLE
Parse closure types

### ISSUE THREAD

**Issue by ethanjdiamond** [krzysztofzablocki/Sourcery#251]
Is there a way to grab the parameters for a variable who's type is a closure?

Ex:
class Foo {
   let bar: (Int?) -> String
}

Given class Foo, i'm iterating over all of the variables, which gives me bar. I'd like to be able to say "if bar is a closure, then for each parameter for that closure, print the type". Is there a way to do that?

**Comment by ilyapuchka** [comment]
Hey, Ethan. Not possible yet unfortunately, we just check for type being closure, but we can add that in a near future. Contributions are welcome as always! 

Ilya Puchka

Отправлено с iPhone

**Comment by ethanjdiamond** [comment]
No worries! Thanks for the quick response.
