### ISSUE TITLE
AutoEquatable/Hashable changes for protocols

### ISSUE THREAD

**Issue by krzysztofzablocki** [krzysztofzablocki/Sourcery#253]
We recently switched to `storedVariables` for the templates, but I think for protocols we should still use computed ones, otherwise nothing will actually be generated right now. thoughts @ilyapuchka ?

**Comment by ilyapuchka** [comment]
Yes, I guess so. Though I'm not sure how good is the practice to define Equatable in protocol extensions in general.

**Comment by krzysztofzablocki** [comment]
It doesn't make `Equatable` conformance, because that would make it PAT, it just adds `==` for them
