### ISSUE TITLE
Provide the dependencies of a type.

### ISSUE THREAD

**Issue by yageek** [krzysztofzablocki/Sourcery#256]
I am using Sourcery with CocoaPods in different libraries projects.
In every project, I annotate some protocols using Sourcery with the annotation `feature`.

In my application Project, I import some of those libraries. I would like to generate some swift file based on the protocols that have been marked as `feature`.

It would be also necessary to import the dependencies of the different 'features' protocol. 

Is it possible to retrieve the frameworks required by one `Type` ?

**Comment by ilyapuchka** [comment]
If you scan your sources using target config param then each type will have "module" property with the module name where it was defined. So if you have list of types you can have list of modules.

**Comment by yageek** [comment]
I did not saw the `module` property of `Type` in the documentation :( With this do I need to manually choose a target name for each library I will import ?

**Comment by ilyapuchka** [comment]
Yep, it's not yet public as we just added support for multiple targets and there are some issues like #214, but you can use it in Stencil templates already.
In the `sourcery.yml` file you need to put project and all its targets that needs to be scanned. Then Sourcery will san all the files which are included in these targets, [here](https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/usage.html) are some details

**Comment by ilyapuchka** [comment]
`module` property of `Type` is now public so can be used to implement this
