### ISSUE TITLE
Update Stencil to 0.9

### ISSUE THREAD

**Issue by cwagdev** [krzysztofzablocki/Sourcery#259]
This new version supports the `elif` tag which is pretty helpful along with a few other things.

https://github.com/kylef/Stencil/blob/master/CHANGELOG.md#090

**Comment by AliSoftware** [comment]
@ilyapuchka StencilSwiftKit 1.0.2, which now depends on Stencil 0.9.0 too, has just been released to CocoaPods, so it shouldn't be a blocker for this anymore 👍
