### ISSUE TITLE
Add tests for bundled templates

### ISSUE THREAD

**Issue by Antondomashnev** [krzysztofzablocki/Sourcery#261]
As a part of the discussion in https://github.com/krzysztofzablocki/Sourcery/pull/257, there was an idea to cover the templates from `./Templates`  with tests because it's getting hard to do the change and check manually if the template is not broken. 

The simpler way was suggested by @krzysztofzablocki that can do the job is to create a project that generates different files with the templates and then we can compare those files with the master files.

**Comment by ilyapuchka** [comment]
Thanks @Antondomashnev for amazing work on that 👍
