### ISSUE TITLE
Settable computed property treated as stored property

### ISSUE THREAD

**Issue by cnicolai** [krzysztofzablocki/Sourcery#262]
Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
Target: x86_64-apple-macosx10.9

Hi!

When I define the following struct

``` Swift
struct timeLength: AutoArbitrary {
    var hours: Double
    var minutes: Double {
        get {
            return hours*60
        }
    }
}
```

and run sourcery with the stencil

```
{% for variable in type.storedVariables %}
{{ variable.name }}
{% endfor %}
```

I get the output I would expect, namely

```
hours
```

When I add a setter to hours

```Swift
struct timeLength: AutoArbitrary {
    var hours: Double
    var minutes: Double {
        get {
            return hours*60
        }
        set {
            hours = newValue/60
        }
    }
}
```

`minutes` is considered a stored property, I get the output

```
hours
minutes
```

I don't really understand this, `minutes` should still be a computed property?

(This is the first time I write anything on GitHub, so if I did anything that is strange or unusual, please let me know! :) )

**Comment by ilyapuchka** [comment]
@cnicolai sounds like a bug to me, because we are supposed to handle this exact case. Thanks for reporting!

**Comment by cnicolai** [comment]
Alright, thanks!
