### ISSUE TITLE
Unknown filter enum

### ISSUE THREAD

**Issue by damianesteban** [krzysztofzablocki/Sourcery#268]
I had a similar issue to this awhile ago but it was due to not having the latest version installed.  I have the latest version this time - not sure what the issue is.

### What version of Swift are you using (swift --version)?

Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)

### What did you do?

Using the AutoEquatable protocol from the templates folder in this repository:

$ sourcery Input.swift equatable.stencil Output.swift

### What did you expect to see?

An auto-generated struct that conformed to the AutoEquatable protocol.

### What did you see instead?

```
Scanning sources...
Loading templates...
Loaded 1 templates
Generating code...
Unknown filter 'enum'
```

**Comment by ilyapuchka** [comment]
Hi, @damianesteban 
Looking at the command you run I'm pretty sure you are using not latest version (latest version require `--sources`, `--templates` and `--output` arguments). Can you try install the  latest one from releases page?

**Comment by damianesteban** [comment]
I removed / cleaned up the version I had installed from homebrew, downloaded the latest release (0.6.0) and executed the following command:

`$ sourcery --sources SourceryTest/ --templates Templates/ --output Output.swift`

And I get the following error:

```
Unknown Arguments: --sources --templates --output

Arguments:

    source - Path to a source swift files
    templates - Path to templates. File or Directory≥
    output - Path to output. File or Directory.

Options:
    --watch [default: false] - Watch template for changes and regenerate as needed. Only works with specific template path (not directory).
    --verbose [default: false] - Turn on verbose logging for ignored entities
```

Is 0.6.0 the most recent release?

**Comment by ilyapuchka** [comment]
Yes, it's the latest release, but it does not fill like you are running this version, because 0.6.0 has a different set of arguments. You probably have older version installed somewhere in your `PATH`
I'll add `--version` command to make debugging such issues easier.

**Comment by ilyapuchka** [comment]
You can run `sourcery --version` to see the version number

**Comment by damianesteban** [comment]
Yes you're right, I have a much older version somewhere in my `PATH`.  Sorry for the confusion.  Thank you.
