### ISSUE TITLE
Include docset in repository or ignore it?

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#271]
Currently docset is included in at docs path in the repo together with its zipped version. That creates conflicts with each doc update. So I would say we should ignore this zip for good. Also we maybe should not keep docset in the repo either and just attach zip archive, mentioned before, to the release along with binary zip. This operation (updating and uploading docset zip) can be part of release process. Any intermediate docs update will be still available via html version of the docs on github. What do you think @krzysztofzablocki ?

**Comment by krzysztofzablocki** [comment]
I was thinking that we should not update docs with each feature, but instead have it as part of process for `rake release` because it confuses people otherwise

**Comment by Kentzo** [comment]
@ilyapuchka My understanding is that there should be docset archive somewhere along a binary release, but cannot find it. Was it decided to abandon docsets completely?

I'm looking to add it to Dash.
