### ISSUE TITLE
Provide API for error output 

### ISSUE THREAD

**Issue by mariotaku** [krzysztofzablocki/Sourcery#275]
Using Sourcery's swifttemplate is a real pleasure. I have a feature request though. Currently if I find something wrong with my annotations, I use `fatalError` to abort generation. It's working but it's not perfect. Lots of stack traces printed and useful error messages was not so easy to find.

Is it possible to provide some logger-like methods to help template creator print out error message and quit build?

**Comment by krzysztofzablocki** [comment]
sounds reasonable, would you like to try making a PR for that? you can add a function for that to `GenerationContext` as thats the main thing that your code runs in

**Comment by mariotaku** [comment]
@krzysztofzablocki Sorry, I'm not yet skilled with Swift but I can try provide some ideas like make `generate` function capable of throwing errors, catch it in its caller, print out error information contained in that error and quit with error codes.

**Comment by ilyapuchka** [comment]
We can just make `ganerate` method throw and import "string as error" extension to swift templates runtime. The tool will take care of printing the error

Ilya Puchka

Отправлено с iPhone
