### ISSUE TITLE
Crash in parseDeclarationAttributes

### ISSUE THREAD

**Issue by Obbut** [krzysztofzablocki/Sourcery#276]
Sourcery seems to crash parsing my code sometimes, on line [740 of FileParser.swift](https://github.com/krzysztofzablocki/Sourcery/blob/50fff7da3fe547178463c0f73eb4c947c5925b42/Sourcery/Parsing/FileParser.swift#L740) in `parseDeclarationAttributes`. It tries to get a substring starting at `9223372036854775807`, which happens to be `NSNotFound`.

I think a range check should be added there, but I don't know if that is all that is needed.

**Comment by Obbut** [comment]
Maybe the solution is just to change that line to this:

```
if location < prefix.length {
    return parseAttributes(prefix.substring(from: location))
}
```

But perhaps there is no bounds check for a reason (the situation should not occur)?

**Comment by krzysztofzablocki** [comment]
we should probably add the `NSNotFound` check explicitly, do you want to send a PR?

do you have sample code that can reproduce the issue? would be good to add an regression test for it

**Comment by ilyapuchka** [comment]
#287 should make it safer but would be great if you can isolate the code that results in issue.
