### ISSUE TITLE
Adding support for SPM

### ISSUE THREAD

**Issue by fbartho** [krzysztofzablocki/Sourcery#28]
Is the plan for consumers of Sourcery to download a built-binary, and then target that at their configuration, or is the plan for people to mostly compile sourcery while patching in their changes?

If the plan is mostly expecting people to compile Sourcery, then I think it would be great if we had Carthage/SPM support. I don't think it's overly political to suggest that there are strong feelings about CocoaPods and its weaknesses/issues.

I don't know if Swift Package Manager is setup to deal with a target like Sourcery, but even if it's only preliminary or partial support, I think it would be useful to have that integrated. Since Sourcery is a tool for building great Swift Apps, I think it would be a good community citizen if it also had SPM support.

**Comment by krzysztofzablocki** [comment]
I think people will tend to use this in both modes:

- As a standalone tool, especially when using `--watch` mode to prototype new templates against existing source code, I think #15 would be the best approach for distributing that, right now easiest way to grab bin is from releases tab, which is meh...
- As part of the build process, this has the benefit of avoiding refactoring bugs in our regular Swift sources. Quite often someone adds a new variable to source code and forgets to update corresponding boilerplate (equality, hashing), and those things Swift compiler doesn't enforce for us, but if we use Sourcery to generate that boilerplate, it will automatically update the code for us avoiding bugs. 

For the build process distribution, I would love to support Carthage and SPM, is any of those something you are familiar with and would have time / like to contribute? I don't have experience with those package managers

**Comment by krzysztofzablocki** [comment]
Actually Carthage I don't think makes sense because this needs binary form not a framework, we just need homebrew and SPM

**Comment by vknabel** [comment]
I could add SwiftPM support. Adding Carthage support should be very easy (share schemes, declare dependencies)

**Comment by krzysztofzablocki** [comment]
@vknabel that would be awesome! and a step towards `brew` integration

**Comment by krzysztofzablocki** [comment]
Swift PM has been added, huge thanks to @vknabel :) closing this one
