### ISSUE TITLE
Prepare the RELEASING.md document

### ISSUE THREAD

**Issue by Antondomashnev** [krzysztofzablocki/Sourcery#280]
@krzysztofzablocki @ilyapuchka I see the number of collaborators is growing so I would like to propose a structure for the releasing process, which is also could be a good dock the new members like me 😄 

As an example of the document I can share the one that we created for the Danger-Change plugin [here](https://github.com/dblock/danger-changelog/blob/master/RELEASING.md)

**Comment by krzysztofzablocki** [comment]
Great idea!

**Comment by ilyapuchka** [comment]
I noticed that current release process requires @krzysztofzablocki github api token, meaning that only one person can release actually. I guess this document will be more useful if other members can release too, but that's a different question =)

**Comment by Antondomashnev** [comment]
Yep, maybe the bot user can release it? So that nobody will share the real token.

**Comment by ilyapuchka** [comment]
I we need to share release rights I think it's better to modify rake file to get path to token file through environment or smth like that.

**Comment by Antondomashnev** [comment]
With the token env you mean that each of the member will generate own token and will use for release? Sounds good 👍

**Comment by ilyapuchka** [comment]
yes, exactly that

**Comment by Antondomashnev** [comment]
After the #286 I can propose the draft, but I expect it will be more a team work on the document 😄

**Comment by ilyapuchka** [comment]
Thanks @Antondomashnev for amazing work on that!

**Comment by Antondomashnev** [comment]
@ilyapuchka I think next release should be done by you or @krzysztofzablocki so we can accumulate the feedback for the process 😄
