### ISSUE TITLE
Iterate over annotations

### ISSUE THREAD

**Issue by bolismauro** [krzysztofzablocki/Sourcery#281]
Hi, 

I need to find a way to iterate over annotations but I can't find a way..

For instance here:
```
{% for type in types.based.TheProtocol %}
  // generate
  {% for case in type.cases %}
    /*  {{ case.annotations }} */
    {% for key,value in case.annotations %}
      // >> {{ key }} - {{ value }}
    {% endfor %}
  {% endfor %}
{% endfor %}
```

it prints the `case.annotations`, which is a dictionary, but for some reasons the for tag doesn't work.

According to the [stencil documentation](http://stencil.fuller.li/en/latest/builtins.html)  `The for tag can iterate over dictionaries.` but it doesn't work.
Am I doing something wrong?

**Comment by ilyapuchka** [comment]
Are you running on the latest master version? We only updated to the Stencil version that supports that in #274, so it's not released yet

**Comment by bolismauro** [comment]
No, I'll wait for it, thanks
