### ISSUE TITLE
Multiple annotations trick

### ISSUE THREAD

**Issue by bolismauro** [krzysztofzablocki/Sourcery#288]
I have a question 

I just discovered this "trick"
```
enum T {

  // sourcery: type= one, array= ok, array= cancel
  case one
}
```

to basically get an array in the annotations. Is it something that I can rely on or it is just a side effect of an internal detail?

Basically I want to be sure that I can rely on this behaviour going forward, otherwise I'll find another solution

**Comment by ilyapuchka** [comment]
That's a feature by design. Bugs related to that were introduced with support for inline annotations, if you don't use them everything should work as expected.
