### ISSUE TITLE
Out of bounds crash

### ISSUE THREAD

**Issue by bolismauro** [krzysztofzablocki/Sourcery#289]
Sourcery crashes for an out of bounds exception during the generation.

In particular, it crashes in `FileParser.swift`, line 708.
If I add `guard location < prefix.length else { return [:] }` before the return, it seems to work, but I'm not sure it is a proper fix to be honest.

Moreover, once you manage to make it work (e.g., by adding that workaround) there are no more crashes, even with without the workaround

Note: I'm using master

**Comment by krzysztofzablocki** [comment]
duplication of #276
