### ISSUE TITLE
Sourcery watch mode erase the content of some of my generated files

### ISSUE THREAD

**Issue by Palleas** [krzysztofzablocki/Sourcery#294]
I have the following `.sourcery.yml` file:

```yml
sources:
    - Paparazzi
templates:
    - Templates
output: Paparazzi
```

A couple of templates (AutoEquatable, etc.).

When I run `sourcery`, It works A1. When I run `sourcery -w`, the content of my `AutoEquatable.generated.swift` file is replaced with

```swift
// Generated using Sourcery 0.6.0 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

STATUS:
Skipping Paparazzi/AutoList.generated.swift as it is empty.
```

I'm using Sourcery `0.6.0` and I just checked, this doesn't happen with sourcery 0.5.9. My templates are available [here](https://github.com/Palleas/Paparazzi/blob/master/Templates/AutoSluggable.stencil), in case that helps. 

Let me know if I can provide additional informations.

**Comment by ilyapuchka** [comment]
Hi, @Palleas
#296 should resolve this issue

**Comment by Palleas** [comment]
That's great to hear! :)
