### ISSUE TITLE
AutoEquatable template doesn't generate correct code for protocols

### ISSUE THREAD

**Issue by Antondomashnev** [krzysztofzablocki/Sourcery#297]
This is the continuation of the question from #286 about `AutoEquatable` protocol issue.
It seems the commit 8bd91e275f09e79122c3303935d3a1853fe1d0d6 brought the bug, because `computedVariables ` is always an empty array.

I think we can use the same logic for protocols as we use in `AutoMockable` template:
```
{% for variable in type.allVariables %}
    ...
{% endfor %}
```
I think we just need to add new condition that the variable actually has getter access.
@ilyapuchka @krzysztofzablocki thoughts?

**Comment by ilyapuchka** [comment]
Do you mean to add check for getter in a template?

**Comment by Antondomashnev** [comment]
@ilyapuchka I mean to change template to iterate through `allVariables` but filter only for those that have getter access 😄

**Comment by ilyapuchka** [comment]
wouldn't they all have it?...

**Comment by Antondomashnev** [comment]
I thought that you can have `{ set }` for protocol variable, seems you're right. One more thing, will `allVariables` also return static variables?

**Comment by ilyapuchka** [comment]
Yes, it will, so they should be filtered by `isStatic` (latest version of Stencil supports `where` or we can use filter `!static`)

**Comment by Antondomashnev** [comment]
cool, I will prepare the fix 👌
