### ISSUE TITLE
Reproduce all comments of a declaration

### ISSUE THREAD

**Issue by Obbut** [krzysztofzablocki/Sourcery#299]
Sometimes I use Sourcery to generate "copies" of methods on a type, with slightly different arguments for example. For these methods, I would like to be able to reproduce the (doc) comment of the original method in my template.

Is it currently possible to get the comments belonging to a certain declaration?

**Comment by Antondomashnev** [comment]
@Obbut Hi ✋ 
As far as I know with the `SourceKitten` framework it's possible, but I would like to ask @ilyapuchka or @krzysztofzablocki if it's within the Sourcery scope of the tool at the moment 😄

**Comment by ilyapuchka** [comment]
it should be possible technically, and I get the point to have it, but I doubt it belongs to the scope of Sourcery.
Without any changes in Sourcery you can workaround this by putting your doc comment in annotation. Not the best of course, but something at least.

**Comment by Antondomashnev** [comment]
@ilyapuchka @krzysztofzablocki should we close the issue, or let's leave at as a discussion point?
