### ISSUE TITLE
Don't hardcode the path in the usage help

### ISSUE THREAD

**Issue by AliSoftware** [krzysztofzablocki/Sourcery#3]
When installed via Pods, the usage still mention the .app:

```
$ Pods/Insanity/bin/sourcery --help
Usage:

    $ Insanity.app/Contents/MacOS/Sourcery <source> <templates> <output>
```

Installed via CocoaPods, Sourcery 0.2.0

**Comment by krzysztofzablocki** [comment]
It's not really hardcoded, basically `insanity` is a simple bash script that is in fact a link into the app, because as you know swift CLI can't embeed frameworks. 
Would be good enchancement to update the print path though if we can figure out how to modify Commander help output

**Comment by krzysztofzablocki** [comment]
I'm going to close it as we will soon be moving to using swift pm build version which doesn't need to do symlink tricks
