### ISSUE TITLE
Not finding Standard Library protocol conformance

### ISSUE THREAD

**Issue by cnicolai** [krzysztofzablocki/Sourcery#301]
Hi!

I tried to work with Sourcery on Types conforming to protocols from the Swift Standard Library, for example Comparable:

```
{% for type in types.implementing.Comparable %}
	{{ type.name }}
{% endfor %}
```

This does not work for structs conforming to Comparable I defined. Am I missing something?

Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
Target: x86_64-apple-macosx10.9

**Comment by ilyapuchka** [comment]
Hey. You need to use `based` here. We dot yet provide full support for standard library types, meaning distinguishing if this is a protocol, so you use `implementing`, or a class and you usr `inheriting`. We only do that for those types defined in the sources scanned by Sourcery.

Ilya Puchka

Отправлено с iPhone

**Comment by cnicolai** [comment]
Thanks! I will try to figure that out.

**Comment by cnicolai** [comment]
Worked for me, thanks again!
