### ISSUE TITLE
Support annotation array detection

### ISSUE THREAD

**Issue by samskiter** [krzysztofzablocki/Sourcery#302]
Im trying to loop over repeated annotations, except sometimes they might not be repeated.

How can I treat the annotation as an array even if it's only a single value?

**Comment by ilyapuchka** [comment]
Annotations are stored as a dictionary so you can access them by their name. In Stencil you can [iterate over dictionary](https://github.com/kylef/Stencil/releases/tag/0.9.0) now, using swift templates it's just normal iteration over dictionary.

**Comment by samskiter** [comment]
Thanks for the fast reply @ilyapuchka - unfortunately don't seem to be able to get that working:

```
{% for type in types.protocols|annotated:"TypeErase" %}

{% for key, value in type.annotations %}{{ key }}{% endfor %}

{% endfor %}
```

This crashes

**Comment by ilyapuchka** [comment]
And what is the crash?

**Comment by samskiter** [comment]
Whoops you beat me to it, was just updating my comment ^^

**Comment by ilyapuchka** [comment]
We didn't release a new version with Stencil 0.9.0 yet, so you need to use latest master version - [CHANGELOG](https://github.com/krzysztofzablocki/Sourcery/blob/master/CHANGELOG.md)

**Comment by samskiter** [comment]
aha ok, thanks, i will try pointing my pod repo to you 👍

**Comment by samskiter** [comment]
@ilyapuchka Looks like your podspec doesn't work out of the box either. i'll see if I can work out how to fix it

**Comment by ilyapuchka** [comment]
CocoaPods will download latest release, so you should build from source code.

**Comment by samskiter** [comment]
@ilyapuchka you can use cocoapods to point to a git repo+sha right? I'm using `pod 'Sourcery', :git => 'https://github.com/krzysztofzablocki/Sourcery.git', :commit => 'a6118efb5b9756eb59570e5e92b625c9b591fd24'`

**Comment by samskiter** [comment]
Ahh i see, you pull from releases

**Comment by samskiter** [comment]
@ilyapuchka Have tried building from master, used the rake scripts to generate a new zip, then pointed to that locally using cocoapods. Getting a slightly different error message now:

```
error: /Users/samduke/Waking-iOS/scripts/Sourcery/Templates/TypeErase.stencil: 'for' statements should use the following 'for x in y where condition' `for key, value in type.annotations`.

```

**Comment by samskiter** [comment]
@ilyapuchka I got it working by iterating like so:

```
{% for type in types.protocols|annotated:"TypeErase" %}

{% for key,value in type.annotations %}{{ key }}{% endfor %}

{% endfor %}
```

But I still get an array for the dictionary values where "TypeErase" is a key

**Comment by samskiter** [comment]
Hey again @ilyapuchka - I also brought this up on SwiftStencilKit here: https://github.com/SwiftGen/StencilSwiftKit/issues/44 and they suggested it might be best to always return an array for each annotation name...

**Comment by ilyapuchka** [comment]
Can you use macro node or swift templates as advised in #307?

**Comment by bolismauro** [comment]
@ilyapuchka @samskiter I decided to keep the ugly stencil I need to have rather than using swift. This is because the generation time is considerably higher than stencil

**Comment by Antondomashnev** [comment]
> hey suggested it might be best to always return an array for each annotation name

@ilyapuchka @bolismauro I, actually, agree with that. I think it's confusing when the same code returns different type of object under different circumstances.

**Comment by samskiter** [comment]
I think that would be great. the only other useful thing to do would be either to define dictionaries through annotations or in some way allow splitting by a string (e.g. ',')

**Comment by Antondomashnev** [comment]
@samskiter you can take a look on #313, they're some proposals that could improve annotations 😄

**Comment by haimwaking** [comment]
I've run into this issue today, is there a resolution for this?

**Comment by Antondomashnev** [comment]
Hey @haimwaking @samskiter check out the https://github.com/krzysztofzablocki/Sourcery/pull/425

In the next Sourcery release you'll be able to use `toArray` filter to convert any value into array.

**Comment by haimwaking** [comment]
Cheers for that, looking forward!
