### ISSUE TITLE
Migrate from CocoaPods to SPM

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#305]
It seems like it should be possible to replace CocoaPods with SPM, using which should remove any need for using containing mac os app to embed frameworks, as they should be linked to the binary at build time. We might though need to get rid of SwiftTryCatch as SPM packages can not contain mixed language code.

**Comment by krzysztofzablocki** [comment]
Keep in mind its important to maintain ability to easily debug and work on the code, SPM isn't ideal for that

**Comment by Antondomashnev** [comment]
I see the drawback also in terms of introducing another dependency manager for the developer. I don't know the real numbers but I think the usage of dependency management systems is like:
1. CocoaPods
2. Carthage
3. SPM

So I think most likely developer will have to introduce SPM as a dependency manager for her project if she wants to integrate Sourcery.

**Comment by ilyapuchka** [comment]
I mean that we should use SPM for managing our own dependencies. This should not, as far as I understand, affect the end users. Using CocoaPods they are going to load latest release artefacts, not the source code. The same with Carthage, most likely users will just load binaries. And even if they load source code to build it with SPM is easier than with Xcode because it produces artefacts in a more predictable path.

**Comment by ilyapuchka** [comment]
@krzysztofzablocki regarding debugging we can use project that SPM generates, it should have all dependencies as separate targets, if I'm not wrong, pretty much as with CocoaPods but with simpler setup.

**Comment by Antondomashnev** [comment]
@ilyapuchka could it have a restriction for us if one of the dependency we will require doesn't support SPM?

**Comment by ilyapuchka** [comment]
Yes, that's a valid point, but that will mean that Sourcery will be not buildable on Linux, so only binary could be used. Using SPM will bring us closer to supporting Linux I think.

**Comment by Antondomashnev** [comment]
Seems we have to decide what is more likely to happen - Sourcery dependency doesn't support SPM or somebody wants to build a source on Linux 😄 

The issue with the dependency could be painful because it can not support SPM, because it's dependencies don't support SPM and so on and so on.

**Comment by ilyapuchka** [comment]
And if we are likely or not to add any other dependencies =)

**Comment by krzysztofzablocki** [comment]
I migrated distribution for all channels to SPM a month or so ago, will migrate main app too sometime soon
