### ISSUE TITLE
Workflows & Best Practices - Example Use Cases

### ISSUE THREAD

**Issue by fbartho** [krzysztofzablocki/Sourcery#31]
It looks like there are several possible ways to use Sourcery, and I think it would make sense to streamline those into example workflows.

Some Example Use Cases:

- Inline --  The most common mode people would use Sourcery. It runs as a build phase script with real Swift project and generates any boilerplate code based on user provided templates. The recently landed comment-attribute system plays nicely in this model.
- Daemon mode -- Using daemon offers the user to run code against existing source and experiment with the templating system. This is **by far the best way to write new templates**, regardless of which use-case you are trying to cover.  
- Xcode Extension -- In this mode, I believe we're using Sourcery as a really powerful snippet engine. The idea is to replace stuff, once, by scanning some of the code, and then generating some subset of methods based on the piece selected. The recently landed comment-attribute system plays nicely in this model.
- Documentation -- In this mode, the user uses Sourcery as a parse tree that then helps the user extract *interesting* things, and generate external resources based on their code. We're using Sourcery as a parsing + template engine. The output of Sourcery in this use case does not serve as code within the App.
- Separated Specs & Code -- This is sort of a combination of `Inline` and `Documentation`, but with some extra features. Specifically, the target customer is making some API/Framework layer. They define their type hierarchy in a directory we can call "Specifications". These specifications get parsed and generate the output code in a wholly separate directory. The output directory is the real Framework/App Xcodeproject, and the user mixes handwritten code with the generated code at this level. The purpose of having a separate input directory is we can have bigger transformations on the code. In issue #20 I suggested a syntax for Attributes that was not dependent on comments. In-code attributes have the benefit of being available to auto-complete, and so the API Generator project could type-check the attributes themselves. Benefits of that include early alerts when combining incompatible attributes.

I think all these use cases are all valid targets for Sourcery, and I think having some example projects & how-to tutorials for each of these case would be valuable. I think this ticket touches a bit on issue #10 -- if we share templates with the community, I think we should show the user how to use them, and for which purpose a given template is targeted.

**Comment by krzysztofzablocki** [comment]
@fbartho good idea, I tweaked your description a little to highlight the most important parts

**Comment by vietstone** [comment]
Hi, I'm new to Sourcery and see it's very appealing. But the ReadMe file doesn't show a tutorial kind of Getting Started. Is there anyone? Thank you.

**Comment by ilyapuchka** [comment]
We are working on docs improvements. For now everything you need to use sourcery can be found in its readme (installation and usage details, available types and properties, templates examples) and stencil docs (if you use it for templates)
