### ISSUE TITLE
Annotations with custom prefix

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#313]
In a lot of cases several annotations might be required for a single declaration which conceptually belong to one domain, i.e. to parse property from JSON one can write template that supports annotations like  `json_key`, `json_default` (to specify default value), `json_get` (to use specific parsing func), `json_map` (to map parsed value to something else using specific func) etc.. Currently it will require using `json_` or alike prefix on each annotation manually.
We can support custom prefixes for parsing annotations so that annotations in code will look like `// json: key = ..., default = ..., get = ...` and can be accessible in templates with `annotations["json"]["key"]` (swift) or `annotations.json.key` (stencil & js). Prefix can be setup using annotation block `//sourcery:annotation_prefix: json` that can accept several strings to support multiple prefixes in a block of code, or with `//sourcery:file:annotation_prefix: json` for file wide support.
This also can be useful for grouping similar annotations like `// skip: equality, description, coding` which will make them more readable and easier to write and use.

Alternatively we can provide support for arrays and dictionaries as annotations values
`// sourcery:  json = [key: ..., default: ..., get: ...]` or `// sourcery: skip = [equatable, description, coding]`

**Comment by Antondomashnev** [comment]
I like the idea 👍 I think if everyone agrees on the feature itself we just need to agree on the syntax.
But I don't think this is something must for the 1.0.0 release, what do you think?

**Comment by ilyapuchka** [comment]
For sure, not a requirement for 1.0

**Comment by samskiter** [comment]
I think it's going to be easy to get confused between an array/dict and a literal string so maybe a special block declaration to say "i'm entering this mode now" or a special way of starting the annotation would be necessary.

e.g. :is this a json string you are defining or do you want a dict?"

**Comment by fpg1503** [comment]
That's really useful, I use an alternative to it very frequently (but the dictionary literals I use follow Swift syntax (the keys are not implicitly String literals)). I mentioned it in #174 and it was fixed in #188.

**Comment by ilyapuchka** [comment]
I think I'll go on and implement it just with `//sourcery:prefix: key1, key2` that will be accessed in code as `annotations.prefix.key1` and `annotations.prefix.key2`. It should be also possible to use such annotations in `annotated` filter, i.e. `annotated:"prefix.key1"`
