### ISSUE TITLE
Scope next Sourcery release.

### ISSUE THREAD

**Issue by Antondomashnev** [krzysztofzablocki/Sourcery#314]
Hi team,
I think at the moment we have a lot of updates in master since the last `0.6.0` release. When do you think we can make another one? Is there any blocker?

**Comment by ilyapuchka** [comment]
I wanted to finish with #307 but I'm going on vocations for the rest of the week. But I'm fine with releasing what we have now in master. Though when it comes to publishing it in Cocoapods I think only @krzysztofzablocki can do that.

**Comment by krzysztofzablocki** [comment]
I can make a new release

**Comment by Antondomashnev** [comment]
@krzysztofzablocki I think it makes sense

**Comment by krzysztofzablocki** [comment]
Someone forgot to share Template scheme? `The workspace named "Sourcery" does not contain a scheme named "Templates-Tests"`

**Comment by Antondomashnev** [comment]
@krzysztofzablocki I think it's me, sorry.

**Comment by krzysztofzablocki** [comment]
@Antondomashnev no worries, can you push it to the master?

**Comment by Antondomashnev** [comment]
@krzysztofzablocki done 😉

**Comment by Joannis** [comment]
Would love a new release. Any idea if you could provide a brew package *with* EJS support for this next sourcery release?
