### ISSUE TITLE
Support in-out parameters

### ISSUE THREAD

**Issue by samskiter** [krzysztofzablocki/Sourcery#317]
I had a quick look here too: https://github.com/krzysztofzablocki/Sourcery/blob/8583c039db54b5956a6b02d8447ce1ed00647941/SourceryTests/Parsing/FileParser%20%2B%20AttributesSpec.swift

Looks like the parser doesn't pull out the 'inout' attribute on params

**Comment by ilyapuchka** [comment]
Thanks for reporting. `inout` is not an attribute, it's part of the type and SourceKit returns it as a typename, so I guess we are currently not just do not parse it but also will not properly infer type of such parameter. Not sure if we should model it with attribute, probably better to do it with boolean property in `MethodParameter`.

**Comment by samskiter** [comment]
Thanks a Boolean would suit my needs fine

**Comment by Antondomashnev** [comment]
Hi @samskiter, the flag `inout` is on master and will be added to the next release.
