### ISSUE TITLE
Feature Request: Daemon Mode watch Sources

### ISSUE THREAD

**Issue by fbartho** [krzysztofzablocki/Sourcery#32]
Currently, the daemon mode documented & built-in to Sourcery targets observing the single template for changes and regenerating on that, while maintaining AST cache. 
It would also be useful to be able to watch the source-code directory, and regenerate AST and code automatically as you change your input files.

**Comment by krzysztofzablocki** [comment]
Yes, that is definitely on the list to add and should be straightforward as soon as I find a way for [KZFileWatchers](https://github.com/krzysztofzablocki/KZFileWatchers) to watch whole subfolder via gcd source
