### ISSUE TITLE
Incorrect insert position of `inline:auto` code

### ISSUE THREAD

**Issue by Liquidsoul** [krzysztofzablocki/Sourcery#320]
**Swift version:** Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42) (Xcode 8.3.2)  
**Sourcery version:** `0.6.0` and `master` (ae69829)

### What did I do?

I used the `inline:auto` feature to add code in existing structs in a unique file.

Here is the template:

```
{% for type in types.structs %}
// sourcery:inline:auto:{{ type.name }}.AutoInit
test
// sourcery:end
{% endfor %}
```

And the swift files with the structs, one with existing code to update and one where new code wille be inserted:
```swift
public struct User {
// sourcery:inline:auto:User.AutoInit
test
// sourcery:end
}

public struct Session {
}
```

### What did I expect to see?

```swift
public struct User {
// sourcery:inline:auto:User.AutoInit
test
// sourcery:end
}

public struct Session {
// sourcery:inline:auto:Session.AutoInit
test
// sourcery:end
}
```
### What did I see instead?

```swift
public struct User {
// sourcery:inline:auto:User
// sourcery:inline:auto:Session.AutoInit
test
// sourcery:end
.AutoInit
test
// sourcery:end
}

public struct Session {
}
```

### Comments

I suspect that the insert position for the second block of code is not updated after inserting the first one 🤔

**Comment by ilyapuchka** [comment]
I also encountered some issue on our code base with auto insertion, so there is definitely something wrong. Thank's for bringing this up @Liquidsoul

**Comment by Liquidsoul** [comment]
I did a little digging and arrived at the point where it seems that the value returned by [`rangeToAppendBody()` ](https://github.com/krzysztofzablocki/Sourcery/blob/master/Sourcery/Sourcery.swift#L377) is not what I expect it to be 🤔 

In the failing test I have with this source file:
```swift
class Foo {
// sourcery:inline:auto:Foo.fake
// sourcery:end
}

class Bar {}
```

It's returning an offset of 27 for `Bar`'s body like if the annotations in `Foo` were not there.

I'll keep digging to see if I find more informations.

(I can share failing test in a pull request if that helps)

**Comment by Antondomashnev** [comment]
@Liquidsoul failing test would be a good start 🚀

**Comment by Liquidsoul** [comment]
@Antondomashnev done in #322

Digging a little more, it seems that the annotations are removed in the code before giving it to SourceKitten 🔍

**Comment by Liquidsoul** [comment]
I'll share where I am now in case I fall asleep 😴 

There seems to be a mismatch in context between the ranges we have from SourceKit and what we get from the `TemplateAnnotationsParser.parseAnnotations()`.

Here is the source I use:
```swift
class Foo {
// sourcery:inline:auto:Foo.fake
// sourcery:end
}

class Bar {}
```

In [`parseContentsIfNeeded()`](https://github.com/krzysztofzablocki/Sourcery/blob/master/Sourcery/Parsing/FileParser.swift#L99-L102) it first remove the "inline" annotation while keeping their positions.

The stored position is where the generated code will be inserted:
```swift
class Foo {
// sourcery:inline:auto:Foo.fake
< where the range starts (45 here)
// sourcery:end
}

class Bar {}
```

The result content after this process:
```swift
class Foo {
}

class Bar {}
```

This content is then [parsed in `Structure`](https://github.com/krzysztofzablocki/Sourcery/blob/master/Sourcery/Parsing/FileParser.swift#L115-L116).
The computed offset for `Bar`'s body in this case is `27`:
```swift
class Foo {
}

class Bar {}
           ^
```

And once the generation is done, we will insert the generated code in the _source_ data [here](https://github.com/krzysztofzablocki/Sourcery/blob/fix%2Fauto-inline/Sourcery/Sourcery.swift#L387-L388).
This means that for the `Bar` case, it will use the offset of the file _without_ the annotation while the annotations are present, hence the incorrect insertion point.

**Comment by Liquidsoul** [comment]
My first thought: maybe the function `TemplateAnnotationsParser.parseAnnotations()` should just remove the generated code but leave the annotations alone.

Meaning that for this initial content:
```swift
class Foo {
// sourcery:inline:auto:Foo.fake
My generated code
// sourcery:end
}

class Bar {}
```

The output would be:
```swift
class Foo {
// sourcery:inline:auto:Foo.fake
// sourcery:end
}

class Bar {}
```

Instead of:
```swift
class Foo {
}

class Bar {}
```

This would leave the code untouched in the example in my previous comment.

I did not try to implement this, I may be able to have a shot at tomorrow.

**Comment by ilyapuchka** [comment]
Does the error happen only on first run of Sourcery? The thing is that with `inline:auto` there should be no annotation in source code initially, it should be added after first run. After that it behaves the same way as with normal `inline` annotation. I was experiencing issues on first run only.

**Comment by Liquidsoul** [comment]
Yes, this happens only for the first run to place the `inline:auto`.
Once the annotations are correctly in place, everything works fine.
