### ISSUE TITLE
AutoMockable extention

### ISSUE THREAD

**Issue by ManWithBear** [krzysztofzablocki/Sourcery#321]
Is here anyway to generate Mock object my AutoMockable template without using AutoMockable protocol?
I would like to have solution as:
`extension AccountListViewInput: AutoMockable { }`
But it's generate error:
`Extension of protocol 'AccountListViewInput' cannot have an inheritance clause`

I understand that AutoMockable inheritance should be in protocol declaration, but I dont want to have it in my main target, only in test target.

**Comment by ilyapuchka** [comment]
Hey @ManWithBear . You can adjust the template to use what ever you need in your case, probably for you it will make sense to use annotations instead of marker protocols.

**Comment by ManWithBear** [comment]
Thanks @ilyapuchka 
Solved with:
```swift
// sourcery:begin: AutoMockable

//// MARK: - AccountList
extension AccountListViewInput { }
extension AccountListModuleInput { }
extension AccountListRouterInput { }
extension AccountListInteractorInput { }
extension AccountListViewOutput { }
extension AccountListInteractorOutput { }
```
and in template `{% for type in types.protocols|annotated:"AutoMockable" %}`

BTW `// sourcery:file: AutoMockable` not worked for me, dunno why. So use begin without end.
Sourcery 0.6.0, Swift 3.1

**Comment by ilyapuchka** [comment]
Glad it helped. `// sourcery:file:` is on master only. And I would not suggest to use `begin` without `end` even though it may work now.

**Comment by ManWithBear** [comment]
Oh, ok. Will fix it tomorrow :)
