### ISSUE TITLE
Support Multiple Output Directories

### ISSUE THREAD

**Issue by grantjbutler** [krzysztofzablocki/Sourcery#324]
I noticed that Sourcery supports the ability to scan multiple targets in an Xcode project. It'd be nice if Sourcery could output generated code to different locations on disk depending on the target it's scanning. For example, I might have an app target and a framework target in the same project. I'd like it if Sourcery could output code generated for the app target into the directory that contains all the app code, and then output code generated for the framework target into the directory that contains all the framework code. As best as I can tell, Sourcery can only output to one directory at this time.

**Comment by krzysztofzablocki** [comment]
I'm wondering if that's a valid use case, the idea of multiple source directories is that the App templates might need to know AST of the framework code, but it's hard to see a case in which the App would modify the framework code, that seems like a fragile scenario

**Comment by ilyapuchka** [comment]
It may make sense for frameworks that you own and some common templates, like description, i.e. Sourcery itself if we add some type in the app target that needs description code to be generated.

**Comment by grantjbutler** [comment]
It's not so much about the app modifying framework code, as it is about needing some of the same functionality in both a framework and application, and Sourcery not seeming to support it correctly.

For example, I'm going to use the `AutoEquatable` scenario. I may have some models in my framework so that both an application and an extension can use them. I want to conform them to `Equatable`, so I add my `AutoEquatable` protocol, add the necessary template, and get my `Equatable` implementations.

Now say I have some other structs exclusive to my application that I want to generate `Equatable` implementations of. I already have the template, so I can reuse that, I'll just need to expose the `AutoEquatable` protocol as public in my framework, or add that protocol to my application. However, from my understanding of how Sourcery works, both the framework's and application's implementations would be in the same generated file. Since I've set up Sourcery to recognize my Xcode project and its various targets, I would want to have separate generated files for my application and framework targets.

I can probably fake this right now by having different name templates (for example, `FrameworkAutoEquatable.stencil` and `AppAutoEquatable.stencil`), but it doesn't seem ideal as I have to remember to update both files when I want to make a change.

**Comment by makadaw** [comment]
+1 for this feature. This can be not so important in mobile apps but can be if you want to split SPM project with different modules.

**Comment by ilyapuchka** [comment]
I tried to implement this along with automatic linking of generated files and unfortunately this seems to introduce a lot of unnecessary complexity in configuration and will require us to make a lot of changes in parsing, as currently parsing results are not aware of sources' targets.
We do though provide module name where scanned type is defined, so you can use that to change output path using `sourcery:file` annotation. We could use it internally to group parsing results per module, but again, I think it's unnecessary complexity and using annotation seems like a much simpler approach.
Otherwise you can run sourcery separately on different targets.
