### ISSUE TITLE
type.accessLevel returns empty string for all types that are not custom.

### ISSUE THREAD

**Issue by Sajjon** [krzysztofzablocki/Sourcery#325]
## What?
`accessLevel` returns empty string for UIKit, Foundation and probably all `Apple` types.

### Swift
Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
Target: x86_64-apple-macosx10.9
### Sourcery
0.6.0

## Example
```swift

protocol AutoDemo {}

private struct Foo {}
struct Bar {}
internal struct Baz {}
public struct Buz {}

extension Foo: AutoDemo {}
extension Bar: AutoDemo {}
extension Baz: AutoDemo {}
extension Buz: AutoDemo {}
extension UIControlEvents: AutoDemo {}
extension NSObject: AutoDemo {}
extension String: AutoDemo {}
```

Given the stencil

```stencil
{% macro accessModifierOf type %}{% if type.accessLevel == '' %}PUBLIC{% else %}{{ type.accessLevel }}{% endif %}{% endmacro %}

{% for type in types.implementing.AutoDemo %}
// `{{ type.name }}` is `{% call accessModifierOf type %}`
{% endfor %}
```

Results in:

```swift
// `Bar` is `internal`
// `Baz` is `internal`
// `Buz` is `public`
// `Foo` is `private`
// `NSObject` is `PUBLIC`
// `String` is `PUBLIC`
// `UIControlEvents` is `PUBLIC`
```

So my fix is using the macro `accessModifierOf` but printing `public` and not `PUBLIC` of course (just wrote that to highlight that `type.accessLevel`) returns an empty string.

**Comment by ilyapuchka** [comment]
I believe extensions themselves do not have access level, at least SourceKit does not return such information (try `sourcekitten structure --text "protocol AutoDemo{}; extension NSObject: AutoDemo {}"`). But _declarations inside_ extension should contain proper access level. 
For known types we simply merge extension with type definition, access level comes from type definition.
The other problem is that Sourcery does not have any means to distinguish conformance to protocols through extensions in `implementing` or `based` collections. I.e. if you extend public class with internal protocol should we expose this protocol in `implementing` collection? This conformance should be not accessible from other modules but will be accessible in the same module (the same for `private` and `fileprivate` scopes).

Depending on your use case maybe there is a better workaround for that. But if `public` is good default for you - use it. But it will be not a good default in general case.

**Comment by ilyapuchka** [comment]
@Sajjon does this answer your question?

**Comment by Antondomashnev** [comment]
@Sajjon could you please follow-up for @ilyapuchka's question?

**Comment by Sajjon** [comment]
@ilyapuchka @Antondomashnev sorry for inactivity! We do not get any information at all since Sourcery does not work for UIKit types, but rather our own types, [as discussed here](https://github.com/krzysztofzablocki/Sourcery/issues/87#issuecomment-317377982).

So we can close this one.
