### ISSUE TITLE
Fix for deleting some characters 

### ISSUE THREAD

**Issue by wassimseif** [krzysztofzablocki/Sourcery#327]
I'm using Sourcery for generating the `init` of classes conforming to the protocol `AutoInitializer`
This is my stencil template 
```

{% for type in types.implementing.AutoInitializer %}
//MARK: {{type.name}} Initialization
extension {{type.name}}{

convenience init({% for var in type.storedVariables %}{{var.name}}:{{var.typeName}},{% endfor %}){
  self.init()
  {% for var in type.storedVariables %}
  self.{{var.name}} = {{var.name}}
  {% endfor %}
}
}


{% endfor %}
```
The thing is `{{var.name}}:{{var.typeName}},` will insert a comma to the last parameter in the `init` which, of course , will not compile. Is there a fix for this ? so that i don't have to remove the commas manually ?

**Comment by ilyapuchka** [comment]
Please refer [Stencil docs](https://stencil.fuller.li/en/latest/builtins.html#for) - you can use `if forloop.last` to detect last loop iteration.
