### ISSUE TITLE
Stops discovering types after encountering generated files

### ISSUE THREAD

**Issue by jmonroe** [krzysztofzablocki/Sourcery#33]
I have discovered that Sourcery seems to stop discovering types after it encounters source files generated by Sourcery.

Given the following file list, sourcery only discovers types in files files A and B.

/source
- A.swift
- B.swift
- /generated (folder containing files generated by sourcery)
- H.swift

This is easily worked around by making sure that your generated files are not located under the input directory.

**Comment by krzysztofzablocki** [comment]
oh crap, that's my bad I was adding ignoring generated sources and made mistake that it prunes old types instead of just continue, fixing now

**Comment by krzysztofzablocki** [comment]
I've a fix but unfortunately can't release it right now because github keeps rejecting zip file, can you try version: https://dl.dropboxusercontent.com/u/11523469/sourcery-0.3.7.zip

**Comment by jmonroe** [comment]
Yes, that fixed it.  Thanks.

**Comment by krzysztofzablocki** [comment]
zip uploading worked through chrome, 0.3.7 is released now :) 
Thank you for reporting the issue and let me know if you find anything else or need a feature
