### ISSUE TITLE
0.6.1 build fails on OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by ilovezfs** [krzysztofzablocki/Sourcery#331]
```
/private/tmp/sourcery-20170529-16408-1yos0up/Sourcery-0.6.1/Packages/SourceKitten.git/Package.swift:17:3: error: argument 'swiftLanguageVersions' must precede argument 'dependencies'
  swiftLanguageVersions: [3, 4],
  ^
swift-build: error: The package at `/private/tmp/sourcery-20170529-16408-1yos0up/Sourcery-0.6.1/Packages/SourceKitten.git' has no Package.swift for the specific version: 0.17.6
Can't parse Package.swift manifest file because it contains invalid format. Fix Package.swift file format and try again.
```

https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/2121/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_sourcery/

Cf. https://github.com/Homebrew/homebrew-core/pull/14042

Seems fine on macOS 10.12 Sierra.

**Comment by jpsim** [comment]
That's because installing SourceKitten via SwiftPM requires Swift 3.1 or later as of 0.17.4 (this PR: jpsim/SourceKitten#377). I've submitted Sourcery 0.6.1 to Homebrew in Homebrew/homebrew-core#14123.

**Comment by Antondomashnev** [comment]
It seems we can close the issue.
