### ISSUE TITLE
Include mutating keyword

### ISSUE THREAD

**Issue by chriseidhof** [krzysztofzablocki/Sourcery#332]
First of all: Sourcery is awesome.

I'd like to generate code for all mutating methods. However, currently, there's no way to know (in Sourcery) if a function is mutating or not. Would it be possible to add this? Is there anything I could do to help with this?

**Comment by ilyapuchka** [comment]
@chriseidhof thanks for suggestion! This will be pretty easy to add, mutating is just another kind of attribute, we just missed it (probably there are some other attributes we are still missing)

**Comment by chriseidhof** [comment]
Awesome. I don't mind doing it, can you give a pointer on where to start?

**Comment by ilyapuchka** [comment]
Sure, look at [Attribute](https://github.com/krzysztofzablocki/Sourcery/blob/master/SourceryRuntime/Sources/Attribute.swift) class, it should handle this attribute the same way as `convenience`.

**Comment by chriseidhof** [comment]
See #338

**Comment by ilyapuchka** [comment]
Implemented with #338
