### ISSUE TITLE
Generate Code in the type class

### ISSUE THREAD

**Issue by wassimseif** [krzysztofzablocki/Sourcery#333]
Is there a way to insert code inside the type class ? Rather than in an extension ?
```
class Quiz {
    var done : Int?
    var level : Int?
}    
```
then after running sourcery it will be 
```
class Quiz {
    var done : Int?
    var level : Int?
}    
init(done : Int? , level: Int?){
   self.done = done 
   self.level = level 
}
``` 
It will fix some problems with convenience initialisers

**Comment by ilyapuchka** [comment]
Hi @wassimseif . Please look at the [inline annotations](https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/writing-templates.html#inline-code-generation).

**Comment by rob-nash** [comment]
How would you write an initialiser. I got this so far. Struggling.

```
public init(
        {% for variable in type.variables %}
        {{ variable.name }}: {{ variable.typeName }}
        {% endfor %}
        ) {}

init(
    done: Int?
    level: Int?
    ) {}
```

**Comment by ilyapuchka** [comment]
@rob-nash I guess you are on the right path, you just need to do the similar loop in the body of init to set variables.
