### ISSUE TITLE
0.5.9_1 Bottle is Missing in Homebrew

### ISSUE THREAD

**Issue by calebd** [krzysztofzablocki/Sourcery#336]
The sorcery bottle was fixed in homebrew/homebrew-core@fc363d74eb but that bottle is missing.

```
-> brew install --force-bottle https://raw.githubusercontent.com/Homebrew/homebrew-core/fc363d74eb/Formula/sourcery.rb
==> Downloading https://homebrew.bintray.com/bottles/sourcery-0.5.9_1.sierra.bottle.tar.gz
Error: Failed to download resource "sourcery"
Download failed: https://homebrew.bintray.com/bottles/sourcery-0.5.9_1.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

Building the 0.5.9 formula from source fails for a variety of reasons.

**Comment by jpsim** [comment]
0.5.9 revision 1 was never merged in Homebrew because I updated the formula to 0.6.0 before the PR got merged: https://github.com/Homebrew/homebrew-core/pull/12203/commits/640a93ff4b41b293a5577d97019062ca4ab63ca1
