### ISSUE TITLE
Move some filters to StencilSwiftKit

### ISSUE THREAD

**Issue by AliSoftware** [krzysztofzablocki/Sourcery#337]
And even some probably on Stencil proper.

Candidates so far: [StencilTemplate.swift#L30-38](https://github.com/krzysztofzablocki/Sourcery/blob/4e920792664029203820fba1a63ba4ba925f552e/Sourcery/Generating/Template/Stencil/StencilTemplate.swift#L30-L38)

* `upperFirst`
* `lowerFirst`
* `replace`
* `contains`
* `hasPrefix`
* `hasSuffix`

\cc @djbe @kylef

**Comment by Antondomashnev** [comment]
As soon as https://github.com/SwiftGen/StencilSwiftKit/issues/64 is merged we can start removing filters from Sourcery in order to use from `StencilSwiftKit`

**Comment by AliSoftware** [comment]
StencilSwiftKit 2.2.0 just got released to CP, including your PR to fix https://github.com/SwiftGen/StencilSwiftKit/issues/64 👍

**Comment by Antondomashnev** [comment]
👍

**Comment by krzysztofzablocki** [comment]
I'm closing this as we already have pr for it #426 and I want to cleanup issues
