### ISSUE TITLE
Support include tag in Stencil templates

### ISSUE THREAD

**Issue by danielr** [krzysztofzablocki/Sourcery#339]
Stencil itself has support for the `{% include %}` tag. However, Sourcery doesn't seem to provide a template loader to the Stencil `Environment`, so `include` does not work:

```
{% include "_Mapping.stencil" %}
```

results in this error message:
```
Template named `_Mapping.stencil` does not exist. No loaders found
```

I'd suggest to (perhaps optionally) make the path for the included templates configurable, so that you can separate "real" templates from "partial" templates that are just made for inclusion and shouldn't trigger generation on their own. Alternatively, we could use a naming convention for this (e.g. a leading underscore, like in Ruby/ERB partials).

**Comment by ilyapuchka** [comment]
@danielr thanks for reporting this, it's now implemented. Please report any issues with that if you find any.

**Comment by danielr** [comment]
@ilyapuchka Thanks for fixing this so quickly! I wanted to have a look myself on Friday, but you were faster ;-) Will try it out next week and report back any issues with the implementation.

**Comment by danielr** [comment]
So, as far as I can see, you didn't implement any separation between "normal" and "partial" templates, right? Is there an explicit way to exclude templates from triggering generation (and thus producing output files) on their own?

**Comment by ilyapuchka** [comment]
Yes, that's true, you need to put partials in a separate directory out of templates directory or mention each template explicitly in config file.

**Comment by ilyapuchka** [comment]
We can add exclude configuration for templates (and sources) to make experience better

**Comment by danielr** [comment]
Excludes definitely sound like a useful feature - not only for this special case, but especially for sources.

Regarding the partials, I didn't realise that you could break out of the template directory via relative paths. I guess that having templates and partials in two sibling directories is a good enough work-around for the time being.

**Comment by ilyapuchka** [comment]
Unfortunately Stencil [explicitly forbids that](https://github.com/kylef/Stencil/blob/6f48fe2d917aa2842bd61e9903ebab12c734483d/Sources/Loader.swift#L82) so I'm working on minimal exclude functionality now
