### ISSUE TITLE
Templates tests require Sourcery.app in bin directory

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#342]
@Antondomashnev running templates tests locally I noticed that they run Sourcery from `bin` folder as a build step, which is copied there only when building for release IIRC. Maybe we should adjust this to make it easier to run tests? Also I think it make sense to run templates tests together with unit tests during development, maybe through a separate scheme.

**Comment by Antondomashnev** [comment]
> run templates tests together with unit tests during development, maybe through a separate scheme.

That's a good idea

> Maybe we should adjust this to make it easier to run tests?

I think the way works fine, but probably we just need to add a build step to build sourcery app and copy it into the bin. I think that should fit out needs.
