### ISSUE TITLE
Crash When Using Cache Generated by Newer Sourcery

### ISSUE THREAD

**Issue by grantjbutler** [krzysztofzablocki/Sourcery#344]
When running an older version of Sourcery against a cache generated by a newer version of Sourcery, it is possible for that older version to crash. See the attached stack trace.

A little bit of context. Our team has standardized which version we use (by including it in our Podfile) to avoid generating diff noise by the generated files being updated where the only change is the version number of Sourcery. Because the version of Sourcery is baked into the repository, it is possible to have two separate versions running on our CI box (for example, when putting together a PR to upgrade which version of Sourcery is bundled in our repo). When this occurs, branches that don't reference the latest version may start failing builds as Sourcery crashes because the cache is for a newer version of Sourcery.

### Stack Trace

This specific crash appears to be because `argumentLabel` was required in older versions of Sourcery, but is now optional in newer versions. Thus, if no `argumentLabel` is persisted by a newer version of Sourcery, older versions will crash when trying to read the cache.

```
2017-06-02 11:50:14.253 Sourcery[75721:27498822] *** Terminating app due to uncaught exception 'NSParseErrorException', reason: 'Key 'argumentLabel' not found.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff8c4aa452 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff90b9df7e objc_exception_throw + 48
	2   Foundation                          0x00007fff87d04721 -[NSCoder(Exceptions) __failWithExceptionName:errorCode:format:] + 0
	3   Foundation                          0x00007fff87d04948 -[NSCoder(Exceptions) __failWithExceptionName:errorCode:format:] + 551
	4   Foundation                          0x00007fff87bdd7b5 _decodeObjectBinary + 3593
	5   Foundation                          0x00007fff87bdc8a5 _decodeObject + 281
	6   Foundation                          0x00007fff87c982eb +[NSKeyedUnarchiver unarchiveObjectWithFile:] + 156
	7   Sourcery                            0x0000000107aca258 _TTSf4gs_n_n___TFC8Sourcery8SourceryP33_DB5C4364BFA94633EE953DD412A08C3011loadOrParsefT6parserVS_10FileParser13cacheDisabledSb_CS_16FileParserResult + 1512
	8   Sourcery                            0x0000000107ac2923 _TFFC8Sourcery8SourceryP33_DB5C4364BFA94633EE953DD412A08C3010parseTypesFzT4fromV7PathKit4Path13cacheDisabledSb_GSaCS_4Type_U1_FVS_10FileParserCS_16FileParserResult + 227
	9   Sourcery                            0x0000000107acac8a _TPA__TTRXFo_oV8Sourcery10FileParser_oCS_16FileParserResult_XFo_iS0__iS1__ + 122
	10  Sourcery                            0x0000000107b2f050 _TTSf4g_n___TTSg5GVs10ArraySliceV8Sourcery10FileParser_GS_S1__s10Collections_CS0_16FileParserResult___TFEsPs10Collection3mapurfzFzWx8Iterator7Element_qd__GSaqd___ + 592
	11  Sourcery                            0x0000000107b2f13c _TTSf4g_n_n_n_g_g_g___TTSg5V8Sourcery10FileParser_CS_16FileParserResult___TFFE8SourcerySa11parallelMapurFTFxqd__8progressGSqFSiT___GSaqd___U_FT_T_ + 140
	12  Sourcery                            0x0000000107b2ed90 _TPA__TTSg5V8Sourcery10FileParser_CS_16FileParserResult___TFFE8SourcerySa11parallelMapurFTFxqd__8progressGSqFSiT___GSaqd___U_FT_T_ + 144
	13  libdispatch.dylib                   0x00007fff965f193d _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x00007fff965e640b _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x00007fff965eb03b _dispatch_queue_drain + 754
	16  libdispatch.dylib                   0x00007fff965f1707 _dispatch_queue_invoke + 549
	17  libdispatch.dylib                   0x00007fff965e9d53 _dispatch_root_queue_drain + 538
	18  libdispatch.dylib                   0x00007fff965e9b00 _dispatch_worker_thread3 + 91
	19  libsystem_pthread.dylib             0x00007fff95d194de _pthread_wqthread + 1129
	20  libsystem_pthread.dylib             0x00007fff95d17341 start_wqthread + 13
)
```

**Comment by ilyapuchka** [comment]
NSCoding, used to serialise parsing results does not have versioning support, so we basically need to use Sourcery version as a part of a cache hash key to avoid this.

**Comment by ilyapuchka** [comment]
It's strange though that it crashes as the exception should be caught and sources should be reparsed, will try to see why it's not the case

**Comment by grantjbutler** [comment]
It is an Objective-C exception which is being thrown. As far as I know, there's no way in Swift to catch an Objective-C exception. I believe that `NSKeyedUnarchived.unarchiveTopLevelObjectWithData(_:)` was introduced to address this (so that you get back an error in Swift instead of an Objective-C exception being thrown). That said, if Sourcery has a little bit of Objective-C to catch that exception, then, yeah, I can see why you're confused as to the exception not being caught.

**Comment by ilyapuchka** [comment]
SwiftTryCatch that we use is supposed to catch Objective-C exceptions, but maybe we should adjust how we unarchive, thanks for suggestion

**Comment by krzysztofzablocki** [comment]
This might be obsolote, there was a bug when I introduced cashing initially that didn't track sourcery version properly and it would crash rather than recover, @grantjbutler does it happen with latest releases? e.g. have cache using newest version and try using a previous release

**Comment by gotev** [comment]
After upgrading from `1.0.2` to `1.4.0` it happened. Using `--disableCache` as reported in https://github.com/krzysztofzablocki/Sourcery/issues/774 solves the problem
