### ISSUE TITLE
0.7.1 and 0.7.0 print "Major.Minor.Patch" not the version when building with SPM

### ISSUE THREAD

**Issue by ilovezfs** [krzysztofzablocki/Sourcery#354]
Homebrew test block fails with

```
==> /usr/local/Cellar/sourcery/0.7.0/bin/sourcery --version
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
MiniTest::Assertion: Expected /0\.7\.0/ to match "Major.Minor.Patch".
```

This is a regression from 0.6.1.

See https://github.com/Homebrew/homebrew-core/pull/14480.

**Comment by ilyapuchka** [comment]
Thanks for reporting @ilovezfs 
Something went wrong during releasing 0.7.0, we will need to re-upload its binary. Can you reproduce Homebrew issue locally with this release? When doing `bin/sourcery --version` I got 0.6.1 (when it should be 0.7.0)

**Comment by ilyapuchka** [comment]
@Antondomashnev I guess the issue with version is simply that in Rakefile `update_metadata` task is done after `build` task. It should the the other way around, right?

**Comment by Antondomashnev** [comment]
@ilyapuchka may be, but then it should've been the same for 0.6.1 release as I used the same rake tasks.

**Comment by Antondomashnev** [comment]
@ilyapuchka I think that makes sense because the binary is built with `old_metadata`. I will prepare the fix along with the other in #359

**Comment by ilovezfs** [comment]
Unfortunately it looks like 0.7.1 still has this issue: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/3039/version=sierra/console

```
==> /usr/local/Cellar/sourcery/0.7.1/bin/sourcery --version
Error: sourcery: failed
Expected /0\.7\.1/ to match "Major.Minor.Patch".
```

**Comment by ilyapuchka** [comment]
@ilovezfs how to reproduce this locally?

**Comment by ilovezfs** [comment]
The Homebrew formula downloads and unpacks https://github.com/krzysztofzablocki/Sourcery/archive/0.7.1.tar.gz and then does this:
```
    system "swift", "build", "-c", "release", "-Xswiftc", "-static-stdlib"
    bin.install ".build/release/sourcery"
    lib.install Dir[".build/release/*.dylib"]
```

**Comment by ilyapuchka** [comment]
Thanks, that's help. Now it's clear that the error is caused by the fact that we are now reading project version from build settings and when building with SPM it, of course, does not work. @Antondomashnev should we revert to our old approach or do you have any idea how to solve that?

**Comment by Antondomashnev** [comment]
@ilyapuchka I've made a quick research across some projects with SPM support, it seems that everyone just hard code the version. So it seems we need to revert to the old code and also update the Rakefile. I can try to work on it this evening.

**Comment by jpsim** [comment]
Here's how we set it for SwiftLint: https://github.com/realm/SwiftLint/blob/0.19.0/Makefile#L109-L115

Also see https://owensd.io/2017/05/29/version-info-in-swift-cli-tools/ for some other ideas

**Comment by Antondomashnev** [comment]
@jpsim thanks, I think I've done almost the same idea 😄

**Comment by ilovezfs** [comment]
:green_apple: for 0.7.2 https://github.com/Homebrew/homebrew-core/pull/14676.

Thanks for the fix!
