### ISSUE TITLE
Upload Sourcery binary built with Xcode 9 to the release

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#357]
As mentioned in #356 we can build Sourcery in Xcode 9 in Swift 3.2 mode (or Swift 4 if no major changes needed), this will make it available for use with Swift 4 (if I get compatibility feature correctly)

**Comment by oscarsilver** [comment]
Any progress on this?

**Comment by igorkravchenko** [comment]
@ilyapuchka could you please upload build for Xcode 9 in Swift 3.2 mode?

**Comment by ilyapuchka** [comment]
I think it will make sense just to do new release

**Comment by Killectro** [comment]
👍 from me as well, newly integrating Sourcery and would love to have a 3.2 compatible mode as well. I'm very thankful for how much time you're going to save me going forward from now on 😄

**Comment by vCrespoP** [comment]
+1 Please, thx!

**Comment by Antondomashnev** [comment]
Done with [0.9.0 release](https://github.com/krzysztofzablocki/Sourcery/releases/tag/0.9.0)
