### ISSUE TITLE
Issues with release process

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#359]
- as mentioned in #354 `update_metdata` task should be performed before `build`
- Gemfile should specify version of ruby to use. With Sierra version (2.0.0p648) loading documentation coverage badge fails because of SSL issue what fails release process. Alternatively we can skip loading badge but then it will be removed all the time because docs are cleaned when they are updated

**Comment by ilyapuchka** [comment]
== Uploading ZIP (11025533 bytes) ==

rake aborted!
Errno::EPIPE: Broken pipe
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:319:in `syswrite'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:319:in `do_write'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:337:in `write'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/generic_request.rb:202:in `copy_stream'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/generic_request.rb:202:in `send_request_with_body_stream'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/generic_request.rb:132:in `exec'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1410:in `block in transport_request'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1382:in `request'
/Users/ilyapuchka/dev/Sourcery/Rakefile:151:in `block in post'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:582:in `start'
/Users/ilyapuchka/dev/Sourcery/Rakefile:150:in `post'
/Users/ilyapuchka/dev/Sourcery/Rakefile:305:in `block (2 levels) in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `call'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => release:github

**Comment by Antondomashnev** [comment]
No it doesn't require more it's something else I'll dig into it soon.

**Comment by Antondomashnev** [comment]
I've done some research on the issue. So far it seems that [this one](https://groups.google.com/a/cloudfoundry.org/forum/#!topic/vcap-dev/uHKx0jBknz0) is the closest one to our problem that it's because of a timeout while uploading. Also, we don't use here any dependency but in similar issue https://github.com/adhearsion/att_speech/issues/10 they suggest to use [Faraday](https://github.com/lostisland/faraday) as a network client.

@ilyapuchka did you notice by any chance that the connection you had was poor and slow? I think there is no drawback to starting using [Faraday](https://github.com/lostisland/faraday) especially because it's already in our dependency list by `Danger`.

**Comment by Antondomashnev** [comment]
@ilyapuchka finally found the issue - check the https://github.com/krzysztofzablocki/Sourcery/commit/faf27a4b7e7f6d3673c4c937e1a74b0cdc296ba8 😄

**Comment by Antondomashnev** [comment]
Let's keep it open until next release.

**Comment by Antondomashnev** [comment]
I've made last `0.8.0` release without issues, so closing issue for now.
