### ISSUE TITLE
Skip the generated preamble

### ISSUE THREAD

**Issue by haimwaking** [krzysztofzablocki/Sourcery#369]
Hi,

I'm trying to use Sourcery to generate a plist file. However, because Sourcery always uses this preamble:

```
// Generated using Sourcery 0.6.0 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT
```

Xcode won't recognise this as a valid plist file. Is there a way to remove or at least customise this part?

**Comment by ilyapuchka** [comment]
Hi, @haimwaking . If you use //sourcery:file:SomeFile.plist annotation in the template it will recognise that you are generting plist and will not put this comment (it does it only for *.swift files)

**Comment by haimwaking** [comment]
You are a hero, thanks!
