### ISSUE TITLE
Write files only on change

### ISSUE THREAD

**Issue by haimwaking** [krzysztofzablocki/Sourcery#370]
Hi,

We have found that after code generation, Xcode will consider a file has changed even if the contents have not and recompile it. This means every build is slowed down. Does sourcery check for file difference before overwriting them? It would really speed us up and avoid us using bash scripts to use Sourcery.

Thanks

**Comment by Antondomashnev** [comment]
Hi @haimwaking as I can see we write content only if it's different:
```swift
fileprivate func writeIfChanged(_ content: String, to path: Path) throws {
    guard path.exists else {
        return try path.write(content)
    }
    let existing = try path.read(.utf8)
    if existing != content {
        try path.write(content)
    }
}
```

**Comment by macduy** [comment]
Thanks Anton, I'll check again as we moved to handling this using bash scripts 😆 . If it works out of the box (and it sounds like it should), we'll migrate to using the config file. I'll test and get back to you if it doesn't work as expected.

**Comment by macduy** [comment]
(You can close this for now)
