### ISSUE TITLE
Support Objective-C sources?

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#376]
As Jazzy supports both swift and objc source code maybe it will be possible to get some code info for ObjC code?
@jpsim can you give some tips how ObjC support is implemented in Jazzy?

**Comment by krzysztofzablocki** [comment]
I really think we shouldn't attempt it, we should focus on Swift, we'd have to increase complexity of both implementation and user understanding if we wanted to support both languages.

Thoughts @Antondomashnev ?

**Comment by ilyapuchka** [comment]
Agree, it will definitely increase complexity and  lead to all possible edge cases causes by interoperability. I'm just wondering if this is even possible technically and can it be done without actually interacting with Objective-C code, but instead using generated interface files.

**Comment by Antondomashnev** [comment]
@krzysztofzablocki @ilyapuchka I agree about focusing on Swift language atm, especially until we reach 1.0 version. There are still plenty of issues open, and ObjC support is big step.

@ilyapuchka regarding even the possibility I don't know, but I see the limitation that we have to build sources before generating code using Sourcery and it can be chicken-egg problem. Sources require generated files to be built, Sourcery requires source files to generate boilerplate.

**Comment by jpsim** [comment]
Jazzy doesn't really know the difference between Objective-C and Swift to be honest. Actually, it could be used to document _any_ language with similar features.

All the parsing work is done entirely in [SourceKitten](https://github.com/jpsim/SourceKitten). SourceKitten uses [SourceKit](https://github.com/apple/swift/blob/master/tools/SourceKit/README.txt) for all its Swift language features, and [libclang](https://clang.llvm.org/doxygen/group__CINDEX.html) for all its C-languages features.

**Comment by ilyapuchka** [comment]
@jpsim we are using mostly `Structure` type provided by SourceKittenFramework, but how to make it work with Objective-C sources?

**Comment by jpsim** [comment]
Some work in SourceKittenFramework would be needed to expose what you want for your use case. So far, SourceKittenFramework's only ObjC functionality is generating docs from `.h` files.

**Comment by krzysztofzablocki** [comment]
Closing this as we want to focus on Swift

**Comment by lvsti** [comment]
In case anyone is still stuck in a mixed codebase like I do, here is a tool to generate a Swift interface from ObjC bridging headers, which can then be fed to Sourcery: https://github.com/lvsti/Bridgecraft

**Comment by toshi0383** [comment]
FYI: Just created code-generation example for mixed project using Sourcery and Bridgecraft.
https://github.com/toshi0383/ObjCSample

@lvsti Thanks for the great tool!
