### ISSUE TITLE
Unable to reference files above the project root using `../` in the paths

### ISSUE THREAD

**Issue by csykes** [krzysztofzablocki/Sourcery#380]
# Context
We've got an Xcode project that consists of multiple sub-projects + some common code base that sits at the root level of the meta-projects. We open the MetaProject.workspace file in Xcode and then select the sub-project's scheme to run/build. Sourcery ends up running from one of the child projects and reference files above it in the directory path. Prior to 0.6.0 we could just use `../` in the sources or templates path to reference those locations but that no longer works.

```
MetaProject
│   MetaProject.xcworkspace
└───SourceryTemplates
└───CommonCode
└───MySubProject
│   │   MySubProject.xcworkspace
│   └───GeneratedStubs
└───AnotherSubProject
│   │   AnotherSubProject.xcworkspace
│   └───GeneratedStubs
```

# Environment
Xcode 8.3.3
Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)

# Issue
After updating to 0.6.1 or 0.7.x we can no longer reference files above the root as the `../` appear to be ignored. We've tried this using both the YAML definition file and Bash shell commands with no luck.

**YAML definition**
```
sources:
  - MySubProject
  - ../CommonCode
templates:
  - ../SourceryTemplates/
output:
  MySubProject/GeneratedStubs

args:
  app: MySubProject
  imports: 
    - PromiseKit
    - CoreLocation
```

**Bash shell definition**
```
"$PODS_ROOT/Sourcery/bin/sourcery" --sources "$SRCROOT/../CommonCode" --templates "$SRCROOT/../SourceryTemplates/" --output "$SRCROOT/MySubProject/GeneratedStubs" --args app=MyProject,imports=PromiseKit,imports=CoreLocation
"$PODS_ROOT/Sourcery/bin/sourcery" --sources "$SRCROOT/MySubProject" --templates "$SRCROOT/../SourceryTemplates/" --output "$SRCROOT/MySubProject/GeneratedStubs" --args app=MyProject,imports=PromiseKit,imports=CoreLocation
```

# Results
We see the following failure in Xcode when we try to run the MySubProject

```
error: '/Users/MrC/Documents/dev/MetaProject/MySubProject/CommonCode' does not exist or is not readable.
error: '/Users/MrC/Documents/dev/MetaProject/MySubProject/SourceryTemplates' does not exist or is not readable.
```

**Comment by Antondomashnev** [comment]
@csykes thanks for reporting it, we'll take a look into the issue soon 😄

**Comment by macduy** [comment]
We have a similar set up and we cannot use configuration files for the same reason :) We currently use horrible bash scripts which we'd love to move away from!

**Comment by ilyapuchka** [comment]
with 0.6.1 (probably it should have been 0.7) paths in the yaml file are relative to the location of this file (before they were relative to the current path from which sourcery is called). can you confirm that yaml file is in a proper location @csykes @macduy ?

**Comment by macduy** [comment]
Yep. I looked at the Xcode build errors and 

```
templates:
 - ../templates/
```

and 

```
templates:
- templates/
```

would resolve to the same directory

**Comment by ilyapuchka** [comment]
will it be the same with `./../templates`? I'll look into this issue on a weekend if this does not resolve it.

**Comment by macduy** [comment]
Yep tried that too and it's the same problem

**Comment by ilyapuchka** [comment]
@csykes  @macduy if you can add a PR with failing test it would help. I tried to reproduce this issue, but these tests pass:

```swift
it("sources include path out of current path using ../") {
    let config = ["sources": ["../otherPath"]]
    let source = Configuration(dict: config, relativePath: relativePath).source
    let expected = Source.sources(Paths(include: [relativePath.parent() + "otherPath"]))
    expect(source).to(equal(expected))
}

it("templates include path out of current path using ../") {
    let config = ["templates": ["../otherPath"]]
    let templates = Configuration(dict: config, relativePath: relativePath).templates
    let expected = Paths(include: [relativePath.parent() + "otherPath"])
    expect(templates).to(equal(expected))
}

```

**Comment by csykes** [comment]
Haven't had a chance to build up a PR with failing tests but we've found that adding an additional `$SRC_ROOT/../` into the configuration file it eventually finds the correct file/directory.Why? Dunno... but at least its a workaround for now.

**Working .sourcery.yaml file:**
```
sources:
  - MySubProject
  - $SRC_ROOT/../../../CommonCode
templates:
  - $SRC_ROOT/../../../SourceryTemplates/
output:
  MySubProject/GeneratedStubs

args:
  app: MySubProject
  imports: 
    - PromiseKit
    - CoreLocation
```

Given that we fetch the latest version of Sourcery from CocoaPods, we end up running the commands from that binary location. So I suspect that has something to do with the issue.

```
    export PODS_ROOT=/Users/MrC/Documents/dev/MetaProject/MySubProject/_iOS/../../Pods
    export SRCROOT=/Users/MrC/Documents/dev/MetaProject/MySubProject/_iOS
```

**Comment by ilyapuchka** [comment]
it works because `SRCROOT` is an absolute path in this case

**Comment by csykes** [comment]
Forgot to highlight that even though its using an absolute path now it still requires one extra `../` to make it find the correct directory location. 

I would have expected it to only need `../../` to move up the two directory levels to find the Templates or CommonCode from the SRC_PATH.

**Comment by Antondomashnev** [comment]
Hi @csykes @macduy I've been trying to debug the issue and I was able to reproduce it. After debugging further I found two things:
1. It seems to be a bug in [PathKit](https://github.com/kylef/PathKit) framework that we use in Sourcery with combining two relative path. I've reported it [already](https://github.com/kylef/PathKit/issues/35). It's related to the initial question from @csykes 
2. I've found the weird behaviour - most likely also related to [PathKit](https://github.com/kylef/PathKit). `$SRCROOT/../CommonCode` doesn't work although if I type the actual value of `$SRCROOT` it works - `/Users/antondomashnev/Work/MetaProject/MySubProject/../CommonCode`.

For now I think your workaround is the best option until we come up with the resolution for the `1` point.

**Comment by csykes** [comment]
Thanks for the update! 

With the work around, our app is using the latest Sourcery version now so I've got no issues waiting this out.

**Comment by Antondomashnev** [comment]
@ilyapuchka I think it makes sense to mention this limitation somewhere in the documentation for config file, what do you think?

**Comment by ilyapuchka** [comment]
I think we should have some kind of FAQ with answers to common questions, then we can put it there.

**Comment by Sajjon** [comment]
I too have problems relating to not being able to use relative paths in my Config file. Any update?
