### ISSUE TITLE
Tracking some statistics

### ISSUE THREAD

**Issue by krzysztofzablocki** [krzysztofzablocki/Sourcery#381]
I think it would be cool to be able to show off some statistics:

- Number of projects using the tool
- Number of lines scanned
- Number of lines generated

I think we'd need to grab the plist identifier since its unique, and then just track 2 numbers along it

What do you think? Ideas for what backend should we use to store it? @ilyapuchka @Antondomashnev

**Comment by Antondomashnev** [comment]
@krzysztofzablocki generally I think it sounds cool 👍 
Regarding the plist identifier as we don't have access to the app itself, do you wanna introduce another command line parameter? I'd like to think about a way of how to grab the plist without asking the user for it. 
* If the sourcery script invocation is a part of run phase we can get everything from environment variables
* If the sourcery was invoked just from command line, do you want to look for `.plist` files or maybe `.xcodeproj`?

Apart of the proposed statistics what do you think if we track also something for us (could be either public or private for anyone) - for example the time sourcery spends of code generation, it could be somehow helpful for performance analysis.

**Comment by krzysztofzablocki** [comment]
I was thinking of finding plist file, we could track performance metric as well, good idea :)

**Comment by Antondomashnev** [comment]
@krzysztofzablocki what if the project has multiple plist files?

**Comment by krzysztofzablocki** [comment]
@Antondomashnev good point, maybe using .xcodeproj is better, we need to streamline some things for this

**Comment by eugeneego** [comment]
Please consider many developers that use Sourcery work on projects with strict NDAs.
All statistics should be optional.
