### ISSUE TITLE
// sourcery:file:<custom file name> ignored when generated file above ~150kB

### ISSUE THREAD

**Issue by macduy** [krzysztofzablocki/Sourcery#386]
I've got a template `equatable.stencil` that defines the output file name at the start using

```
// sourcery:file:SourceryGeneratedEquality.swift`

... template...

// sourcery:end
```

This creates a file `SourceryGeneratedEquality.swift` as expected. However if the generated file grows beyond a certain size (I estimated at around 150 kB), the name of the file reverts to the default `equatable.generated.swift`.

I've noticed this when I started added too many source files, without changing `.sourcery.yml` or the template file.

**Comment by ilyapuchka** [comment]
That's a very weird bug. @macduy could you compile a source file that we can use to reproduce this?

**Comment by krzysztofzablocki** [comment]
let us know if it still happens with newest Sourcery and we'll reopen
