### ISSUE TITLE
Use Sourcery as a Dependency

### ISSUE THREAD

**Issue by rex-remind101** [krzysztofzablocki/Sourcery#388]
First off Sourcery looks amazing, thanks for all the hard work!

I require some meta-programming for a code generator I'm writing in Swift. I'm hoping I can use Sourcery for gathering a bunch of type info from my application and feed that into my code generator - what's the best way to include Sourcery's abstractions and runtime as a library dependency?

Thank you

**Comment by ilyapuchka** [comment]
Hey @rex-remind101 
You can try to include it as a Pod, but this use case is not supported, so I'm not even sure that it will work. But we can add it in future (extracting some code into framework that can be used by other code generators).

**Comment by Antondomashnev** [comment]
@ilyapuchka don't we already have `SourceryRuntime`?

**Comment by ilyapuchka** [comment]
This is just models, they alone are pretty useless for third parties. We need to provide parsing functionality and probably generation (basically templates and context types) as frameworks too. Like SourceKitten framework does. I was thinking about that for quite some time, I think its a valuable feature (there was an [attempt](https://github.com/krzysztofzablocki/Sourcery/issues/67) to do that in early days but for some reason it didn't work out). 
I think it will also help with Linux and SPM support and some other ideas I have in mind. One of them
is to extend a CLI interface in a way that SourceKitten does it - provide different commands for different actions, like `parse` (or `dump`) just to parse sources and store it in some output, `generate` to get this output and generate code using templates, maybe something else (like compile templates). This might be useful for third party frameworks support and as internal tool to get structure of Cocoa/Foundation frameworks.

**Comment by Antondomashnev** [comment]
Now, it's clearer, thanks @ilyapuchka. I see that the issue was closed, although I think it may be useful not even in terms of additional CLI interface, but to simplify the Sourcery code itself. As with split modules I think it could be easier to maintain the codebase.

**Comment by ilyapuchka** [comment]
Totally agree. And it will help with cleaning up test suite =)

**Comment by rex-remind101** [comment]
Thanks for the quick reply :)

For my personal use case I can get away with just parsing the source and storing it in the available models, I'll just use these models directly in my codegen project. I read through https://github.com/krzysztofzablocki/Sourcery/issues/67 and from as much as I gathered this would include moving the models and the parser (and their tests?) into their own framework. Anything I'm missing here? How much work do you think this may be?

FYI I'm currently using SPM for the dependencies of my code generator. However, I do have experience with cocoapods. Not sure if there's a way to use both but I'd be willing to give it a shot if targeting SPM is too far of a stretch for this framework.

**Comment by krzysztofzablocki** [comment]
if you can get away with just models, doesn't that mean you can just write templates to generate what you need? I'm curious what your generator does ?

**Comment by rex-remind101** [comment]
I need representations of the applications current data structures in order to inform my code generator. The generator initially takes an API schema and generates requests, mappings, and Realm model objects. Thing is there's a lot of custom things we do from handlers in our mappings, models, and requests (e.g. evicting certain objects from the DB or sending notifications across the app) that can't be represented by our schema. The plan is to create tags on pieces of our codebase that are read by Sourcery that then help inform the generator of these additional functions.

Also, the code generator needs to work with a lot of legacy code. It is possible that we could build these hooks some other way by refactoring to use subclasses or what not, but that seems like a ton of work, would be less flexible, and would be less clean than having the additional hooks right there alongside the code that is generated.

**Comment by rex-remind101** [comment]
In other words we want to parse the requests, models, and mappings that currently exist in the app ahead-of-time and include what is tagged in there into our code generation process.

**Comment by rex-remind101** [comment]
Thoughts on how I can best get this integration working?

**Comment by ilyapuchka** [comment]
If you only need `SourceryRuntime` then just grab the project source code and link this framework to your project. I don't think it will be wise for us to provide any kind of integration (via any package manager) just for this framework.

**Comment by rex-remind101** [comment]
I'll need the parsing capabilities too which looks like they belong to https://github.com/krzysztofzablocki/Sourcery/tree/master/Sourcery and not `SourceryRuntime` plus all the dependencies. This looks like a lot of source code to drag into my project so I may give SPM a shot first since there's a `Package.swift` and do what you suggest if that doesn't work out. Thanks for the help :)
