### ISSUE TITLE
LowerFirst filter fails for associated value type name

### ISSUE THREAD

**Issue by rafaelnobrepd** [krzysztofzablocki/Sourcery#391]
Hey, this is an amazing project! I'm just beginning to  explore its possibilites.
Given this enum definition:
```
enum LowerCaseTest {
    case lowerCase(value: UIViewController)
    case helloWorld(value: UICollectionViewController)
}
```

And this template:
```
let {{ "HelloWorld" | lowerFirst }} = "sanity check"
{% for case in type.LowerCaseTest.cases %}
let {{ case.associatedValues.first.typeName | capitalize }}Identifier = "this works"
let {{ case.associatedValues.first.typeName | lowercase }}Identifier = "this works"
let {{ case.associatedValues.first.typeName | lowerFirst }}Identifier = "this fails"
{% endfor %}
```

The generated code is this:
```
let helloWorld = "sanity check"
let UIViewControllerIdentifier = "this works"
let uiviewcontrollerIdentifier = "this works"
let UIViewControllerIdentifier = "this fails"
let UICollectionViewControllerIdentifier = "this works"
let uicollectionviewcontrollerIdentifier = "this works"
let UICollectionViewControllerIdentifier = "this fails"
```

Am I missing something? Reading the associatedValue type's name didn't properly lowercased the first letter.

**Comment by ilyapuchka** [comment]
Hey, @rafaelnobrepd 
I don't see the difference between code that generates write and wrong output, can you please check your description?

`let {{ case.associatedValues.first.typeName | lowerFirst }}Identifier = "this works"`
vs
`let {{ case.associatedValues.first.typeName | lowerFirst }}Identifier = "this fails"`

**Comment by ilyapuchka** [comment]
Anyway, these filters only work on `String` types, `typeName` returns `TypeName`, that's why it does not work. `lowercase` filter from Stencil works on any type that can be converted to String, we should improve our custom filters the same way

**Comment by rafaelnobrepd** [comment]
I'm sorry I had a typo, I meant `capitalize` in the first example. That's why then, some of those are filters from Stencil. I would be nice to support this way 👍

**Comment by rafaelnobrepd** [comment]
Worked around with `{{ case.associatedValues.first.typeName.name | lowerFirst }}`. I don't know the API well enough yet 😞

**Comment by ilyapuchka** [comment]
Exactly, though it's not a workaround, but the way this filter works
