### ISSUE TITLE
How to detect if a type supports "==" operator?

### ISSUE THREAD

**Issue by guidomb** [krzysztofzablocki/Sourcery#392]
Maybe this was already addressed but it is not clear to me what is the proper way to detect in a template if a type can be tested for equality using the `==` operator.

In my template I tried adding the following condition: ```{% if instanceVariable.type.based.Equatable %}``` but types like `String` or `Bool` do not match such condition.

I skimmed through previous issues and people (and the documentation) make a distinction between know and unknown types. What does a "known" type mean? Is it related to this?

Thanks

**Comment by ilyapuchka** [comment]
@guidomb This is explained in the docs in section "What are known and unknown type" here https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/writing-templates.html

**Comment by guidomb** [comment]
@ilyapuchka thanks!

So is there any way to detect if a particular (either known or unknown) supports `==` operator?

**Comment by ilyapuchka** [comment]
For now it is only possible for known types. For unknown types you can extend them with phantom protocol that you will use instead of `Equatable` - `extension String: ConformsToEquatable {}`

**Comment by guidomb** [comment]
OK. I'll try that. Thanks the quick response.
