### ISSUE TITLE
--config flag doesn't work

### ISSUE THREAD

**Issue by tcldr** [krzysztofzablocki/Sourcery#394]
As far as I can tell, the `--config` param doesn't work as expected:

With two files with exactly the same content, one named `.sourcery.yml` and the other `application.yml`

Calling `./bin/sourcery`, works as expected and makes use of `.sourcery.yml`, whilst calling `./bin/sourcery --config application.yml` does not, reporting `error: No sources provided.`

Sourcery 0.8.0

**Comment by ilyapuchka** [comment]
From [docs](https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/usage.html): "--config [default: current path] - Path to config file. Directory. See Configuration file."

**Comment by tcldr** [comment]
@ilyapuchka I think it would make more sense to be able to select a file rather than a directory.

The docs say "Path to config file. Directory." which is pretty confusing!

If this means what it appears to mean; that I must specify a *directory* for Sourcery to look for a specific *file* named `.sourcery.yml`. I'm not sure what the use-case could be? This is effectively still a file path, just one that *must* end in `.sourcey.yml`!

However, if one can specify a file directly, they can still do all of the above, but also rename their configuration files for various targets. (As I'd like to do.)

**Comment by ilyapuchka** [comment]
That's just how it works now. See #395
