### ISSUE TITLE
Fully resolved type names for AssociatedValue

### ISSUE THREAD

**Issue by tcldr** [krzysztofzablocki/Sourcery#398]
Hi, I've extended the AutoCases template to extract the associated values from an enum case (useful in a filterMap for example) but I can't see how to get the fully resolved type names for associated values, when that value is generic.

e.g with a structure like so:
```
struct MyContainer {
    struct MyOption <T> { let value: T }
    enum MyValues: AutoCases {
        case valueA
        case valueB
        case valueC(MyOption <Int>)
    }
}
```

The 1st `AssociatedValue` for `MyContainer.MyValues.valueC` is a `MyContainer.MyOption <Int>`. However, calling `typeName` only gets me `MyOption <Int>`. Unlike other types, where you can call `type.name`, for some reason `type` returns nothing when using a generic type, so there appears to be no workaround.

**Comment by ilyapuchka** [comment]
we don't yet provide complete support for generics, but that issue might be addressed when #247 will be complete.
