### ISSUE TITLE
0.8.0 Zip release shows 0.7.2 as its version

### ISSUE THREAD

**Issue by Liquidsoul** [krzysztofzablocki/Sourcery#400]
Hi there,

I downloaded the 0.8.0 zip version of Sourcery and when running `bin/sourcery --version` from the unzipped folder, it prints `0.7.2`.

Is this still the new code showing the incorrect version? Or just the previous version?

**Comment by BenchR267** [comment]
The Info.plist also shows 0.7.2. I think it wasn't built again before releasing.

**Comment by Liquidsoul** [comment]
I've updated the binary in the 0.8.0 release with a build from the 0.8.0 tag.
The release still contains the zip initially uploaded when the release was created (`Sourcery-0.8.0-initial.zip`).
I'll let the issue open a while for other collaborators to stop by before closing the issue (and maybe remove the initial zip).

**Comment by Antondomashnev** [comment]
Thanks @Liquidsoul for fixing my mistake 😄 I've checked `info.plist` of new file and it contains correct version. I'm still thinking how the issue appeared as we have all process automated and it worked fine...
