### ISSUE TITLE
AutoMockable produces strange method names

### ISSUE THREAD

**Issue by garnett** [krzysztofzablocki/Sourcery#407]
0.8.0, latest stencil template:

```
class ConvertBalanceCalculatorViewMock: ConvertBalanceCalculatorView {

    //MARK: - showSourceCurrency

    var showSourceCurrency___Called = false
    var showSourceCurrency___ReceivedCurrency: CurrencyCode?

    func showSourceCurrency(_ currency: CurrencyCode) {
        showSourceCurrency___Called = true
        showSourceCurrency___ReceivedCurrency = currency
    }
```
I don't quite undertand `stencil` syntax, just wanted to confifrm if having `_ _ _` in method names is expected behaviour

**Comment by ilyapuchka** [comment]
I think with #368 this template now replaces `,:()` characters with `_`, though we should probably use empty string instead, @Antondomashnev ?

**Comment by Liquidsoul** [comment]
Looking at the code, I can confirm that with #368, characters `:` and `(` are replaced by `_` and `)` is replaced by empty string.
Maybe we can just use empty string for all the characters. At the same time, maybe we could factorise the stencil's code using a `macro` instead of repeating the replacement code.

**Comment by Antondomashnev** [comment]
@Liquidsoul @ilyapuchka you're right guys, but I've tried the empty string and for me it looked worse. Maybe if we can combine the empty string with capitalized first letter of first method parameter - i'll look better. 
I can take a look on it, how we can make it better.

@Liquidsoul regarding the macro - there is one clear downside for me that prevented me to use them - macro always requires a new line. If you know how to change that behaviour I'm more than happy to replace repeatable code.

**Comment by ilyapuchka** [comment]
@Antondomashnev combining capitalization and empty string seems like a way to go for me.
P.S. swift templates do not have "new line problem" 😉

**Comment by Liquidsoul** [comment]
@Antondomashnev As long as you do not include the newline in the macro you can do that.
I've just tried it on the AutoMockable template and it works pretty well.
Declare the macro like this:
```swift
{% macro fixName name %}{{ name | replace:"(","_" | replace:")","" | replace:":","_" }}{% endmacro %}
```

And replace all:
```swift
{{ method.selectorname | replace:"(","_" | replace:")","" | replace:":","_" }}
```
with:
```swift
{% call fixName method.selectorName %}
```

And you'll have your _replace_ routine in only one place 😃

**Comment by Antondomashnev** [comment]
Amazing, thanks @Liquidsoul
