### ISSUE TITLE
TypesCollection subscript return type should be [Type]

### ISSUE THREAD

**Issue by ahti** [krzysztofzablocki/Sourcery#411]
`TypesCollection[...]` currently returns `Any?`, which makes it painful to use in Swift templates. is there a reason for this, or could it be changed to return `[Type]` (defaulting to `[]` if nothing is found)?

**Comment by Antondomashnev** [comment]
Hi @ahti, thanks for your question. We'll take a look at what's possible to do to improve the experience 😄

**Comment by ilyapuchka** [comment]
@ahti solved with c40efe60d3044e43164e12ecddf1f797d7da176b
