### ISSUE TITLE
Sourcery ignores command line arguments when .sourcery.yml exists in current directory

### ISSUE THREAD

**Issue by garrett-davidson** [krzysztofzablocki/Sourcery#412]
I just started trying out Sourcery (prebuilt binary of 0.8.0) and ran into a very confusing issue. I created a test .sourcery.yml file in the root directory one of my projects, but it didn't do quite what I wanted (my fault). So I tried playing around with the command line arguments while cd'ed into that root directory, but couldn't figure out why nothing I tried was having any effect. Eventually I realized that the configuration file in the current directory will silently take priority over command line arguments, even without passing --config.

**Comment by ilyapuchka** [comment]
This is expected behaviour. What we can surely improve is to add logs telling that yaml file is used and switch to using comand line arguments if they are provided
@Antondomashnev wdyt?

**Comment by Antondomashnev** [comment]
@ilyapuchka I'd personally see two options:
1. Override configuration value if there is a value directly provided in command
2. Throw exception if there is a conflict between configuration and command line argument

I'm not sure about the first option, although this is the behavior I'd want to have for me personally as a developer.
The second option may sound like an overkill for the design though.

**Comment by ilyapuchka** [comment]
I think it will make sense to override options of config file is specified explicitly, not when it is discovered automatically, what do you think? but to be honest I wouldn't override at all to make it simpler.

**Comment by Antondomashnev** [comment]
> specified explicitly, not when it is discovered automatically

What do you mean by discovered automatically?

Have you seen by any chance this overriding behavior somewhere?

**Comment by ilyapuchka** [comment]
By automatically I mean that we have a default value for config path parameter which is current path and we have a default name for the config file to search for, so thus the behaviour described by @garrett-davidson.
Regarding overriding behaviour I don't think I saw it anywhere. I think it will be more straight forward if we use one or another way and just print out a hint to the user about it.

**Comment by Antondomashnev** [comment]
> I think it will be more straight forward if we use one or another way and just print out a hint to the user about it.

Yes, if Sourcery finds command line parameter and configuration file warn the user about possible collisions.

> By automatically I mean that we have a default value for config path parameter which is current path and we have a default name for the config file to search for

Absolutely agree 👍
