### ISSUE TITLE
A tag I am needing that simplify my template drastically is `if item in list`

### ISSUE THREAD

**Issue by kdawgwilk** [krzysztofzablocki/Sourcery#415]
I am unable to find in the docs if this is possible but I would like to be able to use the following in my templates:

```
{% if item in list%}
// Do stuff here now that we know this is in the list
{% endif %}
```

**Comment by ilyapuchka** [comment]
Hi @kdawgwilk 
This is a very good suggestion, but as it is related to [Stencil](https://github.com/kylef/Stencil) we should do it in Stencil repo or at least in [StencilSwiftKit](https://github.com/SwiftGen/StencilSwiftKit).
