### ISSUE TITLE
Update for new version of Swiftlint

### ISSUE THREAD

**Issue by Antondomashnev** [krzysztofzablocki/Sourcery#418]
The new [0.2.2](https://github.com/realm/SwiftLint/releases/tag/0.22.0) of SwiftLint fails the build with:
`Superfluous Disable Command Violation`

Although it may be false positive according to the [issue](https://github.com/realm/SwiftLint/issues/1810) we still need to take a look at it as for now CircleCi doesn't have SwiftLint installed for all Sourcery builds.

**Comment by jpsim** [comment]
SwiftLint now ignores SwiftLint commands in `file_header` rule as of https://github.com/realm/SwiftLint/pull/1816, which shipped as part of [0.23.0](https://github.com/realm/SwiftLint/releases/tag/0.23.0)
