### ISSUE TITLE
Add `implements` and `inherits` properties to type

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#42]
As now we have a separation between `implementing` and `inheriting` types collections in generator we may as well add corresponding properties to `Type` model.
Then `inheritedTypes` (should be renamed to `based` probably?) becomes analogous to `types.based`, `implements` to `types.implementing` and `inherits` to `types.inheriting`.

With that instead of `variable.type.inheritedTypes.MyProtocol` it will be possible to do `variable.type.implements.MyProtocol` which just reads better. Also it will be more consistent with mentioned separation of inheriting and implementing types in generator.

**Comment by krzysztofzablocki** [comment]
I'll add it 👍

**Comment by krzysztofzablocki** [comment]
This will be needed for the following to work properly:
```swift
protocol AutoEquatable {}

struct AStruct: Equatable {
  public static func == (l: AStruct, r: AStruct) -> Bool {
    return true
  }
}

struct Book: AutoEquatable {
  let aStruct: AStruct
}
```

Given template like
```swift
{% for type in types.implementing.AutoEquatable %}
  {% for variable in type.storedVariables %}
    {% if variable.type.inheritedTypes.AutoEquatable %}
      {{ variable.type }}
    {% endif %}
  {% endfor %}
{% endfor %}
```

It should not generate code

**Comment by ilyapuchka** [comment]
Ah, so if `inheritedTypes` is just an array of strings we can not use it in `if type.inheritedTypes.SomeType`? Then looks like those collections should be "dummy" dictionaries like `["TypeName": "TypeName"]`?

**Comment by krzysztofzablocki** [comment]
well right now we don't store real types in inheritedTypes, and we should as we want to be able to query they implement something so I'll add it

**Comment by ilyapuchka** [comment]
We may store them like `[TypeName: Type]`, but I'm not sure we will get something from storing actual type references, because what we need is just to check if the type name is inside the implementing types collection and not to access the metadata of those types. At least I don't see it useful right now.

**Comment by krzysztofzablocki** [comment]
Implemneted in 0.4.1
