### ISSUE TITLE
default.profraw file created when running Sourcery 0.9.0

### ISSUE THREAD

**Issue by Liquidsoul** [krzysztofzablocki/Sourcery#421]
A `default.profraw` file is created when running Sourcery at its 0.9.0 version.
I tried with 0.8.0 and this does not happen.

**Comment by mergesort** [comment]
I'm seeing this as well.

**Comment by Antondomashnev** [comment]
I don't think it's something that we should look into. As far as I understand this is a file with information about tests results.

**Comment by Liquidsoul** [comment]
My point is that this is creating a file in the users' repository for nothing.
As far as I know, we are not executing "tests" when we use Sourcery to perform the code generation 😉

**Comment by Antondomashnev** [comment]
Ah, sorry @Liquidsoul I misunderstood the task, I thought you mean if you run `Sourcery.xcworkspace`. In case of the user - you're right 👍

**Comment by ivira** [comment]
We have similar problem and setting _CLANG_ENABLE_CODE_COVERAGE = NO_ for release build solved the problem.

**Comment by Antondomashnev** [comment]
@ivira thanks for the tip 😉

**Comment by rodrigoruiz** [comment]
I don't think this issue was fixed, I'm still seeing that file.

**Comment by Antondomashnev** [comment]
Resolved with #445

**Comment by DenHeadless** [comment]
Guys, how about releasing this as 0.9.1 update? Seems like necessary bugfix update, this file is changing it's content and showing in git diffs everytime. Requires constant attention and raises questions every time.

**Comment by Antondomashnev** [comment]
@DenHeadless thanks for raising that question. I'll try to release it tonight.
@krzysztofzablocki @ilyapuchka @Liquidsoul  anything we want to add particularly for the release?

**Comment by Antondomashnev** [comment]
@ilyapuchka will try.

**Comment by Antondomashnev** [comment]
@DenHeadless done =)

**Comment by DenHeadless** [comment]
Thanks guys! Confirmed this fix works 🍻
