### ISSUE TITLE
Cocoapods: Sourcery 0.9.0 fails to run 

### ISSUE THREAD

**Issue by Sajjon** [krzysztofzablocki/Sourcery#423]
I cant run Sourcery when installed via pods, Sourcery 0.9.0 that is.

```bash
 ./Pods/Sourcery/bin/sourcery 
./Pods/Sourcery/bin/sourcery: line 6: <MY_PODS_ROOT>/Sourcery/bin/Sourcery.app/Contents/MacOS/Sourcery: No such file or directory
```

Any input? :)

**Comment by Antondomashnev** [comment]
Hi @chriseidhof I've tried to reproduce the issue, but without luck. If you don't mind could you check how [FBSnapshotsViewer](https://github.com/Antondomashnev/FBSnapshotsViewer) uses the latest Sourcery from CocoaPods and share more details on your usage - like a run phase script.

**Comment by Sajjon** [comment]
This is on Sierra 10.12.6 (16G29), using Xcode 9 GM seed and Bundler version 1.15.3 and cocoapods (1.3.1)

**Comment by Antondomashnev** [comment]
Would you be able to try to install or update bundle for the project I've provided above?

**Comment by Sajjon** [comment]
@Antondomashnev Yes that project worked.

I manually removed Pods/Sourcery and ran `bundle exec pod installl` again, and now it works! :D 

So pods must have cached some old files? I performed a `rm -rf ~/Library/Caches/CocoaPods` but not `rm -rf Pods/Sourcery`.

Thanks!

**Comment by Antondomashnev** [comment]
@Sajjon sounds amazing 🎉 
I guess there could be some cache issues, maybe you can post the question in the CocoaPods repo as it may be interesting for them 😄

**Comment by DivineDominion** [comment]
I have a similar issue when I `git clone`, then `swift build` inside, and try to run `./bin/sourcery`:

    ./bin/sourcery: line 6: <...>/bin/Sourcery.app/Contents/MacOS/Sourcery: No such file or directory
