### ISSUE TITLE
Nested enum types

### ISSUE THREAD

**Issue by radianttap** [krzysztofzablocki/Sourcery#427]
I'm trying to generate `AutoEquatable` for enum nested in another type, like this:

```
final class BettingCoordinator: NavigationCoordinator {
	enum Page: AutoEquatable {
		case home
		case live
		case sport(Sport, Int64?, [Int64])
		case nextStandard
		case event(Event?, Int64?)
		case multiEvent([Int64])
		case favorites
		case topLeagues
		case specials
	}
}
```

I can see these types present in `types.enums`, but not in `types.implementing.AutoEquatable`. Is this a bug or expected behavior..?

**Comment by krzysztofzablocki** [comment]
is `AutoEquatable` definition in your scanned sources?

**Comment by radianttap** [comment]
Darn :(

I had this sourcery.yml:
sources: 
 - iosapp

while the protocol declaration was in DataModel folder. Will try again, thanks
