### ISSUE TITLE
`actualTypeName` does not return fully qualified type name for closure types 

### ISSUE THREAD

**Issue by tcldr** [krzysztofzablocki/Sourcery#429]
When using Sourcery to extract closure types, it would be useful if Sourcery would extract fully qualified (actual type names) for all parameters and the return type also. Currently this must be done manually.

**Comment by ilyapuchka** [comment]
Hi, @tcldr . Did you have a look into `ClosureType` [here](https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/Classes/ClosureType.html)? It should give you everything you need.

**Comment by tcldr** [comment]
Hi @ilyapuchka, thanks for response.

Yes, ClosureType has everything required. In case someone else requires it and finds this post down the line, I used the following macros:

    {% macro printClosureParams params %}({% for value in params %}{% call printTypeName value.actualTypeName %}{% if not forloop.last %}, {% endif %}{% endfor %}){% endmacro %}
    {% macro printClosure closure %}({% call printClosureParams closure.parameters %} -> {% call printTypeName closure.actualReturnTypeName %}){% endmacro %}

Where `closure` in the `printClosure` macro accepts a `ClosureType` as its input.

**Comment by ilyapuchka** [comment]
Maybe we can have a collection of snippets like that somewhere in the docs, or maybe even as stencil templates along with others that then can be included in other templates.

**Comment by tcldr** [comment]
I think that would be really useful. It took me quite a while to get up to speed with all the various features, particularly with stencil, so a resource that we could reference would be handy.

**Comment by tcldr** [comment]
Sourcery Cookbook or something.

**Comment by ilyapuchka** [comment]
@krzysztofzablocki maybe we can open PR where people can submit their small snippets like that?

**Comment by tcldr** [comment]
Sounds good to me.

**Comment by krzysztofzablocki** [comment]
sounds good to me as well

**Comment by tcldr** [comment]
Is the github wiki any use for something like this?

**Comment by krzysztofzablocki** [comment]
wiki might be even better for FAQ and snippets

**Comment by ilyapuchka** [comment]
in my opinion it's not very friendly for collaboration, but still can be an option

**Comment by tcldr** [comment]
Whatever you guys decide. Will be delighted to add my small contribution!
