### ISSUE TITLE
Bug in inheritedTypes.Protocol

### ISSUE THREAD

**Issue by bolismauro** [krzysztofzablocki/Sourcery#43]
I have the following code

```swift
protocol AutoEquatable {}

struct AStruct: Equatable {
  public static func == (l: AStruct, r: AStruct) -> Bool {
    return true
  }
}

struct Book: AutoEquatable {
  let aStruct: AStruct
}
```

If I generate the code for this template
```
{% for type in types.implementing.AutoEquatable %}
  {% for variable in type.storedVariables %}
    {% if variable.type.inheritedTypes.AutoEquatable %}
      {{ variable.type }}
    {% endif %}
  {% endfor %}
{% endfor %}
```

I should see an empty file, since `Book` doesn't contain any variable that has `AutoEquatable` as protocol.
But instead I see `Astruct` type definition (which has only `Equatable` as inheritedType).
If I remove the `Equatable` protocol from `Astruct` struct, the generated file is empty.

Basically it seems that  `variable.type.inheritedTypes.AutoEquatable` always passes if `variable.type.inheritedTypes` is not empty. Note that I can use everything instead of `AutoEquatable` (like `variable.type.inheritedTypes.TEST`) and the result is the same

**Comment by krzysztofzablocki** [comment]
yeah I think that's because inheritedTypes is an array not a dictionary, that's why I'm going to add #42, I think we can close this as that task will get rid of it, I'll add your example there

**Comment by bolismauro** [comment]
Alright, I'll add a comment also in #40 then for future reference
