### ISSUE TITLE
Cannot build using Xcode 9

### ISSUE THREAD

**Issue by rex-remind101** [krzysztofzablocki/Sourcery#433]
I cloned the repo and attempted to build using the Sourcery scheme but received the following error
<img width="891" alt="screen shot 2017-11-03 at 12 54 17 pm" src="https://user-images.githubusercontent.com/4573957/32393332-4ba2fbbc-c096-11e7-9ae1-9d3c839e1776.png">

How can I fix this?

**Comment by krzysztofzablocki** [comment]
I assume you are building workspace not pbxproj right ? this builds just fine for me (and the project CI)

**Comment by Antondomashnev** [comment]
@rex-remind101 this is the issue because you don't have the file that named `Xcode_9.0.0_fb.app`. That was my mistake to push it to the master. Now master has the correct path.
