### ISSUE TITLE
Release with Xcode 9.1

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#434]
As Xcode 9.1 ships with Swift 4.0.2 which is not ABI compatible with Swift 4 we need to make a release built with it so that swift templates continue to work. I guess few next releases should contain both binaries, built with Swift 4 and Swift 4.02 to support those who updated and not at the same time.

**Comment by vCrespoP** [comment]
+1

**Comment by buscarini** [comment]
+1

**Comment by mathieutozer** [comment]
+1

**Comment by ilyapuchka** [comment]
Have some issues running rake task for new release. Will investigate them later or perform steps manually.

**Comment by tengyifei** [comment]
+1

**Comment by Antondomashnev** [comment]
The last release was by using Xcode 9.2.
