### ISSUE TITLE
Is Linux supported?

### ISSUE THREAD

**Issue by felix91gr** [krzysztofzablocki/Sourcery#435]
Hi! I think I might want to use Sourcery for a Linear Algebra library I’m making with a friend. Thing is, we want to make it for both Linux and Mac OS. Would it be possible to use Sourcery in our project?

If not, tell me if and how I can help to make this happen :)

**Comment by ilyapuchka** [comment]
Hey @felix91gr . Linux is not supported yet, we have already request for that, it has some tips. Let's use it if you wish to work on that. https://github.com/krzysztofzablocki/Sourcery/issues/306. Also I think this issue https://github.com/krzysztofzablocki/Sourcery/issues/305 will be an important milestone for to support Linux

**Comment by felix91gr** [comment]
Ohh. I’m working on porting SourceKittenDaemon to Linux. In the way, I’ve forked a FileSystemWatcher that we could use.

I’ll set aside some time this summer (I’m in Chile — it’s spring atm). I hope we can port it without too much hassle :)
