### ISSUE TITLE
Is possible to use a template inside another template?

### ISSUE THREAD

**Issue by lucabartoletti** [krzysztofzablocki/Sourcery#436]
I'm testing Sourcery and I really like it.

During my experiments I was trying to automate the following scenario as a test

For each class that adopts a certain protocol, I want to use sorcery to create a `struct B` that has the same property of A and has an init that gets a reference to an instance of A and than populates its property with A's property

My .stencil is:

```
{% for type in types.implementing.AutoStructType %}

// MARK: Struct for {{ type.name }}
public struct {{type.name}}Type {
{% for variable in type.variables %}let {{variable.name}}: {{variable.typeName}}
{% endfor %}
init(from {{type.name | lowerFirst}}: {{type.name}}) {
{% for variable in type.variables %}{{variable.name}} = {{type.name | lowerFirst}}.{{variable.name}}
{% endfor %}
}
}
}
{% endfor %}
```

Is there a way to also make the generate struct adopt other templates (i.e. AutoEquatable and AutoHashable)

**Comment by ilyapuchka** [comment]
@lucabartoletti yes of course, you can use Stencil's own `include` tag for that http://stencil.fuller.li/en/latest/builtins.html#include

**Comment by lucabartoletti** [comment]
Thanks, I think that what I'm trying to achieve is not possible with the current implementation. I pushed   #437
