### ISSUE TITLE
Problem with JSExport.ejs

### ISSUE THREAD

**Issue by alexanderbalaban** [krzysztofzablocki/Sourcery#438]
I use Sourcery binary builded by myself. If I remove this file from "Copy Bundle Resources" stage, everything becomes ok.
Xcode 9.1, Swift 4.0.2 

```
Generating code...
error: Sourcery/Sourcery.app/Contents/Resources/JSExport.ejs: TypeError: JSExport.ejs:3
    1| import JavaScriptCore
    2| 
 >> 3| <%_ for (type of types.implementing.AutoJSExport) { -%>
    4| <%_ if (type.kind != "protocol" && !type.annotations.skipJSExport) { -%>
    5| @objc protocol <%= type.name %>AutoJSExport: JSExport {
    6| <%_ for (variable of type.allVariables) { -%>

undefined is not an object (evaluating 'types.implementing.AutoJSExport')
```

**Comment by ilyapuchka** [comment]
@alexanderbalaban where do you see this? I've just run it myself and it works without errors. Note that Sourcery itself needs Swift 3.2, it will not build with Swift 4.0 without some changes.

**Comment by alexanderbalaban** [comment]
@ilyapuchka looks like a problem with new xcode. 
This is an output from command-line prompt.

**Comment by alexanderbalaban** [comment]
@ilyapuchka JSExport.ejs is a part of Sourcery application. 
```
balaban:sourcery_example alexander.balaban$ ./Sourcery/Sourcery.app/Contents/MacOS/Sourcery --sources . --templates . --output . --verbose
No config file provided or it does not exist. Using command line arguments.
Scanning sources...
Found 6 types.
Loading templates...
Loaded 2 templates.
Generating code...
Rendering template Sourcery/Sourcery.app/Contents/Resources/JSExport.ejs
error: Sourcery/Sourcery.app/Contents/Resources/JSExport.ejs: TypeError: JSExport.ejs:3
    1| import JavaScriptCore
    2| 
 >> 3| <%_ for (type of types.implementing.AutoJSExport) { -%>
    4| <%_ if (type.kind != "protocol" && !type.annotations.skipJSExport) { -%>
    5| @objc protocol <%= type.name %>AutoJSExport: JSExport {
    6| <%_ for (variable of type.allVariables) { -%>

undefined is not an object (evaluating 'types.implementing.AutoJSExport')
```

**Comment by ilyapuchka** [comment]
Do you need this template to your code generation? If not just add it to excluded templates or don't copy it to your templates path. I'll take a look why it fails.

**Comment by alexanderbalaban** [comment]
@ilyapuchka no, I don't need it. Left an issue just to notify about it.  
Thanks!

**Comment by ilyapuchka** [comment]
So for some reason `Proxy` is misbehaving, not proxying calls to undefined keys to custom implementation that should handle this kind of situations (having no types implementing protocol used in template) without errors. As soon as there is at least one type that implements, in this case `AutoJSExport`, it stops failing and generates expected code. Can't provide any workarounds right now so will keep this open for a while and will try to investigate it later (might be related to changes in `Proxy` implementation in JavaScriptCore)

**Comment by ilyapuchka** [comment]
Actually it's not related to proxy, which works fine, its related to some internal implementation details when accessing unknown types. Resolved in the linked PR.
