### ISSUE TITLE
Sourcery generates unwanted files

### ISSUE THREAD

**Issue by maximkhatskevich** [krzysztofzablocki/Sourcery#443]
Sourcery generates unrequested empty files named using standard naming scheme "<TemplateName>.generated.swift" even when these files are empty or not needed at all. Those templates contains custom target file name instructions. The expected files are being generated, but also those empty files are being generated sometime. It only happens sometimes, usually when I'm making changes in those templates and have Sourcery running as daemon (with '--watch' param). Pretty much annoying, so it makes the daemon feature useless.

**Comment by ilyapuchka** [comment]
@maximkhatskevich do you use `prune` flag? 
`--prune [default: false] - Prune empty generated files`

**Comment by maximkhatskevich** [comment]
@ilyapuchka yes, I do. Again, the issue is not about empty files, it's about writing default named files as well as custom named.

**Comment by ilyapuchka** [comment]
Can you provide an example of what files you are expecting to be generated and what you don't expect and what file annotations you use in templates?

**Comment by maximkhatskevich** [comment]
Template file looks like this:

{% for type in types.implementing.ConcurrentProcess %}
// sourcery:file:{{ type.name|replace:".","_" }}_Base.swift
// some Swift code here...
// sourcery:end
{% endfor %}

**Comment by maximkhatskevich** [comment]
The template file is named "MyTemplate.stencil". In a swift file I have a type named "MyType" conforming to 'ConcurrentProcess' protocol. I expect Sourcery to generate only "MyType_Base.swift" file, but it also generates "MyTemplate.generated.swift" file. And same with each template.

**Comment by ilyapuchka** [comment]
When running with watcher with verbose option can you see any error messages in those unneeded generated files?

**Comment by maximkhatskevich** [comment]
@ilyapuchka normally these files only contain data like this:

```
// Generated using Sourcery 0.9.0 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

STATUS:
Generating code...
```

**Comment by maximkhatskevich** [comment]
Same happens with Sourcery runs with "--verbose --prune --watch"

**Comment by maximkhatskevich** [comment]
Also I noticed that any changes in templates (since last time source code has been generated from templates) trigger creation of these unneeded files. After they are created - if I delete these unneeded files, then "undo" any changes that I've just made in the template and save it - the template will be processed normally and only expected file will be updated with recent template, the unneeded files won't be created.

**Comment by maximkhatskevich** [comment]
Of course the above happens only when Sourcery is running as daemon. When run manually - each time it works as expected.

**Comment by ilyapuchka** [comment]
Thanks. Until we find the reason for that I would suggest to add those unneeded files to your `.gitignore`

**Comment by krzysztofzablocki** [comment]
The thing is that when we use Watcher mode and we'd remove those files then your editor might stop seeing them, and I think thats why there is a difference between watcher and regular mode, I vaguely remember I made that choice when I implemented it

**Comment by krzysztofzablocki** [comment]
given you mentioned those files contain status entry, and looking at the source code I can only see this scenario happen if the generation would throw an exception, that exception would then prevent us from rewriting output (which also deals with prunning).

@ilyapuchka that makes sense right? if the stencil file isn't finished and file is saved, it can generate an exception that would prevent prunning phase altogether

**Comment by ilyapuchka** [comment]
@krzysztofzablocki might be, but not so sure. I think a file should not be written to if generation fails, so if it was removed before that on a previous pass it should not be created again in case of exception in a template. What might happen though is that deletion of a file may fail because it is in use by some other process, i.e. editor.

**Comment by Cellane** [comment]
I'm also experiencing this issue when using [this set of templates](https://github.com/nodes-vapor/sourcery-templates) for Vapor. I can't see any error message being thrown in the console but the simple fact that these files are created (and filled with `STATUS: Generating code...`) makes the whole project uncompilable.

For now, I'm using `watch sourcery` as a workaround but I'd appreciate if the `--watch` option behaved in a smarter way, especially if it avoided putting what seems to be status messages into source code files.

**Comment by krzysztofzablocki** [comment]
@ilyapuchka the thing is that status message are written to file separately, and then if generation fails the output phase that does pruning never executes, which is what I think is happening

**Comment by ilyapuchka** [comment]
Maybe we can find a better way to report those statuses? Maybe just in console, printing out what templates changed and what generated files were updated?
