### ISSUE TITLE
How to list all extensions ?

### ISSUE THREAD

**Issue by onmyway133** [krzysztofzablocki/Sourcery#446]
Hi, nice library 👍 . I'm looking for way to list all extensions declared in a certain file, or all extensions on a certain type (like UIView, Int, ...). I want to list extensions made in the project only, not extensions from UIKit or some other standard libraries.

I see https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/Classes/Types.html that there is `extensions` but I don't know how to invoke them. 

![extensions](https://user-images.githubusercontent.com/2284279/33281365-4a461e58-d3a5-11e7-9cd5-46bf86e2f140.png)

**Comment by krzysztofzablocki** [comment]
This should work to list all extensions:

```swift
{% for type in types.extensions %}
  {{ type.name }}
{% endfor %}
```

**Comment by onmyway133** [comment]
@krzysztofzablocki Nice 👍 It works. And how can I list all methods on this extension type (declared in this project only) ?

**Comment by krzysztofzablocki** [comment]
just use the Type docs and iterate same way as above to get all variables / methods

**Comment by onmyway133** [comment]
@krzysztofzablocki It is `allMethods` and `computedVariables`. I begin to like Sourcery. Great stuff 💪
