### ISSUE TITLE
Sourcery doesn't expose subscripts

### ISSUE THREAD

**Issue by dented42** [krzysztofzablocki/Sourcery#447]
Sourcery doesn't seem to give templates a way to look at the subscripts belonging to a protocol (or any other type). This means that when trying to, say, make a type erasing template that generates AnySomething from specially annotated Something protocols, if Something contains a subscript then there's no way to interrogate that information from the template which makes generating anything that complies with that protocol impossible.

**Comment by ilyapuchka** [comment]
@dented42 This may be tricky to implement as we only get parameters information from SourceKit and we will need to somehow understand which parameters belong to which subscript ,as there is again no such grouping in SourceKit response.
