### ISSUE TITLE
Determining the source file and line number of an element

### ISSUE THREAD

**Issue by wildthink** [krzysztofzablocki/Sourcery#454]
Is it possible to access the source file and line number (and possibly the span) of an element identified by sourcery?

For example, I would like to emit the source file and line numbers for identified types and enums in order to build an external index (URL jump table as it were) that an external tool could use to open the original source code and jump to the appropriate line.

Thanks.

**Comment by krzysztofzablocki** [comment]
We don't track that information right now, I'm not sure if its something we want to support. Thoughts on this? @Antondomashnev @ilyapuchka @Liquidsoul @lucabartoletti

**Comment by ilyapuchka** [comment]
It wouldn't be hard to implement, though it seems to me as a bit out of scope, unless we want Sourcery to be a tool not just for code generation but for getting source types information for more generic purposes in a better form than raw SourceKit output.

**Comment by krzysztofzablocki** [comment]
yeah I think the same, I'd rather keep this focused. I'll close this then
