### ISSUE TITLE
Version 0.10.0: Unknown filter 'replace' 

### ISSUE THREAD

**Issue by Lutzifer** [krzysztofzablocki/Sourcery#458]
I can no longer use the replace filter since 0.10.0

Was it removed accidentally?

**Comment by rymcol** [comment]
Same for 'hasPrefix'

**Comment by rymcol** [comment]
If you're affected by this and using `homebrew` you can always `brew switch sourcery 0.9.0` temporarily until there is a fix presuming 0.9.0 was installed previously.

**Comment by Lutzifer** [comment]
I will have a deeper look at that tomorrow

**Comment by krzysztofzablocki** [comment]
@Antondomashnev any idea why that would happen ?

**Comment by Lutzifer** [comment]
it does work, if I call sourcery from Xcode and add the arguments in the scheme, but not if installed via mint or brew

**Comment by Antondomashnev** [comment]
@krzysztofzablocki @Lutzifer not sure what happened. If @Lutzifer will not be able to find a reason I will try to check on the weekend.

**Comment by natanrolnik** [comment]
Same happening here with `contains`. Let me know if there is more info I can provide. Sourcery 0.10.0.

**Comment by Lutzifer** [comment]
Seems to me as if the SwiftPM build is resolving quite an old Version of StencilSwiftKit:

```
Resolving https://github.com/SwiftGen/StencilSwiftKit.git at 1.0.2
```

@Antondomashnev might this be the cause?

**Comment by Antondomashnev** [comment]
@Lutzifer that looks like the source of the problem, yep. I can force update the `0.10.0` with the correct SPM dependencies most likely later tonight.

**Comment by Antondomashnev** [comment]
Update: sorry for the delay, I've been sick past days. Will try to release today.

**Comment by Lutzifer** [comment]
changing the versions as in https://github.com/Lutzifer/Sourcery/tree/fix_versions did it for me.

Also, we should update version to 0.10.1 instead of doing a force update.

**Comment by Antondomashnev** [comment]
@Lutzifer I was planning to do a new version since we have some new things to share already.

**Comment by Antondomashnev** [comment]
The release is done. Could please somebody checks 😄

**Comment by Lutzifer** [comment]
@Antondomashnev works when installed using mint

**Comment by natanrolnik** [comment]
@Antondomashnev I tried updating it via homebrew and 0.10.0 is still the latest version. Was 0.10.1 released?

**Comment by Mazyod** [comment]
I don't think it was fixed for homebrew users. I updated today, and ran into the same problem.

**Comment by jpsim** [comment]
Correct, the homebrew version wasn't updated

**Comment by Antondomashnev** [comment]
Will have a look, thanks for reporting it.

**Comment by Antondomashnev** [comment]
@jpsim @Mazyod the [PR](https://github.com/Homebrew/homebrew-core/pull/21905) in brew has not been merged yet.

**Comment by klundberg** [comment]
PR was merged just a little while ago, thankfully :). Looks like this can be closed

**Comment by Mazyod** [comment]
Still can't seem to make it work:

```sh
if which sourcery >/dev/null; then
  sourcery --version
  sourcery --config sourcery/objc-access.sourcery.yml
else
  echo "warning: Sourcery not installed"
  echo "brew install sourcery"
fi
```

```
0.10.1
Using configuration file at 'sourcery/objc-access.sourcery.yml'. WARNING: Ignoring the parameters passed in the command line.
Scanning sources...
Found 326 types.
Loading templates...
Loaded 1 templates.
Generating code...
error: [...]/sourcery/Templates/ObjCBridge.stencil: Unknown filter 'lowerFirst'
```

**Comment by krzysztofzablocki** [comment]
@Mazyod `lowerFirstWord` or `lowerFirstLetter`, take a look at https://github.com/SwiftGen/StencilSwiftKit

**Comment by Antondomashnev** [comment]
@krzysztofzablocki I think the error @Mazyod once again brought us to the idea in https://github.com/krzysztofzablocki/Sourcery/issues/471.
