### ISSUE TITLE
Argument containing number wrapped in String is treated like number

### ISSUE THREAD

**Issue by slashmo** [krzysztofzablocki/Sourcery#470]
`swift --version`
> Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
> Target: x86_64-apple-macosx10.9

## What did you do?
I use Sourcery to generate a config file containing secret keys such as the Facebook App ID based on arguments passed into the `sourcery` command.
An example of a template for such config file could look like this:
``` swift
public struct Config {
  public let authServiceID: String

  public init(authServiceID: String) {
    self.authServiceID = authServiceID
  }
}

public let config = Config(authServiceID: "{{ argument.authServiceID }}")
```

Now someone could use the following command to generate the Swift file:

```
sourcery --sources . --templates ./templates --args authServiceID="12345314134574513745" --output Sources/SourceryTest/Generated
```

## What did you expect to see?
After running the above command I expect the generated Swift file as follows:
``` swift
public struct Config {
  public let authServiceID: String

  public init(authServiceID: String) {
    self.authServiceID = authServiceID
  }
}

public let config = Config(authServiceID: "12345314134574513745")
```

## What did you see instead?
Instead of `12345314134574513745` the `String` passed in as an argument is treated as a number and produces the following output:

``` swift
public struct Config {
  public let authServiceID: String

  public init(authServiceID: String) {
    self.authServiceID = authServiceID
  }
}

public let config = Config(authServiceID: "1.234531e+19")
```

**Comment by ilyapuchka** [comment]
@slashmo thanks for report.
Try to put single quotes `'` inside double quotes. Should work while we are fixing this.

**Comment by slashmo** [comment]
@ilyapuchka Thanks for the quick response. The trick with the single quotes works indeed. 👍

**Comment by ilyapuchka** [comment]
I think it's not a bug but a detail of `ProcessInfo().arguments`, it removes quotes. So the proper way to pass in strings will be to escape then like this `--args authServiceID=\"12345314134574513745\"`
I'll add this to the guides.
