### ISSUE TITLE
Interpolate environment variables in config

### ISSUE THREAD

**Issue by djbe** [krzysztofzablocki/Sourcery#476]
For a current project, I'd like to point to the generated core data files, which are located in
```.../Library/Developer/Xcode/DerivedData/MyProject-ejmewwsnckjibvevfqzrcrvqxxxv/Build/Intermediates.noindex/My Project.build/Development-iphoneos/My Project.build/DerivedSources```
(or some variation thereof). For now, I can run sourcery via command line `--sources $DERIVED_SOURCES_DIR` parameters, but it'd be nice to do this using a yml config file.

Docker implemented variable substitution in this PR:
https://github.com/docker/compose/pull/1765
It's implemented in Python, but might be a good basis to start from.

**Comment by krzysztofzablocki** [comment]
@djbe I can see how that could be useful for other people, do you want to take a try at implementing that?

**Comment by djbe** [comment]
Sure, I can try to whip something up next week.

I was thinking of keeping it simple, and only supporting `stuff ${STUFF} stuff` syntax (with curly braces). And only interpolate with environment variables, as I don't think there's anything else to interpolate with?

**Comment by krzysztofzablocki** [comment]
works for me, thoughts @Antondomashnev @ilyapuchka @Liquidsoul   ?

**Comment by Antondomashnev** [comment]
Sounds ok for me 👌

**Comment by mylemans** [comment]
Any update on this? I just ran into an issue that this would solve.

**Comment by Lutzifer** [comment]
We (@djbe and me) recently added the possibility to automatically expand environment variables in yml files to swiftgen (https://github.com/SwiftGen/SwiftGen/pull/564)
If this is still of interest for the sourcery project also, I would be willing to start the implementation of that.

For my projects, this would allow me to reuse the yml files across projects.

**Comment by krzysztofzablocki** [comment]
That would be awesome @lutzifer

**Comment by CatalinMustata** [comment]
Hey guys!

This works great if the env variables exist. However, I noticed that if they don't exist, they're not expanded to _nothing_ (as it happens in a shell script) which breaks my use case. Is there a way around this I might have missed?
