### ISSUE TITLE
Improve automockable template to support clousure parameter

### ISSUE THREAD

**Issue by ignazioc** [krzysztofzablocki/Sourcery#479]
I'm using this version of the AutoMockable.stencil
https://raw.githubusercontent.com/krzysztofzablocki/Sourcery/master/Templates/Templates/AutoMockable.stencil

When a protocol contains a method with a clousure parameter like this:

```swift
protocol SampleObjectProtocol: AutoMockable {
    func makeCall(completion: @escaping (String) -> Void)
}
```

The generated code looks like this

```swift
class SampleObjectProtocolMock: SampleObjectProtocol {

    //MARK: - makeCall

    var makeCallCompletionCallsCount = 0
    var makeCallCompletionCalled: Bool {
        return makeCallCompletionCallsCount > 0
    }
    var makeCallCompletionReceivedCompletion: ((String) -> Void)?

    func makeCall(completion: @escaping (String) -> Void) {
        makeCallCompletionCallsCount += 1
        makeCallCompletionReceivedCompletion = completion
    }

}
```

The issue is that the clousure is not executed and the parameters of the clousure cannot be overridden. The solution I have in mind would looks like this

```swift

class SampleObjectProtocolMock: SampleObjectProtocol {

    //MARK: - makeCall

    var makeCallCompletionCallsCount = 0
    var makeCallCompletionCalled: Bool {
        return makeCallCompletionCallsCount > 0
    }
    var makeCallCompletionReceivedCompletion: ((String) -> Void)?

    var makeCallCompletionFirstParameter: String = ""

    func makeCall(completion: @escaping (String) -> Void) {
        makeCallCompletionCallsCount += 1
        makeCallCompletionReceivedCompletion = completion
        completion(makeCallCompletionFirstParameter)
    }

}
```

**Comment by krzysztofzablocki** [comment]
hey @ignazioc, usually you are unit testing that the makeCall was called and with what arguments, calling closure automatically doesn't have a lot of merit if the mock is fully generated. 
Normally you'd just call `makeCallCompletionReceivedCompletion` closure with your arguments ? after mocking if you wanted to have more complex unit tests.

Can you share some example tests you are using?

**Comment by ignazioc** [comment]
The idea behind is similar to what the template already does with functions with a return value.

```swift 
protocol Customer: AutoMockable {
    func fullName() -> String
}


class CustomerMock: Customer {

    //MARK: - fullName

    var fullNameCallsCount = 0
    var fullNameCalled: Bool {
        return fullNameCallsCount > 0
    }
    var fullNameReturnValue: String!

    func fullName() -> String {
        fullNameCallsCount += 1
        return fullNameReturnValue
    }

}
```
being able to set the `fullNameReturnValue ` makes possible to write tests where the `fullName` function returns different values.

A clousure is often uses as an async _return value_ therefore I would like to be able to customize this response.

Let me make one stupid example:
`` `swift
protocol ApiClientProtocol  {
    func login(completion: (Bool) -> void)
}
 

class ObjectToTest {
    var apiClient: ApiClientProtocol
    
    func doLogin() {
        apiClient.login { response in 

        }
    }    
}
```

What I would like to do is to test the `doLogin` method therefor I should mock the `login:` method calling the completion handler once with _`true` and once with `false`

**Comment by ilyapuchka** [comment]
If completion block is stored in mock then can you call it manually after calling your method under test?
I'm afraid trying to automate this scenario will complicate already complex template. At least we will somehow need to distinguish what closure should be called in the mocked method and create variables for all its parameters.

**Comment by krzysztofzablocki** [comment]
I agree, and like I said it's easy to call the received closure by hand. 

If someone needs more complicated mocking there is a project using Sourcery that does build much more powerful mocking API https://github.com/MakeAWishFoundation/SwiftyMocky
