### ISSUE TITLE
Handle tuples as variable types

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#48]
As it's possible to compare tuples of `Equatable` types, but it's not possible to extend tuple types with protocols, we should support them to be able to use them in equatable template. For example it could be used like `{ % if variable.isTuple and variable.tuple.allTypes.implements.AutoEquatable % }`. Also we may support tuple elements names.

**Comment by krzysztofzablocki** [comment]
Good idea 👍

**Comment by krzysztofzablocki** [comment]
I'm going to unassign myself for now as I'm working on few other things, if anyone wants to pick this, just assign it / comment here /cc @ilyapuchka
