### ISSUE TITLE
AutoMockable fails to generate valid code for protocols with associatedTypes

### ISSUE THREAD

**Issue by kdawgwilk** [krzysztofzablocki/Sourcery#481]
I am not sure what the best solution is for generating code in this scenario.  Any ideas how we could handle this?

**Comment by ilyapuchka** [comment]
Yes, we are not parsing associated types information at all at this moment. But it should suffice if you generate all the code that lets compiler to infer this type. In my practice I rarely needed to specify typealias for associated type explicitly. Do you have an example of not working code?
We are parsing typealiases though, but this is not yet documented as we maybe need to add something there to make this API usable (#235)
