### ISSUE TITLE
Method extraction broken for classes

### ISSUE THREAD

**Issue by kaygro** [krzysztofzablocki/Sourcery#485]
There seem to be several problems with parsing of function headers:
- Void isn't always contained in returnTypeName
- returnTypeName only conatins first line  of function declaration if it ends in a multiline where clause

I included an example

swift --version
Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
Target: x86_64-apple-macosx10.9

Input.swift:

`
class SomeClass{
	
	func someFunc<T>(_ xyz: T) where
	 T is Euqatable{
		return x
	}
	
	func someFunc2<T>(_ xzy: T) where T is Equatable{
		return x
	}
	
	func someFunc3(_ xyz: Int){
		return
	}
	
	func someFunc4()->(){
		
	}
	
}
`

template.stencil:

`
//hmm
{% for type in types.all %}
{{ type.kind }} {{ type.name }}{
	{%for method in type.methods%}
	func {{method.name}} returns {{method.returnTypeName}}
	{%endfor%}
}

{% endfor %}
`

expected output :

`
// Generated using Sourcery 0.10.0 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

//hmm
class SomeClass{
	
	func someFunc<T>(_ xyz: T) returns Void where
	 T is Euqatable
	 
 	func someFunc2<T>(_ xzy: T) returns Void where T is Equatable
	
 	func someFunc3(_ xyz: Int) returns Void
	
	func someFunc4() returns ()
}
`
actual ouptput:
`
// Generated using Sourcery 0.10.0 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

//hmm
class SomeClass{
	func someFunc<T>(_ xyz: T) returns where
	func someFunc2<T>(_ xzy: T) returns where T is Equatable{
	func someFunc3(_ xyz: Int) returns {
		return
	func someFunc4() returns ()
}

`

**Comment by ilyapuchka** [comment]
Thanks for reporting this @kaygro. Can you please rephrase issue description to focus more on failing cases?

**Comment by ilyapuchka** [comment]
Also note that Sourcery does not yet have full support for generics, so i.e. they are not supported in methods. That's why first two examples produce unexpected result.

**Comment by kaygro** [comment]
Any suggestions on filtering types, which contain functions with generic constraints?

**Comment by kaygro** [comment]
Just found it, in case someone else wants to know: you can compare shortName and callName, they should differ on such functions.

**Comment by ilyapuchka** [comment]
I've added `isGeneric` property to `Method` for that (#487).

**Comment by ilyapuchka** [comment]
And in fact those results are expected as we parse generic constraints as return type. When we will add more extensive support for generic methods this will most likely change but that's the only way now to generate a correct method override.
Regarding method name not including generic type, this is supported and tested, please check your template.
