### ISSUE TITLE
types.all doesn't include protocols

### ISSUE THREAD

**Issue by kaygro** [krzysztofzablocki/Sourcery#486]
As far as I know, protocols are types in swift,
 but types.all doesn't seem to include them.
I included an example.

swift --version
Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
Target: x86_64-apple-macosx10.9

input.swift:

class SomeClass{}

protocol SomeProtocol{}

template.stencil:
//hmm
{% for type in types.all %}
{{ type.kind }} {{ type.name }}{
	{%for method in type.methods%}
	func {{method.name}} returns {{method.returnTypeName}}
	{%endfor%}
}{% endfor %}

expected output:
// Generated using Sourcery 0.10.0 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

//hmm
class SomeClass{
}

protocol SomeProtocol{
}

actual output:
// Generated using Sourcery 0.10.0 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

//hmm
class SomeClass{
}

**Comment by ilyapuchka** [comment]
This is intended and documented [here](https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/Classes/Types.html#/c:@M@SourceryRuntime@objc(cs)Types(py)all). To get protocols use `types.protocols`
