### ISSUE TITLE
Support sections for annotations

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#49]
Taking as an example `AutoEquatable` protocol it can be tedious to add /// sourcery: skipEquatable for each of the standard library types. Will it be possible to support sections of annotations the same ways as `NS_ASSUME_NONNULL_BEGIN` and `NS_ASSUME_NONNULL_END`, for example like this?

```
// sourcery: skipAnnotations begin

extension String: AutoEquatable {}
extension Int: AutoEquatable {}
...
// sourcery: skipAnnotations end
```

**Comment by krzysztofzablocki** [comment]
I'm going to refactor annotation scanning a bit, should be able to squeeze this in 👍

**Comment by krzysztofzablocki** [comment]
How about this syntax:
```swift
// sourcery:push skipAnnotations, somethingElse = 21

// sourcery:pop
```

which one you'd prefer @khanlou ?

**Comment by khanlou** [comment]
between 
```
// sourcery: skipAnnotations begin
```
and 
```
// sourcery:begin: skipAnnotations, somethingElse = 21
```
i agree that `sourcery:begin` is safer and better in most ways.

not to be a broken record, but maybe we should steal the `push`/`pop` terminology from swiftlint? the more our tools work the same, the better it is for everyone

**Comment by krzysztofzablocki** [comment]
I first had it as push, pop but thought that that would be a very rare case and in #54 I implemented begin /  end, changing it to push pop would be simple though as I'd only need to tweak the variable to be an array of dictionaries and flatten it at the end. @ilyapuchka what do you think? push / pop or begin / end ?

**Comment by khanlou** [comment]
i'm down for begin/end, and it even means a little less state

**Comment by ilyapuchka** [comment]
I think if it will be possible to add additional annotations inside annotations section then we are good. Like this:

```
// sourcery:begin: skipEquality

// some vars

// sourcery: useInEquality
var somevar: SomeType

// the rest
// sourcery:end
```

I guess nested sections are not supported by #54  and that's what you mean by push/pop?

**Comment by krzysztofzablocki** [comment]
no nested section but it ads internal properties like the example you posted
