### ISSUE TITLE
Crash on parse @discardableResult

### ISSUE THREAD

**Issue by CognitiveDisson** [krzysztofzablocki/Sourcery#493]
Hi. I reproduce the flaky crash when parsing a large number of files with `@discardableResult`.
File example:
```
@testable import SomeFramework
import Bla
...
Import Bla2

extension SomeClass1: SomeProtocol {
    @discardableResult
    func defaultModule(routerSeed: RouterSeed)
        -> AssembledModule<UIViewController, Some1ContainerModule>
    {
        return module(
            routerSeed: routerSeed
        ).assembledModule()
    }
}
```
Сrash does not depend on the template, it is reproduced even with empty template. But reproduced through the times with a large number of files ~ 150.

Stack trace
```
Thread 3 Queue : io.pixle.Sourcery.map.4DEADB5D-BEE5-4853-BB0C-E8DB6615D38C.0 (serial)
#0	0x0000000100709f3c in fromSourceKit(_:) at Sourcery/Pods/SourceKittenFramework/Source/SourceKittenFramework/Request.swift:95
#1	0x000000010071722b in Request.send() at Sourcery/Pods/SourceKittenFramework/Source/SourceKittenFramework/Request.swift:374
#2	0x000000010077ad26 in SyntaxMap.init(file:) at Sourcery/Pods/SourceKittenFramework/Source/SourceKittenFramework/SyntaxMap.swift:52
#3	0x0000000100006591 in FileParser.parseTypealiases(from:containingType:processed:) at Sourcery/Sourcery/Parsing/FileParser.swift:817
#4	0x0000000100005202 in FileParser.parse() at Sourcery/Sourcery/Parsing/FileParser.swift:114
#5	0x000000010006007d in Sourcery.loadOrParse(parser:cachesPath:) at Sourcery/Sourcery/Sourcery.swift:304
#6	0x000000010005f8a1 in closure #6 in closure #1 in Sourcery.parse(from:exclude:forceParse:modules:) at Sourcery/Sourcery/Sourcery.swift:262
```
I rewrited the code to understand the reason.
`Request.swift`
```
    public func send() -> [String: SourceKitRepresentable] {
        initializeSourceKit
        let response: sourcekitd_response_t? = sourcekitd_send_request_sync(sourcekitObject)
        defer { sourcekitd_response_dispose(response!) }
        let responseValue = sourcekitd_response_get_value(response!)
        let sourceKitRepresentable = fromSourceKit(responseValue)
        return sourceKitRepresentable as! [String: SourceKitRepresentable] // crash on this line
    }
```
Crash 
> Thread 3: Fatal error: Unexpectedly found nil while unwrapping an Optional value.

Reason:
Method `func  fromSourceKit(_ sourcekitObject: sourcekitd_variant_t)` return nil in case `SOURCEKITD_VARIANT_TYPE_NULL`.

In the 'source' param I saw a line with `@discardableResult`. Removed this line from all files. And everything began to work stably.

**Comment by krzysztofzablocki** [comment]
@CognitiveDisson thats great investigation, could you report this in SourceKitten repo ? as it looks like not sourcery related issue https://github.com/jpsim/SourceKitten

**Comment by CognitiveDisson** [comment]
@krzysztofzablocki Quick response. Yes this is their problem, post it. [link](https://github.com/jpsim/SourceKitten/issues/469)

**Comment by norio-nomura** [comment]
Perhaps a crash occurs in SourceKitten because SourceKit returns an error.
In the next release of SourceKitten, the API will change and we will be able to catch errors without crashing.
https://github.com/jpsim/SourceKitten/pull/447/files#diff-79cf30c35f9909f18dc47be18e24c6afR370

Same function has been provided as `failableSend()` since Sourcekitten-0.10.0, We can use it without waiting for the next release of SourceKitten
https://github.com/jpsim/SourceKitten/blob/0.18.4/Source/SourceKittenFramework/Request.swift#L417

**Comment by norio-nomura** [comment]
Ah, sorry.
Since sourcery does not use `Request.send()` directly, we need the next release of SourceKitten containing the modified `SyntaxMap.init(file:)` that `throws`.
/cc: @jpsim

**Comment by jpsim** [comment]
Since this is actually a SourceKit bug, has anyone reported it to Apple by filing an issue at <https://bugs.swift.org>? I'd happily forward it along to the appropriate team at Apple. /cc @CognitiveDisson
