### ISSUE TITLE
Nonlinear resource allocation

### ISSUE THREAD

**Issue by tamasprezi** [krzysztofzablocki/Sourcery#498]
I'm using Sourcery to generate mocks for my tests and recently I've been experimenting with preprocessing ObjC sources into a Swift header that Sourcery is then able to parse (more about it [here](https://github.com/lvsti/Bridgecraft)). In enterprise-sized projects with a significant share of ObjC in the mixed codebase, this can mean a swift interface file in the ballpark of 500KB - 1MB. I then add this file to the project and have it parsed with the rest of the swift sources of the app target.

What I have noticed is that this huge source file can make Sourcery stall for tens of minutes. Activity Monitor reveals that it's not actually stuck but is working heavily, and during this time memory allocation skyrockets and can reach 12-14GB. 

From the above we could conclude that yeah, large files need a lot of resources. But the surprising fact is that if I split the huge source into two equal parts, the memory high water mark drops to roughly half, while the number of recognized types remain the same. Carefully splitting the files further reduces the memory requirement even more while speeding up the process.

I was looking into [FileParser.swift](https://github.com/krzysztofzablocki/Sourcery/blob/master/Sourcery/Parsing/FileParser.swift) but couldn't wrap my head around the underlying logic. So I'm asking the contributors who are familiar with that part of the code: do you have any explanation for the above behavior? Is it possible to fix it without refactoring the whole thing?

Cheers,
T

--
Sourcery master HEAD (711e95e77e18fc99f181e34bd311b7e7c8d0cc1e as of now)
Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)

**Comment by krzysztofzablocki** [comment]
I think this might be same issue as #420 so if you can confirm that in fact its same part that its mentioned there that raises the memory requirement we can close this as duplicate and move discussion there.

Generally speaking we have 2 parsing phases, `FileParser` deals with separate files and we have a combining phase at the end of all file parsing that joins the type informations together into coherent AST representation.

`FileParser` deals with walking the AST + a lot of custom parsing, there is some recursion involved that might be causing the memory spike

**Comment by tamasprezi** [comment]
Yes it looks pretty much the same, you can mark it as a duplicate.
