### ISSUE TITLE
Compilation performance issue with AutoHashable

### ISSUE THREAD

**Issue by garnett** [krzysztofzablocki/Sourcery#504]
```swift

// Copy-pasted from AutoHashable.
fileprivate func combineHashes(_ hashes: [Int]) -> Int {
	return hashes.reduce(0, combineHashValues)
}

fileprivate func combineHashValues(_ initial: Int, _ other: Int) -> Int {
	#if arch(x86_64) || arch(arm64)
		let magic: UInt = 0x9e3779b97f4a7c15
	#elseif arch(i386) || arch(arm)
		let magic: UInt = 0x9e3779b9
	#endif
	var lhs = UInt(bitPattern: initial)
	let rhs = UInt(bitPattern: other)
	lhs ^= rhs &+ magic &+ (lhs << 6) &+ (lhs >> 2)
	return Int(bitPattern: lhs)
}

// My model
public struct Address {
	public let firstLine: String?
	public let secondLine: String?
	public let postCode: String?
	public let city: String?
	public let country: String?
	public let stateCode: String?

	public init(firstLine: String?, secondLine: String?, postCode: String?, city: String?, country: String?, stateCode: String?) {
		self.firstLine = firstLine
		self.secondLine = secondLine
		self.postCode = postCode
		self.city = city
		self.country = country
		self.stateCode = stateCode
	}
}

extension Address: Equatable {
 	public static func == (lhs: Address, rhs: Address) -> Bool {
		// just a stub implementation
		return true
	}
}


// Offending code
extension Address: Hashable {
	public var hashValue: Int {
		return combineHashes([
			firstLine?.hashValue ?? 0,
			secondLine?.hashValue ?? 0,
			postCode?.hashValue ?? 0,
			city?.hashValue ?? 0,
			country?.hashValue ?? 0,
			stateCode?.hashValue ?? 0,
			0])
	}
}

```

`AutoHashable` generates a code as above. `hashValue` takes eterntity to compile (decided not to wait for exact figures).

```swift
	public var hashValue: Int {
		return combineHashes([
			firstLine?.hashValue ?? 0,
			secondLine?.hashValue ?? 0,
			postCode?.hashValue ?? 0,
			city?.hashValue ?? 0,
                        // commenting out a bit of "complexity"
			//country?.hashValue ?? 0,
			//stateCode?.hashValue ?? 0,
		0])
	}
```

Compile time is back to 20ms if I comment a few of optional short-circuit operators.

I'm aware that it's a swift issue mostly, but I think we could work on another, more verbose version of generated code which does not negatively affect performance.

**Comment by garnett** [comment]
It could be solved with the following addition to the template:
```
private extension Optional where Wrapped: Hashable {
    var innerHashValue: Int {
        return self?.hashValue ?? 0
    }
}
```
which will remove repeatable `??` which is causing the issue.
Please let me know what you think.

**Comment by krzysztofzablocki** [comment]
as long as the end result is the same, given this is simple change I'm all in for faster compilation time

@garnett send a pr? :)

**Comment by garnett** [comment]
Will do 😄

**Comment by ilyapuchka** [comment]
I think #453 addressed this already

**Comment by garnett** [comment]
@ilyapuchka that's a good spot, cheers! I'm still using copy-pasted templates so missed the change. I'll check if it works for me

**Comment by garnett** [comment]
<img width="1390" alt="screen shot 2018-01-30 at 11 13 20" src="https://user-images.githubusercontent.com/829783/35563450-9a55a40a-05ae-11e8-888d-62a33c29aaf9.png">

@ilyapuchka  getting this error by using latest version. Removing `Hashable` fixes the issue.

**Comment by ilyapuchka** [comment]
Are you treating warnings as errors? It is supposed to be just a warning in swift 4, but we better fix that.
@krzystofzablocki should we add ability to check for swift version in templates? Otherwise in such cases templates will need to duplicate a lot of code. I.e. here if template should generate code for swift 3 and 4 it should duplicate all methods because of how ‘#if swift‘ woks

**Comment by garnett** [comment]
@ilyapuchka yes I do. Removing it solves completion times issue, so feel free to close this ticket and open more relevant one if want 

Thanks for rapid response 👍

**Comment by krzysztofzablocki** [comment]
@ilyapuchka but we don't really know the swift version someone will use the generated code on? you can put the ifdef in the template code for the stuff that needs it
