### ISSUE TITLE
Use SPM to build swift templates

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#509]
Currently swift templates are compiled using swiftc, which requires to pass it some non-trivial arguments and perform additional step to properly link SourceryRuntime. Instead we can generate package manifest for each template (or a single manifest with executable for each template) and use SPM to build and run them. This will also let us remove all additional steps and code related to caching as SPM should handle it already. It also will allow to use swift templates with SPM Sourcery installation as it will be possible to add SourceryRuntime as dependency for templates, so SPM will build and link it. With swiftc we can only link to framework (though there might be a way to link SPM-build SourceryRuntime, but it will make users to manually build it). This though might increase build times of templates as it will need to build SourceryRuntime at least once, but as it does not change SPM should be able to cache it after first build.

**Comment by Liquidsoul** [comment]
I've been thinking about doing this for a while. This would potentially open some powerful new features like using library code in Swift templates allowing a nice "plugin" system.
One question we must answer is how we will maintain the version of `SourceryRuntime` contained in the `Package.swift` Swift templates will use?

**Comment by ilyapuchka** [comment]
SourceryRuntime version should be the same as version of sourcery tool.

**Comment by felix91gr** [comment]
Question: can one replace the Swift templates with Stencil ones? Or are there things that are only possible from Swift templates?

**Comment by ilyapuchka** [comment]
The problem with swift templates though is ABI stability, as they now rely on linking framework shipped with Sourcery, so templates and this framework should be compiled with one version of swift.
If you want full power - use EJS, but I think they will work on macOS only, JavaScriptCore does not work on Linux AFAIK

**Comment by felix91gr** [comment]
> so templates and this framework should be compiled with one version of swift.

Ahh, of course. And that's why you'd need to build the SourceryRuntime every time you build a SPM package that uses Swift templates. Right?

**Comment by ilyapuchka** [comment]
Yes, we copy the framework from Sourcery bundle and link it to template executable. But that makes it impossible to use swift templates with SMP installation because SMP builds do not produce dynamic frameworks.

**Comment by ilyapuchka** [comment]
> Ahh, of course. And that's why you'd need to build the SourceryRuntime every time you build a SPM package that uses Swift templates. Right?

we don't actually use SPM to build swift templates, we use `swiftc`

**Comment by felix91gr** [comment]
I see. Yeah, that makes sense.

You'd think that ABI stability is only important for Apple frameworks and such. But no, dynamic frameworks like Sourcery need ABI stability by construction 😄

> Stencil isn't Turing complete.

That makes sense. Hmm. I guess it's a bummer, but I could wait and use Stencil for now until ABI stability enables the rest of Sourcery to be used easily outside of Darwin.

**Comment by art-divin** [comment]
👋🏻  Hi all, 

this issue looks hard enough for me to not understand it. So I might just do this 🦾 Hardest tasks are the most fun ones 🤓 .

I'll update you on this later.

**Comment by krzysztofzablocki** [comment]
We might already be using spm for this @art-divin

**Comment by art-divin** [comment]
@krzysztofzablocki huh, go figure 😓 I wonder, if the topic was something about using SPM to create a package and build that, instead of invoking `swift build -c release` in [SwiftTemplate.swift:249](https://github.com/krzysztofzablocki/Sourcery/blob/ba63cd6b8435e5e0066049eed603386d1a76b368/SourcerySwift/Sources/SwiftTemplate.swift#L238)

**Comment by art-divin** [comment]
In fact, this is already the case. Closing.
