### ISSUE TITLE
Invalid redeclaration of 'report(message:)' at AutoMockable

### ISSUE THREAD

**Issue by albsala** [krzysztofzablocki/Sourcery#510]
It seems something is wrong generating Mocks of extensions with default implementations. AutoMockable test is generating a redeclaration of `report(message:)` for `ExtendableProtocol` at `AutoMockable.generated.swift`. Yet it seems _expected_ ¿? because is exactly what `AutoMockable.expected` contains.
I could try to fix it if I knew what is the expected behaviour.

**Comment by ilyapuchka** [comment]
@albsala can you show a snippet of code that is wrongly generated, what do you expect and what is the input?

**Comment by albsala** [comment]
@ilyapuchka Sure!

This is the protocol defined at `AutoMockable.swift`
```swift
protocol ExtendableProtocol: AutoMockable {
    var canReport: Bool { get }
    func report(message: String)
}
extension ExtendableProtocol {
    var canReport: Bool { return true }

    func report(message: String = "Test") {
        print(message)
    }
}
```

And this is the actual (`AutoMockable.generated.swift`) and expected (`AutoMockable.expected`) generated Mock:
```swift
class ExtendableProtocolMock: ExtendableProtocol {
    var canReport: Bool {
        get { return underlyingCanReport }
        set(value) { underlyingCanReport = value }
    }
    var underlyingCanReport: Bool!

    //MARK: - report

    var reportMessageCallsCount = 0
    var reportMessageCalled: Bool {
        return reportMessageCallsCount > 0
    }
    var reportMessageReceivedMessage: String?

    func report(message: String) {
        reportMessageCallsCount += 1
        reportMessageReceivedMessage = message
    }

    //MARK: - extension_report

    var extensionReportMessageCallsCount = 0
    var extensionReportMessageCalled: Bool {
        return extensionReportMessageCallsCount > 0
    }
    var extensionReportMessageReceivedMessage: String?

    func report(message: String = "Test") {
        extensionReportMessageCallsCount += 1
        extensionReportMessageReceivedMessage = message
    }

}
```

With an _Invalid redeclaration of 'report(message:)'_

**Comment by ilyapuchka** [comment]
It does not seem like invalid redeclaration, it just overrides default implementation defined in extension of the protocol that just prints the message. Not sure if this default implementation is needed, I would expect each mock to have its own implementation of `report` method, but anyway it is valid code.

**Comment by ilyapuchka** [comment]
Ah, sorry, you mean that there are two `report` methods in the mock? I didn't notice that first

**Comment by albsala** [comment]
That's right. Redeclaration and building error.

**Comment by ilyapuchka** [comment]
It is probably just not very good example of test code. What it shows here is that methods with default parameters values do not override methods without default values.

**Comment by ilyapuchka** [comment]
Here is the related issue - https://github.com/krzysztofzablocki/Sourcery/issues/326

**Comment by ilyapuchka** [comment]
Reading this issue and related discussion I see now that the fix should be not to generate mocks for methods defined in extensions - they will be not called as they are not defined in protocol (https://github.com/krzysztofzablocki/Sourcery/issues/158#issuecomment-280935455)
@Antondomashnev do you agree? I didn't use this template so maybe I'm missing a use case when mocks should be defined for methods from extensions.

**Comment by albsala** [comment]
Why exactly will these methods defined in extensions not be called? (I'm sorry but I can't see the sandbox demo since it seems unavailable.)

Let's say this is my protocol (note `newMethod`):

```swift
protocol ExtendableProtocol: AutoMockable {
    var canReport: Bool { get }
    func report(message: String)
}
extension ExtendableProtocol {
    var canReport: Bool { return true }

    func report(message: String = "Test") {
        print(message)
    }

    func newMethod() {
        print("newMethod")
    }
}
```

I'm might be missing something but I'd expect something like this as its Mock:

```swift
class ExtendableProtocolMock: ExtendableProtocol {
    var canReport: Bool {
        get { return underlyingCanReport }
        set(value) { underlyingCanReport = value }
    }
    var underlyingCanReport: Bool!

    //MARK: - report

    var reportMessageCallsCount = 0
    var reportMessageCalled: Bool {
        return reportMessageCallsCount > 0
    }
    var reportMessageReceivedMessage: String?

    func report(message: String = "Test") {
        reportMessageCallsCount += 1
        reportMessageReceivedMessage = message
    }

    //MARK: - newMethod

    var newMethodCallsCount = 0
    var newMethod Called: Bool {
        return newMethod CallsCount > 0
    }

    func newMethod() {
        newMethod CallsCount += 1
    }

}
```

**Comment by ilyapuchka** [comment]
It is related to how method dispatch is implemented in Swift, here is an [article](https://medium.com/ios-os-x-development/swift-protocol-extension-method-dispatch-6a6bf270ba94) that can explain it better. In your example mock implementation of `newMethod` will be only called when called through concrete mock type, not protocol type (and the code that accepts mock uses it through protocol, not concrete type). Same about method `report` with default parameter. Only `report(message:)` will be called as expected on mock. You can check that in a playground.
When defining method with default parameter in extension Sourcery will treat it as a different method (as list of parameters do not match with method defined in protocol), so we can just drop them and only implement methods from protocol. For all new methods from extensions there is no point in mocks.

**Comment by albsala** [comment]
You're right, thank you for the link.
As for the mocking of methods in extensions, you might also be right. Now I can't find any scenario where they might be called.
