### ISSUE TITLE
Calling macro with a parameter invoking a filter crashes

### ISSUE THREAD

**Issue by gushromp** [krzysztofzablocki/Sourcery#515]
So I have a macro
```
{% macro someMacro someParameter %}
```

And when I attempt to invoke it like this:
```
{% call someMacro myType.storedVariables|annotated:"someAnnotation" %}
```
I get this fatal exception:
`Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<SourceryRuntime.Struct 0x7f94a2e1a5a0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key storedVariables|annotated:"json".'`

Calling the macro without the filter on `storedVariables` works just fine:
```
{% call someMacro myType.storedVariables %}
```

Is this considered a bug?

What I'm trying to do is have some sort of "dynamic" for loop which can either loop through `storedVariables` or filtered `storedVariables` based on some condition. Is this possible to do some other way?

**Comment by ilyapuchka** [comment]
Please file this issue in [StencilSwiftKit](https://github.com/SwiftGen/StencilSwiftKit).

**Comment by gushromp** [comment]
I will, thanks for the pointer.

While I'm already here and the issue is closed, can you please help me with my second question (on the bottom)? I don't know where else to ask :)

**Comment by ilyapuchka** [comment]
I don't understand the question clearly. Can you explain your use case?

**Comment by gushromp** [comment]
I want to write a template that loops over either:
a) All stored variables if the type they're contained in is **not** annotated with a certain annotation, or
b) Only those stored variables which are annotated somehow, **if their container type is also annotated**

Example:

```swift

struct MyStruct1 {
    let a
    let b
    let c
}
// the struct is not annotated, so the template for-loop should loop over all stored variables

// sourcery: foo
struct MyStruct2 {
    let a
    // sourcery: bar 
    let b
    // sourcery: bar
    let c
}
// the struct is annotated with `foo`, so the template should only loop over stored variables annotated with `bar`
```

So far the closest I've come to a solution is using a macro which wraps the for loop like this
```
{% macro myMacro param %}
    {% for variable in param %}
    ...
    {% endfor %}
{% endmacro %}
```
 and invoking it with different parameters but that doesn't work because of the way `{% call macroName param %}` is parsed, apparently. 

Any help would be greatly appreciated! :)

**Comment by ilyapuchka** [comment]
You can maybe use `set` node from StencilSwiftKit to workaround `macro` limitation, but it should be just fixed to parse filter expressions, then it will work.

**Comment by gushromp** [comment]
Unfortunately, `set` doesn't seem to do any expression parsing and just uses the plain string value that's put between `{% set var %}` and `{% endset %}`.

Anyway, thanks for the help. I've posted the issue in the StencilSwiftKit repo.

**Comment by ilyapuchka** [comment]
Then it's also a bug for StencilSwiftKit
