### ISSUE TITLE
The type component of member variables doesn't know the the typehierarchy of corresponding swift type.

### ISSUE THREAD

**Issue by kaygro** [krzysztofzablocki/Sourcery#520]
Assume, member is a member variable, whose type implements protocol P.

Then 
{%if member.type.based.P%}
hi
{%endif%}

won't output anything.

**Comment by ilyapuchka** [comment]
Can you provide example of input for such template that does not produce expected result?

**Comment by ilyapuchka** [comment]
Problem is probably that `type` is `nil` in your case, meaning that it is not scanned by Sourcery. This test produces expected result (outputs `implements`):

```swift
// source code
struct MyP: P {}
struct MyStruct {
  let myVar: MyP
}
// template
{% if type.MyStruct.variables.myVar.type.based.P %}implements{% endif %}
```

**Comment by kaygro** [comment]
Sorry for the delay. Here is the example, I had in mind. The problem seems to be that MyP isn't considered to be based on itself. I'm not sure if this is intended.
// source code
protocol MyP {}
struct Implementor: MyP{}
struct MyStruct {
	let impVar: Implementor
	let protVar: MyP
}

class MyClass {
	var impVar: Implementor
	let protvar: MyP
}



// template
{%for type in types.all%}
	{{type.name}}. 
	{%for variable in type.allVariables%}
		{{variable.name}} of type {{variable.type.name}} is 
		{%if variable.type.based.MyP%}
		based on MyP
		{%else%}
		not based on MyP
		{%endif%}
	{%endfor%}
{%endfor%}

// Generated using Sourcery 0.10.1 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT


// template
	Implementor. 
	MyClass. 
		impVar of type Implementor is 
		based on MyP
		protvar of type MyP is 
		not based on MyP
	MyStruct. 
		impVar of type Implementor is 
		based on MyP
		protVar of type MyP is 
		not based on MyP

**Comment by ilyapuchka** [comment]
Yes, type is not considered to be based on itself, it's not the same as `as`, `is`, or `isKindOf`. So you need to check for the type itself too, i.e. check for its name.

**Comment by ilyapuchka** [comment]
I think filter like `isKindOf` that will do both of these check will be welcome
