### ISSUE TITLE
ArrayType elementType?

### ISSUE THREAD

**Issue by drewmclean** [krzysztofzablocki/Sourcery#521]
I am trying to get the elementType from a Variable that is a typed array.  variable.isArray returns true, however: variable.type is nil for some reason.  

public var controls : [Control] = [Control]()

// {{ variable }} output
<Variable: name = controls, typeName = [Control], isComputed = false, isStatic = false, readAccess = public, writeAccess = public, isMutable = true, defaultValue = Optional("[Control]()"), annotations = [:], attributes = [:], isFinal = false, definedInTypeName = Optional(Form), actualDefinedInTypeName = Optional(Form)>

// {{ variable.type }} output
nil

Is there an example of how I can utilize the ArrayType object in sourcery to find the elementType of the array variable?

Thanks,

Andrew

**Comment by ilyapuchka** [comment]
@drewmclean instead of `type` you should use `typeName.array`. `Array` type is defined in standard library which Sourcery does not scan, so does not know anything about it, more [here](https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/writing-templates.html)

**Comment by drewmclean** [comment]
Thanks!
