### ISSUE TITLE
CLI usage is a little tedious due to lack of support for globbing.

### ISSUE THREAD

**Issue by mxcl** [krzysztofzablocki/Sourcery#526]
Since you cannot use a glob, eg:

    sourcery --templates LinuxMain.stencil --sources Tests/A+/*

Doesn’t work since all but one of the sources I specify is treated as arguments. This seems like a common way to use a command line tool to me.

Close if you don’t care, if you care we can talk about it, but it would be a somewhat difficult change to make at this point.

**Comment by ilyapuchka** [comment]
@mxcl do you want all files from `Tests/A+` to be scanned? Then you can just provide it without `*`.

**Comment by mxcl** [comment]
K that'll do me, thanks.
