### ISSUE TITLE
Thin documentation of .swifttemplate format: How to use "string filters"?

### ISSUE THREAD

**Issue by Sajjon** [krzysztofzablocki/Sourcery#528]
Can you help me with how to use string "filters" writing a `.swifttemplate` and not `.stencil`?

I am using `//sourcery:file` command to rename my generated files to contain the type, but when working with nested types, thus containing a dot, Sourcery skips adding ".generated.swift" as per documentation. So I need to use "string filters" to replace the dots in my type name to some other char, maybe "_".

Using `.stencil` templates this can be done like so:
 
```
// sourcery:file:{{ type.name|replace:".","_" }}+NameOfProtocol
...
// sourcery:end
```

But how do I do that using `.swifttemplate`?

```
// sourcery:file:<%= type.name|replace:".","_" %>+NameOfProtocol
...
// sourcery:end
```
Does not work.

I know that I can explicitly use `+NameOfProtocol.generated.swift` to get the extension working, but this is more a question of how to use `|replace` or `|lowercased` etc with `.swifttemplate`.

Sourcery is awesome, and `swifttemplate` are twice as awesome as `.stencil` templates, but Sourcery's documentation about `swifttemplate` is not covering even the basics, unfortunately. 

Apart from a Documentation covering most aspects of `swifttemplate`s it would be great to also have more examples :)

**Comment by ilyapuchka** [comment]
swift templates are just plain swift programs, so you can use standard library or define any custom functions. You just need to wrap it with `<% %>` tags.

**Comment by ilyapuchka** [comment]
You can check [this](https://github.com/krzysztofzablocki/Sourcery/blob/master/Templates/Templates/Decorator.swifttemplate) template for example

**Comment by Sajjon** [comment]
@ilyapuchka thanks! 

Sorry, I just thought that there still would be some macros that we could use for quick mutation of variable names.

I have written some quite powerful templates already but when I wrote them (some months ago) I felt that the documentation was a bit lacking. 

What is the best way of extending some type to some protocol? I used `<% guard enumType.based["AutoCases"] != nil else { continue } -%>` to get all types that conforms to the protocol `AutoCases`, where:
`protocol AutoCases {}` is used on enums to give it `static let count: Int` and `static var all: [Self]`

```swift
<% func generate(_ enumType: Enum, parentCase: EnumCase? = nil) -> String {
    var caseNames = [String]()
    for enumCase in enumType.cases {
        if enumCase.hasAssociatedValue {
            guard
                let associatedValue = enumCase.associatedValues.first,
                case let associatedValueType = associatedValue.type,
                let nestedEnum = associatedValueType as? Enum
            else { caseNames.append("FAIL");continue }
            caseNames.append(generate(nestedEnum, parentCase: enumCase))
        } else {
            if let parent = parentCase {
                caseNames.append(".\(parent.name)(.\(enumCase.name))")
            } else {
                caseNames.append(".\(enumCase.name)")                
            }
        }
    }
    return caseNames.joined(separator: ", ")
} -%>

<% for enumType in types.enums { -%>
<% guard enumType.based["AutoCases"] != nil else { continue } -%>
extension <%= enumType.name %> {
    static let count: Int = <%= enumType.cases.count %>
    static var all: [<%= enumType.name %>] = [<%= generate(enumType) -%>]
}
<% } -%>

```

Is there a better way than writing;
```swift
<% for enumType in types.enums { -%>
<% guard enumType.based["AutoCases"] != nil else { continue } -%>
extension <%= enumType.name %> {
    static let count: Int = <%= enumType.cases.count %>
    static var all: [<%= enumType.name %>] = [<%= generate(enumType) -%>]
}
<% } -%>
```

Because the stencil syntax was quite nice:
`{% for enum in types.implementing.AutoCases|enum %}`

Thanks!

**Comment by ilyapuchka** [comment]
You can still use `where` in `for` loops in Swift, so I would use that. But if it will be removed in future versions of swift, `guard` seems like the only option and I think it's fine and much more familiar to any developer that custom Stencil syntax.

**Comment by Sajjon** [comment]
Great thanks, closing this!
