### ISSUE TITLE
Ruby script for automatically adding generated folder to target

### ISSUE THREAD

**Issue by Sajjon** [krzysztofzablocki/Sourcery#529]
Hi, I do not know if you find this as convenient as I do but when generating many Sourcery files, especially when I use one file per type, it is cumbersome to manually having to add said generated files to the target. So I wrote a small ruby script doing this for me. It is using the gem called [xcodeproj](https://github.com/CocoaPods/Xcodeproj)

The script is based on this by [Kevin Lee](https://github.com/swl367) (I think he was the original author?), but I upgraded it a bit. One important improvement is that I only call `project.save` if there was a change. Because when calling it the xcode project changes and the build gets interrupted.

## Script
```ruby
require 'xcodeproj'

def addfiles(direc, current_group, main_target, changed = false)
      puts "addfiles - `direct`=`#{direc}`, `current_group`=`#{current_group}`, `main_target`=`#{main_target}`"
    Dir.glob(direc) do |item|
      puts "addfiles - `item`=`#{item}`"
        next puts "Next because `.` or `.DS_Store`" if item == '.' or item == '.DS_Store'
        next puts "Next because file (`#{File.basename(item)}`) was in `current_group.children` (#{current_group})" if current_group.children.map { |f| f.name }.include? File.basename(item)
        if File.directory?(item)
            new_folder = File.basename(item)
            created_group = current_group.new_group(new_folder)
            changed = addfiles("#{item}/*", created_group, main_target, changed)
        else 
          i = current_group.new_file(item)
          if item.include? ".swift"
              main_target.add_file_references([i])
              changed = true
          end
        end
    end
    return changed
end

def add_group_to_project(project_path, name_of_generated_folder)
	project = Xcodeproj::Project.open(project_path)

	generated_group = project.main_group[name_of_generated_folder]
	unless generated_group
  	generated_group = project.main_group.new_group(name_of_generated_folder)
	end

	main_target = project.targets.first
	added_new_files = addfiles("#{name_of_generated_folder}/*", generated_group, main_target)

	if added_new_files
             project.save
        end
end

project_path = ENV["PROJECT_FILE_PATH"]
puts "`project_path`=`#{project_path}`"
add_group_to_project(project_path, 'Generated')
```

## Calling script from Xcode Build Phase
I use [rbenv](https://github.com/rbenv/rbenv) for sudo-less ruby, so I can call this script in a Build Phase put AFTER the Sourcery build phase in Xcode like this:

```bash
export PATH=~/.rbenv/shims:$PATH
ruby ../../scripts/add_generated_models_to_target.rb
```
(with *"Shell"* value set to `/bin/sh`) in the Build Phase.

Maybe you can add this for any one else to use?

**Comment by ilyapuchka** [comment]
Actually this will be supported by Sourcery with next release, it was implemented in  https://github.com/krzysztofzablocki/Sourcery/pull/514
But thanks anyway, maybe some users will find it easier to use or more extensible than doing it via configuration

**Comment by Sajjon** [comment]
Haha wow that's awesome! 

I actually the same script for [ModelGen](https://github.com/hebertialmeida/ModelGen) and [SwiftGen](https://github.com/SwiftGen/SwiftGen) too, so I can have the same script in root of my project dir and just use the same script for adding all generated files, if all files are in the same folder named "Generated", but great to have it "natve" via Sourcery!
