### ISSUE TITLE
Version reported by --version flag does not match release and tag version

### ISSUE THREAD

**Issue by guidomb** [krzysztofzablocki/Sourcery#532]
Running `swiftlint --version` for binaries attached to releases [0.10.1](https://github.com/krzysztofzablocki/Sourcery/releases/tag/0.10.1) and [0.10.0](https://github.com/krzysztofzablocki/Sourcery/releases/tag/0.10.0) don't match expected version number. 

The following screenshots shows this problem.
<img width="1440" alt="screen shot 2018-02-24 at 7 36 02 pm" src="https://user-images.githubusercontent.com/390645/36674128-f26dbbf6-1ae3-11e8-80c7-2ae8d70bd96f.png">

**Comment by ilyapuchka** [comment]
Probably it's just something wrong with release script. I noticed the same when switching from cocoapods to homebrew installation. But other than incorrect version everything else is fine.

**Comment by ilyapuchka** [comment]
Shouldn't be an issue any more with 0.11.x releases

**Comment by guidomb** [comment]
I can confirm this is no longer an issue. Thanks!
