### ISSUE TITLE
Convenient verify using AutoMockable

### ISSUE THREAD

**Issue by ssuhanov** [krzysztofzablocki/Sourcery#533]
I use AutoMockable in my iOS projects. And it would be great to write something like this:
```
verify(myMock).mockMethod()
    .mockParameter1(equalsTo: correctValue1)
    .mockParameter2(is: SomeType.self)
```

instead this:
```
XCTAssertTrue(myMock.mockMethodCalled, "mockMethod should be called")
XCTAssertEqual(myMock.mockMethodReceivedArguments?.mockParameter1, correctValue1, "mockParameter1 should be \(correctValue1)")
XCTAssertTrue(myMock.mockMethodReceivedArguments?.mockParameter2 is SomeType, "mockParameter2 should be of \(SomeType.self) type")
```

I have improved the AutoMockable template, and if you want - I can create pull-request with this improvements.

**Comment by ilyapuchka** [comment]
Thanks for the suggestion @ssuhanov! This definitely looks as a better API to me, but can be a matter of developer own preferences and might vary depending on what testing framework is used. Wouldn't it be possible to achieve the same without changing templates (which only generate mocks and not asserts) but by using separate helper methods which will wrap those asserts?

**Comment by ssuhanov** [comment]
@ilyapuchka You're right. I can move this functionality to the separate template (for example AutoVerifyable) and do not touch AutoMockable. :)

**Comment by krzysztofzablocki** [comment]
Also there is https://github.com/MakeAWishFoundation/SwiftyMocky that builds a more advanced mocking system
