### ISSUE TITLE
`containedTypes` is empty if they're defined within an extension

### ISSUE THREAD

**Issue by allenhumphreys** [krzysztofzablocki/Sourcery#534]
Version 0.10.0 installed via cocoapods.

Template:
```
{% for type in types.all where type.name == "MyContainerType" %}

extension {{ type.name }} {

    {% for subtype in type.containedTypes %}
      /* {{ subtype.name }} */
    {% endfor %}
}
{% endfor %}
```

Failing code:
```
struct MyContainerType {

}

extension MyContainerType {

    enum ContainedType {
        case none
    }
}
```

Expected output:
```
extension MyContainerType {

      /* MyContainerType.ContainedType */
}
```

Actual output:
```
extension MyContainerType {

}
```

The extension and the container type are defined in the same file. Is this expected behavior?

**Comment by ilyapuchka** [comment]
I think you should check just for "ContainedType" as a type name, not it's full name. Otherwise you need to use `globalName`

**Comment by allenhumphreys** [comment]
@ilyapuchka The problem definitely isn't with the comparison, I've updated my original examples to eliminate the filtering and make it more clear.

**Comment by ilyapuchka** [comment]
I see. 432f9fb683da20373f9f0cf991b19a315a4ffcba should fix it.
