### ISSUE TITLE
Something is wrong with escaped type names parsing

### ISSUE THREAD

**Issue by garnett** [krzysztofzablocki/Sourcery#536]
I'm using Sourcery 10.1 (but it seems to be reproducible with head version too).

```swift
protocol AutoHashable {}
protocol AutoEquatable {}

public struct Model: AutoEquatable, AutoHashable {
    public enum `Type` {
        case foo
    }

    public let type: `Type`
}

extension Model.`Type`: AutoEquatable, AutoHashable {
    public init?(rawValue: String) { self = .foo }
    public var rawValue: String { return "" }
}
```

Generated code is not compilable as "Type" is not fully escaped. Also, `var hashValue` is not public as the rest of the code.

```swift
extension Model: Hashable {
 // everything is fine here
}
// MARK: - Model.`Type AutoHashable
extension Model.`Type: Hashable {
     var hashValue: Int {

        return combineHashes([
            0])
    }
}
```

Same happens in `AutoEquatable`. codel

If I replace Type with MyType  and remove backticks everything is fine.

I don't have full knowledge of how Sourcery works under the hood, but it may go as deep as SourceKit:
<img width="536" alt="screen shot 2018-03-08 at 11 11 05" src="https://user-images.githubusercontent.com/829783/37148207-7cbc7358-22c1-11e8-8073-d58a9d6ee517.png">
Xcode itself fails to provide proper highlighting (but it compiles).

**Comment by ilyapuchka** [comment]
Strange, when I run this code through I got name `Model.Type` without back ticks

**Comment by ilyapuchka** [comment]
It's weird, I tracked it down to this pr https://github.com/krzysztofzablocki/Sourcery/pull/169 but can't remember why I did it and even it's name is opposite to what is done 😅
So I'll revert it, with it type names will not be escaped, so `type.name` should be correct.

**Comment by garnett** [comment]
It's wierd, I'm using 0.11 version and still having the issue. here is the diff ("correct" part of the diff was added manually so code is compilable, green part of the diff is output of Sourcery):

<img width="468" alt="screen shot 2018-04-04 at 12 25 21" src="https://user-images.githubusercontent.com/829783/38305019-3e28dcce-3803-11e8-8cc2-f51e264ceae3.png">

**Comment by garnett** [comment]
Sorry for screenshots instead of the code, I'll follow up later with minimal reproducible case.

I managed to generate "better" output by moving stuff from extension to declaration:
<img width="626" alt="screen shot 2018-04-04 at 12 34 41" src="https://user-images.githubusercontent.com/829783/38305368-978f6caa-3804-11e8-92e4-e52512e8550d.png">
