### ISSUE TITLE
Deconstruct types composition

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#541]
When using markers like `typealias AutoCodable = AutoDecodable & AutoEncodable`, type that implements `AutoCodable` should also contain `AutoDecodable` and `AutoEncodable` in its `based` and `implements` collections. Currently it only contains `AutoCodable`.

**Comment by ilyapuchka** [comment]
This will be more challenging for property types, i.e. `view: UIView & NibLoadable`. We can store only one type for the property, currently we will not even infer it as type name is `UIView & NibLoadable` which composer will not match with anything. We can always use first component as a type as it can be only concrete type or protocol and the rest of components add up to `implements and `based` collections. But we probably also should add up variables and methods defined in the trailing protocols. Not sure what strategy to use though when there are the same properties or methods defined in the first type, maybe we should just use first of them (I think Swift in this case can raise ambiguity error or it will determine what version of method to use depending of the type through which it is called)
@krzysztofzablocki @Antondomashnev thoughts?

**Comment by ilyapuchka** [comment]
What we can do is to create a special kind of type `class TypeComposition: Type` with additional properties for composed types. This way we can use it as a properties' type as usual and will be able to aggregate composed type information easily. This should be done probably in `Composer` as a step of property (same for methods' types, etc.) types resolution. If types composition is used for protocol conformance, like in `AutoCodable` example, we can break it down into individual types earlier in `FileParser` and then resolve them in `Composer`. `Composer` should also resolve types in `inherited`, `based` and `implements` collections as typealiases can be used there too.

**Comment by krzysztofzablocki** [comment]
@ilyapuchka that seems like a reasonable plan and I don't really have a better idea right now that would deal with this
