### ISSUE TITLE
Add `--exclude-sources` and `--exclude-templates` to CLI

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#547]

**Comment by borisoft** [comment]
#!/bin/bash
./Pods/Sourcery/bin/sourcery --sources ./Domain  --templates SourceryTemplates/Generation.stencil --disableCache --verbose --output ./  --exclude-sources ./Pods


not work ((

**Comment by ilyapuchka** [comment]
🤷‍♂️ 
@borisoft

**Comment by StevenTso** [comment]
move exclude-sources closer to the front:

#!/bin/bash
./Pods/Sourcery/bin/sourcery --sources ./Domain  ./ --exclude-sources ./Pods --templates SourceryTemplates/Generation.stencil --disableCache --verbose --output
