### ISSUE TITLE
Provide generic data for type declaration

### ISSUE THREAD

**Issue by Nonchalant** [krzysztofzablocki/Sourcery#551]
### Environment

sourcery: https://github.com/krzysztofzablocki/Sourcery/commit/cef1a4df0628e5c5356af1dff697b3a2f2f741d2 (master)
swift: 4.0.3

### Input Swift

```swift
struct Result<T: Equatable> {
    let success: T
    let failure: Error
}
```

### Stencil

```
{% for type in types.all %}
// I would like to get generics from type (T: Equatable)
{% endfor %}
```

**I want to know how to get generics info from type** 🙇‍♀️ 

https://github.com/krzysztofzablocki/Sourcery/blob/master/SourceryRuntime/Sources/Type.swift 
It seems to have no generics info... 😭

**Comment by ilyapuchka** [comment]
For now only support generics in variable types via `variable.typeName.generic`. We should add this to types too, but for now you can only check if type is generic or not. You can maybe use annotations as a workaround.

**Comment by Nonchalant** [comment]
@ilyapuchka 
Thank you for reply. I looking forward to support! 🚀 
Until then, I use annotations.

**Comment by truizlop** [comment]
Are there any news about this issue? I'd like to be able to retrieve generic data for type declarations as well. If there is a need for contributors, I can try to implement this myself, but I'd probably need some guidance.
