### ISSUE TITLE
How to get global typealiases

### ISSUE THREAD

**Issue by Nonchalant** [krzysztofzablocki/Sourcery#552]
### Environment

sourcery: https://github.com/krzysztofzablocki/Sourcery/commit/cef1a4df0628e5c5356af1dff697b3a2f2f741d2 (master)
swift: 4.0.3

### Input Swift

```swift
struct Result {
    typealias Value = Int

    let success: Value
    let failure: Error
}

typealias GlobalValue = Int
```

### Stencil

```
{% for type in types.all %}
{{ type.typealiases }} // enable to get Value
{% endfor %}
```

I cannot get **GloabalValue** info. I want to know how to get global typealias info 🙇‍♀️

**Comment by ilyapuchka** [comment]
It's not yet supported, sorry.
