### ISSUE TITLE
Is it possible to iterate over types with same value of annotation?

### ISSUE THREAD

**Issue by gushromp** [krzysztofzablocki/Sourcery#553]
Hi.

I am annotating my types with `someAnnotation` (which has string values).
I want to iterate over all types whose `someAnnotation`'s value is the same string.

Is this possible? Thanks!

EDIT: To further clarify, I mean iterate over all types annotated by `someAnnotation`, but somehow group them by annotation value.

I figured that if I can somehow create an array of distinct annotation values, I could loop over that array and then loop over all types whose value of this annotation is the same, like so:

```
// somehow make an array of distinct values of `someAnnotation` and call it `distinctAnnotationValues`

{% for annotationValue in distinctAnnotationValues %}
{% for type in types.all.annotations.someAnnotation where type.annotations.someAnnotation == annotationValue %}
...
{% endfor %}
{% endfor %}
```

This could work in theory, the trouble is I don't know how I'd make that helper set/array of distinct annotation values and loop over it - if it's even possible to do.

**Comment by ilyapuchka** [comment]
I'm afraid there is no good way to do that with Stencil unless you implement a custom filter that will group values based on a predicate. You can submit such filter to StencilSwiftKit.
