### ISSUE TITLE
Counting Optionals?

### ISSUE THREAD

**Issue by infiniteNIL** [krzysztofzablocki/Sourcery#555]
I'm trying to count the optional variables in a struct so I can add a comment to disable a swift lint warning (cyclomatic complexity) if there are more than 10 optionals. Is there a way to count all the optionals and store it in a variable and then use that variable later as a conditional in an if.

**Comment by krzysztofzablocki** [comment]
depending on the template language, in Swift template its trivial as its regular code so you can do whatever, in Stencil you'd need to use filter chaining, I don't think we have a filter for getting optional values though so you'd need to make a PR with that if you want

**Comment by ilyapuchka** [comment]
In Stencil this will be possible with `filterEach` filter added here https://github.com/kylef/Stencil/pull/189 but first it needs to be merged of course.
Code will look like `type.instanceVariables|filterEach:"$0.isOptional"|count`
For now the only way to do it is hack around for loop:

```
{% set optionalsCount %}
{% for variables in type.instanceVariables where variable.isOptional %}
{% if forloop.last %}{{ forloop.counter }}{% endif %}
{% endfor %}
{% endset %}
```

This should only set `optionalsCount` to the number of optional properties if there are any. This value will be a string so you'll need to compare it to string, not with numbers.
Should work but I didn't test it. Hope this helps.
