### ISSUE TITLE
Sourcery source compatibility

### ISSUE THREAD

**Issue by krzysztofzablocki** [krzysztofzablocki/Sourcery#568]
I'm adding this here in case anyone has time to fix it before I'll do (I won't get to it before tuesday), /cc @Antondomashnev @ilyapuchka 

This email is to notify you about a recent pull request (https://github.com/apple/swift-source-compat-suite/pull/170) which XFAILs the Sourcery project due to https://bugs.swift.org/browse/SR-7273.

The current Sourcery 4.0 hash includes code that was previously allowed, but has been disallowed by an update to Swift. To resolve this, we are requesting a new hash from Sourcery for 4.0 compatibility. Details about the disallowed code can be found here: https://bugs.swift.org/browse/SR-7233 (Note this bug was filed for a different project, but for similar disallowed code.)

To add a new hash, find the “compatibility” field associated with your project in projects.json (example below):

   "compatibility": [
     {
        "version": "4.0",
        "commit": "3041ba7ed84138f13e7973d34973dce2b10259be"
     }
   ]

Check that the new project hash builds against Swift 4.0:

$ ./project_precommit_check project-path-field --earliest-compatible-swift-version 4.0

If the check succeeds, please open a PR against https://github.com/apple/swift-source-compat-suite containing the new hash.

**Comment by ilyapuchka** [comment]
FYI there are no apparent issues when compiling with Swift 4.1 in #571 branch

**Comment by ilyapuchka** [comment]
Strangely enough I saw the `Bus error: 10` during release when running command line build made with  Sourcery-Release scheme.

**Comment by krzysztofzablocki** [comment]
@ilyapuchka I think we just need to update dependencies especially SourceKitten ?

**Comment by ilyapuchka** [comment]
I did that not long time ago, it should be 0.19 version, but maybe there is some new release already.

**Comment by ilyapuchka** [comment]
Yes, we have this version noew

**Comment by krzysztofzablocki** [comment]
@ilyapuchka did you send the PR to compact suite? I think this should work now right?

**Comment by ilyapuchka** [comment]
@krzysztofzablocki no, didn't have time to figure out what is needed, but things seem to work now normally after breaking changes were fixed.
