### ISSUE TITLE
How to judge either or not contain about String

### ISSUE THREAD

**Issue by Nonchalant** [krzysztofzablocki/Sourcery#576]
```
{% for protocol in types.protocols where protocol.name.contain("Hoge") %}
    ...
{% endfor %}
```

I would like to get protocols that name contains "Hoge".
But, I don't know how to. Please show me 🙇‍♀️

**Comment by ilyapuchka** [comment]
There is `contains` filter in https://github.com/SwiftGen/StencilSwiftKit, you should use it. And please refer to Stencil docs to see how filters are applied.

**Comment by Nonchalant** [comment]
@ilyapuchka Thank you 🙇‍♀️
