### ISSUE TITLE
DispatchOverlayShims.h issue with Sourcery 0.11.0

### ISSUE THREAD

**Issue by chrisballinger** [krzysztofzablocki/Sourcery#584]
> ❌  error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/shims/DispatchOverlayShims.h:185:20: error: implicit conversion of C pointer type 'dispatch_data_t _Nonnull' (aka 'struct dispatch_data_s *') to Objective-C pointer type '__swift_shims_dispatch_data_t _Nonnull' (aka 'id') requires a bridged cast

I've tried with both Xcode 9.2 and Xcode 9.3. Reverting to Sourcery 0.10.1 fixes the issue.

**Comment by chrisballinger** [comment]
Should probably mention it's integrated via CocoaPods and an Xcode script build phase:

```bash
if [ -x "$PODS_ROOT/Sourcery/bin/sourcery" ]; then
"$PODS_ROOT/Sourcery/bin/sourcery" --sources "PRODUCTNAME" --templates "PRODUCTNAME/Resources/Sourcery/actionable.swifttemplate" --output "PRODUCTNAME/Resources/Generated/Actionable+AutoConformance.swift"
fi
```

**Comment by ilyapuchka** [comment]
Seriously no idea what that is. Just tried to integrate 0.11 Sourcery in its templates tests via CocoaPods  and all seems fine in Xcode 9.2 and in 9.3, also with swift templates.

**Comment by jinthagerman** [comment]
I am also seeing this in Xcode 9.2 and Sourcery 0.11.

If I run from command line, it works and subsequent runs from Xcode work for awhile.

**Comment by buscarini** [comment]
I'm also seeing this when Sourcery is integrated with CocoaPods. If I use the system one installed with homebrew it works.

**Comment by ilyapuchka** [comment]
Yes, now I see the same issue with swift templates

**Comment by ilyapuchka** [comment]
But I only see that if there is an error in template. There were some breaking changes in types collections, this can cause this issue. Please try to check if you have those and if yes then try to fix them. You can also try to create some simple template to see if it works at all - works for me.

- Type collections `types.based`, `types.implementing` and `types.inheriting` now return non-optional array. If no types found, empty array will be returned. 
This is a breaking change for template code like this:

 ```swift
<% for type in (types.implementing["SomeProtocol"] ?? []) { %>
```

 The new correct syntax would be:

 ```swift
<% for type in types.implementing["SomeProtocol"] { %>
```

**Comment by chrisballinger** [comment]
I can confirm that the 0.11.0 release on CocoaPods has this issue, but the 0.11.0 release using homebrew does not.

**Comment by ilyapuchka** [comment]
Can you provide example that demonstrates the issue?

**Comment by ilyapuchka** [comment]
I think this can be also caused by different versions of dependencies used for different package managers.

**Comment by chrisballinger** [comment]
@ilyapuchka Here is a sample repository demonstrating the issue with 0.11.0 integrated via CocoaPods. It works if you change the Sourcery script phase to use `/usr/local/bin/sourcery` using Homebrew 0.11.0, instead of the PODS_ROOT version. Rolling back to 0.10.1 also works. Note that it only compiles with Xcode 9.2.

* Repo: https://github.com/Raizlabs/ios-template-output/tree/1cf8ae9ab2d94c9715478c2f91a28841c20db6df
* CircleCI output: https://circleci.com/gh/Raizlabs/ios-template-output/8

**Comment by ilyapuchka** [comment]
@chrisballinger Homebrew uses SPM to build, so swift templates are not available there, that's why it's not crashing.

**Comment by chrisballinger** [comment]
Ahh okay thanks!

**Comment by ilyapuchka** [comment]
@chrisballinger please check this with 0.11.2
