### ISSUE TITLE
Vague acronym in docs

### ISSUE THREAD

**Issue by getaaron** [krzysztofzablocki/Sourcery#590]
From the [`Equatable` docs](https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/equatable.html):

> It adds `:Equatable` conformance to all types, except protocols (because it would require turning them into PAT’s)

What does PAT stand for? We should either add a link or expand the acronym to improve clarity.

**Comment by ilyapuchka** [comment]
Protocol with Associated Type
