### ISSUE TITLE
Regression in 0.12 with attributes

### ISSUE THREAD

**Issue by kdawgwilk** [krzysztofzablocki/Sourcery#596]
Using the SwiftyMocky `Mock.swifttemplate` with `0.12` on a protocol with functions using `@discardableResult` attributes yields this code:
![screen shot 2018-04-11 at 3 49 49 pm](https://user-images.githubusercontent.com/7799267/38707467-b10f097c-3e6e-11e8-99a6-e0c558047be8.png)
 Before this release the code generated did not have these problems so it appears to be a regression.

**Comment by ilyapuchka** [comment]
@kdawgwilk  Please provide piece of code of template and the piece of source code that results in faulty output. Please don't post the whole code and the whole template, it will not help.

**Comment by kdawgwilk** [comment]
Well I tried to narrow this down to an easy reproducible zip of just the template and source files but the issue does not show up in a simplified case so I will just close this out

**Comment by kdawgwilk** [comment]
Ah looks like I couldn't reproduce this because I was only using one method in my example and I needed a method following the the first one with an attribute.  Thanks for the fix! 👍
