### ISSUE TITLE
Better resilience for swifttemplates when Xcode is updated

### ISSUE THREAD

**Issue by kdawgwilk** [krzysztofzablocki/Sourcery#597]
I wanted to create this issue to discuss possible way to make Sourcery more resilient to breakages when Xcode is upgraded.  It seems the main issue is for those using CocoaPods because it is distributed with pre-built binaries that the Swift template is linked to when it is built such as `SourceryRuntime` that is tied to a specific version of Swift.  Would it be possible to compile those runtime binaries on the fly and cache them so that when a new version of Swift comes around with Xcode those can just be rebuilt?

**Comment by ilyapuchka** [comment]
The main problem this time is not ABI incompatibility but breaking changes in SourceKitten, for which there is no workaround.
#509 may help with that as we will be able to build runtime lib once and link it with each template instead of compiling it for each template.

**Comment by ilyapuchka** [comment]
Will close it in favour of issue about SPM, but if you have any other ideas PR will be welcome @kdawgwilk
