### ISSUE TITLE
Add reflection to types to know when they are generic

### ISSUE THREAD

**Issue by krzysztofzablocki** [krzysztofzablocki/Sourcery#6]
We need to add ability to recognize generic types, as often we want to avoid those when doing code generation. 

E.g. we'll want to skip `allValues` generation for Enums that are generic.

**Comment by krzysztofzablocki** [comment]
@ilyapuchka I started working on this and wondering whether we should treat the generic part as part of type name or introduce another variable for that component? e.g. `Foo<Element: Equatable>` would you put whole thing as name or just Foo and then add another `var for Element: Equatable`?

Or maybe for now we should just limit generic support to being able to check whether type `isGeneric`, and that will suffice for most needs?

**Comment by ilyapuchka** [comment]
I would say that for now we can have just `isGeneric`. Because how should we handle (if we should at all) generics with complex constraints with `where` and so one?

**Comment by krzysztofzablocki** [comment]
yeah that's my thoughts, I'm not even sure if code-generation in general should even go so far as to try to deal with this, it feels too error prone, I'm going to add `isGeneric` tomorrow so that people can skip those classes ;)
