### ISSUE TITLE
Auto inlining does not adjust offset to inline code after inlining in the same file

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#601]
If template tries to auto inline code in the same file all inlined code after the first auto-inlining is inserted in a wrong position. We need to adjust offset based on the length of the text inserted before.

**Comment by Liquidsoul** [comment]
Do you have some more context on this? Because I thought we've addressed that in the past 🤔 
Does this happen when different "auto-inlining" templates work on the same file?
Because the "same template" case should be covered by our tests.

**Comment by tulushev** [comment]
This also happens with regular inlining, if inlining from multiple templates in the same file.

**Comment by art-divin** [comment]
Minimal Reproducible:

```swift
Input.swift
protocol Action {

}
protocol CompletableAction: Action {

}
class GetProvincesAction: Action {
}
class GetProvincesCompleteAction: CompletableAction {
}
class GetPersonalDataCompleteAction: CompletableAction {
}
```


```
Template.stencil
{% for type in types.all where type.name|lowercase|!contains:"test" and type.implements.Action or type.implements.CompletableAction or type.implements.EmptyAction %}

    // sourcery:inline:auto:{{ type.name }}.AutoEquatableAction
    func someImportantFuncRequiredByTheProtocol() {
    }
   // sourcery:end
{% endfor %}
```

```swift
Output:
protocol Action {

}
protocol CompletableAction: Action {

}
class GetProvincesAction: Action {

// sourcery:inline:auto:GetProvincesAction.AutoEquatableAction
    func someImportantFuncRequiredByTheProtocol() {
    }
// sourcery:end
}
class GetProvincesCompleteAction: CompletableAction {

// sourcery:inline:auto:GetProvincesCompleteAction.AutoEquatableAction
    func someImportantFuncRequiredByTheProtocol() {
    }
// sourcery:end
}
class GetPersonalDataCompleteAction: Completable
// sourcery:inline:auto:GetPersonalDataCompleteAction.AutoEquatableAction
    func someImportantFuncRequiredByTheProtocol() {
    }
// sourcery:end
Action {
}
```

As can be seen, the last insertion cut out `Action` from `Completable` and inserted the function before `{` bracket.

**Comment by krzysztofzablocki** [comment]
that's odd, this should work by just doing inlining in reverse order of the position, if we inject from the end of the file towards the start we shouldn't need to adjust any offsets, I felt that worked before 😕

**Comment by art-divin** [comment]
Now that I have re-tried, cannot reproduce what I was able to before, even on older commits. 
Yet another of those "weird" ones I suppose, I'll keep it in mind.
