### ISSUE TITLE
Unwanted empty auto generated file

### ISSUE THREAD

**Issue by rob-nash** [krzysztofzablocki/Sourcery#607]
As suggested by discussion in #45 

: **Quote** :
Ok, just to confirm something

I use the inline approach for all of the generated code in my project.

The following file demands I have an output key.

while reading .yml 'some/path/.sourcery.yml'. 'Invalid output. 'output' key is missing or is not a string or object.'
The presence of an output key in the following file seems to generate an empty file called someName.generated.swift

```
sources:
  - some/path
templates:
  - some/path
output:
  ./
```

There is currently no option to stop this file from being generated, right?

It's not the end of the world as I can just exclude it from compile sources & git. 
: **EndQuote** : 

I have appended a reproducible example.

```
$ brew info sourcery
sourcery: stable 0.11.2 (bottled), HEAD
https://github.com/krzysztofzablocki/Sourcery
Poured from bottle on 2018-04-24 at 16:07:47
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/sourcery.rb
```

[Test.zip](https://github.com/krzysztofzablocki/Sourcery/files/1946353/Test.zip)

**Comment by ilyapuchka** [comment]
You should put `// MARK` comment inside inline block so that it is inlined with the rest of generated code, then AutoEquatable.generated.swift will be removed.
