### ISSUE TITLE
Sharing macros across stencil files?

### ISSUE THREAD

**Issue by macduy** [krzysztofzablocki/Sourcery#610]
I have a useful macro I would like to use across two stencil files. I tried putting the macro in a separate stencil file and `{% import %}`ing it into the other one but that does not work and results in 

```
Call to undefined block 'X'
```

Is this feature supported?

**Comment by ilyapuchka** [comment]
Hey @macduy . I don't think it is supported unfortunately, Stencil does not have `import` tag and `extends`/`include` tags only allow to include the whole content of another template, not import symbols.

**Comment by ilyapuchka** [comment]
I think will make sense to create an issue for that in Stencil or StencilSwiftKit, it will be a useful feature.

**Comment by ilyapuchka** [comment]
Maybe also you can use `block` tag to do what you want to achieve.

**Comment by blindspotbounty** [comment]
@ilyapuchka could you give an example of block usage, please?
