### ISSUE TITLE
allVariables in AutoMockable doesn't work

### ISSUE THREAD

**Issue by dev4jam** [krzysztofzablocki/Sourcery#613]
In case we have defined in another framework:

```
protocol AutoMockable {
    var ref: SomeType { get }
}

protocol Service: AutoMockable {
    func callApi()
}

```
Sourcery doesn't generate underlying variable ref in Mocked class.

In addition, could you update AutoMockable template to generate final classes for mockable types?

**Comment by ilyapuchka** [comment]
@dev4jam it's hard for me to understand, what exactly is defined in another framework?

**Comment by ilyapuchka** [comment]
If you want Sourcery to be aware of source code from a framework, it should be included in source files that it scans.
