### ISSUE TITLE
Update homebrew

### ISSUE THREAD

**Issue by ProudOfZiggy** [krzysztofzablocki/Sourcery#621]
http://brewformulas.org/Sourcery saying CLI is still 0.11.2. Can you update it up to 0.13.1? So we could install it using `brew install`

**Comment by ilyapuchka** [comment]
There is an issue in Homebrew that blocked 0.12 release

**Comment by ProudOfZiggy** [comment]
So there is no chances that we will get it in close future?

**Comment by blender** [comment]
Hi,

In the mean I created a bottled version at https://github.com/blender/homebrew-tap/blob/master/sourcery.rb

you can install it via

`brew install blender/homebrew-tap/sourcery`

or

` brew install https://github.com/blender/homebrew-tap/blob/master/sourcery.rb`

or copy the file locally and install via

`brew install sourcery.rb`

**Comment by yonaskolb** [comment]
We fixed this in XcodeGen by removing `libxml2` from `HOMEBREW_ISYSTEM_PATHS` https://github.com/yonaskolb/XcodeGen/pull/289
