### ISSUE TITLE
bin/sourcery fails to run

### ISSUE THREAD

**Issue by DivineDominion** [krzysztofzablocki/Sourcery#622]
- Checked out Sourcery as a git submodule into `./external/Sourcery`.
- Ran `swift build` inside
- cd'ed back to the project root
- ran `./external/Sourcery/bin/sourcery`

This is the result:

    ./external/Sourcery/bin/sourcery: line 6: <PROJECT_DIR>/external/Sourcery/bin/Sourcery.app/Contents/MacOS/Sourcery: No such file or directory

While this works:

    $ ./external/Sourcery/.build/debug/sourcery 

I'd have expected it to behave just the same.

---

Xcode Version 9.3 (9E145) on macOS 10.13.4 (17E202)

**Comment by DivineDominion** [comment]
Maybe related: #423

**Comment by ilyapuchka** [comment]
Except that `bin` folder, which is sued for preparing release, should be probably not checked into the repo this is expected. SMP build products are stored under `.build` folder, not `bin`. Please refer to installation section in README.

**Comment by DivineDominion** [comment]
Aha, thanks. Good to know. I'd vote to have the `bin/` folder removed completely to avoid this for other newcomers to Sourcery :)
