### ISSUE TITLE
AutoCodable does not generate CodingKeys for all public enums

### ISSUE THREAD

**Issue by guidomb** [krzysztofzablocki/Sourcery#624]
If I have more than one public enum that conforms to `AutoCodable`, the generated code does not include `CodingKeys` type for each confirming type. Removing the public access modifier to the declaration of the conforming type works around the problem.

**Comment by ilyapuchka** [comment]
@guidomb can you please provide a code sample that demonstrates the issue?

**Comment by guidomb** [comment]
Sorry, about this. It seems that I have an old version of the AutoCodable version. I downloaded the latest version and it worked.
