### ISSUE TITLE
AutoCodable error when parsing an enum with associatedTypes without label

### ISSUE THREAD

**Issue by letatas** [krzysztofzablocki/Sourcery#626]
Hello,

The following type generates an error:

```swift
public enum MeasureType : AutoCodable {
    case on(margin: Double)
    case distance(Double)
}
```

The error being: `error: Error Domain=NSOSStatusErrorDomain Code=-1 "kCFStreamErrorHTTPParseFailure / kCFSocketError / kCFStreamErrorDomainCustom / kCSIdentityUnknownAuthorityErr / qErr / telGenericError / dsNoExtsMacsBug / kMovieLoadStateError / cdevGenErr: Could not parse the request/response. /  / custom to the kind of stream in question  /  / queue element not found during deletion /  / not a SysErr, just a placeholder  /  / General error; gray cdev w/o alert" UserInfo={terminationReason=__ObjC.Process.TerminationReason, error=Fatal error: Unexpectedly found nil while unwrapping an Optional value`

The error disappears with a label on the second case:

```swift
public enum MeasureType : AutoCodable {
    case on(margin: Double)
    case distance(of: Double)
}
```

I'm using Xcode 9.3.1 and Sourcery 0.13.1

**Comment by ilyapuchka** [comment]
@letatas All enum associated values should have labels which correspond to their json keys, similar to properties, otherwise it will be impossible to decode. This is mentioned in the description of the template [here](https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/codable.html)

**Comment by letatas** [comment]
My bad!

Wouldn't it be possible to store it with a generic name, like `distanceParam1` ?
