### ISSUE TITLE
Stencil `split` is not supported

### ISSUE THREAD

**Issue by Hatko** [krzysztofzablocki/Sourcery#627]
On run of Sourcery I get an error

> Unknown filter 'split'

although it's described [here](http://stencil.fuller.li/en/latest/builtins.html#built-in-filters). 

Does Sourcery use the latest version of Stencil? Is there a workaround on this issue?

**Comment by ilyapuchka** [comment]
Sourcery uses 0.10.1 version of Stencil, `split` was added in 0.11
There is no workaround unless you build Sourcery manually with bumped Stencil version
We can't update because of https://github.com/stencilproject/Stencil/issues/217

**Comment by DivineDominion** [comment]
Now that stencilproject/Stencil#217 is closed, could we upgrade Stencil? (My dev machine is broken when it comes to compiling from the CLI at the moment, so I cannot try it myself right now.)
