### ISSUE TITLE
Support for Xcode 10

### ISSUE THREAD

**Issue by daveanderson** [krzysztofzablocki/Sourcery#628]
I'm neither surprised nor disappointed that Sourcery appears to be incompatible with Xcode 10. (I'm not in a position to dig into the root cause or how to resolve it.)

```
sourcekit: [1:connection-event-handler:18435: 0.0001] Connection interruptsourcekit: [1:updateSemanticEditorDelay:18435: 0.0011] disabling semantic editor for 10 secondssourcekit: [1:pingService:18435: 0.0011] pinging servicesourcekit: [1:ping-event-handler:18435: 0.0110] service restoredUsing configuration file at 'REDACTED/.sourcery.yml'
Scanning sources...
error: Connection interrupted
```

**Comment by krzysztofzablocki** [comment]
SourceKitten needs to support new sourcekit version and then we'll support it as well

**Comment by kdawgwilk** [comment]
Shouldn't sourcery still work with CLI tools set to use 9.4 though?  In the past, I have been able to run newer versions of Xcode as long as I have the GM selected from `xcode-select`

**Comment by krzysztofzablocki** [comment]
@kdawgwilk sure, if you have both Xcode's on your machine then that would work

**Comment by kdawgwilk** [comment]
Sorry, I didn't make that clear but I am seeing these errors when trying to use the 9.4 cli tools which seemed unexpected

**Comment by Cellane** [comment]
Same here: using 9.4.1 CLI tools and can run Sourcery as a build phase just fine from Xcode 9.4.1 but for some reason, I always end up with the same error message as OP when running the build from Xcode 10 Beta.

**Comment by stuartro** [comment]
Seems to be working fine (at least, for the 'missing enum case' situation) with Xcode 10 beta 6.
