### ISSUE TITLE
'YES' does not exist or is not readable.

### ISSUE THREAD

**Issue by toshi0383** [krzysztofzablocki/Sourcery#63]
Hi
I encountered a runtime crash caused by force unwrapping, so I'm trying to debug it.

When I run Sourcery.xcworkspace from Xcode without any arguments, it exits with message below.
```
'YES' does not exist or is not readable.
```

Even if I pass the required arguments correctly, it still complains.
```
Unknown Arguments: -DnouMtSdbiNmcResg YES

Arguments:

    [34msource[0m - Path to a source swift files
    [34mtemplates[0m - Path to templates. File or Directory≥
    [34moutput[0m - Path to output. File or Directory.

Options:
    [34m--watch[0m [default: false] - Watch template for changes and regenerate as needed. Only works with specific template path (not directory).
    [34m--verbose[0m [default: false] - Turn on verbose logging for ignored entities
```

Xcode Version 8.2 (8C38)

Any idea?

**Comment by krzysztofzablocki** [comment]
Ah yes I saw that, I think it doesn't pass in arguments correctly, in the shared scheme I just pass in --help as argument and it works. 

Are you trying to develop new features?

**Comment by krzysztofzablocki** [comment]
@toshi0383 I figured it out, I pushed a fix to master, Xcode was passing a debug document versioning argument automatically and that was affecting our command line parsing

**Comment by krzysztofzablocki** [comment]
@toshi0383 were you seeing a crash around typealiases by any chance? if so take a look at #65 and new release

**Comment by toshi0383** [comment]
@krzysztofzablocki Thanks for quick update! 🙏

> 'YES' does not exist or is not readable.

This does not appear anymore.

I will look at the crash issue.
