### ISSUE TITLE
Is it possible to check if property is IBOutlet?

### ISSUE THREAD

**Issue by Hatko** [krzysztofzablocki/Sourcery#631]
It would be really useful if it was possible to check if a property of a class is an `@IBOutlet`

**Comment by ilyapuchka** [comment]
You should be able to access it through `attributes` property of `Variable`.

**Comment by Hatko** [comment]
It seems to me I can't. Could you please help me to figure out why?

**Comment by Hatko** [comment]
For example, I have this class:

```
class ActionTableViewCell: ConfigurableTableViewCell {
    @IBOutlet weak var label: UILabel!

    override func configure(withMeta meta: FormCellSource) {
        super.configure(withMeta: meta)

        guard case let .action(title) = meta.meta else { fatalError("Incorrect meta") }

        label.text = title
    }
}
```

The output of variables is:

Variable: name = label, typeName = UILabel!, isComputed = false, isStatic = false, readAccess = internal, writeAccess = internal, isMutable = true, defaultValue = nil, annotations = [:], attributes = [:], isFinal = false, definedInTypeName = Optional(ActionTableViewCell), actualDefinedInTypeName = Optional(ActionTableViewCell)

**Comment by ilyapuchka** [comment]
I can't reproduce this in unit tests unfortunately. Are you using latest version of Sourcery?

**Comment by Hatko** [comment]
I'm using `0.11.2`. It's not the latest as I can see 🙂

`homebrew` says I have the latest one

**Comment by ilyapuchka** [comment]
It is the latest in homebrew but not the latest release, please see https://github.com/krzysztofzablocki/Sourcery/issues/621

**Comment by Hatko** [comment]
Got it. Thank you 👍
