### ISSUE TITLE
Sourcery fails with Library not loaded

### ISSUE THREAD

**Issue by mathiasnagler** [krzysztofzablocki/Sourcery#632]
Hi there, 

I have an issue with Sourcery 0.13.1. I am not sure whether it is related to Sourcery or my machine somehow, but as I have no idea on how to approach the error, I am posting this issue.

> What version of Swift are you using (swift --version)?

```
swift --version 
Apple Swift version 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)
Target: x86_64-apple-darwin17.5.0
```

> What did you do?

I ran

```
Pods/Sourcery/bin/sourcery --sources "./App" --templates "./Sourcery/actionable.swifttemplate" --output "./Generated/Actionable.swift"
```

Sourcery has been installed via CocoaPods.

> What did you expect to see?

Sourcery completes without an error.

> What did you see instead?

```
No config file provided or it does not exist. Using command line arguments.
Scanning sources...
Found 96 types.
Loading templates...
Loaded 1 templates.
Generating code...
error: Error Domain=NSOSStatusErrorDomain Code=-1 "kCFStreamErrorHTTPParseFailure / kCFSocketError / kCFStreamErrorDomainCustom / kCSIdentityUnknownAuthorityErr / qErr / telGenericError / dsNoExtsMacsBug / kMovieLoadStateError / cdevGenErr: Could not parse the request/response. /  / custom to the kind of stream in question  /  / queue element not found during deletion /  / not a SysErr, just a placeholder  /  / General error; gray cdev w/o alert" UserInfo={terminationReason=__ObjC.Process.TerminationReason, error=dyld: Library not loaded: @rpath/libswiftSwiftOnoneSupport.dylib
  Referenced from: /Users/mnagler/Library/Caches/Sourcery/actionable.swifttemplate/ta%2F1mUB0o27Fnbxhn7khSbAk1gm9GvyMNNmUUKEdg98%3D
  Reason: image not found
}
```

The template I am using seems to be fully valid, because in other projects and for other developers it is working fine. Also, If i use Sourcery installed via `brew`, the same template works as expected.

**Comment by nevillco** [comment]
Seeing this as well. Usually a clean and build fixes it, but it's happening often.

**Comment by anandabits** [comment]
I am also seeing this error and using `--disableCache` with the same version of Swift as the initial post.  @mathiasnagler @nevillco did either of you figure out a workaround?

**Comment by ilyapuchka** [comment]
Please try to download Sourcery sources and build it locally. For Swift templates to work Sourcery should be built with the same version of Swift as one that is installed on machine that runs it.

**Comment by anandabits** [comment]
@ilyapuchka I am running the latest Sourcery release with Swift 4.1 and was able to get past the issue I was having.  I updated my comment to indicate infinite recursion as the source of this error in my case.  Perhaps that information will be helpful to @mathiasnagler or @nevillco.  It may also be useful in updating Sourcery to provide better diagnostic information (even just indicating that there is a problem with a specific template would be quite helpful).

**Comment by ZevEisenberg** [comment]
Deleting `~/Library/Caches/Sourcery` fixed this for me. I also deleted my `Pods` folder and ran `pod install`, but since the result was no change in Git status, I'm guessing that was not what fixed it. Xcode 9.4 (9F1027a) on macOS 10.13.5 (17F77). Sourcery 0.13.1. Hadn't run it on this machine for while, since I usually work on this particular project on another machine, so the cache may have been significantly out of date. If seeing it would be useful, I can recover it from a backup and send it to you.
