### ISSUE TITLE
Xcode 9.4 Error/Support

### ISSUE THREAD

**Issue by dmlebron** [krzysztofzablocki/Sourcery#633]
I'm getting the following error during build quite a few:

```
<unknown>:0: error: input file 'SASecrets.generated.swift' was modified during the build
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
```

It only happens on Xcode 9.4, if I use Xcode 9.3.1 it runs as expected.

**Comment by krzysztofzablocki** [comment]
how did you configure your build phases? sourcery should run before the compilation phase, make sure you dont have watch mode running in console as well

**Comment by dmlebron** [comment]
I wonder if it has something to do with having the scheme build for test on build.

I don't think it's related to the Xcode version...

Should the issue be close or renamed?
