### ISSUE TITLE
Generating code for generic structs and enums

### ISSUE THREAD

**Issue by blindmonkey** [krzysztofzablocki/Sourcery#636]
In our projects, we have a need to use generic `enum`s and generate code for reading and writing that type to JSON. I can see a `isGeneric` parameter on `Type`, but I can't figure out whether it's possible to actually generate code where we can iterate over these generics.

For instance, we might have something like:
```
enum OptionalFeature<F: JSONCodable>: AutoCodable {
  case doNotCare
  case expand
  case doCare(feature: F)
}
```

It seems like we can enumerate all of the `case`s and generate code for them without any problems, but we're having a hard time figuring out the return type for the `parse` method (that reads JSON).

We currently have the return signature as `{{ type.name }}`, but that just generates `func parse(...) -> OptionalFeature`, which the compiler complains about because it doesn't include the generic parameter. At the very least, we need some functionality to iterate over the generic parameter names so we can generate the appropriate return type.

I noticed there were some references to `GenericType`s in `TypeName`, but I didn't see any way to get a `TypeName` from a `Type`.

Is this something that's currently possible? If not, is this on the roadmap?

**Comment by ilyapuchka** [comment]
To access generic parameter's type you need to use `TypeName.GenericType.typeParameters` property

**Comment by blindmonkey** [comment]
Yep, I noticed that `TypeName` had some access to generics, but I'm dealing with `Type`s, and `type.name` is a `String`, not a `TypeName`. How do I get a `TypeName` of a `Type`?

**Comment by ilyapuchka** [comment]
This can be improved but currently you can only read generic type information from properties or method parameters, not from type declaration.

**Comment by ilyapuchka** [comment]
There is no `TypeName` on `Type` because `TypeName` describes type that is used to declare property or method parameter, etc, not type itself.

**Comment by blindmonkey** [comment]
Is this something that's on the roadmap? Or are there currently no plans to support this?

**Comment by ilyapuchka** [comment]
Yes, https://github.com/krzysztofzablocki/Sourcery/issues/551

**Comment by blindmonkey** [comment]
Great. Is there a guide to contributing if I wanted to implement this?

**Comment by ilyapuchka** [comment]
just this https://github.com/krzysztofzablocki/Sourcery/blob/master/CONTRIBUTING.md

**Comment by ilyapuchka** [comment]
I'll close that as duplicate
