### ISSUE TITLE
Project doesn't build if Xcode is not named Xcode.app

### ISSUE THREAD

**Issue by marcelofabri** [krzysztofzablocki/Sourcery#637]
I have two Xcodes installed: `Xcode9.4.app` and `Xcode-beta.app`. Cloning the project and trying to build it fails:

```
/Users/marcelofabri/Library/Developer/Xcode/DerivedData/Sourcery-ayuibpolxmwxaeelsaxgzaensilx/Build/Intermediates.noindex/Pods.build/Debug/libCommonCrypto.build/unextended-module.modulemap:5:12: error: header '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/CommonCrypto/CommonDigest.h' not found
    header "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/CommonCrypto/CommonDigest.h"
           ^
<unknown>:0: error: could not build Objective-C module 'CommonCrypto'
```

Renaming `Xcode9.4.app` to `Xcode.app` fixes the problem.

**Comment by ilyapuchka** [comment]
CommonCrypto defines its header in module map as `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/CommonCrypto/CommonDigest.h`
so it's not an issue in Sourcery. We can change it to "/usr/include/CommonCrypto/CommonDigest.h" but I'd just suggest to use `Xcode.app` name for the main Xcode instance.
