### ISSUE TITLE
Variable.type:Type? is nil when the type is not self-made but built-in

### ISSUE THREAD

**Issue by DivineDominion** [krzysztofzablocki/Sourcery#640]
For example:

```swift
protocol Entity {}
class Position {}
class Person: Entity {
    var position: Position = Position()
    var name: String
}
```

Iterating over the properties like this:

```
{% for type in types.based.Entity %}
/* List of properties: {{type.name}}
    {% for prop in type.storedVariables %}
    name: {{prop.typeName}} 
    type: {{prop.type}}

    {% endfor %}
/*
{% endfor %}
```

Will output:

```
/* List of properties: Person
    name: String
    type:

    name: Position
    type: Class: module = Optional("...") ...
*/
```

Is this intended? Is this all you _want_ to support? If so, I'll gladly add a notice to the docs to clarify what ["if known" means for `Variable.type`](https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/Classes/Variable.html#/c:@M@SourceryRuntime@objc(cs)Variable(py)type).

**Comment by ilyapuchka** [comment]
@DivineDominion we have it explained [here](https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/writing-templates.html)

**Comment by DivineDominion** [comment]
What do you think about having a link to the part of the docs added to the API doc comments? 🤔 I find it weirdly confusing to find my way around with Sourcery, compared to other libraries that do much more complex things in my apps, including RxSwift, and I wonder if that would help make sense of things :)

**Comment by ilyapuchka** [comment]
You we can do that.

**Comment by DivineDominion** [comment]
Ok will do and somit a PR later today
