### ISSUE TITLE
Extent Sourcery with dynamic Context variable pupulation & reading of values

### ISSUE THREAD

**Issue by DivineDominion** [krzysztofzablocki/Sourcery#643]
It seems we're hitting the limits of Sourcery at @objectbox. Basically we would like to propose and discuss a plugin mechanism to provide hooks for custom code.

For us, we'd like to do two things:

1. Run additional checks on the AST (e.g. existence of a property) and produce warnings/errors accordingly. Sourcery has the type info already, and we're generating code based on that anyway, so that's super convenient!

2. Add dynamic context/environmental info to Stencil templates from the outside: populate variables with values not found inside the scanned source, but through plugin code: e.g. invoke some code which, in our case, stores and reads meta info to a file, the end result being used for code gen.

What do you think?

**Comment by anandabits** [comment]
> Run additional checks on the AST (e.g. existence of a property) and produce warnings/errors accordingly. Sourcery has the type info already, and we're generating code based on that anyway, so that's super convenient!

Fwiw, if you’re willing to have the warning/error appear in the generated code you can use `#error` or `#warning`.  I have a template that does validation and produces an error instead of synthesizing code if there are errors in the use of the template.

**Comment by DivineDominion** [comment]
@anandabits hmm that could work if I had Swift 4.2 🤔  I was thinking about the `echo`ing errors/warnings from the run script phase directly that Xcode will show in the issue navigator, like `echo "foo.swift:12:34 error: Cannot do bar"`

It seems you cannot pass `--args` when you use a config file, and you cannot specify the `--args` from within the config file. Did I get that right? Then I'd open a new issue for that.

As for our 2nd use case, the `--args` parameter wouldn't suffice. We need to perform side-effects (read/write to a config file) from the "plugin". We weren't 100% certain if that fits Sourcery's vision. If you folks find that interesting, great!

**Comment by ilyapuchka** [comment]
> It seems you cannot pass --args when you use a config file, and you cannot specify the --args from within the config file. Did I get that right? Then I'd open a new issue for that.

No, args work with config files too. This is mentioned in [usage docs](https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/usage.html)

**Comment by ilyapuchka** [comment]
I think the only viable solution for this kind of use cases is to provide sourcery as a framework instead of trying to fit all that in a tool.

**Comment by DivineDominion** [comment]
I think that'd be a flexible solution, too: `import Sourcery` and provide the extensions as "plug-ins". I think we can whip up something like this that will compile to a similar binary with the same CLI. Is that something you folks want to see happen?

**Comment by ilyapuchka** [comment]
There was a discussion about that long time ago #67

**Comment by krzysztofzablocki** [comment]
@DivineDominion we now have `SourceryFramework` via https://github.com/krzysztofzablocki/Sourcery/pull/715 so maybe thats a starting point to implement whatever is missing

**Comment by DivineDominion** [comment]
Looks good! I don't work at the employer with this project anymore, though, so I'll pass it on to someone else :)
