### ISSUE TITLE
condition with Type.storedVariable.typeName == "Int" is never true

### ISSUE THREAD

**Issue by DivineDominion** [krzysztofzablocki/Sourcery#645]
I want to find out if a type has a property of another given type.

- There is no `theType.storedVariables.based.Foo|first` filter combo as far as I can tell
- Looping through the `storedVariables` and making equality checks for the `typeName` doesn't work

## Minimal Example

Given `test.swift`,

```swift
protocol Proto {}
struct Foo: Proto {
    var bar: Int = 1
    var baz: String = "2"
}
```

and `template.stencil`

```
/*
{% for t in types.based.Proto %}
in {{t.name}}:
{% for p in t.storedVariables %}
{% if p.typeName == "Int" %}
is Int: {{p}}
{% endif %}
{% endfor %}
{% endfor %}
*/
```

### Actual Output 

Running `sourcery --sources test.swift --templates template.stencil` produces this output:

```swift
// Generated using Sourcery 0.13.1 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

/*
in Foo:
*/
```

### Expected Output

```swift
// Generated using Sourcery 0.13.1 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

/*
in Foo:
is Int: Variable: name = bar, typeName = Int, isComputed = false, isStatic = false, readAccess = internal, writeAccess = internal, isMutable = true, defaultValue = Optional("1"), annotations = [:], attributes = [:], isFinal = false, definedInTypeName = Optional(Foo), actualDefinedInTypeName = Optional(Foo)
*/
```

(Using Sourcery v0.13.1)

**Comment by ilyapuchka** [comment]
https://github.com/krzysztofzablocki/Sourcery/issues/644#issuecomment-404149465

**Comment by DivineDominion** [comment]
🤦‍♂️  I'm an idiot. Thank you so much! Lead astray by the "debug" output of collecting `{{ v.typeName }}`s, but of course _that_ turned out to be a String.
