### ISSUE TITLE
Upgrade Stencil

### ISSUE THREAD

**Issue by werediver** [krzysztofzablocki/Sourcery#647]
The latest Stencil release [v0.11.0](https://github.com/stencilproject/Stencil/releases/tag/0.11.0) (released on April 5th) includes some good bug fixes and enhancements.

Are there any impediments to integrating it?

**Comment by petaren** [comment]
Why not `0.12.1` while we're at it?

**Comment by werediver** [comment]
@petaren ~Even v0.11.0 would be a progress.~ Of course, we should integrate the most up-to-date version.

**Comment by ilyapuchka** [comment]
Done with 0.15.0 release
