### ISSUE TITLE
Feature Request: Append on "Per File" code generation

### ISSUE THREAD

**Issue by ethanjdiamond** [krzysztofzablocki/Sourcery#648]
At the end of the [Writing Templates](https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/writing-templates.html) section in the docs, there's a sourcery annotation (sourcery:file) that lets you specify a different output file to generate  to for each type instead of writing the output for all types that apply to a template into one giant file. This has been especially useful because I use the incremental single file compilation mode, and having a giant generated file that all my classes depend on means Xcode has to recompile all of my files that reference that giant file every time it changes.

I ran into a problem lately where I'd like to have two different templates write to the same file, so I can keep my number of files low, but wasn't able to do it because the second template's output overwrites the first one's. Would it be possible to make it so when two or more templates try to write to the same file in the same invocation of sourcery, the second one's output would get appended to the first instead of overwriting it?

**Comment by ilyapuchka** [comment]
You can try following: put two `inline` annotation blocks, one named by each template, in an empty file, make Sourcery to scan this file, then use the same annotation blocks in the templates to wrap all their content. Then Sourcery will process those ranges in the file and will write the content of respective blocks generated by template into it.

**Comment by ethanjdiamond** [comment]
Thanks for the workaround idea Ilya! I'll probably end up doing that in the meantime, but I do feel that appending for one invocation of sourcery is a pretty sensible default. Having to pre-create files and put in sourcery annotation removes a good amount of the gain of generating code in the first place.
