### ISSUE TITLE
Docs are misleading for --args usage.

### ISSUE THREAD

**Issue by fssilva** [krzysztofzablocki/Sourcery#651]
Recently tried to access the values passed by the --args flag. After reading the writing-templates documentation, it mentioned that the content of the args can be accessed by using the `arguments` keyword e.g. `{{arguments.variable}}`. In fact the correct variable is `argument` without the `s` i.e. `{{argument.variable}}`

**Comment by ilyapuchka** [comment]
The issue is that we have `arguments` as variable name, so that's what would be used in swift template, but `argument` in js and stencil templates.
@krzysztofzablocki should we stick to `argument` or `arguments`?

**Comment by fssilva** [comment]
This should definitely be standardized, as it can cause confusion. In my opinion the naming should be `argument` not `arguments`. This would unify the process in all instances  (swift, stencil and js)

**Comment by krzysztofzablocki** [comment]
argument to unify it

**Comment by krzysztofzablocki** [comment]
@fssilva 👍
