### ISSUE TITLE
Feature: CodingKey snake_case

### ISSUE THREAD

**Issue by onato** [krzysztofzablocki/Sourcery#656]
I'm working with an API written in ruby, so, unfortunately, their naming convention uses underscores instead of camelcase. My `CodingKeys` enum is quite boiler platy and I would like to solve this with Sourcery.

```
    enum CodingKeys: String, CodingKey {
        case myVariableOne = "my_variable_one"
        case myVariableTwo = "my_variable_two"
        case myVariableThree = "my_variable_three"
        case myVariableFour = "my_variable_four"
        case myVariableFive = "my_variable_five"

// sourcery:inline:auto:Activity.CodingKeys.AutoCodable
        case id
        case name
        case type
// sourcery:end
```

I'm looking for a way to generate the `myVariable(.*)` lines with sourcery by forcing camelcased variable names to be generated snake_cased.

I couldn't see a way to do this with the current AutoCodable template. If someone has an idea how to do this now, I would be very greatful, otherwise I'd be happy to work on adding the feature.

**Comment by ilyapuchka** [comment]
@onato have you tried to use key strategies provided by standard library instead? it will work for the example that you provided and you will not need to set custom keys and use template annotation for others.

**Comment by onato** [comment]
Bingo! Thank, that'll do the trick.

```
    let decoder = JSONDecoder()
    decoder.keyDecodingStrategy = .convertFromSnakeCase
```
