### ISSUE TITLE
Duplicated contained type

### ISSUE THREAD

**Issue by Hatko** [krzysztofzablocki/Sourcery#658]
I use Sourcery 0.13.1.

Using this template:

```
{% for subtype in type.TestForSourcery.containedTypes %}
  {{subtype.name}}
{% endfor %}
```

For this code:

```
struct TestForSourcery {
  struct InnerStruct {
    static let test = 5
  }
}

private extension TestForSourcery.InnerStruct {
 static var secondVar: Int { return 6 }
}
```

The output is just fine:

`TestForSourcery.InnerStruct`

But if I separate extension to another file, move `private extension TestForSourcery.InnerStruct` to any other file except one with definition, I have output duplicated:

```
            TestForSourcery.InnerStruct
            TestForSourcery.InnerStruct
```

Is it a bug? If not and it is expected behavior, is there a workaround?

**Comment by krzysztofzablocki** [comment]
fixed long ago
