### ISSUE TITLE
Sourcekitten integration

### ISSUE THREAD

**Issue by pkasson** [krzysztofzablocki/Sourcery#662]
Is it possible to get the results of an invocation as a dictionary (to dictionary) instead of toJson from the framework ?

Would like to interact with this directly and not have to parse a file.

**Comment by ilyapuchka** [comment]
@pkasson sorry, I don't understand what do you mean by that.

**Comment by ilyapuchka** [comment]
We use a `Structure` type defined in SourceKittenFramework. If you want to get results of Sourcery parsing in a form of the dictionary and use it in something other than templates - we don't support this usecase.

**Comment by pkasson** [comment]
I didnt have a good example of pulling data out of the framework until viewing sorcery - I see now how you are using the Structure object - works great - thanks !

Initially I was running kitten on the command line before realizing there was a framework, then parsing the output - total pain.
