### ISSUE TITLE
Get imported libraries

### ISSUE THREAD

**Issue by Atimca** [krzysztofzablocki/Sourcery#670]
Hello! Is there any way to import necessary libraries dynamically with Sourcery?

example template code: 
```stencil
func testMethod() -> CLLocation {
    return CLLocation()
}
```

would generate:
```swift
import CoreLocation

func testMethod() -> CLLocation {
    return CLLocation()
}
```

I want this to work for Apple's and our's internal libraries

**Comment by ilyapuchka** [comment]
Not with Sourcery, but I think you can do something like that with `sourcekitten` directly https://github.com/jpsim/SourceKitten/issues/202

**Comment by Atimca** [comment]
Thank you for the fast answer, I will try it!

**Comment by ilyapuchka** [comment]
Actually, you might need to use Sourcery for that anyway because sourcekitten will only give system libraries. So you will need to use both.
Using Sourcery you need to make sure you scan sources of your frameworks, then its types will have `module` property (for some reason it's not documented). Then you can use that in the template to get list of all modules by matching types. You'll not be able to use that for system modules as we don't scan sources, so you'll have to combine that with sourcekitten results.

**Comment by Atimca** [comment]
I've tried to realise how to use `module` without documentation and have bumped into a problem. As I fully understand, If I correctly set all `sources` for `Sourcery`, I get `Type` property and `module` in the type for all `Variables` witch lays in the 3d party libraries. Eventually, I've gotten `Type` property, however `module` property still nil.

Theres my code:

generation target:
```swift
import CoreLocation
import FrameworkForTests
import AviaCore

// sourcery: Libraries
class Foo {
    var internalFramework: SomeStructure!
    var appleFramework: CLLocation!
    var internalPro: Boo!
    var cocoaPods: Offer!
    var simple: Int!
}
```

stencil code:
```stencil
{% for type in types.all %}
    {% if type|annotated:"Libraries" %}
        {{type.name}}
        {% for variable in type.variables %}
            {{variable.name}}: {{ variable.type }}
        {% endfor %}
    {% endif %}
{% endfor %}
```

generated output:
``` swift
        Foo
            internalFramework: Struct: module = nil, 
            appleFramework: 
            internalPro: Struct: module = nil, 
            cocoaPods: Struct: module = nil, 
            simple: Type: module = nil, 
```

expected output:
``` swift
        Foo
            internalFramework: Struct: module = FrameworkForTests, 
            appleFramework: // CoreLocation (Should take from SoureKitten)
            internalPro: Struct: module = nil, // Internal type
            cocoaPods: Struct: module = AviaCore, 
            simple: Type: module = nil, // Foundation Int
```

**Comment by ilyapuchka** [comment]
@Atimca sorry, to get `module` property you need to instruct Sourcery to what projects they belong using `project` key in [configuration file](https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/usage.html)
