### ISSUE TITLE
Sourcery with Swift 4.2, Cocoapods, Xcode 10b6

### ISSUE THREAD

**Issue by daveanderson** [krzysztofzablocki/Sourcery#672]
We recently modified our app (which has an internal .framework) to use Sourcery for the framework as well. 

The build phase script is doing a 

```
"${PODS_ROOT}"/Sourcery/bin/sourcery --config InternalKit/.sourcery.yml
```

And we're getting the error

```
Using configuration file at 'InternalKit/.sourcery.yml'
Scanning sources...
Found 266 types.
Loading templates...
Loaded 4 templates.
Generating code...
error: /var/folders/f8/jv7mx3552r58j521g47x_y400000gn/T/SwiftTemplate.build/main.swift:2:8: error: module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: /var/folders/f8/jv7mx3552r58j521g47x_y400000gn/T/SourceryRuntime.framework/Modules/SourceryRuntime.swiftmodule/x86_64.swiftmodule
import SourceryRuntime
```

xcode-select indicates

```
$ xcode-select -p
/Applications/Xcode-10.app/Contents/Developer
```

with cocoa pods

```
$ pod --version
1.6.0.beta.1
```
and Sourcery

```
$ Pods/Sourcery/bin/sourcery --version 
0.14.0
```

Is this a configuration defect on our end or have we hit some sort of a compatibility issue?

**Comment by ilyapuchka** [comment]
As error says: `module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler`
You can use Sourcery with Swift templates only with Swift 4.1, there was no release for Swift 4.2

**Comment by daveanderson** [comment]
Thank you for the confirmation @ilyapuchka
