### ISSUE TITLE
Some questions...

### ISSUE THREAD

**Issue by randomstrings** [krzysztofzablocki/Sourcery#673]
1. Via Sourcery .stencil templates is it possible to access doc comments (the documentation of structures/functions in source code)? Example:

```swift
/// Returns an array of zone_pick_request ids for all the requests that are currently pickable in the given zone, filtered down with the given filter.
///
/// - Parameters:
///   - zone: The zone to check
///   - filter: The filter to use
public func pickableIdsInZone(zone: Int, filter: NonconveyableFilter) throws -> [Int] {
    ...
}
```

2. Via Sourcery .stencil templates is it possible to access top-level functions in a package, in other words functions that are not embedded within a specific type. Example:

```swift
public func zip3(one: Any, two: Any, three: Any) {
    ...
}
```

Thanks!

**Comment by ilyapuchka** [comment]
@randomstrings I'm sorry but none of this is supported

**Comment by randomstrings** [comment]
Thank you!
