### ISSUE TITLE
Can I get type's property in difference target?

### ISSUE THREAD

**Issue by LimChihi** [krzysztofzablocki/Sourcery#676]
Hello, I wrote a `swifttemplate` to generator code. When I want to write a unit tests in UnitTest target for this template, I found I can not get type's property such as `implements` or `typeName`.
Can I get type's property in difference target?
Here is my template.

[AutoCodable.swifttemplate.zip](https://github.com/krzysztofzablocki/Sourcery/files/2378738/AutoCodable.swifttemplate.zip)

**Comment by ilyapuchka** [comment]
it's not about the template it's about what sources Sourcery scans. To have this data you need to scan sources where types and protocols you are interested in are _defined_.

**Comment by LimChihi** [comment]
I declare a struct in UnitTest target like this:
```swift
struct StructTest: AutoCodable {
    let stringVar: String
}
```
Then Sourcery talk me that `StructTest`'s `implements` is `[:]`. It can not find any implements.

**Comment by ilyapuchka** [comment]
Put this type definition into a separate file and instruct Sourcery to scan it via `sources` key in configuration file or CLI arguments.

**Comment by ilyapuchka** [comment]
You are not scanning file where `AutoCodable` protocol is defined.

**Comment by LimChihi** [comment]
Oh. You are right.
Sorry for wasting your time.
