### ISSUE TITLE
Error in Xcode 10

### ISSUE THREAD

**Issue by hartbit** [krzysztofzablocki/Sourcery#678]
I'm getting an error running Sourcery since I passed to Xcode 10 and updated Sourcery to 0.14.0:

```
No config file provided or it does not exist. Using command line arguments.
Scanning sources...
Found 676 types.
Loading templates...
Loaded 5 templates.
Generating code...
error: Error Domain=NSOSStatusErrorDomain Code=-1 "kCFStreamErrorHTTPParseFailure / kCFSocketError / kCFStreamErrorDomainCustom / kCSIdentityUnknownAuthorityErr / qErr / telGenericError / dsNoExtsMacsBug / kMovieLoadStateError / cdevGenErr: Could not parse the request/response. /  / custom to the kind of stream in question  /  / queue element not found during deletion /  / not a SysErr, just a placeholder  /  / General error; gray cdev w/o alert" UserInfo={terminationReason=__ObjC.Process.TerminationReason, error=dyld: Symbol not found: __T0BOWV
  Referenced from: /Users/david/Library/Caches/Sourcery/AutoCodable.swifttemplate/../SourceryRuntime.framework/Versions/A/SourceryRuntime
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /Users/david/Library/Caches/Sourcery/AutoCodable.swifttemplate/../SourceryRuntime.framework/Versions/A/SourceryRuntime
}
```

**Comment by bscothern** [comment]
Same here. I've deleted my `~/Library/Caches/Sourcery` and the error changed to this:

```
error: /var/folders/x9/bvxmg8bx42jd0hl20q0l6l1c0000gn/T/SwiftTemplate.build/main.swift:2:8: error: module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: /var/folders/x9/bvxmg8bx42jd0hl20q0l6l1c0000gn/T/SourceryRuntime.framework/Modules/SourceryRuntime.swiftmodule/x86_64.swiftmodule
import SourceryRuntime

```
I have also just tried building from source and get the error: "Redefinition of module 'CommonCrypto'".

**Comment by ilyapuchka** [comment]
swift templates require to be built with the same version of swift as Sourcery. There was no release against swift 4.2 yet

**Comment by hartbit** [comment]
@ilyapuchka I'm confused: I haven't updated my project to Swift 4.2, only to Xcode 10.

**Comment by jjamminjim** [comment]
I am having this same issue with Xcode 10 / Swift 4.0.

**Comment by goa** [comment]
Same here.

**Comment by Liquidsoul** [comment]
This issue is related to the fact that swift templates are related to the swift version used to package the Sourcery app because of the ABI not being stable yet.

To use swift templates with an Xcode 10 installation, you need to wait for a release of Sourcery that'll use Xcode 10.

In the meantime, as a workaround, you can change the swift version used in the command-line to the one of Xcode 9.4.1. The simple way is just to use `xcode-select` for that.

**Comment by hartbit** [comment]
> In the meantime, as a workaround, you can change the swift version used in the command-line to the one of Xcode 9.4.1. The simple way is just to use xcode-select for that.

I'm not quite sure I understand. Can you give an example?

**Comment by Liquidsoul** [comment]
With sourcery `0.14.0`, you need to use swift `4.1.2`.
So to check if your CLI uses the correct version run `/usr/bin/swiftc --version`.

If it uses Xcode 9, it should print something like this:
```
Apple Swift version 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
```
And you'd be good to go.

However, with Xcode 10, you'd have something like this:
```
Apple Swift version 4.2 (swiftlang-1000.0.36 clang-1000.10.44)
Target: x86_64-apple-darwin17.7.0
```

On my mac, I have 2 Xcode installations:
- Xcode 9 at `/Applications/Xcode.app`
- Xcode 10 at `/Applications/Xcode-10.app`

To be able to run sourcery locally on my mac, I would just run `sudo xcode-select --switch /Applications/Xcode.app`.

This is not ideal and will not work outside of a local environment but it may do the trick.

Maybe you could also limit the scope of the swift version selection to the sourcery execution using the `TOOLCHAINS` variable but I have not looked into that much and I am not sure this would even work 🤔

**Comment by jjamminjim** [comment]
Yes this should work in my local environment. It will not work in our CI environment, which means I will have to disable Sourcery before deployment. Is there an eta on on a fix?

**Comment by Liquidsoul** [comment]
I suppose that there will be a new release once Xcode 10 is officially out.

For a more general fix of the issue, I am currently working on changing the swift template build system to SPM (#509) so that we would not be dependant to the Swift version of the Sourcery release.
However, this is not something that would come without cost and there are some unsolved issues about how to share the `SourceryRuntime` as source code.

**Comment by tskulbru** [comment]
Im still getting this error in 0.15.0 which has xcode 10 and swift 4.2 support.

**Comment by ilyapuchka** [comment]
@tskulbru can you please provide more info?

**Comment by ichina** [comment]
@tskulbru try to use once sourcery with command line options (without config files .sourcery.yml), and include  `--disableCache` attribute 
for example:
 ```
./bin/Sourcery.app/Contents/MacOS/Sourcery --sources Test.swift --templates Templates/AutoCodable.swifttemplate --output ./Generated --disableCache --verbose
```

**Comment by jjamminjim** [comment]
0.15.0 seems to have solved my issue. Thanks!

**Comment by goa** [comment]
0.15.0 fixed my Xcode 10 issue as well.

**Comment by krzysztofzablocki** [comment]
@tskulbru try nuking the cache and then running with it, might be some stale data

**Comment by riyadshauk** [comment]
Yeah. 0.15.0 fixed my Xcode 10 issue as well. For some reason, I had an older version of SwiftyMocky and also an older version of its dependency, Sourcery, installed. 

Simply running `pod update` solved those problems when I consequently reran `rake mock` as per the SwiftyMocky getting-started docs.

**Comment by chrisballinger** [comment]
I was also experiencing this issue with v0.15.0.

Deleting `~/Library/Caches/Sourcery` fixed the problem for me:

**Comment by goa** [comment]
@chrisballinger's answer fixed it for me as well :)
