### ISSUE TITLE
Proposal: Optional inline or file code generation from the same template

### ISSUE THREAD

**Issue by DivineDominion** [krzysztofzablocki/Sourcery#684]
I'd like to get feedback on an idea I had regarding inline code gen (
https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/writing-templates.html#inline-code-generation)

Couldn't we make inlining the generated code optional?

### Happy Case: Inline on both ends

In template:

```
{% for type in types.all %}
// sourcery:inline:{{ type.name }}.TemplateName
    var generatedStuff = 9876
// sourcery:end
{% endfor %}
```

In source code:

```swift
class MyType {
    var otherStuff = 123
// sourcery:inline:MyType.TemplateName
// sourcery:end
}
```

This will produce:

```swift
class MyType {
    var otherStuff = 123
// sourcery:inline:MyType.TemplateName
    var generatedStuff = 9876
// sourcery:end
}
```

### Sad path: no target :(

In template:

```
{% for type in types.all %}
// sourcery:inline:{{ type.name }}.TemplateName
    var generatedStuff = 9876
// sourcery:end
{% endfor %}
```

In source code:

```swift
class MyType {
    var otherStuff = 123 
}
```

**Note the absence of the inline comments in the code!**

This will produce:

```swift
class MyType {
    var otherStuff = 123
}
```

## Proposed solution

Given the same template as above and the code without inline comments, I'd want the generated code to end up in the `OUTPUTNAME.generated.swift` file just like the rest of the template outside the inline block's bounds.

- This way, users can opt in to have the generated code put inline or in separate files _from the same template._
- This also enables you to use a template to generate code one way for the app, and a different way for the test targets.

The 2nd case is the one that I'm currently craving for: to specify a location in my test code where the generated code should be put. Now I have to run the tool and copy & paste manually, which is no big deal, but this would be nice and sounds manageable to implement.

So, please give me your feedback on this! If it's overwhelmingly positive, I'll implement this later.

**Comment by ilyapuchka** [comment]
This looks like a bug in inlining - if you have a `type.name` it should be appended to the end of this type body. Can you check that? The whole idea of inlining is to insert generated code without need to put annotations manually.
To achieve your goal to have different inline behaviour in test and in app target you could use arguments for that and use `inline` conditionally. The inlining process happens after content is already generated, otherwise using stencil variables will not work to generate type-specific annotations and then basically it does cut-and-paste for you. So something like this should do the job:

```
// sourcery:{% if args.inline %}inline:{% endif %}{{ type.name }}.TemplateName
```

**Comment by DivineDominion** [comment]
Did check with my code base and it sure didn't generate code for a template of this form:

```
{% for type in types.all %}
// sourcery:inline:{{ type.name }}.TemplateName
extension {{ type.name }}: SomeProtocol {
    // more stuff here
}
// sourcery:end
{% endfor %}
```

I think what you mean is the `inline:auto:` combo instead of plain `inline:`

**Comment by ilyapuchka** [comment]
Yes, right, I mean `auto`. So then what will be the difference between what you want and using `auto`?

**Comment by ilyapuchka** [comment]
I probably don't understand what "no target" means. If Sourcery didn't scan the source of the type and don't have `type.name` then again you can use this as a condition to generate different annotation. 
We can have better diagnostics when inlining ofc, i.e. when we can't find corresponding annotation in code to paste code in.

**Comment by DivineDominion** [comment]
@ilyapuchka without `auto:`, Sourcery will "paste" the generated code only when you put the annotations in your source. If you don't do that, no generated code will be put anywhere at all. Like it's being cut to the clipboard but never pasted.

Your args suggestion would work in combination with leaving the annotations out of the source code. But I found the current behavior strange, that no code gets generated at all as @krzysztofzablocki pointed out.

**Comment by ilyapuchka** [comment]
I agree that in case we don't find place to paste we should fallback to pasting in `.generated` file

**Comment by DivineDominion** [comment]
I could have a look next week, but I guess it's just a matter of minutes for you to change the code base you know so well. So if you want to go ahead, you have my blessing :) Otherwise, I'll wrap something up on Monday or Tuesday.
