### ISSUE TITLE
error: module compiled with Swift 4.2 cannot be imported in Swift 4.1.2:

### ISSUE THREAD

**Issue by ichina** [krzysztofzablocki/Sourcery#687]
i had installed Sourcery via building with XCode 10 from sources (last release 0.15.0)
so everything is fine with .stencil templates, but with .swifttemplate (AutoCodable) i get this error
```
$ Sourcery.app/Contents/MacOS/Sourcery --sources <sourcesPath> --templates <AutoCodable.swifttemplate> --output <outputPath>
No config file provided or it does not exist. Using command line arguments.
Scanning sources...
Found 77 types.
Loading templates...
Loaded 1 templates.
Generating code...
error: /var/folders/j3/19jmj93j46n7yj3lyy53b0280000gn/T/SwiftTemplate.build/main.swift:2:8: error: module compiled with Swift 4.2 cannot be imported in Swift 4.1.2: /var/folders/j3/19jmj93j46n7yj3lyy53b0280000gn/T/SourceryRuntime.framework/Modules/SourceryRuntime.swiftmodule/x86_64.swiftmodule
import SourceryRuntime
       ^
```

so there is some problem with `Swift 4.2` and `.swifttemplate` templates

same error happens with prebuilt binary and cocoapods

this error not happens on previous version 0.14.0

**Comment by ichina** [comment]
same things happens with prebuilt binary

**Comment by ilyapuchka** [comment]
That means that the template is built using swift 4.1.2
What is the output of `swift --version` ?

**Comment by ilyapuchka** [comment]
I downloaded archive attached to the 0.15.0 release, and run `./bin/Sourcery.app/Contents/MacOS/Sourcery --sources Test.swift --templates Templates/AutoCodable.swifttemplate --output ./Generated --disableCache --verbose`
This successfully generated expected output.
`swift --version` returns

```
Apple Swift version 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)
Target: x86_64-apple-darwin17.7.0
```

I have only Xcode 10 installed.
Please ensure that swift --version returns expected output, it might be that you have several versions of swift environment or Xcode installed, in this case you might need to run Xcode-select

**Comment by ilyapuchka** [comment]
If you don't need AutoCodable templates to be run - remove them from templates folder

**Comment by ichina** [comment]
oh, i see, its trully was a swift 4.1.2. I have updated Command Line Tools to the latest and now its swift 4.2. 
in first time after update i got same issue as here https://github.com/krzysztofzablocki/Sourcery/issues/678, but --disableCache attribute completely fix this problem for me.
thank you.
