### ISSUE TITLE
0.15.0 installation via Mint fails with 'Package.swift not found'

### ISSUE THREAD

**Issue by HSchultjan** [krzysztofzablocki/Sourcery#689]
Installing Sourcery 0.15.0 via Mint fails with error `Package.swift not found`. 

```
➜ mint install krzysztofzablocki/Sourcery@0.15.0
🌱  Cloning https://github.com/krzysztofzablocki/Sourcery.git 0.15.0...
Package.swift not found
```

**Comment by yonaskolb** [comment]
@HSchultjan seems to install fine here with Mint 0.11.2

Can you post the results of the following commands?
```
mint --version
swift --version
```
Do other packages install correctly with Mint for you?

**Comment by yonaskolb** [comment]
Ok can confirm there is an issue when trying to install Sourcery 0.15.0 with Swift 4.1, as it now requires Swift 4.2. If you update your default swift version to Swift 4.2 it will work. You can use `xcode-select` for this.
We'll update the error messaging in Mint 👍

**Comment by HSchultjan** [comment]
Good to know! Thanks for the quick help!
