### ISSUE TITLE
Crash on multibyte enum case

### ISSUE THREAD

**Issue by toshi0383** [krzysztofzablocki/Sourcery#69]
Arguments
```
/Users/toshi0383/github/Sourcery/test/ /Users/toshi0383/github/Sourcery/test/autoequatable.swift.template /Users/toshi0383/github/Sourcery/out/
```

source: test/Sample.swift
```
protocol AutoEquatable {}
enum JapaneseEnum {
    case アイウエオ
}
struct Cat: AutoEquatable {
    let name: String
    let age: Int
    let flag: Bool
}
struct Dog: AutoEquatable {
    let name: String
    let age: Int
    let flag: Bool
}
```

template: test/autoequatable.swift.template
```
{% for type in types.implementing.AutoEquatable %}
extension {{ type.name }}: Equatable {}

func == (lhs: {{ type.name }}, rhs: {{ type.name }}) -> Bool {
    {% for variable in type.storedVariables %} if lhs.{{ variable.name }} != rhs.{{ variable.name }} { return false }
    {% endfor %}
    return true
}
{% endfor %}
```

crash
<img width="1421" alt="xcode-crash" src="https://cloud.githubusercontent.com/assets/6007952/21431939/beeef1b2-c8ac-11e6-91a2-22081b0e7c82.png">

Looks like it's inside SourceKitten.
SwiftLint doesn't crash on same code. I don't know why.

**Comment by krzysztofzablocki** [comment]
I pushed a fix to master, would you mind taking a look whether it works for your codebase?

**Comment by jpsim** [comment]
Yeah, this is likely a bug in SourceKitten, and likely the same issue as realm/SwiftLint#1006.

We're investigating the following re-implementation, but since that breaks other things we haven't fully determined the scope of this issue:

```swift
func lineAndCharacter(forByteOffset offset: Int) -> (line: Int, character: Int)? {
    let characterOffset = location(fromByteOffset: offset)
    return lineAndCharacter(forCharacterOffset: characterOffset)
}
```

**Comment by jpsim** [comment]
And to reiterate from twitter, yes all offsets and lengths reported by SourceKit are in bytes.

**Comment by krzysztofzablocki** [comment]
ok I think the master is working now, I used the suggestion for translating the byteOffset, once sourcekitten solves the internal issue we can go back to using old function. @toshi0383 can you confirm current master works for you? I added test but just to be sure

**Comment by toshi0383** [comment]
Confirmed fix at master. 👍
