### ISSUE TITLE
Controlable or deterministic order of iteration for dictionaries

### ISSUE THREAD

**Issue by tarleb** [krzysztofzablocki/Sourcery#695]
The order in which *for* loops iterate through dictionaries is currently non-deterministic. E.g., a statement like 

    {% for impl in type.implements %}
        {{impl}}
    {% endfor %}

can produce different different outputs on each run. This poses a problem with generated files which are checked into source control.

It would be great to either iterate through dictionaries in a predefined order, e.g., lexicographic order of keys. Alternatively, a filter to convert the dictionary into an array would be equally helpful.

**Comment by ilyapuchka** [comment]
This is fixed in latest Stencil release, which we already updated but didn't release with it yet. Please wait for next release.

**Comment by tarleb** [comment]
Great, thanks!

**Comment by tarleb** [comment]
Tested with current master, working as advertised. Thanks again!
