### ISSUE TITLE
Config's file exclude key not working

### ISSUE THREAD

**Issue by jeremierichard** [krzysztofzablocki/Sourcery#697]
Hi,
For some reason I have a read-only file in my project.

When I specify this file's exclusion within config file as described in the documentation : 
```
sources:
    include:
      - .
    exclude:
      - ./excludedFolder
```

 I have error `file.extension isn't writeable` even if file.extension is in the excludedFolder

So I have moved all my included files into a specific folder that I only include in my config file : 
```
sources:
    include:
      - ./includedFiles
```
But the same error is raised even if file.extension is not in the includedFiles.

It seems that files are accessed in writeable mode even if they are excluded or  not included ?

**Comment by Cyberbeni** [comment]
Relates to #880 
@jeremierichard If I understand this correctly, passing a single file to output instead of a folder (or the default current folder) should solve this issue.

**Comment by krzysztofzablocki** [comment]
sounds like a bug, will take a look
