### ISSUE TITLE
Default values for variables

### ISSUE THREAD

**Issue by txaiwieser** [krzysztofzablocki/Sourcery#70]
It would be great to have the ability to access a default value assigned to a variable.

I would like to contribute if possible, just need some opinions and directions! :)

👍

**Comment by krzysztofzablocki** [comment]
that could be useful, the way I'd approach it would be to add tests to parser that has default value and then see whether sourcekitten feeds as those values, if not then you'd need to write manual parsing similar to how we are parsing annotations or typealiases

**Comment by ilyapuchka** [comment]
I first wanted to suggest to support method parameters default values for the sake of the consistency, but than I thought, how exactly that can be used in templates? 
Also default property values are not required to be simple literals, so it can be for example a method call or even a complex closure call, how that can be used in a template?

**Comment by krzysztofzablocki** [comment]
yeah I'm not sure about the use-case here as well, @txaiwieser what were you thinking about?

**Comment by krzysztofzablocki** [comment]
If we don't hear any reasonable use-case this week then we should probably close this

**Comment by brassel** [comment]
My use case is related to the one I posted in issue #210. I start Sourcery on a certain class. For certain methods I find in that class I generate new classes. Each class has a property for every parameter of the orginal method. So, e.g., I find a method

`func drawButton(showBorder: Bool = true, borderColor: UIColor = .red)`

I generate

`class MyButton : UIButton {
  showBorder : Bool,
  borderColor: UIColor
...}`

and, naturally, I would like to reuse the original default parameter, e.g.,

`class MyButton : UIButton {
  showBorder : Bool = true,
  borderColor: UIColor = .red
...}`

**Comment by brassel** [comment]
By now I created a workaround by reparsing Sourcery's `Method.name` and grabbing the information from there. But that really feels like unnecessary overhead.

**Comment by brassel** [comment]
To comment on ilyapuchka's comment above: I think my usecase would be just the same if the default values would be more complicated like complete closures. But my workaround mentioned above would stop to function. I know by construction of the code I scan with Sourcery that there will be no complex expressions. But in the general case you would have to expose the whole Expression class of the AST to do this, I realize from that comment. So, here are a few remarks with respect to that:

* you could just expose the default value as an unstructured string, as - I think - you do in other places as well
* if you expose the complete expression structure you could also greatly extend Sourcery in other places. E.g., you could give access to the method bodies as well.
