### ISSUE TITLE
[Question] Pass in a map to args

### ISSUE THREAD

**Issue by ethanjdiamond** [krzysztofzablocki/Sourcery#702]
Hello!

Is it possible to pass a map into a Sourcery template via --args? I'd like to parse a .yaml file and pass in the result into a Sourcery template, but the docs make it seem like --args can only be one variable deep (i.e. arguments.key instead of arguments.key0.key1.key2).

Is there a way to do what I want?

Thanks!

**Comment by ilyapuchka** [comment]
@ethanjdiamond arguments are just key value pairs of string keys to string values, there is no additional processing of values done on Sourcery side. What you describe is more like making Sourcery accept arbitrary structured data (could be in one or another format).

**Comment by ethanjdiamond** [comment]
Yeah, that is what I'm talking about. Is that possible or planned?

**Comment by ilyapuchka** [comment]
@ethanjdiamond no, this feature was not considered before
