### ISSUE TITLE
[Question] Add import in generated AutoMockable file

### ISSUE THREAD

**Issue by alexis-letexier** [krzysztofzablocki/Sourcery#703]
Hello !

I use Sourcery to mock my protocols with your AutoMockable template but my protocols require some import of my frameworks or apple frameworks (for example `UserNotifications`). 

Is is possible to add some imports without editing the AutoMockable template ?

Thanks a lot,

**Comment by ilyapuchka** [comment]
@alexis-letexier you can do it similar to LinuxMain template using `{{ argument.testimports }}`, to make it configurable instead of hardcoding your own imports, but this will still require changes in the template.

**Comment by alexis-letexier** [comment]
Yes I'll do it

**Comment by ned1988** [comment]
hi, was it merged? or can you help me to understand where to add `{{ argument.testimports }}` in `AutoMockable`

**Comment by amadeu01** [comment]
@denys-meloshyn 

One of the ways of doing so is:

```
// swiftlint:disable all
{% for import in argument.imports %}
import {{ import }}
{% endfor %}

{% for type in types.types|!enum where type.implements.AutoCopy or type|annotated:"AutoCopy" %}
// MARK: - AutoCopy for {{ type.name }}
extension {{ type.name }} {
    {{ type.accessLevel }} func copy({% for field in type.storedVariables %}{{ field.name }} : {{ field.typeName }}? = nil{% ifnot forloop.last %}, {% endif %}{% endfor %}) -> {{ type.name }} {
        return {{ type.name }}(
        {% for field in type.storedVariables %}
            {{ field.name }}: {{ field.name }} ?? self.{{ field.name }}{% ifnot forloop.last %}, {% endif %}
        {% endfor %})
    }
}

{% endfor %}
// swiftlint:enable all
```

Take a look at ` {{ type.accessLevel }} func copy`

And then in your config file:

```
sources:
...
templates:
...
output:
...
args:
  imports: 
    - SomeFramework
```

**Comment by vsnv** [comment]
@ilyapuchka @krzysztofzablocki  Hi guys! I have this case: 

File Foo.swift:
```
import UIKit

protocol Foo {
  var navigationController: UINavigationController { get set }
}

```

File Bar.swift:
```
// sourcery: AutoMockable
protocol Bar: Foo {
  func someFunc()
}
```
type.imports for Bar return [], but i need to get "import UIKit" somehow. Is it possible? Thx!

**Comment by ilyapuchka** [comment]
Hi. There is no such thing as Type.imports, you’ll need to use arguments to pass imports that you need via —args command line flag or in yaml config file. E.g. --args import=UIKit and then adjust template to access them in the templte as {{ arguments.import }}

Sourcery does not scan and aggregate imports from the source files - it’s not trivial, does not belong to any types, rather modules and their dependencies and we don’t handle modules.

Ilya Puchka

**Comment by vsnv** [comment]
@ilyapuchka ok, thank you very much 😃
