### ISSUE TITLE
Xcode Build gets Cancelled when using sourcery in Build Phase for test target

### ISSUE THREAD

**Issue by SunDog** [krzysztofzablocki/Sourcery#708]
So, I trying to use sourcery to generate mocks for my project but unfortunately every time I try to run the tests Xcode automatically cancels the build.

#### What version of Swift are you using (swift --version)?
>Xcode Version 10.1 (10B61)
Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
Target: x86_64-apple-darwin18.2.0

#### What did you do?
>Run tests with a buildPhase that runs sourcery and add the files to the testTarget

#### What did you expect to see?
>Test being executed normally 

#### What did you see instead?
>Xcode cancels build

---
Sample Project: https://github.com/SunDog/CancelBuildExample

**Comment by aramark-pivotal** [comment]
I am seeing the exact same issue.  My build fails for the reason: Cannot find file `MyFile.generated.swift`.  It looks like the file is in fact generated and subsequent builds work afterwards for me.  It seems it is trying to build the whole project, files included, in parallel with the generation script. Generation doesn't finish before build task looks for the file, so it stops.

**Comment by SunDog** [comment]
Unfortunately it's still not working for me :(

I updated the sample [CancelBuildExample](https://github.com/SunDog/CancelBuildExample) with your suggestion in case you want to see it but the result is still the same. Maybe you have other scripts running after Sourcery gives the compiler time to finish this linking.

So far I'm tracking generated file on git but sometimes it get's very inconvenient for code review and specially for CI.

Thank you very much!

**Comment by vsnv** [comment]
> Unfortunately it's still not working for me :(
> 
> I updated the sample [CancelBuildExample](https://github.com/SunDog/CancelBuildExample) with your suggestion in case you want to see it but the result is still the same, however, I must say that rate of success increased. Maybe you have other scripts running after Sourcery gives the compiler time to finish this linking.
> 
> So far I'm tracking generated file on git but sometimes it get's very inconvenient for code review and specially for CI.
> 
> Thank you very much!

Sorry for necroposting :) Maybe someone has this problem too: I solved it by using $(SCROOT) instead of $(PROJECT_DIR)
