### ISSUE TITLE
Running Sourcery from Mint - "Couldn't find executable 'argument'"

### ISSUE THREAD

**Issue by gbrhaz** [krzysztofzablocki/Sourcery#710]
I have installed Sourcery 0.15.0 via Mint, and I'm running the command

'mint run sourcery --silent'

I have created a .sourcery.yml file because adding any kind of command line argument like --sources and --templates just throws an error with "Couldn't find executable --<argument>"

I'm not sure if this is a Sourcery issue or a Mint issue, but since the README says command line arguments vary depending on installation and doesn't explain how, I thought I'd post here first.

**Comment by ilyapuchka** [comment]
I don't think there is anything special required from tools to be built with Mint, so I suspect it might be an issue in Mint itself. cc @yonaskolb

**Comment by yonaskolb** [comment]
If passing arguments to a package via mint you have to specify the executable
```
mint run krzysztofzablocki/sourcery sourcery --sources ...
```

**Comment by Liquidsoul** [comment]
This seems to be an issue in your command-line call. Feel free to reopen if it was not the case.
