### ISSUE TITLE
Processing Parameter lists

### ISSUE THREAD

**Issue by vander2675** [krzysztofzablocki/Sourcery#711]
Hello, 
First of all, great Tool!

I'm trying currently to let Sourcery generate a version of the `copy` Function from `data class` Kotlin for my `structs` in Swift.

To accomplish this, I need to create the `func` with all stored variables of the `struct` as Parameters. My Problem with this right now is, that I need to insert a workaround using Annotation to detect if a Parameter is the last one in the `struct`, to omit the last colon.

Template:

```yml
import Foundation

//MARK: - Copyable for structs
{% for struct in types.implementing.Copyable %}
extension {{struct.name}} {
    {{ struct.accessLevel }} func copy(
    {% for var in struct.storedVariables %}
    {{ var.name }}: {{ var.typeName }}? = nil{% if var|!annotated:"lastProperty" %},{% endif %}
    {% endfor %}
    ) -> {{struct.name}} {
        return {{ struct.name }}(
          {% for var in struct.storedVariables %}
          {{ var.name }}: {{ var.name }} ?? self.{{ var.name }}{% if var|!annotated:"lastProperty" %},{% endif %}
          {% endfor %}
        )
    }
}
{% endfor %}
```

But this approach is error prone and does not scale very well. 

I just wanted to ask if there is already a better way to do this, but I  just haven't found it yet.

**Comment by ilyapuchka** [comment]
@vander2675 Stencil has a special for-loop variable that you can use for that - `forloop.last` (http://stencil.fuller.li/en/latest/builtins.html#for)

**Comment by vander2675** [comment]
Perfect. Thank you
