### ISSUE TITLE
Typo (“folter” -> “folder”)

### ISSUE THREAD

**Issue by mdznr** [krzysztofzablocki/Sourcery#712]
https://github.com/krzysztofzablocki/Sourcery/blob/85bdf335133a5594abf57cc4fa3d92d733534798/Sourcery/Sourcery.swift#L418

**Comment by ilyapuchka** [comment]
@mdznr mind submitting a PR?

**Comment by fishcharlie** [comment]
This looks to be fixed. Close this issue?
