### ISSUE TITLE
Installing via Mint, and then Homebrew still results in not being able to run .swifttemplate

### ISSUE THREAD

**Issue by gbrhaz** [krzysztofzablocki/Sourcery#713]
I installed Sourcery 0.15.0 using Mint first, but since the AutoCodable template is a .swifttemplate, I decided to try with Homebrew instead.

Unfortunately, running 'mint uninstall sourcery' and then 'brew install sourcery' I still get the error 

warning: Skipping template AutoCodable.swifttemplate. Swift templates are not supported when using Sourcery built with Swift Package Manager yet. Please use only Stencil or EJS templates. See https://github.com/krzysztofzablocki/Sourcery/issues/244 for details.

I have also tried deleting all known instances of sourcery in /usr/local and ~/Library/Caches/Homebrew

**Comment by ilyapuchka** [comment]
@gbrhaz as the error message says swift templates are not supported for SMP builds (both Homebrew and Mint use it build Sourcery binary from its sources). 

@Liquidsoul have this constraint been lifted with #681 ? If yes, I suppose we need to drop this check and update docs to reflect it.

**Comment by Liquidsoul** [comment]
@ilyapuchka you are right, once a version with #681 is released, swift templates will be available when using SPM. I'll look into double-checking that fact and make the changes to drop the check alongside the docs update.
