### ISSUE TITLE
Is there a way to resolve transitive inheritance?

### ISSUE THREAD

**Issue by cornr** [krzysztofzablocki/Sourcery#714]
I have build three templates `AutoEquatable` `AutoHashable` `AutoCustomStringConvertible` for which a created marker protocols. Everything works as expected.
Now I see we have tons of "Plain Objects" classes which all implements those 3 marker protocols. My Idee is to create a new marker protocol `AutoPlainObject` which inherits from `AutoEquatable` `AutoHashable` `AutoCustomStringConvertible`.

My problem now is how to resolve these transitive implements.
In `{{type.based}}` and `{{type.inheritedTypes }}` only direct inheritance is included. Is there a way to resolve transitive inheritance?

**Comment by ilyapuchka** [comment]
@cornr there is an issue for that with proposed design https://github.com/krzysztofzablocki/Sourcery/issues/541 but ATM this is not supported
