### ISSUE TITLE
Cant generate using interpolated variable values

### ISSUE THREAD

**Issue by pkasson** [krzysztofzablocki/Sourcery#716]
I don't see how one can generate header comments in a generated file with a commented value such as:

// generated. 2019-01-02 at 6:17:50 EST

Is it possible to execute code and get values back, such as the date and time example above?

**Comment by dmsl1805** [comment]
@pkasson I don't think it is possible to do with Stencil template. But should be easy with Swift template. I have not tried JS, but could be also possible

**Comment by ilyapuchka** [comment]
@pkasson Stencil has a tag `now`. With swift or JS templates you can execute any code in the template. You can't change the default comment, but you can add your own as the first line of your template.

**Comment by pkasson** [comment]
I knew you guys would know the way ... just starting out with Sourcery - its way cool.

Where can I get a good link on using Swift templates ?

**Comment by ilyapuchka** [comment]
There is a short reference in the docs and you can look at AutoCodable template as an example.
