### ISSUE TITLE
{{ type.inherits }} -isKindOfClass vs -isMemberOfClass?

### ISSUE THREAD

**Issue by MattW86** [krzysztofzablocki/Sourcery#719]
Hi,
My expectation from {{ type.inherits.NSObject }} is to be true for a UITableviewCell subclass. Is my understanding incorrect? or how can I achieve this? Cheers..

**Comment by krzysztofzablocki** [comment]
Sourcery doesn't know what `UITableViewCell` is or what it inherits from, if your classes inherit (explicitly as in the source that is scanned by the Sourcery) from `UITableViewCell` you can use `type.based.UITableViewCell`
