### ISSUE TITLE
Crash when using AutoMockable in methods with more than one param.

### ISSUE THREAD

**Issue by grsouza** [krzysztofzablocki/Sourcery#720]
Hi, I'm using the provided AutoMockable template, but I'm getting a crash when trying to mock the following protocol.

```swift
protocol RegisterInteractable: class, AutoMockable {
    func signUp(name: String, email: String, password: String, confirmPassword: String) -> Single<Void>
}
```

I noticed that the crash happens when trying to mock methods with more than one param.

The crash is:

`Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<SourceryRuntime.MethodParameter 0x7fc3d1821170> valueForUndefinedKey:]: this class is not key value coding-compliant for the key unwrappedTypeName if param.'`

Anyone knows how to solve this problem?

**Comment by krzysztofzablocki** [comment]
something seems off here, our tests cover that use-case and don't crash, do you have a sample test or project to reproduce?

**Comment by ilyapuchka** [comment]
This seems to be an error in the template because the crash log mentions `unwrappedTypeName if param` as a key

**Comment by ilyapuchka** [comment]
Which probably means that the template with a `if-else` stencil syntax is used with an older version of Sourcery, which does not support this syntax.

**Comment by grsouza** [comment]
I've made some changes to the original template, if you wan't, I can send a pull request
