### ISSUE TITLE
Not apply arguments in cli params, when configuration file exists.

### ISSUE THREAD

**Issue by noppefoxwolf** [krzysztofzablocki/Sourcery#726]
https://github.com/krzysztofzablocki/Sourcery/blob/master/Sourcery/main.swift#L104

When confuguration file exists, Looks like args used by just check configuration exists.
And, I cannot found test for apply argument in cli params.

**Comment by noppefoxwolf** [comment]
https://github.com/krzysztofzablocki/Sourcery/blob/master/Sourcery/main.swift#L104

When confuguration file exists, Looks like args used by just check configuration exists.

**Comment by noppefoxwolf** [comment]
https://github.com/krzysztofzablocki/Sourcery/blob/master/Sourcery/main.swift#L152
Umm, I found warning message.
But I think that arguments should merge with yml configuration.

**Comment by ilyapuchka** [comment]
@noppefoxwolf can you please rephrase the problem?
