### ISSUE TITLE
Detect open variables, methods and classes

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#73]
As in Swift not everything is automatically overridable there should be a way to check for that in templates to not try to override these methods/variables or subclass non-open classes. Can be implemented by adding `isOpen` property to methods, properties and classes. 

@krzysztofzablocki should we also add a dedicated type `Class` and move there properties like `supertype`, `inherits` and this new property as they are not applicable for structs, enums and protocols?

**Comment by krzysztofzablocki** [comment]
yeah I was thinking we probably should introduce separate Class type
