### ISSUE TITLE
AutoCases outputs lacks commas

### ISSUE THREAD

**Issue by AmitaiB** [krzysztofzablocki/Sourcery#730]
For the enum:
```swift
enum SciFiVillions: AutoCases {
    case cylons
    case klingons
    case vogons
}
```
under the current AutoCases template, this was generated:
```swift
internal extension SciFiVillions {
static let count: Int = 3
static let allCases: [SciFiVillions] = [
  .cylons
  .klingons
  .vogons
]
}
```
The hierarchy is flattened, and the commas do not get applied.

Possible Solution:
- adjust template:
```
{% for enum in types.implementing.AutoCases|enum %}
{{ enum.accessLevel }} extension {{ enum.name }} {
    static let count: Int = {{ enum.cases.count }}
{% if not enum.hasAssociatedValues %}
    static let allCases: [{{ enum.name }}] = [
{% for case in enum.cases %}        .{{ case.name }},
{% endfor %}        ]
{% endif %}
}
{% endfor %}
```
Under polished template, you get:
```swift
internal extension SciFiVillions {
    static let count: Int = 3
    static let allCases: [SciFiVillions] = [
        .cylons,
        .klingons,
        .vogons,
        ]
}
```
Everything spaced appropriately, and syntactically correct.

I was going to make a PR, but the Guidelines scared me off.

**Comment by krzysztofzablocki** [comment]
not sure how the new template format got into 0.15 since the stencil update seems to have happened later on but the templates are correct in master, we just need to make a new release

**Comment by Liquidsoul** [comment]
I’m working on doing releasing a new version soon. Hopefully I’ll do this tomorrow.

**Comment by krzysztofzablocki** [comment]
new release is up and it should work with it
