### ISSUE TITLE
[Question] Is there a way to filter a type's storedVariables to create a new array to iterate on?

### ISSUE THREAD

**Issue by hooliooo** [krzysztofzablocki/Sourcery#733]
Is there a way to create a new array of variables to iterate through? I want to find only variables with a certain annotation. So I can do something like this:

`{% map type.storedVariables(filter this) into parameters using var %}{{ var.name }}: {{ var.typeName }}{% endmap %}`

and create:
`func someFunc({{ paramters|join:", "}}) -> SomeValue {`
 `.....`
`}`

**Comment by hooliooo** [comment]
Never mind. I switched to swifttemplate

**Comment by krzysztofzablocki** [comment]
That's what our filters are for, you just pipe using | operator and can use things like annotated:"something"
