### ISSUE TITLE
[Question] Is it possible to generate inline code AND generate the AutoEquatable/AutoHashable implementations from the generated properties in one go?

### ISSUE THREAD

**Issue by hooliooo** [krzysztofzablocki/Sourcery#734]
Let's say I have a stencil template:
```
{% for type in types.all %}
{% if type|annotated:"AutoGenerateProperties" %}
// sourcery:inline:auto:{{ type.name }}.AutoGenerateProperties
{% for var in type.storedVariables %}
    {{ type.accessLevel }} {% if var.isMutable %}var{% else %}let{% endif %} {{ var.name }}: {{ var.typeName }}
{% endfor %}
// sourcery:end
{% endif %}
{% endfor %}
```

I have a Fruit protocol annotated for sourcery
```
protocol Fruit {
    // sourcery: defaultValue: = "Apple"
    var name: String { get set }

    // sourcery: defaultValue: = "Red"
    var color: String { get set }

    // sourcery: skipEquality, skipHashing
    var size: CGSize: { get set }
}
```

and I have an Apple struct with no implementation yet:
```
// sourcery: AutoGenerateProperties,AutoEquatable,AutoHashable
struct Apple: Fruit{
}
```

When I run sourcery,  the inline code generation works BUT the AutoEquatable and AutoHashable implementations for Apple are empty. 

So, what I currently do is: 

1. Run sourcery
2. Delete  `// sourcery:inline:auto:{{ type.name }}.AutoGenerateProperties`, `// sourcery:end`, and the `AutoGenerateProperties` annotation from `Apple` 
3. Run sourcery again 

The AutoEquatable and AutoHashable implementations are correctly generated in the second sourcery call. 

Is there any way to do the inline code generation and AutoEquatable/AutoHashable generation in one sourcery command?

**Comment by krzysztofzablocki** [comment]
this is a bit surprising, the fact you use inline in one template should not break other templates, I assume you use our bundled Equality / Hashing templates (that don't have anything inlined) ?

**Comment by hooliooo** [comment]
Yes I am using the AutoEquatable and AutoHashable from https://github.com/krzysztofzablocki/Sourcery/tree/master/Templates/Templates

**Comment by krzysztofzablocki** [comment]
does the issue happen if you don't use `:auto` and just regular inline with manual markers?

**Comment by hooliooo** [comment]
It still happens.
I removed the generated lines and left only this on Apple:
```
// sourcery: AutoGenerateProperties,AutoEquatable,AutoHashable
struct Apple: Fruit{
// sourcery:inline:Apple.AutoGenerateProperties
// sourcery:end
}
```

Ran sourcery. It created the variables in my Apple.swift file but AutoEqutable.generated.swift has:
```
public func == (lhs: Apple, rhs: Apple) -> Bool {
    return true
}
```
AutoHashable.generated.swift has:
```
// MARK: - Apple AutoHashable
extension Apple: Hashable {
    public func hash(into hasher: inout Hasher) {
    }
}
```

I've changed the template to:
```
{% for type in types.all %}
{% if type|annotated:"AutoGenerateProperties" %}
// sourcery:inline:{{ type.name }}.AutoGenerateProperties
{% for var in type.allVariables %}
    {{ type.accessLevel }} {% if var.isMutable %}var{% else %}let{% endif %} {{ var.name }}: {{ var.typeName }}
{% endfor %}
// sourcery:end
{% endif %}
{% endfor %}
```

**Comment by krzysztofzablocki** [comment]
but your `Apple` type doesn't have any variables, so what else would you expect to be generated?

**Comment by hooliooo** [comment]
I see. So let's say the Fruit protocol has all the necessary Equatable and Hashable properties and I rewrite how AutoEquatable and AutoHashable work, it would be possible since those templates would make Sourcery read the properties from the Fruit protocol instead?

**Comment by hooliooo** [comment]
Yeah it works. Sorry about that 😅. I didn't think about the AutoEquatable and AutoHashable templates
