### ISSUE TITLE
Non-empty generated file with inline-only stencil template

### ISSUE THREAD

**Issue by zSOLz** [krzysztofzablocki/Sourcery#738]
Hi all,
Current version (v0.16) generates xxx.generated.swift file for case when it should not be created. We are using template for inline-only code which looks like this:
```
{% for autoMockableType in types.all %}
// sourcery:inline:{{ autoMockableType.name }}.AutoMock
code
// sourcery:end
{% endfor %}
```
Previously (v0.15) the code was generated only inside inline sections:
```
class MockClass: NSObject, MockProtocol {
    // sourcery:inline:MockClass.AutoMock
    code
    // sourcery:end
}

```
But currently (v0.16) we have additional xxx.generated.swift generated by Sourcery with inline blocks for all other classes and files in our code:
```
// Generated using Sourcery 0.16.0 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

// sourcery:inline:___VARIABLE_productName___.AutoMock
code
// sourcery:end
// sourcery:inline:___VARIABLE_productName___Presenter.AutoMock
code
// sourcery:end
// sourcery:inline:___VARIABLE_productName___View.AutoMock
code
// sourcery:end
// sourcery:inline:___VARIABLE_productName___ViewController.AutoMock
code
// sourcery:end
```

Is it a bug or I missed something?

**Comment by krzysztofzablocki** [comment]
I noticed that yesterday, I'll take a look at whats going on

**Comment by zSOLz** [comment]
> I noticed that yesterday, I'll take a look at whats going on

Hi there! Any updates about this issue?

**Comment by ilyapuchka** [comment]
`___VARIABLE_productName___` suggests that Sourcery scanned Xcode templates, or did you just use that as a placeholder? If that's the case exclude templates from scanning to avoid this.

I think that this can be a result of [this change](https://github.com/krzysztofzablocki/Sourcery/pull/692), but it seems as a valid use case.

**Comment by zSOLz** [comment]
> `___VARIABLE_productName___` suggests that Sourcery scanned Xcode templates, or did you just use that as a placeholder? If that's the case exclude templates from scanning to avoid this.
> 
> I think that this can be a result of [this change](https://github.com/krzysztofzablocki/Sourcery/pull/692), but it seems as a valid use case.

Thank you for the answer. Unfortunately in my sample output I kept only few files. Real generated file includes thousands of our classes. Templates are just a part of them.
I reproduced the issue in the sample project which is attached to the post:
- Unarchive
- Do pod install (Sourcery version should be 0.16.0 or 0.16.1)
- Open the project and build it (Sourcery runs at the end of build phase)
- Check `StencilGenTest/Sourcery/Configs/GenerateMock.generated.swift`, It contains inline code that basically should not be there
- If you **pin** Sourcery version to 0.15.0, then **delete** `GenerateMock.generated.swift` and do the same steps again, you can see the file `GenerateMock.generated.swift` will no longer be created

[StencilGenTest.zip](https://github.com/krzysztofzablocki/Sourcery/files/3137993/StencilGenTest.zip)

**Comment by ilyapuchka** [comment]
This is a result of #692 and is now expected behaviour - if there is no destination for inline annotations the code will no longer be stripped out. See the original issue for rationale. If you need code to be not generated you'll have to adjust templates to skip the types you are not interested in, or only process types that are explicitly marked.

**Comment by zSOLz** [comment]
Thank you for answer.
> If you need code to be not generated you'll have to adjust templates to skip the types you are not interested in
Think there is no way to skip files expect put all of them explicitly to the template. In our case it wouldn't help because it's about thousand of such classes.
> or only process types that are explicitly marked
That's probably could be a solution. Thank you.

**Comment by ilyapuchka** [comment]
We can think about annotating template with something like `sourcery:inline:strip_generated_code:true/false` to additionally control this behaviour

**Comment by zSOLz** [comment]
> We can think about annotating template with something like `sourcery:inline:strip_generated_code:true/false` to additionally control this behaviour

Yes, that would be really helpful! Right now I should do two steps - explicitly set class as a 'AutoMockable' and add inline section. Would be much better to do it in one step.

**Comment by ilyapuchka** [comment]
If you only need inline annotations and don't need separate generated file at all you can as well just remove it after running Sourcery in the build step
