### ISSUE TITLE
AutoMockable template references '*Invocations' instead of 'ReceivedInvocations'

### ISSUE THREAD

**Issue by lordcodes** [krzysztofzablocki/Sourcery#740]
In the provided AutoMockable template, it generates a property that has 'ReceivedInvocations' in its name. However, the references to this property that are generated incorrectly use 'Invocations' with 'Received' missing.

This means that the AutoMockable.swift that is generated won't compile.

**Comment by krzysztofzablocki** [comment]
this is fixed on master and will be deployed in next release

**Comment by lordcodes** [comment]
@krzysztofzablocki Excellent, thank you.
