### ISSUE TITLE
Error while rendering swift templates

### ISSUE THREAD

**Issue by pjechris** [krzysztofzablocki/Sourcery#741]
- What version of Swift are you using (swift --version)?
4.2.1

- What did you do?
Tried to render a swift template with Sourcery 0.16.0

- What did you expect to see?
A successful rendering

- What did you see instead?
Sourcery generates an I/O error (with both Cocoapods and brew version):

```
Rendering template AnnotationInject/Templates/Register.swifttemplate
error: Error Domain=NSCocoaErrorDomain Code=4 "The folder “context.bin” doesn’t exist." UserInfo={NSFilePath=/var/folders/f8/3ms78sln7cn0mylv4v903ykm0000gn/T/SwiftTemplate/0.16.0/context.bin, NSUserStringVariant=Folder, NSUnderlyingError=0x7fa04767ec90 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

**Comment by krzysztofzablocki** [comment]
same as https://github.com/krzysztofzablocki/Sourcery/issues/739, try nuking the cache per last comments there

**Comment by Liquidsoul** [comment]
It appears that we may have a bug here, I am on it.
Try creating the folders manually as a workaround for now (`/var/folders/f8/3ms78sln7cn0mylv4v903ykm0000gn/T/SwiftTemplate/0.16.0/` in your example @pjechris)

**Comment by pjechris** [comment]
Erf should have double-checked open issues, sorry :(
FYI nuking and creating folder are working as long as I don't restart my computer.
