### ISSUE TITLE
[Question] is it possible to define a custom argument in .sourcery.yml to use in a .stencil or .swifttemplate?

### ISSUE THREAD

**Issue by hooliooo** [krzysztofzablocki/Sourcery#742]
So I have some templates that generates files and I want to use the custom argument in my .sourcery.yml file:
```
{% for type in types.all %}
// sourcery:file:Generated/{{ argument in yml file here }}+TemplateName
// sourcery:end
{% endfor %}
```

Is this possible? Maybe its obvious but I didn't see any literature on this kind of functionality

**Comment by krzysztofzablocki** [comment]
can't you leverage `--args` for this?

**Comment by hooliooo** [comment]
Sorry I wasn’t clear. How do you use your defined arg1=foo in the .source.yml file in a stencil 😅

**Comment by hooliooo** [comment]
Found it 😅 missed that bit about arguments
