### ISSUE TITLE
support for Xcode 10.2 swift5 

### ISSUE THREAD

**Issue by rootpassword** [krzysztofzablocki/Sourcery#743]
I have try with "rm -rf /Library/Caches/Sourcery" and "--disableCache", but it`s does not work.The Xcode show error With "module compiled with Swift 4.2 cannot be imported by the Swift 5.0 compiler: /var/folders/xc/36050s51s4qwthtcyhgh0000gn/T/SourceryRuntime.framework/Modules/SourceryRuntime.swiftmodule/x86_64.swiftmodule
import SourceryRuntime"

**Comment by Liquidsoul** [comment]
I suppose that you're using version 0.15.0 of Sourcery which is not compatible with the Swift 5.0 compiler. This is a known issue that's been around for every Swift release.
However, from version 0.16.0, this will not be an issue anymore.
So if you need to use the Swift 5.0 compiler, please use version 0.16.0.
