### ISSUE TITLE
Inline generated code has whitespace on empty lines

### ISSUE THREAD

**Issue by marcelofabri** [krzysztofzablocki/Sourcery#747]
After https://github.com/krzysztofzablocki/Sourcery/pull/731, the inline generated code contains whitespace in the same number as the `// sourcery` annotation on lines that should be empty.

This is a problem for us because we use SwiftLint to validate that there're no trailing whitespaces in the source code.

We removed the empty line to workaround the issue in our case, but it'd be good to fix this.

**Comment by marcelofabri** [comment]
@Liquidsoul can we have a new release with this fix?

**Comment by Liquidsoul** [comment]
I'll see if I can release a `0.16.1` with this fix by the end of the week (if @krzysztofzablocki is ok with that of course 😉 )
