### ISSUE TITLE
Generic arguments

### ISSUE THREAD

**Issue by kzaher** [krzysztofzablocki/Sourcery#75]
Hi, is there a way to get generic arguments of structs, classes ...?

**Comment by krzysztofzablocki** [comment]
Not right now, right now we only have is generic to run templates on non generic classes. 

Generics are pretty complicated to support and usually not generate boilerplate, curious what's the use case you'd like to use it for?

**Comment by kzaher** [comment]
Well I have something like this:

```
public struct Connections<Service>: AutoEquatable, AutoLens {
    public let xxxxxxxConnection: XXXXConnection<Service>
    public let yyyyyConnection: YYYYConnection
    }
}
```

My starting point was
https://gist.github.com/FilipZawada/934397bbef58e529762aff571a59d9b0

I've also taken a look at Kickstarter app and their source code.

I'm trying to introduce lenses for part of my codebase. There was no way I would decide to write all that code by hand, but I thought I could give it a shot by using this project. 

The problem is that even though some of them are simple, they have generic arguments. It looks like this is a deal breaker for both lenses and using this project to generate the code.

I guess I could theoretically create some additional protocols for lenses and hack something out, but  not sure is there actually a simple way to get this. I've tried to check out Sourcery code base and SourceKitten output, but couldn't find anything usable.

Right now I'm back to using `var`s, but I'm curious did I miss something obvious.

Yeah, I understand why introducing generics is a complex request, but just wanted to ask to confirm or disprove my suspicions.

**Comment by krzysztofzablocki** [comment]
Without modyfing Sourcery, I think you could introduce typealias and use that in template, alternative would be to leverage our annotation system which is really flexible.

**Comment by kzaher** [comment]
Thnx for answering,

lenses are not that critical for me right now.
