### ISSUE TITLE
[Enhancement] Switch the lib Commander to another CLI library

### ISSUE THREAD

**Issue by Cookiezby** [krzysztofzablocki/Sourcery#754]
Hi I found the current Commander library can only receive 14 parameter, Considering Sourcery is a really powerful tool for generating code automatically, It may be necessary to improve the ability of the command line. 

I found the lib [Commandant](https://github.com/Carthage/Commandant) which Carthage is currently using can be a good choice.  I am willing to help if the suggestion can be accepted.

**Comment by ilyapuchka** [comment]
having too many arguments is IMO a sign that the interface should change, i.e. using environment variables for some parameters

**Comment by Cookiezby** [comment]
Thank you for your reply, I agree with you that too many arguments is not a good sign.  

The original thought is that I hope to add an option while generating the code through cli, the head comment on top of the file will not be added. I know it is important to tell people that the code is generated by the library, but maybe it will be better to offer an option to user. what do you think about that, or do have any idea for the upgrade of the interface?  Thanks @ilyapuchka
