### ISSUE TITLE
import Sourcery to another swift library

### ISSUE THREAD

**Issue by Cookiezby** [krzysztofzablocki/Sourcery#757]
Thanks for the update of 0.16.1, Sourcery is now able to be imported by SPM. However, I find that not all of the libraries are included in the products

```swift
products: [
    .executable(name: "sourcery", targets: ["Sourcery"]),
    .library(name: "SourceryRuntime", targets: ["SourceryRuntime"]),
    .library(name: "SourceryJS", targets: ["SourceryJS"]),
    .library(name: "SourcerySwift", targets: ["SourcerySwift"]),
    // SourceryFramework ?
],
```
when I try to parse some file use Sourcery, I found some classes are lost like FileParse which belongs to SourceryFramework. Other dependencies like StencilKit is also not included, It seems that If I want to generate the code this library is also necessary.

```swift
products: [
    .executable(name: "sourcery", targets: ["Sourcery"]),
    .library(name: "Sourcery", targets: ["Sourcery"]),
],
// this can import all the dependencies Sourcery is using.
```
I am quite new to the SPM, Is this the correct way to solve this problem?

**Comment by ilyapuchka** [comment]
I think what's missing is the SoruceryFramework as a product?
