### ISSUE TITLE
Sourcery 0.16.X fails to generate cases

### ISSUE THREAD

**Issue by steverichey** [krzysztofzablocki/Sourcery#759]
I've tried 0.16.0 via Homebrew, the 0.16.1 binary from the releases tab, and building from source (after adding some #available checks to allow Sourcery to compile). In all cases, templates generated empty cases inside an enum, e.g.:

    enum SomeUniqueEnum: String {
        case
        case
    }

And so on. I have one stencil file that generates enums for a number of types in my codebase to fulfill protocol conformance. I was eventually able to resolve this issue by reverting to 0.15.0. I am using Xcode 10.2.1 and macOS 10.14.4.

**Comment by ilyapuchka** [comment]
@steverichey can you please submit a pull request with a test that fails to demonstrate this issue? or at least with a template code that results in it (not full template please, only relevant pieces)?

**Comment by krzysztofzablocki** [comment]
this template is incorrect, you are mixing things up, you either:

1. wanted to use global `type.` subscript that is a sibling of `types.` but you overwrote it in your for loop so you are trying to access something that doesn't exist in this context
2. wanted to use containedTypes of your parent type, but forgot that part

Either way fix is either not overriding the global argument or simply using `type.containedType.DefinedCases.cases.` in the inner for loop
