### ISSUE TITLE
Discovering types stored in linked frameworks

### ISSUE THREAD

**Issue by bivanov** [krzysztofzablocki/Sourcery#763]
I have following layout:

- `Proto.framework` with public protocol, say, `MyProtocol`
- `Impl1.framework` that has `Proto.framework` as pod dependency and presents public class `Impl1` that conforms to `MyProtocol`
- Binary build of `Impl1.framework` that stored somewhere else, called `Impl1Binary.framework`
- iOS application project that has both `Proto.framework` and `Impl1Binary.framework` as pod dependencies; it has access to `Impl1` class and has own implementation of `MyProtocol` called `DefaultImpl`

So, in the end I have two classes that conform to `MyProtocol`. I would like to observe them with Sourcery, for example, in next manner:

```
{% for type in types.based.MyProtocol %}
    {{ type.name }}
{% endfor %}
```

Not so much surprising, I can only see `DefaultImpl` mention in generated source. What I can see here is that Sourcery is aware of `MyProtocol`, but is not aware of any implementations aside of specified project (that is fully logical). So my question is if there is any way to specify compiled frameworks as definition sources?

NB: There was some discussion [here](https://github.com/krzysztofzablocki/Sourcery/issues/87), but I'm not sure what was the outcome.

**Comment by ilyapuchka** [comment]
There was no outcome of previous discussions. There were some tips of how this could be possibly done technically for iOS frameworks, not sure about 3rd party frameworks, but there were no progress on that. You'll have to use annotations or other ways to help Sourcery understand code that it does not scan.
