### ISSUE TITLE
Handle closure types

### ISSUE THREAD

**Issue by ilyapuchka** [krzysztofzablocki/Sourcery#77]
As mentioned in #72 we may add support for closures, to detect variables/method parameters types being closures, detect number and types of their arguments (may correlate with #48). Will require to strip unneeded spaces as SourceKit does not do that for type names

**Comment by krzysztofzablocki** [comment]
@ilyapuchka do we want to add just basic `closure as parameter` handling to #72 before merging? I'm thinking that without this it might prevent implementing some features with method reflection?

**Comment by ilyapuchka** [comment]
As for now I'm imagining using methods reflection for generating methods overrides and being able to construct a method calls, but all of that will require at most passing parameters to original method using their names, as maximum knowing their type names, but no more info about arguments is required. 
For 1.0 I would maybe even limit closures support by just detecting closures and stripping unneeded white spaces in their signature.

**Comment by krzysztofzablocki** [comment]
@ilyapuchka yeah that was my thinking, so do you want to add that to your pr before we merge it?

**Comment by ilyapuchka** [comment]
I was thinking to do that separately, maybe along with tuples support
