### ISSUE TITLE
Support Carthage

### ISSUE THREAD

**Issue by BowdusBrown** [krzysztofzablocki/Sourcery#771]
Thanks for this amazing project. Would love support for Carthage.  

A framework was [discussed in the past](https://github.com/krzysztofzablocki/Sourcery/issues/388#issuecomment-319017922). Is a framework now available?

Other discussions.
https://github.com/krzysztofzablocki/Sourcery/issues/67 https://github.com/krzysztofzablocki/Sourcery/issues/388

**Comment by Liquidsoul** [comment]
There is no official Carthage support but I do not see why this would not work as all our framework schemes are shared. So Carthage should be able to build the Sourcery frameworks.

Maybe you could try to do a Carthage integration in your project and give us some feedback?

**Comment by BowdusBrown** [comment]
Thanks for response.

Carthage completed an update cycle successfully.

### Cartfile
```ruby
github "krzysztofzablocki/Sourcery" == 0.16.1
```

### Output
```bash
$ carthage update Sourcery
*** Cloning Sourcery
*** Checking out Sourcery at "0.16.1"
*** xcodebuild output can be found in /var/folders/vl/630ywf4s62j1ppzyh271sdb80000gn/T/carthage-xcodebuild.sgrvg6.log
*** Downloading Sourcery.framework binary at "0.16.1"
*** Building scheme "SourceryJS" in Sourcery.xcworkspace
*** Building scheme "SourceryRuntime" in Sourcery.xcworkspace
*** Building scheme "SourceryFramework" in Sourcery.xcworkspace
*** Building scheme "SourcerySwift" in Sourcery.xcworkspace
```

### Generated
<img width="289" alt="Screenshot 2019-07-13 at 06 18 40" src="https://user-images.githubusercontent.com/51816980/61167386-1de6e900-a536-11e9-8641-c0d714e6a9d4.png">

### Problem
I have attempted to run all of them as an Xcode `run script` build phase on my iOS project.

I'm not sure which binary to execute and I suspect these frameworks will only work for Mac targets anyway.

`Cannot execute binary file.`

```bash
./Carthage/Build/Mac/SourcerySwift.framework/Versions/A/SourcerySwift --config ./.sourcery.yml
```

I really like what @bradhilton did here https://github.com/krzysztofzablocki/Sourcery/issues/67#issuecomment-449759900 and it would be awesome to at least achieve that in the short term.

**Comment by Liquidsoul** [comment]
So if I understand your objective, you would like to run the Sourcery CLI in your project using Carthage?

Unfortunately for you, this is not something we will be supporting anytime soon, I don't even think that is even possible with Carthage.

Carthage is a tool for dependency management. It will generate frameworks for you to import, it will not generate binaries to run.
All you can do with Carthage is integrate our frameworks as dependencies but this will not give you the full power of Sourcery because we do not expose a `SourceryCLI` framework for you to build upon. I don't think that making such a framework is a rework that we wish to do. And more importantly this would not solve your use case. This would be more of a way to _extend_ Sourcery, not to use it as it is in a project.

You have plenty of other options to use Sourcery in your project that [we support](https://github.com/krzysztofzablocki/Sourcery#installation).

**Comment by BowdusBrown** [comment]
Thanks for the response.

**Comment by uli-objectbox** [comment]
@BowdusBrown When I asked the Carthage developers about a situation like this, they said it's not _really_ supported. However, there is one workaround they mentioned: Create a "fake framework" of your own that contains the CLI tool's binary. Nobody ever links to that framework, but you can Carthage will download the fake framework and you can reference the file in it. It's an ugly solution, but it would be an option.

But one of your comments sounds like you want to run the Sourcery CLI on iOS? You can't run CLI tools on iOS AFAIK. Sourcery will only be useful either if your app uses the framework to process files on iOS, or if you use the CLI tool on a Mac as part of the build process.

**Comment by BowdusBrown** [comment]
Hi @uli-objectbox thanks for the response.
At the moment, I am running Sourcery CLI as a build phase in my iOS project.
I was hoping to get the installation steps [here](https://github.com/BowdusBrown/Records/wiki/Installation) down from 4 steps, to 3 steps by somehow getting Carthage to build sourcery (as a CLI tool) and then run it. I appreciate a custom script could do this, via homebrew. But I was kinda hoping it could be more local to my project somehow. Maybe a build phase would build sourcery in my project directory somewhere and cache it there for all future builds, so the CLI doesn't get installed in /usr/local/bin which is more global. I dunno, just thinking out loud.
