### ISSUE TITLE
Sourcery cache doesn't seem to work

### ISSUE THREAD

**Issue by kean** [krzysztofzablocki/Sourcery#774]
Hi, 

We are using Sourcery 0.16.1 and we have some performance issues. The cache doesn't seem to work.

We currently scan roughly 100k lines of code total. Sourcery takes the same amount of time to run, no matter whether the cache is there or not (I clear the Sourcery caches folder to test it). What is more interesting, is that disabling caches actually improves the performance:

Without `--disableCache`:

```
~> sourcery
Scanning sources...
Found 3162 types.
Loading templates...
Loaded 1 templates.
Generating code...
Finished.
Processing time 15.028859972953796 seconds
```

With `--disableCache`:

```
~> sourcery --disableCache
Using configuration file at '.sourcery.yml'
Scanning sources...
Found 3162 types.
Loading templates...
Loaded 1 templates.
Generating code...
Finished.
Processing time 10.06436002254486 seconds
```

**Comment by krzysztofzablocki** [comment]
This happens because our symbol resolution clashed with sourcekitten so we were comparing different `Version` objects and the cache was always considered incorrect

**Comment by kean** [comment]
Thank you, @krzysztofzablocki! I really appreciate your quick response, we will migrate to the new version as soon as it is out.
