### ISSUE TITLE
Environment variable substitution fails if variable is not present

### ISSUE THREAD

**Issue by CatalinMustata** [krzysztofzablocki/Sourcery#780]
I'm working on a project where I'm using Sourcery to generate an Environment struct that contains API keys and secrets, configured from ENV variables. Previously, I was manually passing them as args in the Run Script command, but seeing as they can now be expanded in the `.sourcery.yml` file, I switched to this solution.

In the meantime, I have noticed that if the ENV variable is not defined in a specific build configuration, expansion is simply not performed, instead of it being expanded to nothing. Moreover, I've also noticed that if the arg is hardcoded to nothing, Sourcery treats it as a literal `<null>`

Is there any way to make this scenario (using a config file) behave just as passing empty args through the command line?

**Comment by krzysztofzablocki** [comment]
You could make a PR with the changes needed to make it behave more like shell, @Lutzifer original work was here https://github.com/krzysztofzablocki/Sourcery/pull/724

**Comment by CatalinMustata** [comment]
I'm not familiar with what's going on, but I can give it a shot.

**Comment by CatalinMustata** [comment]
Added the PR: https://github.com/krzysztofzablocki/Sourcery/pull/781

**Comment by CatalinMustata** [comment]
Fixed the PR and tested my changes locally - all works as expected now.
