### ISSUE TITLE
[suggestion] add "@" to the annotation mark?

### ISSUE THREAD

**Issue by alexlee002** [krzysztofzablocki/Sourcery#784]
the annotation is like this:
```
// sourcery: 
```
it's easy to be taken as useless comments,   Can add “@” at the beginning?  looks like this:

```
// @sourcery:
```

**Comment by ilyapuchka** [comment]
we are following swiftlint footsteps here, which I believed used in other Swift tools, this format should be familiar for those familiar with them and is easy to get used to. It's also common that sourcery and swiftlint annotations would come together especially for inlined code, where for some reason swiftlint rules shouldn't be enforced, so keeping them aligned is better.

**Comment by alexlee002** [comment]
can we suggest swiftlint to support the new format?  here is another  swift annotation tool:

```swift
@saber.scope(App)
```
this seems looks more like the annotation in other languages.
