### ISSUE TITLE
Sourcery doesn't work on macOS 10.15 beta

### ISSUE THREAD

**Issue by Titaniys** [krzysztofzablocki/Sourcery#787]
🌱  Using krzysztofzablocki/Sourcery 0.16.2 from Mintfile.
🌱  Sourcery 0.16.2 already installed
🌱  Running sourcery 0.16.2...
dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /usr/local/lib/mint/packages/github.com_krzysztofzablocki_Sourcery/build/0.16.2/sourcery
  Reason: image not found

**Comment by daveanderson** [comment]
On 10.15 19A583 I'm hitting a `This copy of libswiftCore.dylib requires an OS version prior to 10.14.4` which may or may not be related.

**Comment by daveanderson** [comment]
I resolved my issue by deleting `~/Library/Caches/Sourcery` and trying again. The cached copy of `mergeable.swifttemplate` was trying to use the pre-10.14.4 libswiftCore.dylib

**Comment by mgray88** [comment]
> On one macOS 10.15 19A583 machine I'm hitting a `This copy of libswiftCore.dylib requires an OS version prior to 10.14.4` which may or may not be related. On another one it works fine.

Still encountering this issue on 10.15.1, the above solution deleting the cache did not solve the problem

Could this be solved by building from source on my machine?

**Comment by krzysztofzablocki** [comment]
@mgray88 using .swifttemplate?

**Comment by mgray88** [comment]
@krzysztofzablocki Yes

```AutoCodable.swifttemplate: This copy of libswiftCore.dylib requires an OS version prior to 10.14.4.```

**Comment by anandabits** [comment]
FWIW, my team just ran into this issue with a .swifttemplate as well

**Comment by mgray88** [comment]
Built 0.17.0 from scratch on macOS 10.15.1, with Xcode 11.2.1 OR Swift 5.1.2 solves this issue

**Comment by dwsolberg** [comment]
@krzysztofzablocki Would it be possible for you to release an official version built in macOS 10.15.1 with Xcode 11.2.1? I have tested that this a build made in this way works in both the latest Mojave and Catalina and in Xcode 10.3 and Xcode 11.2.1.

**Comment by krzysztofzablocki** [comment]
I don't have Catalina installed because my work computer is locked out until the company verifies compatibility issues 😭, maybe one of our core contributors could make that release @ilyapuchka @Liquidsoul @Antondomashnev ?

**Comment by ilyapuchka** [comment]
@krzysztofzablocki I'm not updating as well because it constantly crashes for other colleagues =/

**Comment by Liquidsoul** [comment]
@krzysztofzablocki not updating either yet because I still use some 32bit apps I need to migrate from 😅
