### ISSUE TITLE
Remove ".generated" and change file name, HOW?

### ISSUE THREAD

**Issue by mendesbarreto** [krzysztofzablocki/Sourcery#792]
Hello everybody,

I am using Sourcery to build a script to create a project template Architecture, for example, I run a script called "/.create-feature.sh Login" and it will create the folder and class structure needed to start a new feature, which is something like CleanSwift already does. it seems like:

Feature
-- Login
-- ViewControllers -> LoginViewController.swift
-- ViewModels -> LoginViewModels
-- etc...

My problem is the Sourcery generates every file with the "fixname.generated.swift", so:
- I want to remove the ".generated." from the file name.
- I'd like to specify the name of my file base on the parameter which I pass when the script is executed.

This is because my idea is to auto-generate a structure that will work as a guide to accomplish the architecture thing. 

Any help will be appreciated.

Thank you for all

**Comment by krzysztofzablocki** [comment]
per file annotation in docs https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/writing-templates.html#per-file-code-generation

**Comment by mendesbarreto** [comment]
Thank you so much, this solved my problem, you saved my life hahaha.

**Comment by mendesbarreto** [comment]
One last question, I promise,

I am trying to link the files to the project, but I looked in the documentation and find only the option when you use the config file and when you use this option you can't use the flags to pass parameters, my script looks like:

```shell
sourcery \
--args feature="$FEATURE_NAME" \
--output "$FEATURE_LAYER_PRESENTATION/ViewController" \
--sources "$FEATURE_CONTROLLER_TEMPLATE" \
--templates "$FEATURE_CONTROLLER_TEMPLATE"
```

So you know some way to the sourcery acepts parameters and config file or some flag to link files to project.

Thank you so much.

**Comment by krzysztofzablocki** [comment]
I don't really use link feature, maybe @ilyapuchka knows?

**Comment by ilyapuchka** [comment]
we are limited on number of command line parameters we can have, so some more complicated configurations are available only through config files.

**Comment by ilyapuchka** [comment]
Speaking of your use case I use Xcode templates for that without any issues for quite some time already (with a git hook that checks if local templates are up to date with those stored in the repo)

**Comment by mendesbarreto** [comment]
Hello @ilyapuchka, thank you for your response.

> we are limited on number of command line parameters we can have, so some more complicated configurations are available only through config files.

I tried to mix the yaml with the params, but if the Sourcery finds the YAML file he ignores the params, or if I omit some properties on YAML and pass by parameters on the command line does not work as well.

------

> Speaking of your use case I use Xcode templates for that without any issues for quite some time already (with a git hook that checks if local templates are up to date with those stored in the repo)

Unfortunately, Xcode template doesn't solve my problem because I want to generate folders and some files on my project in one shot, the other reason I don't use Xcode to develop ahahahah, I use AppCode, so I am not sure if it will work.

But anyway, I am very grateful for your response guys.

**Comment by mendesbarreto** [comment]
I saw here the Appcode has the template as well, but not work the way I need =) .

Thank you for all
