### ISSUE TITLE
Adding support for `isOptional` filter

### ISSUE THREAD

**Issue by dingwilson** [krzysztofzablocki/Sourcery#793]
Any thoughts on adding support for an `optional` filter? (similar to the current `typeName.isOptional`) 

For example: I only want to generate a section of code, if a type contains an optional variable:

```swift
{% if type.variables|instance|optional %}
  // code here
{% endif %}
```

(or is there another way of approaching this?)

**Comment by krzysztofzablocki** [comment]
I'd be fine with it, send a pr :)

**Comment by dingwilson** [comment]
Sounds good @krzysztofzablocki! I will take a look at this tonight. 🚀
