### ISSUE TITLE
Sourcery doesn't see generated files as a resource?

### ISSUE THREAD

**Issue by ElviraBurchik** [krzysztofzablocki/Sourcery#796]
Hi!

I experience an issue with generating InjectionForwarding with generated Providers.

Currently, we use mocks generation and mocks generation in our project, and everything works fine.
Now I try to automate the generation of the following boilerplate code:
```
protocol ProtocolName {
    func foo()
}

protocol ProtocolNameProvider {
    var protocolName: ProtocolName { get }
}
```

.stencil file is simple:
```
{% for type in types.protocols where type|annotated:"Providable" %}
protocol {{ type.name }}Provider {
	var {{ type.name|lowerFirstLetter }}: {{ type.name }} { get }
}

{% endfor %}
```

When I re-generate InjectionForwarding after generating Providers, my services are removed from InjectionForwarding. It looks like Sourcery doesn't see generated files or smth like that, because when I create a new empty file in the project directory and just copy contents of generated files with Providers - everything works.

Could you please help me to understand what happens?

**Comment by ElviraBurchik** [comment]
Today I was able to find out the reason. 

If I remove the comment line 
`// Generated using Sourcery 0.17.0 — https://github.com/krzysztofzablocki/Sourcery`
everything works. So it looks like Sourcery really ignores generated files. 

Could you please tell me the motivation? Will it be safe to remove this line from generation? 
Thank you :)

**Comment by krzysztofzablocki** [comment]
you would cause chicken and egg situation, you can't use output as source in a single phase, you'd need to do 2-phase generation or just write 2 templates that generate them from real source (which I think you can given your use-case). 

If you don't want to write a template to use the real source then you'll need to to rely on the output of first phase, we support that and its documented in the readme under `force-parse`:

```
--force-parse - File extensions of Sourcery generated file you want to parse. You can provide multiple extension using multiple --force-parse options. (i.e. file.toparse.swift will be parsed even if generated by Sourcery if --force-parse toparse). Useful when trying to implement a multiple phases generation.
```

**Comment by ElviraBurchik** [comment]
Thanks for your help! Now it works
