### ISSUE TITLE
Support Swift 5.1's Property Wrappers

### ISSUE THREAD

**Issue by conradludgate** [krzysztofzablocki/Sourcery#803]
I have a struct where some of the fields are using some custom property wrappers. I want to be able to extract those values. Example

Using the Lazy property from this spec https://github.com/apple/swift-evolution/blob/master/proposals/0258-property-wrappers.md#delayed-initialization

```swift
protocol Test {}
struct Foo: Test {
    @Lazy var bar: Int = 1234
}
```

With the template

```stencil
{% for type in types.implementing.Test %}
extension {{type.name}} {
    func test() {
        {% for variable in type.variables %}
        print("{{variable.name}}", "{{variable.typeName}}")
        {% endfor %}
    }
}
{% endfor %}
```

I get

```swift
extension Foo {
    func test() {
        print("bar", "Int")
    }
}
```

But it doesn't have the value `_bar: Lazy<Int>`. Also, these property wrappers have support for projectedValue's too. In which case, `$bar: Lazy<Int>` would also be available, but the type would have to be known in that case.

**Comment by conradludgate** [comment]
Variables also support having multiple properties at once (see https://github.com/apple/swift-evolution/blob/master/proposals/0258-property-wrappers.md#composition-of-property-wrappers).
I'm not sure how this would be supported in Sourcery. There could be an array of properties on each variable, similar to how attributes are supported.

**Comment by ilyapuchka** [comment]
Unfortunately AFAIK property wrappers are not provided by SourceKit as part of types metadata so to support that we would need to parse wrappers manually which is quite cumbersome considering in how many ways they can be applied - in the same line vs separate & multiple lines, mixed with comments, mentioned multiple wrappers (though AFAIK it's not in 5.1 but already in swift master), with generic types and constructor arguments. We would also need to match wrappers usage with their declaration to figure out types of generated properties.

**Comment by daltonclaybrook** [comment]
Is this possible now that Sourcery is built on SwifySyntax rather than SourceKit? (cc: @krzysztofzablocki)

**Comment by daltonclaybrook** [comment]
I started sketching out some ideas for this. It looks like property wrappers are supported in SwiftSyntax via the `CustomAttributeSyntax` type.
https://github.com/krzysztofzablocki/Sourcery/compare/1.3.4...daltonclaybrook:dalton/property-wrappers

**Comment by krzysztofzablocki** [comment]
definitely doable now, I'd tweak the implementation to use real list instead of description string splitting in custom syntax case

**Comment by krzysztofzablocki** [comment]
@daltonclaybrook send me a pr when you finish 👍 I'm focused on SourceryPro app for a bit longer but will merge after

**Comment by daltonclaybrook** [comment]
@krzysztofzablocki Will do. I'll probably have some more time to look at this in the next few days.

**Comment by nikitamounier** [comment]
Hi! Just wanted to know, has there been any progress on this? I'm creating a "publification" template to make a type public using Sourcery Pro (I'm modularising my app into Swift packages) & make a public init if necessary, but have ran into the same problem of not being able to detect property wrappers.

**Comment by krzysztofzablocki** [comment]
not sure if @daltonclaybrook had any time to do finishing touches? if not you could pick up the code he linked and just apply my improvement if you are free? otherwise I can take a look when I get some time this week

**Comment by daltonclaybrook** [comment]
Hey folks, sorry for the neglect on this. Let me see if I can wrap this up today.
