### ISSUE TITLE
[Feature Request] Add support for TypeName.isSet

### ISSUE THREAD

**Issue by kennycarruthers** [krzysztofzablocki/Sourcery#805]
`TypeName` includes helpful properties like `isArray` and `array`, along with matching properties for `Dictionary` and tuples. It would be nice if equivalent properties were available for `Set`.

**Comment by krzysztofzablocki** [comment]
@kennycarruthers sounds good, would you be able to make a pr for that?

**Comment by art-divin** [comment]
#1281 adds this feature
