### ISSUE TITLE
Sourcery can't find classes inheriting from a generic class

### ISSUE THREAD

**Issue by BenoitCaron** [krzysztofzablocki/Sourcery#809]
Hi,
I'm attempting to list all the UIViewControllers of an app. Using the following stencil and sample classes, I managed to get some of them, but I'm am facing some limitations.

I am using the latest sourcery version as of now (0.17.0).

```stencil
let sourceryClasses =
[{% for type in types.based.UIViewController %}
    "{{type.name}}"{% if not forloop.last %},{% endif %}
{% endfor %}
]
```
```swift
class BaseViewController: UIViewController { }
class SubclassedBaseViewController: BaseViewController { }
class GenericBaseViewController<T: Equatable>: UIViewController { }
class SubclassedGenericBaseViewController: GenericBaseViewController<String> { }
```
The result here is 
```swift
let sourceryClasses =
[
    "BaseViewController",
    "GenericBaseViewController",
    "SubclassedBaseViewController"
]
```
As you can see, the last class is missing. How come?

**Comment by art-divin** [comment]
🕵🏻  Hello,

I have just investigated this and found the issue:

1. superclass table lookup is done using the name which includes generic specialization
2. but the lookup table stores superclasses without any generics (keys are pure class names)
3. thus the lookup fails, and consequent lookups are too different from the initial intention

Fix incoming ⏲️

**Comment by art-divin** [comment]
#1287 fixes this
