### ISSUE TITLE
Error on Generate mock for generic type

### ISSUE THREAD

**Issue by fevicks** [krzysztofzablocki/Sourcery#811]
**I am using the below protocol**
```
import Foundation

//sourcery: AutoMockable
protocol Client {
     func performRequest<T: Decodable>(
        api: APIEndpoint,
        decodeTo: T.Type,
        completion: @escaping (Result<T, APIError>) -> Void
    )
}
```

i am getting error on mocking above protocol 

**Autogenerated code is below**
```
class ClientMock: Client {

    //MARK: - performRequest<T: Decodable>

    var performRequestApiDecodeToCompletionCallsCount = 0
    var performRequestApiDecodeToCompletionCalled: Bool {
        return performRequestApiDecodeToCompletionCallsCount > 0
    }
    var performRequestApiDecodeToCompletionReceivedArguments: (api: APIEndpoint, decodeTo: T.Type, completion: (Result<T, APIError>) -> Void)?
    var performRequestApiDecodeToCompletionReceivedInvocations: [(api: APIEndpoint, decodeTo: T.Type, completion: (Result<T, APIError>) -> Void)] = []
    var performRequestApiDecodeToCompletionClosure: ((APIEndpoint, T.Type, @escaping (Result<T, APIError>) -> Void) -> Void)?

    func performRequest<T: Decodable>(        api: APIEndpoint,        decodeTo: T.Type,        completion: @escaping (Result<T, APIError>) -> Void    ) {
        performRequestApiDecodeToCompletionCallsCount += 1
        performRequestApiDecodeToCompletionReceivedArguments = (api: api, decodeTo: decodeTo, completion: completion)
        performRequestApiDecodeToCompletionReceivedInvocations.append((api: api, decodeTo: decodeTo, completion: completion))
        performRequestApiDecodeToCompletionClosure?(api, decodeTo, completion)
    }
}
```

**Error Message**
`Use of undeclared type 'T'`

How i can fix this issue?
**I am using the below template** 

((https://raw.githubusercontent.com/krzysztofzablocki/Sourcery/master/Templates/Templates/AutoMockable.stencil))

**Comment by krzysztofzablocki** [comment]
Bundled templates are just common case solutions, not all possible variants and generics like this are one of the cases they don't handle, you'd need to tweak them to support such case

**Comment by fevicks** [comment]
@krzysztofzablocki thanks for quick response. Actually i am not familiar with Stencil, & just started using Sourcery. shall you provide Stencil code for Generic type?

**Comment by krzysztofzablocki** [comment]
Generics, in general, are more complicated as we don't have full support for those in the AST, people usually apply automation to non generic types.

**Comment by sergiocampama** [comment]
I've managed to add basic support for some basic types for generics in this stencil: https://gist.github.com/sergiocampama/e024fc8f1258d89463b27a5d2353f58b

but it only works for the first layer of generics, which is good for now for me, but more complex things like:

```
// sourcery: AutoMockable
protocol SomeProtocol {
    func remoteCall<Request: Encodable, Response: Decodable>(_ request: Request, completion: @escaping (Result<Response, Error>) -> Void)
}
```

is a bit outside my zone of comfort for the stencil language.
