### ISSUE TITLE
.inherits doesn't work with existential

### ISSUE THREAD

**Issue by pranshudunzo** [krzysztofzablocki/Sourcery#815]
If a superclass is declared as an existential it doesn't come in inherits property of a type like:

`class A: B & P {}`

where B is a class and P is a protocol.

In this case B or any any superclass of B is not present in inherits dictionary of type A.

**Comment by art-divin** [comment]
👋🏻  Hello, 

thank you for reporting the issue! It was fun to investigate & fix properly.

#1314 resolves this issue. ✅
