### ISSUE TITLE
Sourcery fails when using `project` in configuration file with a project that uses swift packages.

### ISSUE THREAD

**Issue by nicholaslythall** [krzysztofzablocki/Sourcery#816]
Sourcery output:
```
error: while reading .yml 'YoufoodzTests/.sourcery.yml'. 'The element XCSwiftPackageProductDependency is not supported'
```

If the swift packages are removed from the project, Sourcery runs fine

Sourcery version: `17.0`

**Comment by bogdangolubcr** [comment]
I have the same issue with xcode 11.4

**Comment by ilyapuchka** [comment]
We are using https://github.com/tuist/XcodeProj for parsing Xcode projects, so I suppose it's related to the issue in that project. We use quite old version, have you tried to bump to more up to date version?

**Comment by ilyapuchka** [comment]
cc @pepibumur

**Comment by jasdeepsaini** [comment]
I tried updating XCodeProj to version 7.0.0 which has the [fix](https://github.com/tuist/XcodeProj/pull/439) needed to support SPM packages.  That has a dependency on PathKit 1.0.0.  

The PathKit dependency conflicts with Stencil which has a dependency on PathKit 0.9.2.   Stencil has not done a release since September 2018, but there has been some recent commits including updating to using PathKit 1.0.0.  If Stencil is updated, it should be possible to update the version of xcodeproj used in this project.

**Comment by pepibumur** [comment]
> I tried updating XCodeProj to version 7.0.0 which has the fix needed to support SPM packages. That has a dependency on PathKit 1.0.0.

Right, the version of XcodeProj used by Sourcery is very old and doesn't have that object type defined. My recommendation is to update to the latest version of XcodeProj

**Comment by jasdeepsaini** [comment]
`Stencil` 0.14.0 was released today with the an update to the `PathKit` dependency.  Should be able to update XcodeProj now.

**Comment by junjielu** [comment]
Any update here?

**Comment by Lutzifer** [comment]
@junjielu 

I found a workaround for us using shell:

```
# Until https://github.com/krzysztofzablocki/Sourcery/issues/816 is fixed, we use a workaround

# Remove any leftover temporary XcodeProjects
rm -rf AppTemplateSourcery.xcodeproj || true

# Copy the XcodeProject to a temporary XcodeProject
cp -r AppTemplate.xcodeproj AppTemplateSourcery.xcodeproj

# Remove the sections that sourcery cannot work with using sed
sed -i .bak '/^.*Begin XCSwiftPackageProductDependency section.*/,/^.*End XCSwiftPackageProductDependency section.*/d' AppTemplateSourcery.xcodeproj/project.pbxproj
sed -i .bak '/^.*Begin XCRemoteSwiftPackageReference section.*/,/^.*End XCRemoteSwiftPackageReference section.*/d' AppTemplateSourcery.xcodeproj/project.pbxproj

# Run sourcery. The project inside the .yml definition needs to point to the temporary XcodeProject
bin/mint run krzysztofzablocki/Sourcery  sourcery              --config  Resources/CodeGeneration/sourceryRelease.yml  &
bin/mint run krzysztofzablocki/Sourcery  sourcery              --config  Resources/CodeGeneration/sourceryDebug.yml    &
bin/mint run krzysztofzablocki/Sourcery  sourcery              --config  Resources/CodeGeneration/sourceryKit.yml      &

wait

# Cleanup after Workaround
rm -rf AppTemplateSourcery.xcodeproj || true
```

Note: I have not tested, if the marker "Begin XCSwiftPackageProductDependency section" and similar is vanilla Xcode or is a result of using https://github.com/yonaskolb/XcodeGen
