### ISSUE TITLE
List all variables of a certain type?

### ISSUE THREAD

**Issue by cschep** [krzysztofzablocki/Sourcery#820]
Hi! Thank you for Sourcery, what a cool project!

I'm trying to do something that seems easy, but I've been failing for over an hour so I figured I'd just ask..

I have a situation in my app where I'd like to mark certain strings somehow (I can do anything, comment/annotation, make them all inherit from a class, mark them with a protcol, etc)

I want to list all variables in the app of that type.. perhaps Sourcery is almost too powerful for this? Seems like it wants me to be acting a level above this, maybe I should just use grep? ha ha :) 

Thanks!

**Comment by krzysztofzablocki** [comment]
not sure I understand the purpose, maybe show sample source code of what you are trying to gather? if it's variables of specific types you want to list then you could just loop over all types in the project and then do inner loop on all `storedVariables` of each type that inherits from basetype or implements a protocol

**Comment by cschep** [comment]
So let's say I have a type `FetchedString`, for this example let's say it's a struct..

```
struct FetchedString {
    var string: String
    var name: String
    var key: String
}
```

I want to use Sourcery to find every instance of that type in my app.

`let fs = FetchedString(string: "hello world", name:"hello", key: "foo.bar.hello.world")`

Ultimately I'd like the output to be something like..

`"foo.bar.hello.world": "hello world"`

and inline i'd love to transform the use of that struct to something else..

`let fs = AnotherClass.getString(key, variables)`

Is sourcery the right tool for this source code transforming? Or is it operating more on the level of types themselves and less on the level of like.. instances of those types?

Thanks!

**Comment by krzysztofzablocki** [comment]
Sourcery doesn't scan your code blocks, only type definitions so I think it's not the right tool to use here, sounds to me like you don't need to understand your type syntax tree but just need string transformation, use grep or something like that instead in that case.

**Comment by cschep** [comment]
I did end up using grep to solve my problem, thanks so much for taking the time to help me!
