### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by erichoracek** [krzysztofzablocki/Sourcery#821]
Would it be possible to cut a new release? There's been a number of [new commits to master](https://github.com/krzysztofzablocki/Sourcery/compare/0.17.0...master) since the last release over 7 months ago which I'd love to be able to use without building locally. Let me know if I can help in any way!

**Comment by krzysztofzablocki** [comment]
@erichoracek since you contributed to repo before I can give you access to make releases, are you on newest OSX? if so you could cut release following our process from https://github.com/krzysztofzablocki/Sourcery/blob/master/RELEASING.md 

I don't have newest osx installed and so I couldn't cut release

**Comment by erichoracek** [comment]
@krzysztofzablocki Yes—I'm on Catalina (10.15.4). I'd be happy to take on cutting a new release.

**Comment by krzysztofzablocki** [comment]
@erichoracek awesome :) invite sent

**Comment by erichoracek** [comment]
@krzysztofzablocki Great, thanks—accepted. Can I grab trunk access on CocoaPods trunk as well?
```
pod trunk add-owner Sourcery horacek.eric@gmail.com
```

**Comment by erichoracek** [comment]
In preparation for cutting the release I've updated the docs and the circle CI Xcode/Ruby version 
- #824
- #825

**Comment by erichoracek** [comment]
And then here's a draft PR for bumping the version to `0.18.0` once we've merged the prep PRs #826

**Comment by krzysztofzablocki** [comment]
@erichoracek added you to trunk

**Comment by erichoracek** [comment]
Looks like we're good!
- Release https://github.com/krzysztofzablocki/Sourcery/releases/tag/0.18.0
- Homebrew PR https://github.com/Homebrew/homebrew-core/pull/53896
- Trunk Podspec https://github.com/CocoaPods/Specs/blob/master/Specs/9/2/2/Sourcery/0.18.0/Sourcery.podspec.json
