### ISSUE TITLE
var.type.name returning Array

### ISSUE THREAD

**Issue by marcelofabri** [krzysztofzablocki/Sourcery#828]
After upgrading from 0.17.0 to 0.18.0, `var.type.name` is returning `Array` (without the generics param) in some cases. Previously it would return the short syntax (`[Element]`).

I'm still trying to come up with a repro example (it doesn't happen when reducing the source file, even with the same template), but I think https://github.com/krzysztofzablocki/Sourcery/pull/798 might've introduced this.

**Comment by krzysztofzablocki** [comment]
whats returned from `var.typeName.array` ? from @ilyapuchka description in that pr the return of `Array` is on purpose and one should switch to using https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/Classes/TypeName.html#/c:@M@SourceryRuntime@objc(cs)TypeName(py)array

**Comment by marcelofabri** [comment]
Yes, regular `name`, but not always (I couldn’t reproduce it with a simple input). I’ll try to come up with a reproducible example.

**Comment by marcelofabri** [comment]
OK, I was able to reduce the issue to having an `extension Array` in the sources:

```swift
import Foundation

public final class Example: AutoInit {
    public let numbers: [Int]
}

public extension Array where Element: Encodable {
    func mapping() -> [[String: Any]] {
        guard !isEmpty else { return [] }
        return map { $0.mapping }
    }
}
```


```stencil
{# Returns the full type of a property, e.g. Model.Style instead of just Style #}
{% macro resolveTypeName var %}{% if var.type %}{{ var.type.name }}{% if var.typeName.isOptional %}?{% endif %}{% else %}{{ var.typeName.name }}{% endif %}{% endmacro %}

{% for type in types.based.AutoInit %}extension {{ type.name }}: Testable {
    public enum TestFactory {
        public static func makeModel({% for var in type.storedVariables %}{% set typeName %}{% call resolveTypeName var %}{% endset %}{{ var.name }}: {{ typeName }} = .testableDefault(){% if not forloop.last %},
                                     {% endif %}{% endfor %}) -> {{ type.name }} {
            return {{ type.name }}({% for var in type.storedVariables %}{{ var.name }}: {{ var.name }}{% if not forloop.last %},
                   {% for i in 0...type.name.count %} {% endfor %}{% endif %}{% endfor %})
        }
    }

    public static func testableDefault() -> {{ type.name }} {
        return TestFactory.makeModel()
    }
}
{% if not forloop.last %}

{% endif %}
{% endfor %}
```


**Result with 0.18.0**:

```swift
// Generated using Sourcery 0.18.0 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT




extension Example: Testable {
    public enum TestFactory {
        public static func makeModel(numbers: Array = .testableDefault()) -> Example {
            return Example(numbers: numbers)
        }
    }

    public static func testableDefault() -> Example {
        return TestFactory.makeModel()
    }
}
```

**Result with 0.17.0**:

```swift
// Generated using Sourcery 0.17.0 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT




extension Example: Testable {
    public enum TestFactory {
        public static func makeModel(numbers: [Int] = .testableDefault()) -> Example {
            return Example(numbers: numbers)
        }
    }

    public static func testableDefault() -> Example {
        return TestFactory.makeModel()
    }
}
```

I've test with this command:

```
sourcery --sources file.swift --templates Testable.stencil --output Testable.generated.swift --verbose --disableCache 
```

**Comment by krzysztofzablocki** [comment]
@ilyapuchka any idea what could be causing this?

**Comment by ilyapuchka** [comment]
yeah, probably because now we compose the type "correctly" when there are extensions and then resolve it in the properties

**Comment by ilyapuchka** [comment]
I guess the template should be adjusted to consider for `isGeneric` or `isArray` and then reach out to the `array` metadata to reconstruct the type. It should work in both scenarios (with/without extension) I suppose

**Comment by marcelofabri** [comment]
>I guess the template should be adjusted to consider for `isGeneric` or `isArray` and then reach out to the `array` metadata to reconstruct the type. It should work in both scenarios (with/without extension) I suppose

@ilyapuchka that feels unnatural to me 😬

Can we special case this somehow? I think it’s really unlikely that someone will have a custom `Array` type in their project

**Comment by ilyapuchka** [comment]
It's not about custom array types, it's about representing generic type fully and correctly, this is already a special case because we have to parse shortcut syntax and we have special metadata accessors that allow to reconstruct the type (which can be provided as a convenience computed property by the framework though).

**Comment by marcelofabri** [comment]
> It's not about custom array types, it's about representing generic type fully and correctly, this is already a special case because we have to parse shortcut syntax and we have special metadata accessors that allow to reconstruct the type (which can be provided as a convenience computed property by the framework though).

yeah, I just think this behavior is very surprising and I don't fully understand what was wrong with the previous behavior 

would the same thing happen to `Dictionary`? 🤔

**Comment by ilyapuchka** [comment]
Yes, same will apply to dictionaries as they are handled in a similar way.
Here is the original issue for which this behaviour was changed
https://github.com/krzysztofzablocki/Sourcery/pull/798

it suggests that full name should be accessible through `typeName.array.name`

**Comment by marcelofabri** [comment]
I'm not sure closing this without any changes (at least documentation) is the right call. This behavior is extremely surprising for me as a user and isn't called out explicitly anywhere.

**Comment by krzysztofzablocki** [comment]
but this is documented, and as @ilyapuchka said this makes generic support more uniform, previous behavior existed prior to more general generic support

@marcelofabri I'd be fine with adding a convenience accessor for type name to reproduce this old behaviour, you could create a computed variable on the `TypeName` that would just look whether type is generic and if so recreate the fully qualified name, so that you don't need to do it templates, would you have time to try to make a PR for that?
