### ISSUE TITLE
Sourcery detects enum conformance to typealias of protocol composition as a raw type

### ISSUE THREAD

**Issue by jacobdweightman** [krzysztofzablocki/Sourcery#830]
I want to preface this by saying that this issue is probably an unimplemented feature rather than a bug, but it did cause me some trouble trying to figure out what was going on in my project.

Given:
* two protocols `A` and `B`
* a typealias `C` for the composition of `A` and `B`

When:
* there is an enum `Foo` conforming to `C`

Then:
* `C` is detected as the `rawType` of `Foo`.

I would instead expect that that the `rawType` is `nil`. I've attached a minimal example.

[sourcerybug.zip](https://github.com/krzysztofzablocki/Sourcery/files/4565226/sourcerybug.zip)

**Comment by jacobdweightman** [comment]
Perhaps also worth noting is that this issue was new in v0.18.0. I suspect this may be due to the expanded support for typealiases, because previously the `rawType` was `nil` though I suspect that `rawTypeName` was not.

**Comment by erichoracek** [comment]
Good catch, thanks for reporting! I've put up a fix in #832.
