### ISSUE TITLE
Not able to render AutoCodable.swifttemplate

### ISSUE THREAD

**Issue by Yannmm** [krzysztofzablocki/Sourcery#835]
Xcode 11.4.1, not sure where goes wrong, since there is not error message.

```
Using configuration file at './sourcery.yml'
Scanning sources...
	loadOrParse: 0.0028589963912963867
	resolution took 0.0006489753723144531
	combiningTypes: 0.0008379220962524414
	total: 0.0037360191345214844
Found 2 types.
Loading templates...
Loaded 1 templates.
	Loading took 0.005620002746582031
Generating code...
Rendering template /Users/ryan/Desktop/WhatIsSourcery/Templates/AutoCodable.swifttemplate
/usr/bin/env "xcrun" "swift" "build" "-Xswiftc" "-Onone" "-Xswiftc" "-suppress-warnings" "--disable-sandbox"
error: 
```

**Comment by nangadiquotient** [comment]
Facing the same error here too in Xcode 11.4.1
Loading templates...
Loaded 5 templates.
	Loading took 0.04272198677062988
Generating code...
Rendering template /Users/nangadi/coupons-ios/couponsapp/Coupons/Coupons_Framework/Sourcery/Templates/AutoCodable.swifttemplate
/usr/bin/env "xcrun" "swift" "build" "-Xswiftc" "-Onone" "-Xswiftc" "-suppress-warnings" "--disable-sandbox"
error:

**Comment by RenGate** [comment]
Most likely this is caused by the same issue mentioned in https://github.com/krzysztofzablocki/Sourcery/issues/817
