### ISSUE TITLE
Inherited method appears twice in allMethods 

### ISSUE THREAD

**Issue by lordzsolt** [krzysztofzablocki/Sourcery#838]
Given the following class structure:

```
protocol BaseProtocol {
	var variable: Int { get }
	func doSomething()
}

class BaseClass: BaseProtocol {
	var variable: Int = 0
	func doSomething() {}
}

protocol ExtendedProtocol: BaseClass {
	var externdedVariable: Int { get }
	func extendedDoSomething()
}

class ExtendedClass: BaseClass, ExtendedProtocol {
	var externdedVariable: Int = 0
	func extendedDoSomething() { }
}
```

When navigating the `allMethods` property of `ExtendedProtocol`, `doSomething` will appear twice, once with `definedInTypeName = BaseClass` and once with `definedInTypeName = BaseProtocol`.
Interestingly, `allVariables` only contains `variable` once.

Example stencil file:

```
{% for protocol in types.protocols where protocol.name|hasSuffix:"ExtendedProtocol"  %}
class Mock{{ protocol.name|replace:"Protocol","" }}: {{protocol.name}} {

{% for variable in protocol.allVariables|!definedInExtension %}
    {{ variable.name }} coming from {{variable.definedInTypeName}}
{% endfor %}

{% for method in protocol.allMethods|!definedInExtension %}
    {{ method.name }} coming from {{method.definedInTypeName}}
{% endfor %}

}

{% endfor %}
```

#

This is particularly a problem when trying to generate mocks. Using the current `AutoMockable.stencil`, the generated mock will not compile, because all the helpers generated for `doSomething` will be created twice.

**Comment by YuryBogdanov** [comment]
We've faced the same issue when trying to build project on macOS 10.15.4.
However everything is ok on macOS 10.15 (19A602). It seems something has been broken in the latest macOS releases.

**Comment by krzysztofzablocki** [comment]
I think the reason is that `definedInTypeName` is not excluded from equality and as such when we flatten methods for `allMethods` it doesn't treat those methods as same, this was change made by @Antondomashnev a long time ago: https://github.com/krzysztofzablocki/Sourcery/commit/c73f18dbf125cb9c40b7fb33d00126f486239dc1

I honestly am not sure whether this should be excluded from equality or we need to deal with this other way (as I never relied on this defined variables), thoughts @Antondomashnev @ilyapuchka ?

**Comment by lordzsolt** [comment]
I don't mind it being this way. My only problem is that the Mock template becomes useless in this case. I've even tried filtering out duplicates somehow, but was unsuccessful.

**Comment by lordzsolt** [comment]
Any updates on this? 😞

**Comment by lordzsolt** [comment]
Can we get an update on this? 

```
protocol Foo {
    func doSomething()
}

protocol Foo2 {
    func doSomething()
}

protocol Foo3: Foo, Foo2 {
    func doSomethingElse()
}
```

The `AutoMockable` template still fails with this.

**Comment by lordzsolt** [comment]
@Uncpy Nope, I wasn't able to fix it 😞 

As a workaround, I removed:
- Protocols requiring class conformance, so replace `protocol SomeProtocol: SomeClass` with `protocol SomeProtocol: SomeClassProtocol`.
- Methods that appear in multiple protocols and instead move it to a parent protocol.

```swift
// Before:
protocol A { 
    func doSomething()
    func doSomethingA()
}
protocol B { 
    func doSomething()
    func doSomethingB() 
}

// After:

protocol C { doSomething() }
protocol A: C { doSomethingA() }
protocol B: C { doSomethingB() }
```

I've only had these problems in a single instance every time, so it was easy to fix.

If the codebase gets more complex and this starts to appear more, I'm considering forking Sourcery...

**Comment by lordzsolt** [comment]
I would gladly make a PR fixing this, but I would like some opinions from maintainers, if this is a bug or a "feature".

@krzysztofzablocki @Antondomashnev @ilyapuchka

**Comment by krzysztofzablocki** [comment]
I think just excluding `definedInTypeName` from equality will fix the issue but I'm not sure if that's what we want, @ilyapuchka @Antondomashnev what do you think?

**Comment by lordzsolt** [comment]
Well, either way, the fact that `allVariables` and `allMethods` behave differently makes me think it's a bug.

----

Another possible solution I can see is to merge the methods from the two protocols, and make `definedInTypeName` an array. But that solution can get complicated real quick, because it will affect other fields as well. So unless there is need for it, it's probably not worth the time investment.

**Comment by krzysztofzablocki** [comment]
@lordzsolt yeah it's weird as both aren't excluding the `definedInTypeName`, how is sourcery registering the variables vs methods there?

**Comment by lordzsolt** [comment]
Given these protocols:

```swift
protocol A {
    var value: Int { get }
    func doSomething()
}

protocol B {
    var value: Int { get }
    func doSomething()
}

protocol C: A, B {
    func somethingSomething()
}
```

This is the output:

```
    Variable: name = value, typeName = Int, isComputed = false, isStatic = false, readAccess = internal, writeAccess = , isMutable = false, defaultValue = nil, annotations = [:], attributes = [:], isFinal = false, isLazy = false, definedInTypeName = Optional(A), actualDefinedInTypeName = Optional(A)

    Method: name = somethingSomething(), selectorName = somethingSomething, parameters = [], returnTypeName = Void, `throws` = false, `rethrows` = false, accessLevel = internal, isStatic = false, isClass = false, isFailableInitializer = false, annotations = [:], definedInTypeName = Optional(C), attributes = [:]
    Method: name = doSomething(), selectorName = doSomething, parameters = [], returnTypeName = Void, `throws` = false, `rethrows` = false, accessLevel = internal, isStatic = false, isClass = false, isFailableInitializer = false, annotations = [:], definedInTypeName = Optional(A), attributes = [:]
    Method: name = doSomething(), selectorName = doSomething, parameters = [], returnTypeName = Void, `throws` = false, `rethrows` = false, accessLevel = internal, isStatic = false, isClass = false, isFailableInitializer = false, annotations = [:], definedInTypeName = Optional(B), attributes = [:]
```

As you can see, `value` with `definedInTypeName = `Optional(B)` is not even present, while `doSomething` is present twice.

**Comment by krzysztofzablocki** [comment]
@lordzsolt definitely something is off, I'll take a look today, can you tell me what behaviour would you expect here? it definitely should be consistent between variable and method but I wonder what the right behaviour is, I personally never used definedInTypeName nor do I see any common need for that so I'd opt in for skipping equality on those properties as for 99% of codegen needs it doesn't matter and it's same method

**Comment by lordzsolt** [comment]
Yeah, I agree with you. For codegen reasons, there should be a single method.

Otherwise, everything will be generated twice and won't compile, because "redeclaration" errors.

**Comment by krzysztofzablocki** [comment]
@lordzsolt fixed this on master by matching the behaviours of `allVariables`, the reason there was a difference was because we filter out the variables composition when we flatten it, we do same for methods now

**Comment by sochalewski** [comment]
@krzysztofzablocki Could you please describe how to get old behavior with `allMethods` in 1.0.3?

**Comment by krzysztofzablocki** [comment]
@sochalewski why do you want to have duplicates? you should be able to get that by walking the inheritance / conformance hierachy

**Comment by sochalewski** [comment]
@krzysztofzablocki It seems that flattening sometimes works incorrectly. I've got a template to auto generate mocks which uses `allMethods` and most of mocks are generated correctly, but some of them not.

In example:
```swift
protocol RemoteUrlOpening: AnyObject {
  func open(_ url: URL)
}

//sourcery: AutoMockable
protocol UrlOpening: RemoteUrlOpening {
  func open(
    _ url: URL,
    options: [UIApplication.OpenExternalURLOptionsKey: Any],
    completionHandler completion: ((Bool) -> Void)?
  )
}
```

This treats `open(_ url: URL)` from the inherited protocol as a duplicate while it's not. Thus only `open(_:options: completionHandler:) appears in the generated mock. In 1.0.2 both functions appear in the mock.

 On the other hand the following works properly even in 1.0.3:
```swift
//sourcery: AutoMockable
protocol UrlOpening: RemoteUrlOpening {
  func open(_ url: URL)
  func open(
    _ url: URL,
    options: [UIApplication.OpenExternalURLOptionsKey: Any],
    completionHandler completion: ((Bool) -> Void)?
  )
}
```

I believe `filter` in `flattenAll(_:filter)` should compare not only function's name, but its parameters too.

**Comment by krzysztofzablocki** [comment]
looks like we should use selectorName for flattening functions?

**Comment by krzysztofzablocki** [comment]
@sochalewski I added a test with the code you provided and the AST sourcery parses is correct https://github.com/krzysztofzablocki/Sourcery/commit/94d85c8ad99192b42dda2814470da6225f51b176

same when copying your code and running basic template:

```swift
// code
protocol RemoteUrlOpening {
  func open(_ url: URL)
}

protocol UrlOpening: RemoteUrlOpening {
  func open(
    _ url: URL,
    options: [UIApplication.OpenExternalURLOptionsKey: Any],
    completionHandler completion: ((Bool) -> Void)?
  )
}

// template
{% for method in type.UrlOpening.allMethods %}
{{ method.name }}
{% endfor %}

// output 
open(
    _ url: URL,
    options: [UIApplication.OpenExternalURLOptionsKey: Any],
    completionHandler completion: ((Bool) -> Void)?
  )
open(_ url: URL)
```

Can you provide a failing spec or a running example?

**Comment by sochalewski** [comment]
@krzysztofzablocki As I mentioned I use `allMethods` combined with `!definedInExtension`.

```swift
protocol UrlOpening {
  func open(_ url: URL)
  func open(
    _ url: URL,
    options: [UIApplication.OpenExternalURLOptionsKey: Any],
    completionHandler completion: ((Bool) -> Void)?
  )
}

extension UrlOpening {
    func open(_ url: URL) {
        open(url, options: [:], completionHandler: nil)
    }
}
```

Let's go with the example above.

### `allMethods`

```swift
// template
{% for method in type.UrlOpening.allMethods %}
{{ method.name }}
{% endfor %}

// output 
open(_ url: URL)
open(
    _ url: URL,
    options: [UIApplication.OpenExternalURLOptionsKey: Any],
    completionHandler completion: ((Bool) -> Void)?
)
open(_ url: URL)
```

The above outputs `open(_ url: URL)` twice as the first comes from the protocol and the second from the extension.

### `allMethods|!definedInExtension`, ex. 1

```swift
// template
{% for method in type.UrlOpening2.allMethods|!definedInExtension %}
{{ method.name }}
{% endfor %}

//output
open(_ url: URL)
open(
    _ url: URL,
    options: [UIApplication.OpenExternalURLOptionsKey: Any],
    completionHandler completion: ((Bool) -> Void)?
)
```

This works correctly. But going with a bit more complicated example (below) makes it wrong.

### `allMethods|!definedInExtension`, ex. 2

```swift
//code
protocol RemoteUrlOpening {
  func open(_ url: URL)
}

protocol UrlOpening: RemoteUrlOpening {
  func open(
    _ url: URL,
    options: [UIApplication.OpenExternalURLOptionsKey: Any],
    completionHandler completion: ((Bool) -> Void)?
  )
}

extension UrlOpening {
  func open(_ url: URL) {
    open(url, options: [:], completionHandler: nil)
  }
}

// template
{% for method in type.UrlOpening.allMethods|!definedInExtension %}
{{ method.name }}
{% endfor %}

//output
open(
    _ url: URL,
    options: [UIApplication.OpenExternalURLOptionsKey: Any],
    completionHandler completion: ((Bool) -> Void)?
)
```

This outputs only `open(_:options:completionHandler:)` missing `open(_:)` at all.

Hope this is helpful to resolve the issue I encountered.

**Comment by krzysztofzablocki** [comment]
this isn't issue with method flattening but with type extension, I don't think that in the first example it should list 3 methods because the type really has 2 methods, one just have default implementation and from Sourcery standpoint that shouldn't be treated as separate method

**Comment by krzysztofzablocki** [comment]
@sochalewski take a look at https://github.com/krzysztofzablocki/Sourcery/pull/897 and the tests I added there, let me know if the changes make sense

**Comment by sochalewski** [comment]
@krzysztofzablocki I've checked changes from #897 out and it works well ❤️
