### ISSUE TITLE
 Error installing Sourcery

### ISSUE THREAD

**Issue by lalitkantcg** [krzysztofzablocki/Sourcery#841]
pod install
Analyzing dependencies
Downloading dependencies
Installing Sourcery (0.18.0)

[!] Error installing Sourcery
[!] /usr/bin/curl -f -L -o /var/folders/xr/j6pyw9xs5b53dnd2jfdqv5800000gq/T/d20200621-1482-9ez0jr/file.zip https://github.com/krzysztofzablocki/Sourcery/releases/download/0.18.0/sourcery-0.18.0.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   630    0   630    0     0   1506      0 --:--:-- --:--:-- --:--:--  1507
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 400 Bad Request

I am using MacOS Mojave with this version 10.14.5

If I am trying to install other pods its working but for installing Sourcery there is issue. Please fix this issue

**Comment by forsan** [comment]
I face the same issue, any fix, please?

**Comment by Liquidsoul** [comment]
Hi,

We cannot replicate your issue if you give us only the output of the commands without the setup you use. If you cannot give us information from your project, try to isolate the problem in a sample project that you can give us.

But by the look of it, this does not seem to be a Sourcery-related issue but more of a Cocoapods one.
I have installed Sourcery in a fresh new project without any issue using cocoapods `1.9.3` so maybe try to bump your Cocoapods version?

**Comment by forsan** [comment]
now working fine, the problem related to some restrictions on the internet of my company.
