### ISSUE TITLE
Arguments value not inserted to template

### ISSUE THREAD

**Issue by dautovicharis** [krzysztofzablocki/Sourcery#847]
Before I created this  ticket, I have tried multiple solutions including:
- custom .sourcery.yml config file with args
- without .sourcery.yml
- hardcoded args
- args from env variables
- different sourcery pods versions

Here is an example: 

**Target swift version**: `4.2`

**Version** -> `Version: pod 'Sourcery', '~> 0.18.0'`

**.sourcery.yml**
```
sources:
    - ProjectSource
templates:
    - Templates
output: CodeGenerated
```

**Run the script from the target build phases (second step) after dependencies**
`${PODS_ROOT}/Sourcery/bin/sourcery --args api="test"   --verbose`

**Template:**
```
enum Keys: String {
    case api = "{{argument.api}}"
  
        var value: String {
        return self.rawValue
    }
}
```

**Generated file:** 
```
// Generated using Sourcery 0.18.0 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

enum Keys: String {
    case api = ""
    var value: String {
    return self.rawValue
    }
}

```

**The result is always the empty string.**
`print("Sourcery:\(Keys.api.value)")`

**Comment by krzysztofzablocki** [comment]
you usually do this in your yaml:

```yaml
sources:
...
templates:
...
output:
...
args:
  api:test
  arrayArgument: 
    - firstValue
```

**Comment by dautovicharis** [comment]
This works, but I can't figure out what was wrong before. This is fine if we have hardcoded value in yml file.

My real case scenario is 
- multiple targets
- every target has its own xcconfig file
- values from xcconfig file should be inject into a template.

This was the initial problem I was solving but then moved to a simple one (hardcoded case), because wanted to be sure that my setup is correct.

I was following this example -> https://www.lordcodes.com/articles/managing-secrets-within-an-ios-app
`${PODS_ROOT}/Sourcery/bin/sourcery --args api=\"$API_ID\"`

And also found this one -> https://www.lordcodes.com/articles/managing-secrets-within-an-ios-app (JAVA_HOME for testing purposes)
`${PODS_ROOT}/Sourcery/bin/sourcery --args random="pollo",api=$JAVA_HOME`

**Both examples give me an empty string for api param.**

**Comment by krzysztofzablocki** [comment]
is the hardcoded value getting passed through in the above case `pollo` ? or is `random` also empty

**Comment by dautovicharis** [comment]
random is also empty.

**Comment by krzysztofzablocki** [comment]
@dautovicharis if you have yml file then arguments from command line will be ignored https://github.com/krzysztofzablocki/Sourcery/blob/e15dcb63d4f2dde6fa7abd6fd816e8be769478fd/Sourcery/main.swift#L142 

You can use the environment variables in yml files, we had that supported since https://github.com/krzysztofzablocki/Sourcery/pull/724

**Comment by dautovicharis** [comment]
@krzysztofzablocki  It works now.

 I have tried so many combinations yesterday and I don't know where I did mistake initially.


After trying again my initial cmd it  just started working
`${PODS_ROOT}/Sourcery/bin/sourcery --sources ./Project --templates ./Templates --output ./CodeGenerated --args api=\"$API_SECRET\"`


`API_SECRET` is the value from `xcconfig` file which is assigned to the project `target` and this is what I needed.

Thanks for your help.

**Comment by krzysztofzablocki** [comment]
you probably had `.yml` file before but removed it now :) keep in mind you could achieve the same using .yml file and env variable, even if it's not available you could simply export something as env variable from your build phase
