### ISSUE TITLE
Syntax: Is "or" operator allowed in forloop

### ISSUE THREAD

**Issue by of99** [krzysztofzablocki/Sourcery#848]
I have a statement

`{% for enum in types.enums where enum.localName == "someEnum" or enum.localName = "someOtherEnum" %}`

However when i try to execute this statement i get the following error.

` 'if' expression error: dangling token`

At first i thought it was a problem with if somewhere in my template. Took me a while to figure out that the "or" was causing this error. Am i doing something wrong here or is "or" not allowed in for loop.

**Comment by krzysztofzablocki** [comment]
or is allowed https://stencil.fuller.li/en/latest/builtins.html#built-in-filters but you are doing `=` in the second part not equality

**Comment by of99** [comment]
How could have i missed it. Thanks :)
