### ISSUE TITLE
string_1 | lowercase | contains: string_2 | lowercase doesn't work

### ISSUE THREAD

**Issue by oltv00** [krzysztofzablocki/Sourcery#853]
>What version of Swift are you using (swift --version)?

➜ swift --version
Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
Target: x86_64-apple-darwin19.6.0

>What did you do?

I am writing my custom template and I have a problem.

There are the following input data:
```
method_1 = fetchData
method_2 = didFetchData
```

If I try to print the result

``
{{ method_2.shortName|lowercase|contains:method_1.shortName|lowercase }}
``

then I suddenly get `false`

If I use the construction:

```
{% if method_2.shortName|lowercase|contains:method_1.shortName|lowercase %}
  do something
{% endif %}
```

then `do something` will be executed as intended, since `didfetchdata` contains `fetchdata`

but if 

```
method_1 = fetchData
method_2 = didFetchSomeElse
```

that construction 

```
{% if method_2.shortName|lowercase|contains:method_1.shortName|lowercase %}
  do something
{% endif %}
```

it will work so that `do something` is also executed!

--

Is this a bug, or am I using filters incorrectly?

**Comment by ilyapuchka** [comment]
What might be happening is that last lowercase is applied on the result of contains, you can try to remove the last filter to see that. If that’s the case It would be stencil issue so you can file it in the Stencil repo.

Ilya Puchka

**Comment by oltv00** [comment]
> What might be happening is that last lowercase is applied on the result of contains, you can try to remove the last filter to see that. If that’s the case It would be stencil issue so you can file it in the Stencil repo. Ilya Puchka
> […](#)

I suppose, you're right.
Because construction
`method.shortName|lowercase|contains:_method.shortName|uppercase`
give me `FALSE`

Ok, I'll check the Stencil repo.
Thanks
