### ISSUE TITLE
Auto indent '// sourcery:inline:auto' comment to the correct level

### ISSUE THREAD

**Issue by inickt** [krzysztofzablocki/Sourcery#854]
In #731 it looks like this is intended behavior, and while its not a huge deal to indent the auto generate the comments manually it would be great if Sourcery was able to detect the level of indentation and auto indent the inline comment (which would also indent the templated code as well).

Thanks for maintaining such a great tool!

**Comment by ilyapuchka** [comment]
If formatting is a problem I'd suggest to run tools like SwiftFormat on the files generated by Sourcery, or even anything that is using Stencil which is not great with formatting.

**Comment by art-divin** [comment]
I agree, formatting is outside of Sourcery/Stencil scope at the moment, while SwiftFormat is an excellent tool for this, which works quite fast as well 👍🏻
