### ISSUE TITLE
Upgrading to latest SourceKitten version

### ISSUE THREAD

**Issue by tum-aweink** [krzysztofzablocki/Sourcery#857]
Hi!
I am currently working on a project which uses the Sourcery framework. Another library in our project depends on Yams version 3..<4 but the currently used SourceKitten version relies on Yams 2..<3. Therefore SPM cannot resolve my dependencies correctly.
As SourceKitten released a new version (0.30.0) in which it depends on Yams 4.0.0 - are there any plans on upgrading?

**Comment by krzysztofzablocki** [comment]
@tum-aweink happy to accept PR upgrading it, I'm way too exhausted atm to do it myself

**Comment by tum-aweink** [comment]
@krzysztofzablocki we managed to upgrade the Yams dependency (fork: https://github.com/PSchmiedmayer/Sourcery) - therefore we needed to restructure the project folder. We would like to run your tests but after updating the pods and regenerating the Xcode project we ran into a code signing error: 
![image](https://user-images.githubusercontent.com/14924669/94299172-91bcb800-ff67-11ea-972e-61f827104e56.png)
which seems to be fixed when using `--deep` signing flag:
![image](https://user-images.githubusercontent.com/14924669/94299304-c4ff4700-ff67-11ea-9e95-154333b4b838.png)
But after that we get multiple compiler errors (probably located in tests):
![image](https://user-images.githubusercontent.com/14924669/94299380-e19b7f00-ff67-11ea-993a-efd71b0abb93.png)

Any help is highly appreciated!

**Comment by DavidBertet** [comment]
I fixed Xcode 12 issues in that PR #869

I reused your pictures to illustrate the PR description
