### ISSUE TITLE
Multiline method declarations parsing

### ISSUE THREAD

**Issue by lexorus** [krzysztofzablocki/Sourcery#862]
I'm using Sourcery to generate mocks and noticed the wrong behavior when dealing with functions that are split between multiple lines. When the code is generated, the newlines are removed, but whitespaces remain in place.
This is not a critical issue, since this is generated code, but it's not really that hard to fix anyway.

Seems like the root cause is [`func strippingComments() -> String`](https://github.com/krzysztofzablocki/Sourcery/blob/master/SourceryFramework/Sources/Parsing/FileParser.swift#L936) function. I already found a way to fix this, but I might not be fully aware about the reason behind those implementation details, and as [CONTRIBUTING.md](https://github.com/krzysztofzablocki/Sourcery/blob/master/CONTRIBUTING.md) suggests in `Contributing Code`:
>2. Open an issue to discuss a new feature.

**What version of Swift are you using (swift --version)?**
```
Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
Target: x86_64-apple-darwin19.6.0
```

**What did you do?**
I was using `TemplatesTests` to simulate the behavior, so will use a bit modified example code from there.
```swift
protocol SameShortMethodNamesProtocol: AutoMockable {
    func start(car: String,
               of model: String)
    func start(plane: String,
               of model: String)
}
```

**What did you expect to see?**
```swift
class SameShortMethodNamesProtocolMock: SameShortMethodNamesProtocol {
// ...
    func start(car: String,
               of model: String) {
        startCarOfCallsCount += 1
        startCarOfReceivedArguments = (car: car, model: model)
        startCarOfReceivedInvocations.append((car: car, model: model))
        startCarOfClosure?(car, model)
    }

// ...
    func start(plane: String,
               of model: String) {
        startPlaneOfCallsCount += 1
        startPlaneOfReceivedArguments = (plane: plane, model: model)
        startPlaneOfReceivedInvocations.append((plane: plane, model: model))
        startPlaneOfClosure?(plane, model)
    }
}
```

**What did you see instead?**
```swift
class SameShortMethodNamesProtocolMock: SameShortMethodNamesProtocol {
// ...
    func start(car: String,               of model: String) {
        startCarOfCallsCount += 1
        startCarOfReceivedArguments = (car: car, model: model)
        startCarOfReceivedInvocations.append((car: car, model: model))
        startCarOfClosure?(car, model)
    }

// ...
    func start(plane: String,               of model: String) {
        startPlaneOfCallsCount += 1
        startPlaneOfReceivedArguments = (plane: plane, model: model)
        startPlaneOfReceivedInvocations.append((plane: plane, model: model))
        startPlaneOfClosure?(plane, model)
    }
}
```

**Comment by krzysztofzablocki** [comment]
I'm definitely happy to make this more consistent, so either remove whitespaces to match newline behaviour or keep both, don't really have any preference here, happy to accept PR :)
