### ISSUE TITLE
Sourcery not finding type conformances on macOS 11 / Xcode 12.1

### ISSUE THREAD

**Issue by MutatingFunc** [krzysztofzablocki/Sourcery#864]
**Disclaimer: I'm a first-time Sourcery user. This looks like a bug to me, but I could well be doing something wrong.**

macOS 11 beta (latest 20A5395g)
Xcode 12.1

_What version of Swift are you using (swift --version)?_
Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
Target: x86_64-apple-darwin20.1.0

_What did you do?_
Following the tutorial from this page: https://www.hackingwithswift.com/articles/85/introduction-to-sourcery

_What did you expect to see?_
The results described in the tutorial. Specifically, an `allCases` extension generated for conforming types.

_What did you see instead?_
Everything works as intended, except conformances are not generated. My generated Swift code file contains the protocol, but not any extension.

I have named my protocol CaseIterable2 to avoid ambiguity with the built-in protocol.

Example `sourcery --watch` log:
```
Source changed at ~/Downloads/SourceryTest/SourceryTest/Direction.swift
Scanning sources...
	loadOrParse: 0.004230022430419922
	resolution took 0.0001499652862548828
	combiningTypes: 0.00037097930908203125
	total: 0.004621028900146484
Found 5 types.
Loading templates...
Loaded 1 templates.
	Loading took 0.0003170967102050781
Generating code...
		Processing Ranges took 8.189678192138672e-05
	Generation took 0.0007470846176147461
Finished.
```

Full project here:
https://github.com/MutatingFunc/SourceryTest

**Comment by krzysztofzablocki** [comment]
CaseIterable needs to be declared in your sources not in the template (thus generated source), Sourcery doesn't scan the source it generated because that would lead to chicken and egg problem

**Comment by MutatingFunc** [comment]
Thanks for the advice. Unfortunately, even moving the protocol definition to one of my own sources doesn't solve the issue.

**Comment by krzysztofzablocki** [comment]
change the template to 

```swift
{% for enum in types.implementing.CaseIterable2|enum %}
```

**Comment by MutatingFunc** [comment]
Still no luck, either changing just that line, or making that the entire template in case that's what you meant. I've pushed a commit with these two changes applied.

**Comment by MutatingFunc** [comment]
I've got it! I was using:
`{% for enum in types.enums.implementing.CaseIterable2 %}`
when I needed
`{% for enum in types.enum.implementing.CaseIterable2 %}`

Further to that, I missed that your suggestion dropped the `.enums` part of the lookup last time round. Thanks for the support!
