### ISSUE TITLE
Getting Use of undeclared type 'MFMailComposeViewController'

### ISSUE THREAD

**Issue by HB-HemantBhatt** [krzysztofzablocki/Sourcery#865]
Hi, 

I am getting the following error in automockable file which are as follows:

following two are from **FBSDKShareKit**
- Use of undeclared type 'ShareDialog'
- Use of undeclared type 'MessageDialog'

following two are from **MessageUI**
- Use of undeclared type 'MFMessageComposeViewController'
- Use of undeclared type 'MFMailComposeViewController'

Please let me know is there any changes which i need to do. For other pods it is working fine so unable to find the root cause.

Thanks!

**Comment by krzysztofzablocki** [comment]
have you imported those frameworks in the generated code you have? because this isn't Sourcery issue

**Comment by HB-HemantBhatt** [comment]
> have you imported those frameworks in the generated code you have? because this isn't Sourcery issue

I have imported frameworks in the code it is being build successfully. When i am running test case then is showing error to me in automockable file.

**Comment by lordzsolt** [comment]
@HB-HemantBhatt You should modify the AutoMockable.stencil file, this part:

```
import Foundation
#if os(iOS) || os(tvOS) || os(watchOS)
import UIKit
#elseif os(OSX)
import AppKit
#endif
```

Just add `import FBSDKShareKit` and `import MessageUI` below `UIKit`.

And if you're not doing any OSX development, you might as well delete the whole `#if #else #endif` parts.
