### ISSUE TITLE
Is per-file generation compatible with swifttemplate technique?

### ISSUE THREAD

**Issue by sstadelman** [krzysztofzablocki/Sourcery#867]
I'm migrating some productive stencil templates to swifttemplate, and have been successful until adding the per-file generation annotation.  Can you share whether the `// Sourcery:file:<...>` in-line annotation pattern ought to work in this scenario, or if there is an alternative?

My file structure is like this:

```swift
<%_
/* extensions on String and Variable */
let models = types.protocols.filter({ $0.annotations["generated_component"] != nil })
for model in models {
/* variable definitions */
-%>
// sourcery:file:ViewModels/<%= componentName %>+ViewBuilder_Model.generated.swift
import SwiftUI
  
public struct <%= componentName %><<%= templateParameters %>>: View {
    /* etc.... */
}
<%_ } -%>
```

**Comment by krzysztofzablocki** [comment]
I think markers should work everywhere, replacement happens AFTER the generation phase so you simply need to write your swifttemplate in a way that creates the output in the format described in our docs https://cdn.rawgit.com/krzysztofzablocki/Sourcery/master/docs/writing-templates.html#inline-code-generation

**Comment by sstadelman** [comment]
@krzysztofzablocki it was the `// sourcery:end` tag that was the culprit.  Thank you for the assistance!
