### ISSUE TITLE
Problem when using SwiftyMocky templates

### ISSUE THREAD

**Issue by raduraducu** [krzysztofzablocki/Sourcery#872]
When trying to generate the mocks using:

> ../Pods/Sourcery/bin/Sourcery.app/Contents/MacOS/Sourcery --sources ../Sources --templates ../Pods/SwiftyMocky/Templates --output ../GeneratedMocks

I keep getting this error:

> Generating code...
> 	Generating AllTypes.swifttemplate took 2.083559989929199
> 		Processing Ranges took 0.00027108192443847656
> 	Generating Header-Mock.swifttemplate took 2.025299072265625
> 		Processing Ranges took 0.00021195411682128906
> 	Generating Header-Prototype.swifttemplate took 2.029873013496399
> 		Processing Ranges took 0.00018799304962158203
> error: [1/29] Compiling SourceryRuntime AccessLevel.swift
> [2/29] Compiling SourceryRuntime Annotations.swift
> [3/29] Compiling SourceryRuntime Attribute.swift
> [4/29] Compiling SourceryRuntime BytesRange.swift
> [5/29] Compiling SourceryRuntime Class.swift
> [6/29] Compiling SourceryRuntime Coding.generated.swift
> [7/29] Compiling SourceryRuntime Definition.swift
> [8/29] Compiling SourceryRuntime JSExport.generated.swift
> [9/29] Compiling SourceryRuntime Log.swift
> [10/29] Compiling SourceryRuntime Method.swift
> [11/29] Compiling SourceryRuntime PhantomProtocols.swift
> [12/29] Compiling SourceryRuntime Protocol.swift
> [13/29] Compiling SourceryRuntime ProtocolComposition.swift
> [14/29] Compiling SourceryRuntime Struct.swift
> [15/29] Compiling SourceryRuntime Subscript.swift
> [16/29] Compiling SourceryRuntime TemplateContext.swift
> [17/29] Compiling SourceryRuntime Type.swift
> [18/29] Compiling SourceryRuntime TypeName.swift
> [19/29] Compiling SourceryRuntime Typealias.swift
> [20/29] Compiling SourceryRuntime Typed.generated.swift
> [21/29] Compiling SourceryRuntime Variable.swift
> [22/29] Compiling SourceryRuntime Description.generated.swift
> [23/29] Compiling SourceryRuntime Diffable.generated.swift
> [24/29] Compiling SourceryRuntime Diffable.swift
> [25/29] Compiling SourceryRuntime Enum.swift
> [26/29] Compiling SourceryRuntime Equality.generated.swift
> [27/29] Compiling SourceryRuntime Extensions.swift
> [28/29] Compiling SourceryRuntime FileParserResult.swift
> [29/30] Merging module SourceryRuntime
> [30/31] Compiling SwiftTemplate main.swift
> /private/var/folders/t_/qv63qprj7p544mj2pfx3zzqw0000gn/T/SwiftTemplate/0.18.0/Sources/SwiftTemplate/main.swift:10:23: error: cannot find 'projectImports' in scope
>  for projectImport in projectImports(argument) { 

 swift --version = Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)
SwiftyMocky & Sourcery are installed via pods
PODS:
  - SwiftyMocky (4.0.1):
    - Sourcery (>= 1.0)

**Comment by krzysztofzablocki** [comment]
this issue should go into SwiftMocky repo
