### ISSUE TITLE
[minor] [typo] Parenthesis => parentheses (when should used in plural form, which is everywhere)

### ISSUE THREAD

**Issue by artyom-razinov** [krzysztofzablocki/Sourcery#876]
Plural form of `parenthesis` is `parentheses`, and it's like in every instance of usage of this word in the project (code works with parentheses in general, not like with only a single one, opening or closing parenthesis).

E.g. this is good:
- left parenthesis
- right parenthesis

This is not good:
- Method name without arguments names and parenthesis, i.e. `foo<T>`
- extracts enums with empty parenthesis as ones with () associated type

I know the issue is a joke.

I wanted to fix it myself, but I've stumbled upon `docs/search.json` and was afraid to edit it, because I don't know how it works and I don't know what will happen after I edit it (e.g. some state somewhere will become inconsistent, etc).

If you say that I just can replace it everywhere where it will be semantically correct, I would do it.

**Comment by krzysztofzablocki** [comment]
majority of docs is generated so you only need to update code comments and [guides](https://github.com/krzysztofzablocki/Sourcery/tree/a3aab352e78ea3e2eccb2bb9375740ff9bd3427f/guides) and then simply call `rake docs`, I'd be happy to accept PR fixing any wording mistakes, English isn't my native language so no wonder there are mistakes like this

Thanks for pointing it out 👍
