### ISSUE TITLE
Slower parsing time and new warnings since update

### ISSUE THREAD

**Issue by Robuske** [krzysztofzablocki/Sourcery#879]
Hello, unfortunately I am not sure which version I was using before, pretty sure it was 1.0.0, but since I updated to 1.0.2 the "Scanning sources" step spews a few new warnings with _"unknown type, please add type attribution to variable"_.
And besides the warnings the parsing got way slower, it used to take around 20-30 seconds, its taking 50-60 seconds now.

This happened booth on a machine that I updated the version and on a machine with a fresh install. But the warnings seem to only appear once, if I run the command again they don't appear again, but the time still is around 50 seconds.

Environment:

```shell
Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)
Target: x86_64-apple-darwin20.1.0
```

macOS Big Sur 11.0.1

**Comment by krzysztofzablocki** [comment]
can you share actual statistics from Sourcery run? file parsing results are cached so they can't be taking same amount of time in subsequent runs

**Comment by Robuske** [comment]
To make it clear, I do delete the generated files between the runs, but only them, I don't even know where the Sourcery caches are. But here are some results.

After a clean:

```shell
Using configuration file at '.sourcery.yml'
Scanning sources...
	loadOrParse: 59.422215938568115
	resolution took 0.3300340175628662
	combiningTypes: 0.5686570405960083
	total: 60.07856202125549
Found 1786 types.
Loading templates...
Loaded 1 templates.
	Loading took 0.0030629634857177734
Generating code...
	Generating App.stencil took 0.32400691509246826
		Processing Ranges took 0.05888700485229492
	Generation took 0.5033609867095947
Finished.
Processing time 60.58570396900177 seconds
```

Immediately after:

```shell
Using configuration file at '.sourcery.yml'
Scanning sources...
	loadOrParse: 0.3648730516433716
	resolution took 0.2786959409713745
	combiningTypes: 0.4255850315093994
	total: 0.8518719673156738
Found 1786 types.
Loading templates...
Loaded 1 templates.
	Loading took 0.0019649267196655273
Generating code...
	Generating App.stencil took 0.17072808742523193
		Processing Ranges took 0.04961597919464111
	Generation took 0.4783710241317749
Finished.
Processing time 1.332108974456787 seconds
```

And again:

```shell
Using configuration file at '.sourcery.yml'
Scanning sources...
	loadOrParse: 0.33434295654296875
	resolution took 0.27713704109191895
	combiningTypes: 0.42103397846221924
	total: 0.8167339563369751
Found 1786 types.
Loading templates...
Loaded 1 templates.
	Loading took 0.002047896385192871
Generating code...
	Generating App.stencil took 0.1679309606552124
		Processing Ranges took 0.05011403560638428
	Generation took 0.46274495124816895
Finished.
Processing time 1.2812999486923218 seconds
```

After another clean:

```shell
Using configuration file at '.sourcery.yml'
Scanning sources...
	loadOrParse: 59.082428097724915
	resolution took 0.2842189073562622
	combiningTypes: 0.45350801944732666
	total: 59.5957510471344
Found 1786 types.
Loading templates...
Loaded 1 templates.
	Loading took 0.0019530057907104492
Generating code...
	Generating App.stencil took 0.20003795623779297
		Processing Ranges took 0.050665974617004395
	Generation took 0.3454749584197998
Finished.
Processing time 59.943500995635986 seconds
```

**Comment by krzysztofzablocki** [comment]
looks to me like you are removing your caches, don't you have their folder setup up manually in yml file?

**Comment by Robuske** [comment]
Nope, here is our _Makefile_ code:

```makefile
generate_snapshots_code: 
	sourcery

clean_snapshots_code:
	rm $(GENERATED_SNAPSHOTS_DIR)/*.generated.swift
```

And our yml:

```yml
sources:
  - Modules/Sources
templates:
  - Tools/Sourcery
output: Modules/Tests/
prune: true
```

I don't think that should influence this, but we also use SwiftGen generation. But we also just generate some files and clean them directly, there is not even an wildcard in their case.

(Sorry for the delay on the response)

**Comment by krzysztofzablocki** [comment]
is this on your local machine or CI ? 
it's really odd you are getting whole parsing process, was it happening before as well? normally when people use Sourcery you only re-parse source files that actually changed.

Unless you have a script that touches modified date on every file in your project all subsequent runs of Sourcery should take minimal amount of time, e.g. Times app has 2500+ types and subsequent sourcery runs take less than 2s

**Comment by Robuske** [comment]
It's on my local machine.

Based on what you said I decided to test something, apparently _SwiftGen_ string generation "dirties" the files for some reason, but only the strings one, not the assets. Which is pretty weird since it should only look in two specific folders 🤔
Seems like I need to open an issue there too.

Well, that explains the long time on subsequent runs, but doesn't explain the time increase between versions.
I decided to [test different _Sourcery_ versions](https://remarkablemark.org/blog/2017/02/03/install-brew-package-version/) to make sure I was not crazy about the time increase, and well, I am not crazy.
There is a huge performance drop on version 1.0.1, I will paste here the parse time for the versions I tested, all of them I was doing what I described on the other comment, cleaning the folders and running again (along with _SwiftGen_, to keep it consistent and because it dirtying the files made sure the parse happened again).
Also, like I said at the beginning, version 1.0.1 introduced some new warnings on the first run. The time is consistent on subsequent runs, only the warnings don't appear again.

---

Version 0.18.0 (https://github.com/Homebrew/homebrew-core/blob/2a1be005156315495a40d83e8479d8385beb5489/Formula/sourcery.rb):

```shell
Using configuration file at '.sourcery.yml'
Scanning sources...
	loadOrParse: 17.468809008598328
	resolution took 0.5005619525909424
	combiningTypes: 0.5892449617385864
	total: 18.14744508266449
Found 1783 types.
Loading templates...
Loaded 1 templates.
	Loading took 0.0023690462112426758
Generating code...
	Generating App.stencil took 0.16137003898620605
		Processing Ranges took 0.04744899272918701
	Generation took 0.30121099948883057
Finished.
Processing time 18.451603055000305 seconds
```

---

Version 1.0.0 **without** Big Sur bottle (https://github.com/Homebrew/homebrew-core/blob/53200319a23744dcef3aa9734a1f672b698667ce/Formula/sourcery.rb):

```shell
Using configuration file at '.sourcery.yml'
Scanning sources...
	loadOrParse: 17.138863921165466
	resolution took 1.0415350198745728
	combiningTypes: 1.1832979917526245
	total: 18.41755700111389
Found 1783 types.
Loading templates...
Loaded 1 templates.
	Loading took 0.004739046096801758
Generating code...
	Generating App.stencil took 0.15608203411102295
		Processing Ranges took 0.04809391498565674
	Generation took 0.3227109909057617
Finished.
Processing time 18.742681980133057 seconds
```

---

Version 1.0.0 **with** Big Sur bottle (https://github.com/Homebrew/homebrew-core/blob/7ff625cef52eff9f102504b91502e183c6b32c0d/Formula/sourcery.rb):

```shell
Using configuration file at '.sourcery.yml'
Scanning sources...
	loadOrParse: 18.496602058410645
	resolution took 1.0461959838867188
	combiningTypes: 1.1835639476776123
	total: 19.745056986808777
Found 1783 types.
Loading templates...
Loaded 1 templates.
	Loading took 0.0021500587463378906
Generating code...
	Generating App.stencil took 0.15960299968719482
		Processing Ranges took 0.04956197738647461
	Generation took 0.31984496116638184
Finished.
Processing time 20.067407965660095 seconds
```

---

Version 1.0.1 (https://github.com/Homebrew/homebrew-core/blob/2d5d7761a33fbc3eaaeb2be1848df140ddf9c56b/Formula/sourcery.rb):

```shell
Using configuration file at '.sourcery.yml'
Scanning sources...
# Shows some warnings like: <<unknown type, please add type attribution to variable 'var xxxxxx'>>
	loadOrParse: 51.82023203372955
	resolution took 0.2910339832305908
	combiningTypes: 0.4483109712600708
	total: 52.351884961128235
Found 1783 types.
Loading templates...
Loaded 1 templates.
	Loading took 0.0025529861450195312
Generating code...
	Generating App.stencil took 0.2468569278717041
		Processing Ranges took 0.0522540807723999
	Generation took 0.43969500064849854
Finished.
Processing time 52.79865896701813 seconds
```

---

Version 1.0.2 (current default version on Homebrew):

```shell
Using configuration file at '.sourcery.yml'
Scanning sources...
# Shows some warnings like: <<unknown type, please add type attribution to variable 'var xxxxxx'>>
	loadOrParse: 50.78591501712799
	resolution took 0.2795799970626831
	combiningTypes: 0.4115910530090332
	total: 51.26980698108673
Found 1783 types.
Loading templates...
Loaded 1 templates.
	Loading took 0.003300905227661133
Generating code...
	Generating App.stencil took 0.1722348928451538
		Processing Ranges took 0.04899299144744873
	Generation took 0.3341299295425415
Finished.
Processing time 51.61031496524811 seconds
```

**Comment by krzysztofzablocki** [comment]
the parsing time increase is totally expected because we didn't actually parse as much as we simply parsed a first line of your variable declaration, we now parse a whole block and do more transformations. 
In complex declarations before we'd often not get proper type inference because of that, now we only miss very few types which is what the warning let's you know.

This shouldn't be a big deal for almost anyone because parser results are cached and we re-parse only the files that have been modified, so even if you had tens of thousands of files, you'll have a longer first parse but subsequent runs should always be really fast due to that caching

**Comment by Robuske** [comment]
I see, based on the release notes I didn't get that something like that had changed. Makes sense then.

Good point about the caching for other tools too, I will have to take a look a that, thanks.

**Comment by Robuske** [comment]
I just want to report that whatever was the problem between _Sourcery_ and _SwiftGen_ seems to have been fixed. I am not sure when it was fixed, so I can't say for sure, but if I had to guess I would say it was [version 1.3.0](https://github.com/krzysztofzablocki/Sourcery/releases/tag/1.3.0) with the change from _SourceKit_ to _SwiftSyntax_.
