### ISSUE TITLE
All files under --output path are checked for write access

### ISSUE THREAD

**Issue by Cyberbeni** [krzysztofzablocki/Sourcery#880]
I have this inside my Xcode build phase:
```bash
ROOT_DIR="$(git rev-parse --show-toplevel)"

if [ -f "$(brew --prefix)/bin/sourcery" ]; then
    PARAMS=""
    for exclude in $(find "$SRCROOT" -name ".git"); do
        PARAMS="$PARAMS --exclude-sources `echo "$exclude" | sed 's/ /\\ /g'`/.."
    done
    "$(brew --prefix)/bin/sourcery" --prune --sources "$SRCROOT" $PARAMS --templates "$ROOT_DIR/tools/Sourcery" 2> /dev/null
fi
```
There is another repository checked out somewhere inside my SRCROOT which is inside the gitignore and is always updated to the latest version.
When this runs, I get an error message `error: '/path/to/repo/.git/objects/61/0a7b68e878da90f425f04d62e78f750c7fd82d' isn't writable.`

**Comment by krzysztofzablocki** [comment]
hey, you'll need to show us what you are actually passing in to our tool, we can't be asked to analyse your script code or know your environment setup

**Comment by Cyberbeni** [comment]
It can be reproduces just by doing this:
```console
> touch a.stencil
> mkdir a
> touch a/a
> chmod 444 a/a
> sourcery --sources ./a --exclude-sources ./a/a --templates ./a.stencil
No config file provided or it does not exist. Using command line arguments.
error: '/Users/cyberbeni/Desktop/test/sourcery/a/a' isn't writable.
'/Users/cyberbeni/Desktop/test/sourcery/a/a' isn't writable.%
```
The script in the OP finds all the .git named files/folders and then passes their parents into `--exclude-sources`, so `--exclude-sources ./a/.git/..` should exclude `./a`

**Comment by Cyberbeni** [comment]
Tried to do some debugging but for some reason breakpoints don't work for me in this project (I opened Package.swift)
But I managed to figure out that the error is coming from this line: https://github.com/krzysztofzablocki/Sourcery/blob/5d77d28852879980c0bc3d36a465f42970b4fef1/Sourcery/main.swift#L73

As far as I understand, if the output is a folder then that has to be checked for write access and the files inside it based on the template names but not the files that have different names or are inside a subdirectory.

**Comment by krzysztofzablocki** [comment]
yes output needs to be writable and the file names aren't just based on templates names but it's more flexible than that (you can customize them in template code) so we can't have a check here. Just make a dedicated output folder for codegen that's writeable
