### ISSUE TITLE
@objcMembers in separate line breaks annotation

### ISSUE THREAD

**Issue by Cyberbeni** [krzysztofzablocki/Sourcery#882]
This works:
```swift
// sourcery: init, isEqual, hash
@objcMembers public final class
```

This doesn't:
```swift
// sourcery: init, isEqual, hash
@objcMembers
public final class
```

**Comment by art-divin** [comment]
👋🏻 hello @Cyberbeni ,

thank you very much for reporting this issue!

Seems like this issue was resolved by #1172. Feel free to re-open if you have any issues 👍🏻
