### ISSUE TITLE
How to add extra new lines spacing in sourcery output?

### ISSUE THREAD

**Issue by krishnaagarwal1994** [krzysztofzablocki/Sourcery#885]
I am trying to generate mocks using Sourcery by writing my own stencil template, in the output at some places I need to give a single line spacing between two variables. I tried doing {{ type.name \n }}, assuming that each variable in the output would also add a new line before printing the next type, but it's not working.
Can you please help suggest how to add line spacing in the stencil template?

Thanks In advance.

**Comment by Cyberbeni** [comment]
This will have a newline after each `type.name`:
```
{% for type in types.all %}
{{ type.name }}
{% endfor %}
```
This will print them in a single line with 1 space between them (and omitting the space after the last):
```
{% for type in types.all %}{{ type.name }}{% ifnot forloop.last %} {% endif %}{% endfor %}
```

**Comment by krishnaagarwal1994** [comment]
@Cyberbeni Thanks for the reply and I totally agree with what you say. But the above template will print each type on a new line. eg.
A
B
C
But what I need is one extra line of spacing between each type.name in the output, eg.
A
//Empty Line
B
//Empty Line
C

**Comment by Cyberbeni** [comment]
Then just add an extra newline, like this:
```
{% for type in types.all %}
{{ type.name }}

{% endfor %}
```

**Comment by krishnaagarwal1994** [comment]
@Cyberbeni That's the first thing I tried, and it's not working for me. Can you please help confirm if this is working correctly for you?

**Comment by Cyberbeni** [comment]
Hmm, it doesn't work for me either. Weird, I remember having some empty lines in my generated file. 🤔

**Comment by krishnaagarwal1994** [comment]
@Cyberbeni Having empty lines is a very normal use case. Do let me know in case you figure out the solution.

**Comment by krzysztofzablocki** [comment]
I just tested and it works as expected

```swift
{% for type in types.all %}
{{ type.name }}

{% endfor %}
```

```swift
ABRA.Test

ABRAIntegration

ABRANetworkWrapper
```

**Comment by krishnaagarwal1994** [comment]
@krzysztofzablocki Thank you, it's now working for me as well, earlier it didn't work for me, and @Cyberbeni , I don't know why. Since the issue is now resolved I am closing this issue.
