### ISSUE TITLE
Support for while loop of something like recursion

### ISSUE THREAD

**Issue by krishnaagarwal1994** [krzysztofzablocki/Sourcery#886]
I have a use case where I am parsing a struct/class along with its properties and make those struct/classes conform to Codable protocol, struct/class properties may be of primitive data types like String, Int, Bool, Double, etc, or custom user-defined data types. For properties that custom user-defined data type, i again need to declare a struct/class for them and make it conform to Codable protocol, this sequence continues.. In order to achieve this, I need to use a while loop of recursion. Since I was unable to find one so I tried calling macroA inside the macroA, which caused the segmentation fault.
What should be the right/available approach to achieve the above thing get done?

```
{% macro declareVariable variable %}{% if variable.isMutable %}var {% else %}let {% endif %}{{ variable.name }}: {{ variable.typeName }}{% endmacro %}

{% macro printAllVariables type %}
	{% for variable in type.variables %}
		{% call declareVariable variable %}
	{% endfor %}
{% endmacro %}

{% macro printNonPrimitiveType type%} 
{% if type.kind == "struct" or type.kind == "class"%} 
	struct {{ type.name }}: Codable {
		{% call printAllVariables type %}
	}
        {% for variable in type.variables %}
	{% call printNonPrimitiveType variable %}
	{% endfor %}
{% endif %}
{% endmacro %}
```

**Comment by ilyapuchka** [comment]
This could be a an issue or a feature request for Stencil, not Sourcery. You could use Sqift templates for more powerful language features. Built-in codable template already is written in Swift.

Ilya Puchka

**Comment by krzysztofzablocki** [comment]
Recursion works in Stencil, I use it in in many templates, I think your template is written incorrectly, you are calling `printNonPrimitiveType` with a variable when it expects a `type`

**Comment by krishnaagarwal1994** [comment]
@krzysztofzablocki So does that mean a macro can call itself recursively, right?

**Comment by krzysztofzablocki** [comment]
yep like you'd expect

**Comment by krishnaagarwal1994** [comment]
@krzysztofzablocki  Thanks for confirming, will close the issue now.
