### ISSUE TITLE
Shorter expression for non-local typeName?

### ISSUE THREAD

**Issue by Cyberbeni** [krzysztofzablocki/Sourcery#888]
Imagine a structure like this:
```swift
public enum A {
    public struct B {}
    public struct C { let b: B }
}
```
When generating code for C to a separate file into a separate extension using `variable.typeName`, it will look like this:
```swift
public extension A.C {
    init(b: B) {
        self.b = b
    }
}
```
(I know that init has to be generated in the same file, it's just an example)
But this will error because B is not defined in the scope, so I need to use the following expression: `{% if variable.type %}{{variable.type.name}}{% else %}{{variable.typeName}}{% endif %}`
Is there a shorter expression for this?

**Comment by krzysztofzablocki** [comment]
I don't know how your template looks for the output you provided but a variable won't have type **only** if Sourcery doesn't know it (it's not scanned or it can't be inferred [easy fix by attributing it explicitly] ) which you really shouldn't is not a case you should be running into in our own types, so your template should be using just `{{ variable.type.name }}`

**Comment by Cyberbeni** [comment]
String/Bool/etc. didn't have `type`, just `typeName`.

**Comment by krzysztofzablocki** [comment]
you can make a function using macro tag to not repeat the pattern multiple times
