### ISSUE TITLE
Changes in imported swift files do not trigger a cache rebuild

### ISSUE THREAD

**Issue by hhanesand** [krzysztofzablocki/Sourcery#889]
Assuming we have a file like `Generation.swift` and it's imported like so:

```
<%- includeFile("../Utility/Generation.swift") -%>
```

If there is a compilation error stemming from code in `Generation.swift`, fixing that error and rerunning Sourcery results in the same compilation error popping up. 

Workaround: Make a trivial change to the template that is importing the file to force Sourcery to re-import the effected file.

**Comment by hhanesand** [comment]
I'm also seeing a bug where Sourcery overwrites Generation.swift with a previous version if one tries to re-run Sourcery, but I haven't quite tracked down reproduction steps. Currently the only fix I've found is to rename the file being imported. Nuking the Sourcery staging directory may work, but I haven't tried that. (passing --disableCache doesn't seem to help)

**Comment by krzysztofzablocki** [comment]
what is `Generation.Swift` because Sourcery doesn't write to files that are included (they are only read) so I don't really see how you could experience 2nd issue you've mentioned

**Comment by hhanesand** [comment]
Yeah, I figured that. Something else must be going on. Poor form to report 2 things in one issue anyways, let's leave discussion for the first comment.
