### ISSUE TITLE
Associated values are missing some information

### ISSUE THREAD

**Issue by dagio** [krzysztofzablocki/Sourcery#89]
Right now for each enum associated values we have : 

- name <- name
- typeName <- name of type of associated value

I suggest we could have similar information as variables : 

- name <- Name
- type <- type of the variable, if known
- typeName <- returns name of the type, including things like optional markup
- unwrappedTypeName <- returns name of the type, unwrapping the optional e.g. for variable with type Int? this would return Int
- isOptional <- whether is optional

The main motivation is to know if an associated value is optional

**Comment by krzysztofzablocki** [comment]
Actually that's already available, just not documented

**Comment by krzysztofzablocki** [comment]
Available in (0.5.0](https://github.com/krzysztofzablocki/Sourcery/releases/tag/0.5.0)
