### ISSUE TITLE
Fixed StencilSwiftKit version instead of branch

### ISSUE THREAD

**Issue by hectr** [krzysztofzablocki/Sourcery#898]
[Latest StencilSwiftKit release](https://github.com/SwiftGen/StencilSwiftKit/releases/tag/2.8.0) should allow Sourcery's `Podfile` and `Package.swift` to use a fixed version (`2.8.0`) instead of pointing to the `stable` branch.

Would it be possible to have a new Sourcery release that uses **StencilSwiftKit 2.8.0**?

**Comment by krzysztofzablocki** [comment]
yeah we can, we didn't use fixed version because they didn't have release in a long time

**Comment by krzysztofzablocki** [comment]
Done in 1.1.1
