### ISSUE TITLE
Generate more errors to ease writing templates

### ISSUE THREAD

**Issue by krzysztofzablocki** [krzysztofzablocki/Sourcery#90]
@kzaher suggested a valid point, 
if someone is doing things like `types.implementing.AutoEquatable` it would be useful to throw error if `AutoEquatable` isn't in our database of known types, so that people understand why it's happening.

If we are doing that then we can as well do following:
- If someone references Class in `implementing` inform them it's used via `inheriting` or `base`, same for mismatches in `inheriting`
- If someone references a type we don't know about via `implementing` `inheriting` let them know about `base`

**Comment by Joannis** [comment]
I didn't see this yet. An ancient issue. I could try contributing to this, if you'd like.

**Comment by krzysztofzablocki** [comment]
@Joannis contributions are always welcomed 👍
