### ISSUE TITLE
Variables with Self type do not get resolved

### ISSUE THREAD

**Issue by erichoracek** [krzysztofzablocki/Sourcery#900]
In [Swift 5.1](https://swift.org/blog/swift-5-1-released/), [SE-0068](https://github.com/apple/swift-evolution/blob/master/proposals/0068-universal-self.md) expanded Swift’s use of `Self` so that it refers to the containing type when used inside classes, structs, and enums. However, Sourcery doesn't seem to support this. For example:

If you have the following Swift file `test.swift`:
```swift
struct A {
  static var specificType: A { .init() }
  static var selfType: Self { .init() }
}
```

And the following template `test.stencil`:
```stencil
{% for type in types.types %}
{% for variable in type.staticVariables %}
{{ variable.name }}
- {{ variable.type.name }}
- {{ variable.typeName.name }}
{% endfor %}
{% endfor %}
```

And run `sourcery --sources test.swift --templates test.stencil --output output.txt`:

You'll get the following `output.txt`:
```
specificType
- A
- A
selfType
- 
- Self
```

Note that `variable.type.name` is `nil` for `selfType`.

My expectation would be the following output instead:
```
specificType
- A
- A
selfType
- A
- Self
```

Tested on Sourcery version 1.1.1

**Comment by krzysztofzablocki** [comment]
Thanks for providing nice report @erichoracek, I'll try to add this feature to next release
