### ISSUE TITLE
Question - Is it possible to generate SwiftUI views for models?

### ISSUE THREAD

**Issue by avnerbarr** [krzysztofzablocki/Sourcery#911]
I require some simple data entry, but have lots of different models.

Is it possible to annotate the models and the SwiftUI data entry views could be generated for me :)

Thanks!

**Comment by krzysztofzablocki** [comment]
@avnerbarr yep, I've pretty much did that in https://github.com/krzysztofzablocki/AutomaticSettings

**Comment by avnerbarr** [comment]
Thanks @krzysztofzablocki !

I'm trying it now, but running into an issue integrating `AutomaticSettingsViewDSL`

```
'navigationBarTitle' is unavailable in macOS
```
(there are several more scattered around)


In the package https://github.com/krzysztofzablocki/AutomaticSettings/blob/main/Package.swift it seems like it should support mac applications right?

```
let package = Package(
    name: "AutomaticSettings",
    platforms: [
            .macOS(.v10_15),
            .iOS(.v13)
    ],
```

**Comment by krzysztofzablocki** [comment]
the idea and almost all of the template will work but you'd need to add some system `#if os(macOS)` in the template, I didn't really have time to attribute it correctly (sorry), would love a pr with those changes if you could add one :)

**Comment by avnerbarr** [comment]
Working on it now.

Still trying to understand how to compile the templates. I can open the PR though for review.

**Comment by krzysztofzablocki** [comment]
@avnerbarr sure, we can discuss it in settings repo
