### ISSUE TITLE
Sourcery 1.3.2 fails to generate mocks

### ISSUE THREAD

**Issue by falcowinkler** [krzysztofzablocki/Sourcery#915]
```
swift version: 5.1
XCode version: 12.3
```
Command:
`./Pods/Sourcery/bin/sourcery --disableCache --watch`

Expected behaviour: 
Code generation works as before

Actual behaviour:
```bash
Using configuration file at '.sourcery.yml'
Scanning sources...
Found 788 types in 634 files, 1 changed from last run.
Loading templates...
Loaded 1 templates.
Generating code...
Finished.
Starting watching sources.
```

Generated file:

```swift

// Generated using Sourcery 1.3.2 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT
// swiftlint:disable line_length
// swiftlint:disable variable_name

import Foundation
#if os(iOS) || os(tvOS) || os(watchOS)
import UIKit
#elseif os(OSX)
import AppKit
#endif
```

I am using a slightly modified AutoMockable.stencil, but also with the original the error persists.
When downgrading again to 1.3.1 everything works fine again

**Comment by krzysztofzablocki** [comment]
@falcowinkler we are gonna need a bit more data to do anything about this, show us a code of a sample type that doesn't get processed

**Comment by falcowinkler** [comment]
@krzysztofzablocki 
It seems that the problem exists only for types that are annotated with interface inheritance

```swift
protocol AutoMockable {}
```
And for example
```swift
protocol NotificationCenterWrapperProtocol: AutoMockable {
    func post(name: NSNotification.Name, object: Any?, userInfo: [AnyHashable: Any]?)
   ...
}
```

So it seems that `where type.based.AutoMockable` predicate doesn't work anymore since the version upgrade. As i said, the mocks are generated fine in 1.3.1... Did something change in this regard?

**Comment by krzysztofzablocki** [comment]
use type.implements.AutoMockable if you define the protocol in your scanned source code

**Comment by falcowinkler** [comment]
no, `type.implements.AutoMockable` also doesn't work for 1.3.1 even.. also if i just use the AutoMockable.stencil from this repo.

I'm not really sure what's going on. I think best would be to create a minimal project first, or i can write a test for it

**Comment by krzysztofzablocki** [comment]
example would be ideal, and probably easier for you to prep, I can write tests once I confirm the issue

**Comment by falcowinkler** [comment]
@krzysztofzablocki i am able to reproduce it reliably also in a small example project.
https://github.com/falcowinkler/sourcery-experiments
can you kindly have a look if you can reproduce the issue? i added the necessary steps in the README

**Comment by krzysztofzablocki** [comment]
yeah Sourcery works fine, but you'd need to use fully qualified name which for your configuration is `type.based["sourcery-experiments.AutoMockable"]` given you use module integration

I know @eldudi wanted to add convience support for skipping module name when querying those things but he doesn't have time right now, so probably next release?

**Comment by paweldudek** [comment]
@falcowinkler yeah I'm a bit busy right now but I might be able to have a fix next week. I managed to work around this by doing the following: 

```
{% if variable.type.implements["MyModule.MyType"] %}
```

**Comment by falcowinkler** [comment]
thanks for the fast reply! with explicit module it works in version 1.3.2. i am curious why it worked in the previous version... otherwise thanks for this great software, it's working really well for us.

**Comment by krzysztofzablocki** [comment]
@falcowinkler because as I kept improving composer I need to rely on fully qualified names, you could have 2 types with the same name in different modules and old version would be broken but new would work
