### ISSUE TITLE
Make "No templates provided" warning a warning and not an error.

### ISSUE THREAD

**Issue by Lutzifer** [krzysztofzablocki/Sourcery#916]
We have uniform folder structures across multiple projects.

Sometimes, we don't yet have sourcery templates for specific cases, which yields this error:

` ❌  error: while reading .yml 'sourcery.yml'. 'Invalid templates. No templates provided.'`

What do you think of toning this down to "warning"?

**Comment by krzysztofzablocki** [comment]
fine by me, it's error since it's just wasteful operation but send over a pr and I'll merge it

**Comment by krzysztofzablocki** [comment]
@Lutzifer want to send that pr?

**Comment by Lutzifer** [comment]
Yeah, still needs some testing, might find some time later today

**Comment by Lutzifer** [comment]
@krzysztofzablocki I can no longer reproduce this using 1.4.2
