### ISSUE TITLE
Performance when using multiple .swifttemplates

### ISSUE THREAD

**Issue by GabrielHauber** [krzysztofzablocki/Sourcery#917]
We are using Sourcery to generate several different files from different templates. Currently we have 8 templates, 7 of which are `.swifttemplate` and one is a `.stencil`

I've noticed that there seems to be significant overhead for each `.swifttemplate` - between 2.5 and 3s on my machine, that is not present for the `.stencil` file. This means that a code generation run is of the order of of 20-30 seconds processing just over 3,000 types even if no files have changed. This overhead exists even if the `.swifttemplate` file is empty and outputs nothing.

If I combine 2 `.swifttemplate`s into one, then I lose the overhead of processing the second template, but gain the extra complexity of having two unrelated things in the same file making it more complex for a human to understand.

Are there any other optimisation steps I am potentially missing?

**Comment by krzysztofzablocki** [comment]
swifttemplates are compiled as normal Swift application which is why they are so slow, not much you can do there. I really recommend Stencil or ejs over swifttemplate for that reason

1.3.1 will probably be faster than 1.3.3 for your setup since old composer didn't require extra processing

**Comment by GabrielHauber** [comment]
Thanks. I thought that might be the case but was hoping for something different.
