### ISSUE TITLE
AssociatedValue external name fallback only works well when adding a prefix

### ISSUE THREAD

**Issue by Cyberbeni** [krzysztofzablocki/Sourcery#918]
https://github.com/krzysztofzablocki/Sourcery/blob/542bf3576404cff3367218107b4b8f6171db5d91/SourceryFramework/Sources/Parsing/SwiftSyntax/AST/EnumCase%2BSwiftSyntax.swift#L19-L21

I think this should be something like this:
```swift
if externalName == nil {
    externalName = name ?? hasManyValues ? "p\(idx)" : node.name
}
```

Currently if it's a single unnamed associated value then externalName will be empty.
If it's multiple values then it is currently named as just a single number but Swift doesn't allow parameter names to start with a number, so it needs a prefix letter.
I don't know if `node.name` is actually correct but the idea is that if I have a `case file(URL)` then the name `file` is probably suitable for that parameter. But I think using "p0" in this case would also be fine.

For something like Equatable generation, this will be prefixed with "l" or "r" in the stencil, so it's not  problem there.
But for something like Codable generation, using it without prefixing would be preferred.

**Comment by krzysztofzablocki** [comment]
@Cyberbeni I don't understand what you are talking about here?  this is implemented to correlate with how you'd use the names in a binding sysstem:

if you have enums with associated values that are unnamed you refer to them by numbers e.g.
```swift
case value(Int, named: Float)
if case let .value(content) = myEnumValue {
  content.0
  content.named
}
```

if you have named arguments those are external names and that's working as expected

**Comment by Cyberbeni** [comment]
Ah, I was expecting it to be used like this:
```swift
let value1 = try decodeValue1()
let value2 = try decodeValue2()
self = .value(value1, named: value2)
```
but I guess `forloop.counter` can always be used for this

**Comment by krzysztofzablocki** [comment]
yeah no worries, most AST decisions are based on how what's going to enable you to write valid swift
