### ISSUE TITLE
open vars/classes showing accessLevel as "internal"

### ISSUE THREAD

**Issue by hborawski** [krzysztofzablocki/Sourcery#927]
Ignore the edits, accidentally hit enter while going for the quote key 🤦 

First time using sourcery and it's working great for the most part, but I've run into an issue where `open` variables and classes are showing the access level as `internal`, and I haven't been able to find other issues like this or any mention of a configuration issue.

I put together a quick demo repo to illustrate the problem: https://github.com/hborawski/SourceryExample

Config file: https://github.com/hborawski/SourceryExample/blob/main/.sourcery.yml
Template: https://github.com/hborawski/SourceryExample/blob/main/SourceryExample/example.stencil
Example Types: https://github.com/hborawski/SourceryExample/blob/main/SourceryExample/SourceryExample.swift
Output: https://github.com/hborawski/SourceryExample/blob/main/SourceryExample/output.swift

This is using the latest Sourcery (`1.3.4`) so any help is much appreciated!

**Comment by krzysztofzablocki** [comment]
thanks for reporting, I'll take care of that soon

**Comment by robertjpayne** [comment]
@krzysztofzablocki I think `isFinal` on classes may be affected by this as well. Using 1.3.4 it's breaking our build pipeline because `isFinal` is set to `0` even when the class is clearly marked as final.

**Comment by krzysztofzablocki** [comment]
@robertjpayne might making a ticket with a code sample that fails? I'll make a new release of https://merowing.info/sourcery-pro/ and will get on it

**Comment by robertjpayne** [comment]
@krzysztofzablocki it's not the easiest to get setup into the project files – but from quick looks the entire `attributes` dictionary you get from `ClassDeclSyntax` is always empty. I'm trying to sort it out.
