### ISSUE TITLE
1.3.4 Catalina bottle is missing

### ISSUE THREAD

**Issue by fchauvin** [krzysztofzablocki/Sourcery#943]
This error seems to have started yesterday when running `brew install sourcery` on our CI.

![Screen Shot 2021-04-13 at 10 08 11 AM](https://user-images.githubusercontent.com/1099119/114566560-69b14f80-9c40-11eb-82d8-0f8764a8e9fb.png)

**Comment by krzysztofzablocki** [comment]
that's a release that happened a while ago, we didn't change anything on our side so seems like brew issue?

**Comment by fchauvin** [comment]
Yeah you seem to be right, according to this thread here: https://github.com/Homebrew/discussions/discussions/691

Thanks for the quick response, will close now.
