### ISSUE TITLE
AutoCodable not generating code

### ISSUE THREAD

**Issue by lizhihui0215** [krzysztofzablocki/Sourcery#948]
I have run sourcery in my project. and I have copied the [AutoCodable.swifttemplate](https://github.com/krzysztofzablocki/Sourcery/blob/master/Templates/Templates/AutoCodable.swifttemplate) and [AutoEquatable.stencil](https://github.com/krzysztofzablocki/Sourcery/blob/master/Templates/Templates/AutoEquatable.stencil) into my project 
I did everything on doc here: [Codable](https://github.com/krzysztofzablocki/Sourcery/blob/master/guides/Codable.md)
But when i run sourcery the AutoCodable related sources are not generated but the AutoEquatable are fine.

could any one help on this.

```
Using configuration file at './.sourcery.yml'
Scanning sources...
	loadOrParse: 0.014073014259338379
ast warning: Found "extension HTTPHeader" of type for which there is no original type declaration information.
resolution took 0.0013399124145507812
	combiningTypes: 0.0031189918518066406
	total: 0.0523909330368042
Found 41 types in 10 files, 10 changed from last run.
Loading templates...
Loaded 2 templates.
	Loading took 0.010114073753356934
Generating code...
Rendering template /Users/lizhihui/Workspace/Asset/Asset/SourceryGenerated/Templates/AutoCodable.swifttemplate
/usr/bin/env "xcrun" "--sdk" "macosx" "swift" "build" "-Xswiftc" "-Onone" "-Xswiftc" "-suppress-warnings" "--disable-sandbox"
/var/folders/0r/n9nphfkd5pd56j1t80lz3rjc0000gn/T/SwiftTemplate/1.4.1/.build/debug/SwiftTemplate "/var/folders/0r/n9nphfkd5pd56j1t80lz3rjc0000gn/T/SwiftTemplate/1.4.1/context.bin"
	Generating AutoCodable.swifttemplate took 6.451053023338318
		Processing Ranges took 0.0003409385681152344
Skipping /Users/lizhihui/Workspace/Asset/Asset/SourceryGenerated/AutoCodable.generated.swift as it is empty.
Rendering template /Users/lizhihui/Workspace/Asset/Asset/SourceryGenerated/Templates/AutoEquatable.stencil
	Generating AutoEquatable.stencil took 0.0049610137939453125
		Processing Ranges took 0.00031507015228271484
	Generation took 6.467684030532837
Finished.
Processing time 6.523002028465271 seconds
```

**Comment by krzysztofzablocki** [comment]
Which version of Sourcery are you running?

**Comment by krzysztofzablocki** [comment]
what's your command line tools version? `xcode-select -p` ?

**Comment by lizhihui0215** [comment]
@krzysztofzablocki hope this can help.
<img width="566" alt="Screen Shot 2021-04-29 at 6 24 41 PM" src="https://user-images.githubusercontent.com/3880275/116537179-790aeb00-a918-11eb-8dfb-b3eb058b2502.png">

**Comment by krzysztofzablocki** [comment]
@lizhihui0215 could you try creating a sample that reproduces the issue? without sample code it's not going to be easy to reproduce because Sourcery succeeded but the template just doesn't generate output?

are you using annotations or marker protocol to find types to extend?

**Comment by lizhihui0215** [comment]
Hi @krzysztofzablocki 
here is sample project [SourceryTest](https://github.com/lizhihui0215/SourceryTest)

**Comment by krzysztofzablocki** [comment]
@lizhihui0215 this is working properly, your code doesn't need any generated code to work so the template doesn't generate any, you need to do something that actually requires a custom implementation for it to generate it, otherwise it just falls back to default which system generates, e.g. add this

```swift
enum Test {
    case something(Int, name: String)
}

extension Test: AutoCodable {}
```

and you'll see generated code appearing.

Or add some custom coding keys, or processing per https://github.com/krzysztofzablocki/Sourcery/blob/master/guides/Codable.md and it will generate the code for you, but right now your code simply doesn't need any codegen so the template is smart enough to skip it

**Comment by krzysztofzablocki** [comment]
@lizhihui0215 let me know if anything is unclear
