### ISSUE TITLE
Detecting build running from terminal doesn't work (in GitHub Actions)

### ISSUE THREAD

**Issue by Cyberbeni** [krzysztofzablocki/Sourcery#967]
My action was running these commands:
```bash
/usr/local/bin/git clone --depth 1 --branch 1.4.2 https://github.com/krzysztofzablocki/Sourcery /Users/runner/install-swift-tool-794b233d-2f0c-5d6d-a5a9-5ee54587f249
/usr/bin/swift build --package-path /Users/runner/install-swift-tool-794b233d-2f0c-5d6d-a5a9-5ee54587f249 --configuration release --disable-sandbox
```

The build failed because of `<unknown>:0: error: unknown argument: '-rpath'`: https://github.com/Cyberbeni/install-swift-tool/runs/2754226819?check_suite_focus=true#step:3:224

It's not supposed to add that linker flag when running from command line: https://github.com/krzysztofzablocki/Sourcery/blob/1.4.2/Package.swift#L225

Shouldn't we check if `ProcessInfo.processInfo.arguments[0] == "/usr/bin/swift"` instead of the environmental variables?

**Comment by krzysztofzablocki** [comment]
you might be onto something @Cyberbeni, can you make that work with both normal Swift build and rake build?
