### ISSUE TITLE
[QUESTION] Are there other examples of inline code templates?

### ISSUE THREAD

**Issue by melMass** [krzysztofzablocki/Sourcery#973]
Hi,

Amazing tool!
Is there an example of inline init for instance?

I don't understand this part of the doc, is it inserting the comment? What is .TemplateName?

To see if inlining worked I tried the auto example and it added the comment at the end of every type declaration of my project, fortunately, I committed before testing it. But I can't wrap my head around how It works and how to avoid "corrupting" source files.

Thanks

**Comment by krzysztofzablocki** [comment]
the way auto variant of inline works is exactly that, it will add code at the end of type declaration.

As you saw it adds blocks to mark the code that was generated:
 
```swift
// sourcery:inline
// sourcery:end
```

that way in next sourcery run it knows which code not to parse and which to replace in subsequent runs, that's how it avoids corruption and chicken-egg situations

**Comment by melMass** [comment]
Thanks! 
So if I understand you, when I deleted the `inline:auto` from my template it should have deleted the section in the source code? Or maybe just the comment remains.

---

Sorry but I'm still not sure so I will take an example.

### Controls.swift
```swift
import Foundation
import SwiftUI

protocol ControlProtocol {
    var id: UUID { get }
    var name: String { get set }

    func draw() -> AnyView
}

struct SliderControl: ControlProtocol {
    var id: UUID
    var name: String
    func draw() -> AnyView {
        AnyView(Text(name))
    }
}

struct ColorControl: ControlProtocol {
    var id: UUID
    var name: String

    func draw() -> AnyView {
        AnyView(Text(name))
    }
}

```

How would you convert this to have the init inline instead of an extension:

### ControlsInit.stencil

```stencil
import Foundation

{% for st in types.implementing.ControlProtocol %}
extension {{ st.name }} {

  init(name:String="Untitled"){

    self.id = UUID()
    self.name = name
  }

}
{% endfor %}
```

**Comment by krzysztofzablocki** [comment]
probably like this
```swift
{% for st in types.implementing.ControlProtocol %}
// sourcery:inline:auto:{{ st.name }}.ControlsInit
  init(name:String="Untitled"){

    self.id = UUID()
    self.name = name
  }
// sourcery:end
{% endfor %}
```

PS. if you start using Sourcery more I recommend getting [SourceryPro](https://merowing.info/sourcery-pro/) since it has powerful stencil editor and Xcode extension

**Comment by melMass** [comment]
Ohhhh ok! this: `{{ st.name }}.ControlsInit` is just for reference or is sourcery using the value somehow (that's what causes confusion to me).

Just got it!

![image](https://user-images.githubusercontent.com/7041726/126494015-6d84b744-08b7-4f95-96c0-a63eb0d5e581.png)

**Comment by melMass** [comment]
Do you have a version compatible with macOS 10.15? I can't update for the meantime...

**Comment by krzysztofzablocki** [comment]
it's just reference convention so that you know where to look for the template code later on, as you often have many templates in project.

as far as Pro it requires Big Sur because it's using SwiftUI

**Comment by melMass** [comment]
IMO it should be stated clearly.
Also, I guess you know, but there is another templating software called Sourcery Pro: https://sourcery.ai/pro/
