### ISSUE TITLE
fore-parse not working (for protocols?) in 1.5.0

### ISSUE THREAD

**Issue by fabianmuecke** [krzysztofzablocki/Sourcery#983]
Hi,

I'm using Sourcery with AutoProperties and in a later stage, I'm trying to generate structs for compositions (typealiases) of these. Sourcery 1.5.0 does not find my auto generated protocols, although I'm using force-parse for the generated files. Using Sourcery 1.4.2, this works as expected. 

Maybe related or not: I'm also trying to use a template to generate an initializer for the generated structs. This never works, because said AutoInit template seems to be run before the AutoStruct, ignoring the order I defined the templates in my config.yml and AutoStruct then overwriting the AutoInit. Should the order of templates be respected and this is a bug or should I just run two different configs to make sure the order is respected?

**Comment by krzysztofzablocki** [comment]
you missed the info about renaming the argument to be consistent, from changelog:
correct passing force-parse argument to specific file parsers and renames it to forceParse to align with other naming

**Comment by fabianmuecke** [comment]
I see. Thanks for pointing it out!
