### ISSUE TITLE
Squiggly blue line on comment instead of code

### ISSUE THREAD

**Issue by mirel-spr** [krzysztofzablocki/Sourcery#985]
Using Sourcery in VSCode on Windows 10.

Sourcery puts the squiggly blue line underneath the commented code instead of the actual line of code.

![image](https://user-images.githubusercontent.com/44804291/131626986-221098d5-02b3-48b9-be5e-eb2fc03e6ced.png)

![image](https://user-images.githubusercontent.com/44804291/131627066-9f0c6fcd-485f-4d5e-987f-7e7470d242ee.png)

VS Code info:
![image](https://user-images.githubusercontent.com/44804291/131627315-d2ca8cba-8a7f-4f00-94b4-984b07506e17.png)

Windows specifications:
Edition	Windows 10 Enterprise for Virtual Desktops
Version	21H1
Installed on	‎17/‎06/‎2021
OS build	19043.1165

**Comment by krzysztofzablocki** [comment]
wrong sourcery :) this is Swift codegen tool

**Comment by mirel-spr** [comment]
> wrong sourcery :) this is Swift codegen tool

Oops my apologies
