### ISSUE TITLE
Extensions are not parsed

### ISSUE THREAD

**Issue by tdermendjiev** [krzysztofzablocki/Sourcery#987]
Trying to list `types.extensions`, I noticed that for some reason extensions are not being parsed.

Example:

```
//Sample.swift
class Sample {

}

extension Sample {
    func open() {
        
    }
}
```

```
//Sample.stencil

Classes:
{% for type in types.classes %}
  {{ type.name }}
{% endfor %}

Extensions:

{% for type in types.extensions %}
  {{ type.name }}
{% endfor %}
```

```
//Sample.generated.swift

// Generated using Sourcery 1.5.0 — https://github.com/krzysztofzablocki/Sourcery
// DO NOT EDIT

Classes:
  Sample

Extensions:
```

**Comment by tdermendjiev** [comment]
I found out that this is caused by merging all types with the same name:

https://github.com/krzysztofzablocki/Sourcery/blob/master/SourceryRuntime/Sources/Composer.swift#L53

Why is it necessary?

**Comment by krzysztofzablocki** [comment]
because you want to combine the AST same as language does, Sample should list open as it's function even though it's added in extension

**Comment by tdermendjiev** [comment]
I agree but what if I still need to list all extensions? It is not true that there are 0 extensions.

**Comment by krzysztofzablocki** [comment]
what's your example use case to need that?

**Comment by tdermendjiev** [comment]
I am working on a tool that exposes Swift classes to Objective-C runtime. This would enable frameworks based on objc runtime (like NativeScript) to use Swift libraries. For that purpose I need to list all extension declarations.
