### ISSUE TITLE
HI Sourcery can update .xccconfig file value ? 

### ISSUE THREAD

**Issue by saroar** [krzysztofzablocki/Sourcery#988]
<img width="984" alt="Screenshot 2021-09-11 at 21 38 49" src="https://user-images.githubusercontent.com/8770772/132958057-f672d07d-f75f-4fa5-bd1a-d6fa2db7e430.png">

I am talking about this value? 👆🏻

**Comment by krzysztofzablocki** [comment]
no since we don't scan those files
