### ISSUE TITLE
Unable to build on Xcode 13 RC

### ISSUE THREAD

**Issue by richardxyx** [krzysztofzablocki/Sourcery#989]
I was trying to build the latest release of Sourcery (1.5.0) via SPM on the Xcode 13 RC 1 (13A233) toolchain. Due to an API change in `strdup` one of Sourcery's dependencies [PathKit](https://github.com/kylef/PathKit) fails to build:

```
[10/18] Compiling PathKit PathKit.swift
/private/var/folders/l9/fczt2v494bx7q_48_skjvzqr0000gp/T/mint/github.com_krzysztofzablocki_Sourcery/.build/checkouts/PathKit/Sources/PathKit.swift:583:12: error: value of optional type 'UnsafeMutablePointer<CChar>?' (aka 'Optional<UnsafeMutablePointer<Int8>>') must be unwrapped to a value of type 'UnsafeMutablePointer<CChar>' (aka 'UnsafeMutablePointer<Int8>')
      free(cPattern)
           ^
/private/var/folders/l9/fczt2v494bx7q_48_skjvzqr0000gp/T/mint/github.com_krzysztofzablocki_Sourcery/.build/checkouts/PathKit/Sources/PathKit.swift:583:12: note: coalesce using '??' to provide a default when the optional value contains 'nil'
      free(cPattern)
           ^
                    ?? <#default value#>
/private/var/folders/l9/fczt2v494bx7q_48_skjvzqr0000gp/T/mint/github.com_krzysztofzablocki_Sourcery/.build/checkouts/PathKit/Sources/PathKit.swift:583:12: note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
      free(cPattern)
           ^
                   !
```

A PR fixing the issue has already been opened in the PathKit repo (https://github.com/kylef/PathKit/pull/78). Once PathKit offers a release containing the fix we can update the dependency in order to resolve this.

Swift version:
```
swift-driver version: 1.26.9 Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)
Target: x86_64-apple-macosx11.0
```

**Comment by richardxyx** [comment]
Issue we can follow in the PathKit repo: https://github.com/kylef/PathKit/issues/77

**Comment by AF-cgi** [comment]
Please merge the open PRs to release a hotfix version. Currently it's not possible to compile Sourcery with Xcode 13. From that reason It's not possible to install it via Mint, if you have only Xcode 13 installed.

**Comment by Armenm** [comment]
It's a blocker for us too!

**Comment by mthole** [comment]
Blocker here as well.

**Comment by krzysztofzablocki** [comment]
updated on master, but you'd be better off using binary distribution (or brew once I release it) since using just SPM causes the issue with the config wheres if you use binary it doesn't matter which version of Xcode your developers have it will still work consistently
