### ISSUE TITLE
Documentation HTML invalid

### ISSUE THREAD

**Issue by fabianmuecke** [krzysztofzablocki/Sourcery#990]
The sourcery documentation has been broken for a couple of days now. It looks, like there is an additional `</div>` generated after `</body>`, which makes at least my browser (Chrome on macOS) show me the source code instead of rendering the HTML page.

e.g. https://cdn.jsdelivr.net/gh/krzysztofzablocki/Sourcery@master/docs/Classes/ProtocolComposition.html 

![image](https://user-images.githubusercontent.com/317346/133745741-c42e07a8-6a1b-4ce0-9b03-73c935c30102.png)

**Comment by krzysztofzablocki** [comment]
fixed

**Comment by fabianmuecke** [comment]
This issue seems to be back: https://cdn.jsdelivr.net/gh/krzysztofzablocki/Sourcery@master/docs/index.html
![image](https://user-images.githubusercontent.com/317346/152977073-1b37d865-f79c-440d-ad9a-05462c8d0a89.png)

**Comment by krzysztofzablocki** [comment]
the documentation is now hosted [here](http://merowing.info/Sourcery/)

**Comment by fabianmuecke** [comment]
Ah, thanks. Google sent me to this page https://github.com/krzysztofzablocki/Sourcery/blob/master/guides/Writing%20templates.md which contains an outdated link to the Types documentation. Will update my bookmark.
