### ISSUE TITLE
Binary directory changed in 1.6.0 with CocoaPods installation

### ISSUE THREAD

**Issue by johntmcintosh** [krzysztofzablocki/Sourcery#995]
The project readme mentions that with a CocoaPods installation, it's expected for the Sourcery binary to be available at:

```
$PODS_ROOT/Sourcery/bin/sourcery
```

After upgrading to the new 1.6.0 version, the binary is instead now located at 

```
$PODS_ROOT/Sourcery/Sourcery-1.6.0/bin/sourcery
```

which is more difficult to use with build scripts since the version number is part of the binary path.

I glanced at the last few commits but it wasn't apparent to me that there was a visible build configuration change that would have caused this, though I may be overlooking it. Maybe it was an unintended change resulting from the update [to start building with Xcode 13](https://github.com/krzysztofzablocki/Sourcery/commit/309b6d67aaa88e0fe1b4f74c1a917a33afddb58b)? 

NOTE: I'm running CocoaPods version 1.11.2, but I confirmed that downgrading to Sourcery 1.5.0 with the same CocoaPods version moves the binary back to the original location, so I think the root cause is likely related to a build configuration or pod deployment rather than CocoaPods itself.

**Comment by krzysztofzablocki** [comment]
should be ok now, let me know if it isn't
