### ISSUE TITLE
Subscript `returnTypeName` does not contain `where` clause.

### ISSUE THREAD

**Issue by g-amichnia** [krzysztofzablocki/Sourcery#996]
As in title, example:

```swift

protocol ProtocolWithSubscripts {
    // ...
    subscript<T>(with generic: T) -> Int where T: FloatingPoint { get set }
}
```

In `Subscript` documentation it says:

```
Return value type name used in declaration, including generic constraints, i.e. where T: Equatable
```

It seems to be regression, as in Sourcery 1.0.3 it was still working.

Is this a new bug or known limitation? It would be great to have at least something similar to the `Method` `.name` variable, that returns the whole name, with all generic constraints, etc.

// Using Sourcery 1.6.0, Swift 5.5

**Comment by krzysztofzablocki** [comment]
We should probably add `genericRequirements` same as I did for protocols

**Comment by g-amichnia** [comment]
Would love that! Also for methods. We would use that a lot in SwiftyMocky, now we have very ugly heuristics to parse full name by ourselves. 

As for subscripts, also one more small thing, I noticed that params labels and names seem to work differently:

```swift
subscript(x x: Int) -> Int // name is x, and label is x, what I expect
subscript(x: Int) -> Int // name is x, but label is also x, previously label was nil
```

When trying to recreate the original, since full `name` is lacking, some ambiguity arises.
